= Applicable Policy Configuration
:page-nav-title: Configuration
:page-wiki-name: Applicable Policy Configuration
:page-wiki-id: 24676635
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2018-03-09T15:04:30.547+01:00
:page-wiki-metadata-modify-user: michael
:page-wiki-metadata-modify-date: 2020-02-21T14:24:26.071+01:00
:page-upkeep-status: yellow
:page-toc: top
:page-moved-from: /midpoint/reference/roles-policies/applicable-policies/configuration/

MidPoint is very flexible system, especially when it comes to xref:/midpoint/reference/cases/approval/[approval] and other xref:/midpoint/reference/roles-policies/policy-rules/[policies]. But the flexibility comes at a cost.
Policy definition can be quite complex.
Some of this complexity is inherent and cannot really be avoided.
But once the policies are created then it should be quite easy to apply them to individual objects such as users and roles.
And starting from midPoint 3.8 there indeed is a simple way how to apply even a very complex policies.

The general idea of metarole-based configuration and the corresponding user interface is introduced on xref:/midpoint/reference/roles-policies/applicable-policies/[User-Friendly Policy Selection] page.
This page describes configuration details.


== Configuration

Applicable policies are defined as meta-roles.
If the policy is applied (e.g. by checking a check-box) then corresponding meta-role is assigned.
The policies are sorted into policy groups.
Policy groups are just xref:/midpoint/architecture/archive/data-model/midpoint-common-schema/orgtype/[Orgs]. Any meta-role which is a member of the org is considered to be part of the policy group.
The policy groups (orgs) needs to be referred from system configuration.
Therefore the complete configuration may look like this:

.System Configuration
[source,xml]
----
<systemConfiguration>
    ...
    <defaultObjectPolicyConfiguration>
        <type>RoleType</type>
        <applicablePolicies>
            <policyGroupRef oid="b1cb876e-23a2-11e8-bf14-ff36603a9ae0"/>
            <policyGroupRef oid="b7e2f6f0-23a2-11e8-983a-b315ed2c30b3"/>
        </applicablePolicies>
    </defaultObjectPolicyConfiguration>
</systemConfiguration>
----

.Policy group for approval
[source,xml]
----
<org oid="b1cb876e-23a2-11e8-bf14-ff36603a9ae0">
    <name>policy-meta-approval</name>
    <subtype>policy</subtype>
    <displayName>Approval policies</displayName>
</org>
----

.Policy group for security
[source,xml]
----
<org oid="b7e2f6f0-23a2-11e8-983a-b315ed2c30b3">
    <name>policy-meta-security</name>
    <subtype>policy</subtype>
    <displayName>Security policies</displayName>
</org>
----

.Meta role for manager approval
[source,xml]
----
<role oid="4798bd8e-23a3-11e8-a502-e32261e4ecff">
    <name>meta-role-policy-approval-manager</name>
    <subtype>policy</subtype>
    <displayName>Approval by manager</displayName>
    <assignment>
        <!-- Assignment so this meta-role is part of the policy group -->
        <targetRef oid="b1cb876e-23a2-11e8-bf14-ff36603a9ae0" type="OrgType"/>
    </assignment>
    <!-- inducements with policy rules for actual approval policy will be here -->
</role>
----


.Meta role for owner approval
[source,xml]
----
<role oid="a38b7eec-23a3-11e8-9f81-f7fb91a9d52a">
    <name>meta-role-policy-approval-role-owner</name>
    <subtype>policy</subtype>
    <displayName>Approval by role owner</displayName>
    <assignment>
        <!-- Assignment so this meta-role is part of the policy group -->
        <targetRef oid="b1cb876e-23a2-11e8-bf14-ff36603a9ae0" type="OrgType"/>
    </assignment>
    <!-- inducements with policy rules for actual approval policy will be here -->
</role>
----

.Meta role for SoD policy
[source,xml]
----
<role oid="d5d76b9a-23a3-11e8-be88-bb290240045b">
    <name>meta-role-policy-sod</name>
    <subtype>policy</subtype>
    <displayName>Segregation of Duties Policy</displayName>
    <assignment>
        <!-- Assignment so this meta-role is part of the policy group -->
        <targetRef oid="b7e2f6f0-23a2-11e8-983a-b315ed2c30b3" type="OrgType"/>
    </assignment>
    <!-- inducements with policy rules for actual SoD policy will be here -->
</role>
----

See xref:/midpoint/reference/roles-policies/metaroles/policy/[Using Metaroles for Policy Configuration] page for a more specific examples of approval policy specification in a metarole.

[TIP]
.Display names
====
Display names of roles and orgs are used by midPoint user interface whenever possible.
In case that display names are not available, ordinary object names are used.
So midPoint always has something to display to the user.
However, it is recommended to use display names.
Firstly, ordinary object names are required to be unique.
This requirement usually leads to a very complex naming convention for roles that is not entirely user-friendly.
There is no such requirement for display names.
Therefore display names can be used almost freely to provide a meaningful information to the user.
====


== See Also

* xref:/midpoint/reference/roles-policies/applicable-policies/[User-Friendly Policy Selection]

* xref:/midpoint/reference/roles-policies/metaroles/policy/[Using Metaroles for Policy Configuration]

* xref:/midpoint/reference/roles-policies/policy-rules/[Policy Rules]

* xref:/midpoint/reference/roles-policies/metaroles/gensync/['Roles, Metaroles and Generic Synchronization']
