= Constants
:page-wiki-name: Constants
:page-wiki-id: 24086076
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2017-05-16T10:28:58.038+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2017-05-16T10:37:25.198+02:00
:page-since: "3.6"
:page-midpoint-feature: true
:page-alias: { "parent" : "/midpoint/features/current/" }
:page-upkeep-status: yellow

MidPoint is often deployed in several environments: development environment, testing environment, production environment.
These environments have almost the same configuration.
The difference is often just host names and port numbers.
However, these configuration properties may be spread across many places: resource configuration, xref:/midpoint/reference/expressions/mappings/outbound-mapping/[outbound mappings], xref:/midpoint/reference/expressions/object-template/[object templates] and so on.
It might be quite hard to maintain all these properties up to date, especially when moving configuration updates from development environment to testing and from testing to production.

Therefore midPoint 3.6 has a new mechanism for that: _constants_. The constants can be defined in a single place in the system and then easily used in midPoint xref:/midpoint/reference/expressions/expressions/[expressions]. The constant definition can be bound to a specific environment and defined locally.
Then the midPoint configuration object do not contain any environment-specific data and the configuration can be easily transferred from environment to environment.


== Configuration and Use

See xref:configuration.adoc[] for more details.


== See Also

* xref:/midpoint/reference/expressions/expressions/[Expression]

* xref:configuration.adoc[]