---
midpoint-feature: dashboard
doc-type: intro
---
= Introduction to dashboards in midPoint
:page-wiki-name: Customizable Dashboards
:page-wiki-id: 27361691
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2019-01-31T11:38:34.604+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-02-01T13:16:14.087+01:00
:page-nav-title: Dashboards
:page-keywords: [ 'dashboards', 'dashboard' ]
:search-alias: "dashboards"
:page-upkeep-status: green
:page-toc: top

Dashboards are a fundamental tool for efficient identity governance and administration (IGA) in your organization.
They provide centralized overview of critical metrics, enabling managers to monitor compliance, track operational efficiency, and respond to risks proactively.
You can configure dashboards based on the metrics that are important for you and your stakeholders.

== Key motivations for using dashboards

* Dashboards reduce operational overhead by automating data aggregation and presentation.
* They help you spot potential risks more easily because they can highlight unwanted or non-compliant situations (e.g., users with accumulated high-risk access permissions)
* You can configure as many different dashboards as you need for various roles who are interested in different metrics. For example, a security officer needs different data than the HR personnel.
* You can customize the look and behavior of each dashboard: They can display custom data differently, use distinct color coding to show warnings, and so on.

Dashboards can show the number of active employees, failed resources, suspended tasks, and so on.
You can make dashboards much more powerful than that, though.
When you set them up to use xref:/midpoint/reference/admin-gui/collections-views/configuration/#collection-domain[collection domains]
and connect them with xref:/midpoint/reference/roles-policies/policies/policy-rules/[policy rules] through xref:/midpoint/reference/roles-policies/policies/policy-rules/#object_marks[object marks], you gain the ability to monitor xref:/midpoint/reference/admin-gui/dashboards/compliance-dashboard/[compliance] of your organization and xref:/midpoint/reference/misc/notifications/[receive warnings] that an action is needed to put the situation back in line with requirements.

== How dashboards help you stay compliant

Here is a simplified architectural outline showing how dashboards can help you with compliance through policy rules and notifications:

* Policy Rules  → Object marks → Object collections → Dashboards:
    ** Policy rules define compliance criteria (e.g., _users must not have both finance and HR roles_).
    ** Marks are added to objects that trigger (i.e., usually violate) the policy rule.
    ** Collections aggregate objects marked by the policy rule.
    ** Dashboards display the results, often with thresholds for visual alerts (e.g., _red for critical violations_).
* Notifications:
    ** Thresholds in collections can trigger notifications (e.g., email alerts) when compliance metrics exceed acceptable limits.

This architecture ensures compliance is a dynamic, actionable process integrated into your daily operations.

== Reports created from dashboards

System administrators often like to get a daily report with operational statistics.
If the data they are interested in are already shown in a dashboard, they do not need to duplicate the setup for their static report.
They can use a xref:/midpoint/reference/misc/reports/configuration/dashboard-report/[dashboard report] that takes the data from the configured dashboard and periodically generates a static report they can then conveniently receive, for example, via e-mail.

== See also

* xref:configuration/[]
* xref:/midpoint/reference/admin-gui/collections-views/[]
* xref:/midpoint/features/planned/compliance/[]
* xref:/midpoint/reference/schema/archetypes/[]
* xref:/midpoint/reference/misc/notifications/[]
