= Example of Dashboard report: Using policySituation for report
:page-nav-title: Example: policySituation
:page-wiki-name: Example of dashboard report: Using policySituation for report
:page-wiki-id: 52002836
:page-wiki-metadata-create-user: lskublik
:page-wiki-metadata-create-date: 2020-05-04T13:00:25.101+02:00
:page-wiki-metadata-modify-user: lskublik
:page-wiki-metadata-modify-date: 2020-05-04T14:37:22.496+02:00
:page-upkeep-status: yellow
:page-upkeep-note: check TODO's after sampleRef is fully in prod remove links

Please see xref:/midpoint/reference/admin-gui/dashboards/configuration/[Dashboard configuration] for basic information about configuration variables.


== Example Use-case

The Administrator needs to display all users which have value of description set as 'Created by mP'

== Configuration

At first, we need to configure a policy rule. In this Example we add the following snippet of configuration to our system configuration in Midpoint.

//TODO check after sampleRef is fully in prod
.*Example System Config configuration*
[%collapsible]
====
link:https://github.com/Evolveum/midpoint-samples/blob/master/samples/misc/system-policy-rec.xml[Git]

sampleRef::samples/misc/system-policy-rec.xml[]
====

Now, we have to recompute all users in order to set our policySituation for them, when they meet the criteria of our filter.

Afterwards We need to configure object collection for users with policySituation.

//TODO check after sampleRef is fully in prod
.*Example ObjectCollection configuration*
[%collapsible]
====
link:https://github.com/Evolveum/midpoint-samples/blob/master/samples/objectCollection/users-with-policySituation.xml[Git]

sampleRef::samples/objectCollection/users-with-policySituation.xml[]
====

When we have the object collection in place, we want to set up an import Dashboard object with a widget for our object collection.

//TODO check after sampleRef is fully in prod
.*Example Dashboard configuration*
[%collapsible]
====
link:https://github.com/Evolveum/midpoint-samples/blob/master/samples/dashboard/users-policy-situation.xml[Git]

sampleRef::samples/dashboard/users-policy-situation.xml[]
====

After the successful import of the dashboard object you can see the dashboard in the menu *Dashboards* > *Users created by mP dashboard*.

We want to report it out as a table of users created by Midpoint, for this we can use a dashboard report.

//TODO check after sampleRef is fully in prod
.*Example Dashboard Report Configuration*
[%collapsible]
====
link:https://github.com/Evolveum/midpoint-samples/blob/master/samples/reports/users-created-policy-dashboard-report.xml[Git]

sampleRef::samples/reports/users-created-policy-dashboard-report.xml[]
====

Now we can run the report in the report menu, open the task which generated the report and download the report.


== See Also

- xref:/midpoint/reference/misc/reports/examples/[Report Examples]
- xref:/midpoint/reference/misc/reports/configuration/[Report Configuration]
- xref:/midpoint/reference/misc/reports/configuration/collection-report.adoc[Collection Based Reports]
- xref:/midpoint/reference/misc/reports/configuration/dashboard-report.adoc[Dashboard Based Reports]
- xref:/midpoint/reference/concepts/query/#reference-query[Reference Query]
