= Milestone to Milestone upgrade instructions and notes
:toc:
:page-nav-title: Milestone upgrade instructions

WARNING: This page is written for internal purposes, and we don't give any guarantee that these instructions and notes are complete, nor that it will work at all... but we do our best.

This page contains the upgrade instructions and incompatibility changes that could cause problems during upgrades from a milestone to a milestone, before the "in development" version is released. Useful for continuous testing of the developed features etc.

The upgrade instructions between releases are in the https://docs.evolveum.com/midpoint/release/[release notes].

== 4.11-RC2
== 4.11-RC1
== 4.11-M6

* Iteration specification (`IterationType`) has a new boolean property `useTokenOnlyOnConflict` and changed default value for `start`.
By default, `useTokenOnlyOnConflict` is `true`, which means the token expression is not evaluated for the first (non conflicting) attempt.
The default `start` value is now `0` when `maxIterations` is defined, and `1` when it is not.
This can break existing custom token expressions that expect to be evaluated on the first (non conflicting) attempt.
In that case, set `useTokenOnlyOnConflict` to `false` explicitly.
== 4.11-M5
