---
layout: release
release-version: '4.11'
visibility: hidden
---
= MidPoint 4.11
:release-version: 4.11
:page-visibility: hidden
:page-liquid:
:page-toc: top

Release {release-version} is a seventy-second midPoint release, code-named _Braille_.
The {release-version} release brings accessibility improvements, compliance features as well as many incremental improvements and bugfixes.

++++
{% include release-data.html %}
++++

++++
{% capture dedicationContent %}
<p>
<a href="https://en.wikipedia.org/wiki/Louis_Braille">Louis Braille</a> (1809-1852) was a French educator.
He invented a reading and writing system named after him, intended for use by visually impaired people.
Braille invented the system at an early age, and dedicated most of his life to improve his system.
The system invented by Braille opened up the world of knowledge and learning to the visually impaired people.
</p>
<p>
Similarly to Braille's system, midPoint 4.10 brings major improvements in accessibility.
Self-service part of midPoint user interface was meticulously reviewed and improved to correctly support tools used by the visually impaired people.
Moreover, midPoint 4.10 brings many incremental improvements and new features in various areas, reminiscent of Braille's relentless improvements of his system through his life.
Overall, midPoint 4.10 opens up the world of identity management and governance to everybody.
</p>
{% endcapture %}
{% include release-dedication.html content=dedicationContent %}
++++

== Changes With Respect to Version 4.10

=== New Features and Major Improvements

* bug:MID-10965[] Fast correlators simulation.

== Changes With Respect To Version 4.10

=== New Features and Major Improvements

#TODO#

=== Other Improvements

* Added Slovenian language into repo/system-init/src/main/resources/initial-objects/lookup-table/200-lookup-languages.xml and repo/system-init/src/main/resources/initial-objects/210-lookup-locales.xml

=== Major Bugfixes

#TODO#

=== Other Bug Fixes

#TODO#

=== Releases Of Other Components

#TODO UDPATE#

* New version (1.5.2.0) of xref:/connectors/connectors/org.identityconnectors.databasetable.DatabaseTableConnector/[DatabaseTable Connector] was released and bundled with midPoint. The connector suggest all names of columns for configuration properties related with name of column.

* New version (2.8) of xref:/connectors/connectors/com.evolveum.polygon.connector.csv.CsvConnector/[CSV Connector] was released and bundled with midPoint. The connector suggest all names of columns for configuration properties related with name of column.
** Fixed NPE with multivalue attributes when delimiter is not defined. (bug:MID-8609[]).
** Fix UTF-8 BOM character in csv file during of discovery functions. (bug:MID-9497[] and bug:MID-9498[]).

* New version (3.8) of xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[AD/LDAP Connector] was released and bundled with midPoint. The connector suggest all names of columns for configuration properties related with name of column.
** Native association support.
** Possibility to choose attributes that should not be returned by default.
** Possibility to choose to encode string values in case of the presence of non standard ASCII characters.
** Workaround for open-ldap mandatory member attribute.
** Possibility to specify used auxiliary object classes in connector configuration.
** Allow to send the LDAP_DIRSYNC_OBJECT_SECURITY flag in Active Directory sync request control.

++++
{% include release-quality.html %}
++++

=== Limitations

Following list provides summary of limitation of this midPoint release.

* Functionality that is marked as xref:/midpoint/versioning/experimental/[Experimental Functionality] is not supported for general use (yet).
Such features are not covered by midPoint support.
They are supported only for those subscribers that funded the development of this feature by the means of
xref:/support/subscription-sponsoring/[subscriptions and sponsoring] or for those that explicitly negotiated such support in their support contracts.

* MidPoint comes with bundled xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector].
Support for LDAP connector is included in standard midPoint support service, but there are limitations.
This "bundled" support only includes operations of LDAP connector that 100% compliant with LDAP standards.
Any non-standard functionality is explicitly excluded from the bundled support.
We strongly recommend to explicitly negotiate support for a specific LDAP server in your midPoint support contract.
Otherwise, only standard LDAP functionality is covered by the support.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector] page for more details.

* MidPoint comes with bundled xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)].
Support for AD connector is included in standard midPoint support service, but there are limitations.
Only some versions of Active Directory deployments are supported.
Basic AD operations are supported, but advanced operations may not be supported at all.
The connector does not claim to be feature-complete.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)] page for more details.

* MidPoint user interface has flexible (responsive) design, it is able to adapt to various screen sizes, including screen sizes used by some mobile devices.
However, midPoint administration interface is also quite complex, and it would be very difficult to correctly support all midPoint functionality on very small screens.
Therefore, midPoint often works well on larger mobile devices (tablets), but it is very likely to be problematic on small screens (mobile phones).
Even though midPoint may work well on mobile devices, the support for small screens is not included in standard midPoint subscription.
Partial support for small screens (e.g. only for self-service purposes) may be provided, but it has to be explicitly negotiated in a subscription contract.

* There are several add-ons and extensions for midPoint that are not explicitly distributed with midPoint.
This includes xrefv:/midpoint/reference/support-4.9/interfaces/midpoint-client-java/[Java client library],
various https://github.com/Evolveum/midpoint-samples[samples], scripts, connectors and other non-bundled items.
Support for these non-bundled items is limited.
Generally speaking, those non-bundled items are supported only for platform subscribers and those that explicitly negotiated the support in their contract.

* MidPoint contains a basic case management user interface.
This part of midPoint user interface is not finished.
The only supported parts of this user interface are those that are used to process requests, approvals, and manual correlation.
Other parts of case management user interface are considered to be experimental, especially the parts dealing with manual provisioning cases.

This list is just an overview, it may not be complete.
Please see the documentation regarding detailed limitations of individual features.

== Platforms

MidPoint is known to work well in the following deployment environment.
The following list is list of *tested* platforms, i.e. platforms that midPoint team or reliable partners personally tested with this release.
The version numbers in parentheses are the actual version numbers used for the tests.

It is very likely that midPoint will also work in similar environments.
But only the versions specified below are supported as part of midPoint subscription and support programs - unless a different version is explicitly agreed in the contract.

=== Operating System

MidPoint is likely to work on any operating system that supports the Java platform.
However, for *production deployment*, only some operating systems are supported:

* Linux (x86_64)
* Windows Server (2022)

We are positive that midPoint can be successfully installed on other operating systems, especially macOS and Microsoft Windows desktop.
Such installations can be used to for evaluation, demonstration or development purposes.
However, we do not support these operating systems for production environments.
The tooling for production use is not maintained, such as various run control (start/stop) scripts, low-level administration and migration tools, backup and recovery support and so on.
Please see xref:/midpoint/install/bare-installation/platform-support/[] for details.

Note that production deployments in Windows environments are supported only for LTS releases.

=== Java

Following Java platform versions are supported:

* Java 21.
This is a *recommended* platform.

* Java 17.

OpenJDK 21 is the recommended Java platform to run midPoint.

Support for Oracle builds of JDK is provided only for the period in which Oracle provides public support (free updates) for their builds.

MidPoint is an open source project, and as such it relies on open source components.
We cannot provide support for platform that do not have public updates as we would not have access to those updates, and therefore we cannot reproduce and fix issues.
Use of open source OpenJDK builds with public support is recommended instead of proprietary builds.

=== Databases

*PostgreSQL is the only supported database* for midPoint deployments since 4.10.

Although in previous versions of midPoint other databases were supported using object-relational mapping abstraction (Hibernate), it is no longer the case now.
xrefv:/midpoint/reference/support-4.9/repository/native-postgresql/[Native PostgreSQL repository implementation] was developed and tuned specially for PostgreSQL database, taking advantage of native database features, providing improved performance and scalability.
It is currently the only option.

Our strategy is to officially support the latest stable version of PostgreSQL database (to the practically possible extent).
We make no commitments for future support of any other database engines.
See xrefv:/midpoint/reference/support-4.9/repository/repository-database-support/[] page for the details.

Only a direct connection from midPoint to the database engine is supported.
Database and/or SQL proxies, database load balancers or any other devices (e.g. firewalls) that alter the communication are not supported.

Following database engines are supported:

* PostgreSQL 17, 16, 15, 14

PostgreSQL 17 is recommended.

=== Supported Browsers

* Firefox
* Safari
* Chrome
* Edge
* Opera

Any recent version of the browsers is supported.
That means any stable stock version of the browser released in the last two years.
We formally support only stock, non-customized versions of the browsers without any extensions or other add-ons.
According to the experience most extensions should work fine with midPoint.
However, it is not possible to test midPoint with all of them and support all of them.
Therefore, if you chose to use extensions or customize the browser in any non-standard way you are doing that on your own risk.
We reserve the right not to support customized web browsers.

== Important Bundled Components

.Important bundled components
[%autowidth]
|===
| Component | Version | Description

| Tomcat
| 10.1.48
| Web container

| ConnId
| 1.6.0.0
| ConnId Connector Framework

| xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP connector bundle]
| 3.9.2
| LDAP and Active Directory

| xref:/connectors/connectors/com.evolveum.polygon.connector.csv.CsvConnector/[CSV connector]
| 2.9
| Connector for CSV files

| xref:/connectors/connectors/org.identityconnectors.databasetable.DatabaseTableConnector/[DatabaseTable connector]
| 1.5.3.0
| Connector for simple database tables

|===

++++
{% include release-download.html %}
++++

== Upgrade

MidPoint is a software designed with easy upgradeability in mind.
We do our best to maintain strong backward compatibility of midPoint data model, configuration and system behavior.
However, midPoint is also very flexible and comprehensive software system with a very rich data model.
It is not humanly possible to test all the potential upgrade paths and scenarios.
Also, some changes in midPoint behavior are inevitable to maintain midPoint development pace.
Therefore, there may be some manual actions and configuration changes that need to be done during upgrades,
mostly related to xref:/midpoint/versioning/feature-lifecycle/[feature lifecycle].

This section provides overall overview of the changes and upgrade procedures.
Although we try to our best, it is not possible to foresee all possible uses of midPoint.
Therefore, the information provided in this section are for information purposes only without any guarantees of completeness.
In case of any doubts about upgrade or behavior changes please use services associated with xref:/support/subscription-sponsoring/[midPoint subscription programs].

Please refer to the xrefv:/midpoint/reference/support-4.9/upgrade/upgrade-guide/[] for general instructions and description of the upgrade process.
The guide describes the steps applicable for upgrades of all midPoint releases.
Following sections provide details regarding release {release-version}.

=== Upgrade From MidPoint 4.9

MidPoint {release-version} data model is backwards compatible with previous midPoint version.
Please follow our xrefv:/midpoint/reference/support-4.9/upgrade/upgrade-guide/[Upgrade guide] carefully.

[IMPORTANT]
Be sure to be on the latest maintenance version for 4.9, otherwise you will not be warned about all the necessary schema changes and other possible incompatibilities.

Note that:

 * There are database schema changes (see xrefv:/midpoint/reference/support-4.9/upgrade/database-schema-upgrade/[Database schema upgrade]).

 * Version numbers of some bundled connectors have changed.
 Connector references from the resource definitions that are using the bundled connectors need to be updated.

 * See also the _Actions required_ information below.

=== Upgrade From Other MidPoint Versions

Upgrade from midPoint versions other than 4.9.x to midPoint {release-version} is not supported directly.
Please upgrade to 4.9.5 first.

=== Deprecation, Feature Removal And Major Incompatible Changes Since 4.9

NOTE: This section is relevant to the majority of midPoint deployments.
It refers to the most significant functionality removals and changes in this version.

The support for databases other than PostgreSQL was dropped.

=== Changes In Initial Objects Since 4.9

NOTE: This section is relevant to the majority of midPoint deployments.

MidPoint has a built-in set of "initial objects" that it will automatically create in the database if they are not present.
This includes vital objects for the system to be configured (e.g., the role `Superuser` and the user `administrator`).
These objects may change in some midPoint releases.
However, midPoint is conservative and avoids overwriting customized configuration objects.
Therefore, midPoint does not overwrite existing objects when they are already in the database.
This may result in upgrade problems if the existing object contains configuration that is no longer supported in a new version.

The following list contains a description of changes to the initial objects in this midPoint release.
The complete new set of initial objects is in the `config/initial-objects` directory in both the source and binary distributions.

_Actions required:_ Please review the changes and apply them appropriately to your configuration. Ninja can help with updating existing initial objects during upgrade procedure using `initial-objects` command.
For more information see xrefv:/midpoint/reference/support-4.9/deployment/ninja/use-case/upgrade-with-ninja/#initial-objects[here].

* 000-system-configuration.xml: improved `safe` expression profile, added `permissive` and `prohobitive` profiles, renamed `script-safe` to `script-limited` permission profile, added possibility for configuration of volatility of attribute in resource wizard, added task execution constraints to advanced options tab, updated default paging options, made operation execution recording a regular feature, extended with compliance dashboard, improving `help` attribute values.
* 010-value-policy.xml: improved localization for name attributes, removed max password length constraint, added `ignoreWhenGenerating` value policy feature.
* 020-archetype-system-user.xml: fixed the color of the icon.
* 021-archetype-system-role.xml: fixed the color of the icon.
* 023-archetype-manual-provisioning-case.xml: added the color for the icon.
* 024-archetype-operation-request.xml: added the color for the icon.
* 025-archetype-approval-case.xml: added the color for the icon.
* 028-archetype-application-role.xml: fixed the plural label.
* 029-archetype-application.xml: fixed the displaying of the application classifications and governance panels.
* 040-role-enduser.xml: extended assignment panels configuration.
* 041-role-approver.xml: added manualProvisioningContext item to read authorization of the CaseType object in order to correctly display case details page; fixed authorizations.
* 042-role-reviewer.xml: extended certification campaign read authorization.
* 062-archetype-classification.xml: extended with documentation attribute.
* 063-archetype-clearance.xml: extended with documentation attribute.
* 090-report-audit.xml: queries are updated to use MidPoint Query language.
* 100-report-reconciliation.xml: queries are updated to use MidPoint Query language.
* 110-report-user-list.xml: queries are updated to use MidPoint Query language.
* 140-report-certification-campaigns.xml: queries are updated to use MidPoint Query language.
* 150-archetype-location.xml: a new one.
* 150-archetype-organization.xml: a new one.
* 150-archetype-organizational-unit.xml: a new one.
* 150-archetype-project.xml: a new one.
* 150-archetype-team.xml: a new one.
* 150-report-certification-cases.xml: fixed campaign name column value, queries are updated to use MidPoint Query language.
* 160-report-certification-work-items.xml: queries are updated to use MidPoint Query language.
* 200-lookup-languages.xml: extended with new languages.
* 210-lookup-locales.xml: extended with new locales.
* 200-report-indirect-assignments.xml: queries are updated to use MidPoint Query language.
* 250-mark-no-classification.xml: a new one.
* 250-mark-privileged-access.xml: a new one.
* 250-mark-unowned.xml: a new one.
* 253-object-collection-application-active.xml: a new one.
* 300-classification-privileged-access.xml: extended with documentation, assignment and inducement.
* 300-policy-require-classification.xml: a new one.
* 300-policy-require-owner.xml: a new one.
* 350-object-collection-application-suspicious.xml: a new one.
* 350-object-collection-application-unowned.xml: a new one.
* 350-object-collection-application-without-classification.xml: a new one.
* 350-object-collection-privileged-users.xml: a new one.
* 350-object-collection-role-active.xml: a new one.
* 350-object-collection-role-all.xml: a new one.
* 350-object-collection-role-unowned.xml: a new one.
* 350-object-collection-user-active.xml: a new one.
* 353-users-with-sod-violations.xml: added documentation attribute, added configuration of the default view.
* 354-roles-privileged.xml: added documentation attribute, added configuration of the default view.
* 357-suspicious-roles.xml: added documentation attribute, added configuration of the default view.
* 358-suspicious-users.xml: added documentation attribute, added configuration of the default view.
* 390-org-projects.xml: a new one.
* 390-org-teams.xml: a new one.
* 390-org-world.xml: a new one.
* 536-archetype-task-certification-start-campaign.xml: task activity panel was fixed to display the data from the certificationStartCampaign container.
* 538-archetype-task-certification-reiterate-campaign.xml: task activity panel was fixed to display the data from the certificationReiterateCampaign container.
* 811-exclusion-violation.xml: extended with documentation attribute.
* 830-suspicious.xml: extended with documentation attribute.
* 899-dashboard-compliance.xml: a new one.
* 910-task-recompute-all-users.xml: a new one.

Please review link:https://github.com/Evolveum/midpoint/commits/master/gui/admin-gui/src/main/resources/initial-objects[source code history] for detailed list of changes.

TIP: Copies of initial object files are located in `config/initial-objects` directory of midPoint distribution packages. These files can be used as a reference during upgrades.
On-line version can be found in https://github.com/Evolveum/midpoint/tree/v{release-version}/config/initial-objects[midPoint source code].

=== Schema Changes Since 4.9

NOTE: This section is relevant to the majority of midPoint deployments.
It describes what data items were marked as deprecated, or removed altogether from the schema.
You should at least scan through it - or use the `ninja` tool to check the deprecations for you.

.Items being deprecated
[%autowidth]
|===
| Type | Item or value | Note
| `AccessCertificationConfigurationType`
| `availableResponse`
| Configure actions in the cert. items collection view instead.

| `ItemRefinedDefinitionType`
| `emphasized`
| Use `displayHint` instead.

| `ResourceObjectTypeDefinitionType`
| `association`
| Use association types (in schemaHandling) instead.

| `ResourceObjectTypeDefinitionType`
| `protected`
| Use "marking" instead.

| `ShadowType`
| `association`
| Legacy associations of this shadow. Not used anymore.

| `SynchronizationActionsType`
| `unlink`
| Use `<synchronize/>` action instead.
|===

The `synchronize/membership` container was added to the object operation policy object, present in xrefv:/midpoint/reference/support-4.9/concepts/mark/[object marks] (like the `Protected` one).
It controls the handling of the membership of entitlements possessing given object mark.

_Actions required:_

* Inspect your configuration for deprecated items, and replace them by their suggested equivalents.
Make sure you don't use any removed items.
You can use `ninja` tool for this.

* Be sure to apply the changes to initial objects 800-804 (object marks), as well as to your custom object marks to handle the membership in the expected way.

[#_behavior_changes_since_4_9]
=== Behavior Changes Since 4.9

* The contract for `ModificationsSupplier` in dynamic object modifications (repo API) was changed.
+
The original approach was that the caller, i.e., repository, cloned the existing object before handling it to the callback (modifications supplier).
Now, the implementor of the callback is responsible for not modifying the provided object in any way.

* Projections with denied access no longer cause "preview changes" operation to fail.
+
If a user has no authorization to see particular projection (shadow), the "preview changes" operation used to finish with "Access denied" fatal error even if there were parts of the result visible to the user.
This is now changed (fixed): only the relevant projections are hidden now.
All the remaining data are displayed to the user.
See also bug:MID-10397[].

* Expression profile changes:

** Script expression evaluator was removed from `safe` expression profile, as it is not considered to be safe.

** Two new expression profiles were added: `permissive` (allowing all expressions) and `prohibitive` (allowing no expressions).

** Permission profile `script-safe` was renamed to `script-limited`, as the existing mechanism for script permission checks is not considered to provide complete safety and security.
This profile is not considered to provide strict security, therefore the name was changed to avoid mis-interpretation.
Corresponding description was added to the profile.

** See xref:/midpoint/reference/expressions/expressions/security/[Expression Security] page for a description of recommended use of expression profiles.

++++
{% include release-issues.html %}
++++
