---
layout: release
release-version: '4.10'
visibility: hidden
---
= MidPoint 4.10
:release-version: 4.10
:page-visibility: hidden
:page-liquid:
:page-toc: top

Release {release-version} is a sixtieth midPoint release, code-named _Verne_.
The {release-version} release brings improvements in role engineering, certification, approvals, stability and miscellaneous improvements.

++++
{% include release-data.html %}
++++

++++
{% capture dedicationContent %}
<p>
<a href="https://en.wikipedia.org/wiki/Jules_Verne">Jules Gabriel Verne</a> (1828-1905) was a French novelist, poet, and playwright.
His best-selling novels, always well-researched according to the scientific knowledge then available, taking into account the technological advances of the time.
Verne, considered to be one of the fathers of science-fiction genre, inspired several generations of readers.
</p>
<p>
Similarly to Verne's novels, midPoint 4.9 brings several technological advancements, bringing them from the drawing board to real life.
Shadow caching and value metadata were prototyped a long time ago, they became production-quality reality in midPoint 4.9.
Improvements in role mining and brand-new outlier detection functionality are reaching up to the boundaries of science fiction.
The new access certification look and feel is reminiscent of the colorful worlds that Verne has described.
Other features and improvements of this release make midPoint more complete, easier to use and much more sophisticated.
Overall, midPoint 4.9 is a major step from the past into the future.
</p>
{% endcapture %}
{% include release-dedication.html content=dedicationContent %}
++++

== Changes With Respect To Version 4.9

=== New Features and Major Improvements

* bug:MID-10147[] Added support for new capability `lastLoginTimestamp`.
* bug:MID-10213[] Fix synchronization of large number of tasks (>10 000).
* bug:MID-10270[] Summary panel for roles now uses display name and identifier (same as for organizations and services).
* bug:MID-10204[] Fix error during preview of changes.
* bug:MID-10319[] Fixed incorrect error message displayed when performing "Unlock" action on user list page.
* bug:MID-10317[] Fixed missing message when user disable fails.
* bug:MID-10320[] Fixed ninja zip option used during export/import.
* bug:MID-10218[] Task execution constraints added to advanced options tab.
* bug:MID-10216[] Support exclusion of metadata in `get`/`search` rest APIs.
* bug:MID-10305[] Remove max password length constraint.
* bug:MID-10048[] Fix ClassCastException when creating duplicates of object types with new archetype
* bug:MID-9300[] Secure schema usage in PostgresSQL (not using public schema).
* bug:MID-10278[] Fix non-clickable part of a button in Edit Schema popup panel.
* bug:MID-10513[] Fixed css issues with popup modal background in Safari.
* bug:MID-10410[] Better indication for failed tasks and their subtasks.
* bug:MID-10412[] Implemented configurable thresholds for task activities.
* bug:MID-10496[] Task doesn't start at next scheduled time.
* bug:MID-10414[] Page size global configuration for object collection views.
* bug:MID-10411[] Improved task run history errors search.
* xref:/midpoint/reference/admin-gui/dashboards/compliance-dashboard/[Compliance dashboard]

=== Other Improvements

* StartupConfiguration incorporates 'midpoint.' properties from Spring environment sources.
* Implemented xrefv:/midpoint/reference/support-4.9/resources/attribute-caching/#_caching_passwords[shadow password caching], with the possibility of storing them in reversible encrypted form.
* Improved handling of xrefv:/midpoint/reference/support-4.9/resources/resource-configuration/schema-handling/volatility/[volatile shadow attributes].
* Update GUI views after changing of the archetype, that is used in the view. See bug:MID-9776[].
* Adding support for PKCE (Proof Key for Code Exchange) as additional security for OIDC authentication module. See bug:MID-10155[].
* Adding new configuration attribute for OIDC authentication module, that is used for ID Token signing algorithm. See xref:/midpoint/reference/security/authentication/flexible-authentication/modules/oidc/[Oidc Module].
* Apply the Web Content Accessibility Guidelines (WCAG) to all login pages and self-service pages. See bug:MID-9847[].
** Used 'honeypot' instead of captcha on self-registration and post-authentication pages to protect against spam bots.
* Improved the documentation on the resource configuration. See bug:MID-10176[].
* Allow volatility configuration per mapping through the Resource Wizard. See bug:MID-10170[].
* Change the CSS style of sub-containers in the vertical form panel to create a new object for reference. See bug:MID-10030[].
* Documentation of xref:/midpoint/reference/resources/shadow/purpose/[shadow purpose] was added. See bug:MID-10419[].
* Some policy rule constraints allow to the `targetArchetypeRef` to specify objects by archetype. See bug:MID-10647[].
* Assignment modification constraint of policy rules allows specification of scope.
This can be used for approval of indirect role assignments and similar cases. See bug:MID-10663[].
* There are two new functions in midPoint function library for access to "governance" users (approvers/owners): `getRoleMemberUsers`, `getServiceMemberUsers`.
* Use delta's "visualizer" used by GUI also in notifications and other improvements in notifications. See bug:MID-6112[], bug:MID-10633[], bug:MID-10632[], bug:MID-10635[], bug:MID-10372[], bug:MID-10634[], bug:MID-10636[].
* Built-in archetypes for organizational structures and locations.
* xrefv:/midpoint/reference/master/roles-policies/policies/identity-governance-rules/[Compliance-related] marks (no classification, unowned, privileged access), object collections and policies.
* xrefv:/midpoint/reference/master/roles-policies/policies/privileged-access/[`Privileged access` classification] automatically sets `Privileged access` mark for directly affected roles and users.
* Updated various libraries, mainly: Spring Boot, Tomcat, Hibernate, PostgresSQL JDBC driver.
* Add OAuth 2 credential flow to mail servers notification configuration

=== Other Bug Fixes

* Fixed boolean column values for Quartz tables in Oracle 23 - "Quartz broken after DB upgrade". See bug:MID-10715[].
* Fixed "Couldn't get assignments conflicts" error occurring during Request access. See bug:MID-10124[].
* Fixed "No definition for item ... in outbound mapping for association" error. See bug:MID-10214[].
* Fixed the issue with policy rules `minAssignees`/`maxAssignees` not being triggered. See bug:MID-9869[].
* Fixed retrieving referenced objects with their own references when caching is enabled. See bug:MID-10271[].
* Fixed inconsistent behaviour for `deleted` situation in combination with `deleteFocus` reaction. See bug:MID-10195[].
* Fixed midPoint freezing when shadow partitioning, referenced objects, and shadow caching was used. See bug:MID-10231[].
* Added support for removing "dangling" non-tolerant reference attribute values (i.e., those that do not match any association). See bug:MID-10285[].
* Changes in default shadow caching policy are now correctly applied, without requiring any action on the user side. See bug:MID-10126[].
* Fixed `NullPointerException` occurring in mappings when the source reference value pointed to non-existing object. See bug:MID-10162[].
* "Native references" capability is now correctly shown in GUI. See bug:MID-10194[].
* Fixed handling of multi-valued resource configuration properties defined using `const` expression. See the last comment in bug:MID-7918[].
* Fixed repeated modifications of objects when manually attached object marks were used. See bug:MID-10121[].
* Fixed preview changes when auto-assigned roles with approvals were used. See bug:MID-10345[].
* Stopped generating passwords with "problematic" characters, like comma, apostrophe, ampersand, and so on.
Now it's possible to define characters that are accepted in the password, but not used when generating a new password value.
The default password policy was updated in this regard.
See bug:MID-9541[] and the xref:/midpoint/reference/security/credentials/password-policy/#_ignoreWhenGenerating[docs].
* Stopped displaying some shadow operational properties (like the synchronization timestamp, iteration, and so on) among changes in simulation results.
See bug:MID-9737[] and bug:MID-9986[].
* Midpoint Query Language Fixed inconsistent whitespace behavior when using `not` filter, modified grammar of query language. See bug:MID-9351[].
* Fixed code completions & validation for @metadata language concept in Midpoint Query language. See bug:MID-10324[].
* Fixed problem with handling syntax error in Midpoint Query Language. See bug:MID-8196[] and bug:MID-9585[].
* Fixed removal of the shadow transition mark in the mark table panel. See bug:MID-10228[].
* Fixed refresh names, help texts and search items for all saved search configurations. See bug:MID-10321[].
* Fixed phantom changes when displaying an existing object type in the resource wizard. See bug:MID-10284[].
* Added a popup to create a new item for the Schema Extension panel. See bug:MID-10283[].
* Harmonize the design of the mapping table panel for object template and resource object type mapping. See bug:MID-10291[].
* Removed the use of page parameters for view collection in popup tables. See bug:MID-10254[].
* Fixed display of row without object name for Task Errors panel. See bug:MID-10354[].
* Fixed the display of the 'User Dashboard Links' panel in the System Configuration panel. See bug:MID-10133[].
* Fixed the object class name column in the Resource Details panel. See bug:MID-10005[].
* Fixed saving of audit record with malformed username as parameter during login (User-Enumeration attack). See bug:MID-10383[].
* Add a save button to the wizard's table of object and association types. See bug:MID-10046[].
* Add an error message when the 'securityQuestionsForm' authentication module is the first in the authentication sequence. See bug:MID-10149[].
* bug:MID-10225[] Fix issue where opening of certification campaign stage hangs indefinitely.
* Fixed "preview changes" and "access request" functionality when some projections are hidden by authorizations. See bug:MID-10397[].
* bug:MID-10739[] Use SecureRandom instead of Random.
* Fixed different certification bugs. See bug:MID-10208[], bug:MID-10190[], bug:MID-10134[], bug:MID-10262[], bug:MID-10261[], bug:MID-10373[], bug:MID-10376[], bug:MID-10469[], bug:MID-10520[] and others.
* Fixed organizations list display bug. See bug:MID-10150[].
* Fixed the icon for Case type objects that was not displayed. See bug:MID-10164[].
* Fixed the issue with date field update. See bug:MID-10107[].
* Fixed the issue with wrong redirection after unassigning the object. See bug:MID-10151[].
* Fixed the issue with displaying Service type objects in the role catalog. See bug:MID-10206[].
* Password policy checks are being applied to an extension attribute of the ProtectedStringType. See bug:MID-10129[].
* Fixed empty required fields validation in UI in case the parent container is empty. See bug:MID-10210[].
* Fixed the issue with password policy check popover. See bug:MID-10128[].
* Fixed the sorting of the organisation tree in the Role catalog (from now, sorted by display name). See bug:MID-10246[].
* Fixed filtering of the work items in UI. See bug:MID-10167[].
* Fixed input string validation in the Flexible Authentication module. See bug:MID-10123[].
* Fixed the displaying of the historical user data. See bug:MID-10153[].
* Fixed error in logs during the work in the resource wizard. See bug:MID-10233[].
* Hided password strength bar for the protected string panel. See bug:MID-10129[].
* Fixed the error while creating new application service object with manager. See bug:MID-10277[].
* Fixed the error during self password update. See bug:MID-10316[].
* Fixed the usage of the MidpointFormValidator during object updates. See bug:MID-10127[].
* Fixed authorization check in GUI by using EndPointsUrlMapping actions check. See bug:MID-10336[].
* Fixed the displaying of the Policy rule panel. See bug:MID-10343[].
* Fixed the issue with duplicated error message displaying on the Repository objects page. See bug:MID-10344[].
* Made authorization error message more user-friendly. See bug:MID-10206[].
* Fixed default panels configuration of the details pages for start campaign and reiterate campaign tasks. See bug:MID-10205[].
* Fixed error on the Task Internal performance panel. See bug:MID-10445[].
* Fixed error on the task details page. See bug:MID-10395[].
* Fixed defaultAssignmentConstraints configuration usage during Request Access. See bug:MID-10425[].
* Fixed Person of interests step in Access Request to take into account objects filter and to analyze more carefully changing the persons of interest. See bug:MID-10398[].
* Fixed changing the mark for user object. See bug:MID-10423[].
* Fixed session storage for Cases table. See bug:MID-10473[].
* Fixed the issue with the displaying the value of the work item Name column. See bug:MID-10427[].
* Fixed the issue with dashboard resource widget. See bug:MID-10497[].
* Fixed the sorting of the first column in the collection view table. See bug:MID-10486[].
* Removed the button for credentials change on the Password panel of the object details page to be hidden without proper authorization. See bug:MID-10507[].
* Fixed error when setting read permission with filter on ReportDataType. See bug:MID-10498[].
* Fixed localization error while changing the password. See bug:MID-10471[].
* Fixed the accumulation of the authentication attempts. See bug:MID-10502[].
* Fixed loading the fresh user object on the Self Service Credentials page. See bug:MID-10544[].
* Fixed saving schema extension. See bug:MID-10437[].
* Fixed creation of the new generic PolicyType. See bug:MID-10463[].
* Fixed Access Request checkout step when validity is set to mandatory. See bug:MID-10459[].
* Fixed import object with ObjectReferenceType extension attribute. See bug:MID-10503[].
* Fixed deny rule for task delete operation. See bug:MID-10625[].
* Fixed setting of the assignment subtype. See bug:MID-10624[].
* Fixed sorting in the All Tasks table. See bug:MID-10640[].
* Fixed incorrect message while approving a work item. See bug:MID-10629[].
* Fixed Reconciliation report running. See bug:MID-10436[].
* Fixed displaying the list of the application classifications. See bug:MID-10638[].
* Fixed Object collection search item visibility on object list pages. See bug:MID-10648[].
* Fixed mark (*) visibility on the custom forms. See bug:MID-10656[].
* Fixed manual unlock of the user. See bug:MID-9856[].
* Improved the message on the mail nonce module panel during Reset password flow. See bug:MID-10679[].
* Fixed case details page displaying. See bug:MID-10690[].
* Fixed schema fetch error. See bug:MID-10665[].
* Connid version was upgraded to 1.6.0.0. See bug:MID-10552[].
* Fixed the error during saving the extension schema if there is ObjectReferenceType item. See bug:MID-10693[].
* Fixed the search with upper case letters on the Projections panel. See bug:MID-10713[].
* Fixed the initialization process of resource connector capabilities. See bug:MID-10644[], bug:MID-10676[].
* Fixed the usage and application of the archetype filter within authentication definition. See bug:MID-10683[].
* Fixed the reflexion of the custom system name on different pages. See bug:MID-10696[].
* Fixed the query for the certification items while loading self dashboard page. See bug:MID-10753[].
* Refactored container properties panel (e.g. object details page) not to wrap each property value field into a form.
This reduced the number of the csrf fields which is sent by request after the form submitting.
Also, increased the size of the http request header size to cope with big headers.
See bug:MID-10748[].
* Fixed "Select all" functionality in the assignment restriction popup while creating a delegation. See bug:MID-10757[].
* Fixed loading and displaying the data on the Errors panel of the Task page. See bug:MID-10682[].
* Fixed NPE on the Internals configuration page. See bug:MID-10749[].
* Fixed "Matching rule" dropdown in Attribute override settings. See bug:MID-10710[].
* Fixed 500 error while creating an application role with a lack of permission. See bug:MID-10778[].

=== Releases Of Other Components

* New version (1.5.2.0) of xref:/connectors/connectors/org.identityconnectors.databasetable.DatabaseTableConnector/[DatabaseTable Connector] was released and bundled with midPoint. The connector suggest all names of columns for configuration properties related with name of column.

* New version (2.8) of xref:/connectors/connectors/com.evolveum.polygon.connector.csv.CsvConnector/[CSV Connector] was released and bundled with midPoint. The connector suggest all names of columns for configuration properties related with name of column.
** Fixed NPE with multivalue attributes when delimiter is not defined. (bug:MID-8609[]).
** Fix UTF-8 BOM character in csv file during of discovery functions. (bug:MID-9497[] and bug:MID-9498[]).

* New version (3.8) of xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[AD/LDAP Connector] was released and bundled with midPoint. The connector suggest all names of columns for configuration properties related with name of column.
** Native association support.
** Possibility to choose attributes that should not be returned by default.
** Possibility to choose to encode string values in case of the presence of non standard ASCII characters.
** Workaround for open-ldap mandatory member attribute.
** Possibility to specify used auxiliary object classes in connector configuration.
** Allow to send the LDAP_DIRSYNC_OBJECT_SECURITY flag in Active Directory sync request control.

++++
{% include release-quality.html %}
++++

=== Limitations

Following list provides summary of limitation of this midPoint release.

* Functionality that is marked as xref:/midpoint/versioning/experimental/[Experimental Functionality] is not supported for general use (yet).
Such features are not covered by midPoint support.
They are supported only for those subscribers that funded the development of this feature by the means of
xref:/support/subscription-sponsoring/[subscriptions and sponsoring] or for those that explicitly negotiated such support in their support contracts.

* MidPoint comes with bundled xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector].
Support for LDAP connector is included in standard midPoint support service, but there are limitations.
This "bundled" support only includes operations of LDAP connector that 100% compliant with LDAP standards.
Any non-standard functionality is explicitly excluded from the bundled support.
We strongly recommend to explicitly negotiate support for a specific LDAP server in your midPoint support contract.
Otherwise, only standard LDAP functionality is covered by the support.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector] page for more details.

* MidPoint comes with bundled xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)].
Support for AD connector is included in standard midPoint support service, but there are limitations.
Only some versions of Active Directory deployments are supported.
Basic AD operations are supported, but advanced operations may not be supported at all.
The connector does not claim to be feature-complete.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)] page for more details.

* MidPoint user interface has flexible (responsive) design, it is able to adapt to various screen sizes, including screen sizes used by some mobile devices.
However, midPoint administration interface is also quite complex, and it would be very difficult to correctly support all midPoint functionality on very small screens.
Therefore, midPoint often works well on larger mobile devices (tablets), but it is very likely to be problematic on small screens (mobile phones).
Even though midPoint may work well on mobile devices, the support for small screens is not included in standard midPoint subscription.
Partial support for small screens (e.g. only for self-service purposes) may be provided, but it has to be explicitly negotiated in a subscription contract.

* There are several add-ons and extensions for midPoint that are not explicitly distributed with midPoint.
This includes xrefv:/midpoint/reference/support-4.9/interfaces/midpoint-client-java/[Java client library],
various https://github.com/Evolveum/midpoint-samples[samples], scripts, connectors and other non-bundled items.
Support for these non-bundled items is limited.
Generally speaking, those non-bundled items are supported only for platform subscribers and those that explicitly negotiated the support in their contract.

* MidPoint contains a basic case management user interface.
This part of midPoint user interface is not finished.
The only supported parts of this user interface are those that are used to process requests, approvals, and manual correlation.
Other parts of case management user interface are considered to be experimental, especially the parts dealing with manual provisioning cases.

This list is just an overview, it may not be complete.
Please see the documentation regarding detailed limitations of individual features.

== Platforms

MidPoint is known to work well in the following deployment environment.
The following list is list of *tested* platforms, i.e. platforms that midPoint team or reliable partners personally tested with this release.
The version numbers in parentheses are the actual version numbers used for the tests.

It is very likely that midPoint will also work in similar environments.
But only the versions specified below are supported as part of midPoint subscription and support programs - unless a different version is explicitly agreed in the contract.

=== Operating System

MidPoint is likely to work on any operating system that supports the Java platform.
However, for *production deployment*, only some operating systems are supported:

* Linux (x86_64)
* Windows Server (2022)

We are positive that midPoint can be successfully installed on other operating systems, especially macOS and Microsoft Windows desktop.
Such installations can be used to for evaluation, demonstration or development purposes.
However, we do not support these operating systems for production environments.
The tooling for production use is not maintained, such as various run control (start/stop) scripts, low-level administration and migration tools, backup and recovery support and so on.
Please see xref:/midpoint/install/bare-installation/platform-support/[] for details.

Note that production deployments in Windows environments are supported only for LTS releases.

=== Java

Following Java platform versions are supported:

* Java 21.
This is a *recommended* platform.

* Java 17.

OpenJDK 21 is the recommended Java platform to run midPoint.

Support for Oracle builds of JDK is provided only for the period in which Oracle provides public support (free updates) for their builds.

MidPoint is an open source project, and as such it relies on open source components.
We cannot provide support for platform that do not have public updates as we would not have access to those updates, and therefore we cannot reproduce and fix issues.
Use of open source OpenJDK builds with public support is recommended instead of proprietary builds.

=== Databases

Since midPoint 4.4, midPoint comes with two repository implementations: _native_ and _generic_.
Native PostgreSQL repository implementation is strongly recommended for all production deployments.

See xrefv:/midpoint/reference/support-4.9/repository/repository-database-support/[] for more details.

Since midPoint 4.0, *PostgreSQL is the recommended database* for midPoint deployments.
Our strategy is to officially support the latest stable version of PostgreSQL database (to the practically possible extent).
PostgreSQL database is the only database with clear long-term support plan in midPoint.
We make no commitments for future support of any other database engines.
See xrefv:/midpoint/reference/support-4.9/repository/repository-database-support/[] page for the details.
Only a direct connection from midPoint to the database engine is supported.
Database and/or SQL proxies, database load balancers or any other devices (e.g. firewalls) that alter the communication are not supported.

==== Native Database Support

xrefv:/midpoint/reference/support-4.9/repository/native-postgresql/[Native PostgreSQL repository implementation] is developed and tuned
specially for PostgreSQL database, taking advantage of native database features, providing improved performance and scalability.

This is now the *primary and recommended repository* for midPoint deployments.
Following database engines are supported:

* PostgreSQL 16, 15, 14

PostgreSQL 16 is recommended.

==== Generic Database Support (deprecated)

xrefv:/midpoint/reference/support-4.9/repository/generic/[Generic repository implementation] is based on object-relational
mapping abstraction (Hibernate), supporting several database engines with the same code.
Following database engines are supported with this implementation:

* Oracle 21c, 23ai
* Microsoft SQL Server 2019

Support for xrefv:/midpoint/reference/support-4.9/repository/generic/[generic repository implementation] together with all the database engines supported by this implementation is *deprecated*.
It is *strongly recommended* to migrate to xrefv:/midpoint/reference/support-4.9/repository/native-postgresql/[native PostgreSQL repository implementation] as soon as possible.
See xrefv:/midpoint/reference/support-4.9/repository/repository-database-support/[] for more details.

=== Supported Browsers

* Firefox
* Safari
* Chrome
* Edge
* Opera

Any recent version of the browsers is supported.
That means any stable stock version of the browser released in the last two years.
We formally support only stock, non-customized versions of the browsers without any extensions or other add-ons.
According to the experience most extensions should work fine with midPoint.
However, it is not possible to test midPoint with all of them and support all of them.
Therefore, if you chose to use extensions or customize the browser in any non-standard way you are doing that on your own risk.
We reserve the right not to support customized web browsers.

== Important Bundled Components

.Important bundled components
[%autowidth]
|===
| Component | Version | Description

| Tomcat
| 10.1.28
| Web container

| ConnId
| 1.6.0.0-RC1
| ConnId Connector Framework

| xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP connector bundle]
| 3.9.1
| LDAP and Active Directory

| xref:/connectors/connectors/com.evolveum.polygon.connector.csv.CsvConnector/[CSV connector]
| 2.8
| Connector for CSV files

| xref:/connectors/connectors/org.identityconnectors.databasetable.DatabaseTableConnector/[DatabaseTable connector]
| 1.5.2.0
| Connector for simple database tables

|===

++++
{% include release-download.html %}
++++

== Upgrade

MidPoint is a software designed with easy upgradeability in mind.
We do our best to maintain strong backward compatibility of midPoint data model, configuration and system behavior.
However, midPoint is also very flexible and comprehensive software system with a very rich data model.
It is not humanly possible to test all the potential upgrade paths and scenarios.
Also, some changes in midPoint behavior are inevitable to maintain midPoint development pace.
Therefore, there may be some manual actions and configuration changes that need to be done during upgrades,
mostly related to xref:/midpoint/versioning/feature-lifecycle/[feature lifecycle].

This section provides overall overview of the changes and upgrade procedures.
Although we try to our best, it is not possible to foresee all possible uses of midPoint.
Therefore, the information provided in this section are for information purposes only without any guarantees of completeness.
In case of any doubts about upgrade or behavior changes please use services associated with xref:/support/subscription-sponsoring/[midPoint subscription programs].

Please refer to the xrefv:/midpoint/reference/support-4.9/upgrade/upgrade-guide/[] for general instructions and description of the upgrade process.
The guide describes the steps applicable for upgrades of all midPoint releases.
Following sections provide details regarding release {release-version}.

=== Upgrade From MidPoint 4.8

MidPoint {release-version} data model is backwards compatible with previous midPoint version.
Please follow our xrefv:/midpoint/reference/support-4.9/upgrade/upgrade-guide/[Upgrade guide] carefully.

[IMPORTANT]
Be sure to be on the latest maintenance version for 4.8, otherwise you will not be warned about all the necessary schema changes and other possible incompatibilities.

Note that:

 * There are database schema changes (see xrefv:/midpoint/reference/support-4.9/upgrade/database-schema-upgrade/[Database schema upgrade]).

 * Version numbers of some bundled connectors have changed.
 Connector references from the resource definitions that are using the bundled connectors need to be updated.

 * See also the _Actions required_ information below.

// It is strongly recommended migrating to the xrefv:/midpoint/reference/support-4.9/repository/native-postgresql/[new native PostgreSQL repository implementation]
// for all deployments that have not migrated yet.
// However, it is *not* recommended upgrading the system and migrating the repositories in one step.
// It is recommended doing it in two separate steps.
// Please see xrefv:/midpoint/reference/support-4.9/repository/native-postgresql/migration/[] for the details.

=== Upgrade From Other MidPoint Versions

Upgrade from midPoint versions other than 4.8.x to midPoint {release-version} is not supported directly.
Please upgrade to 4.8.5 first.

=== Deprecation, Feature Removal And Major Incompatible Changes Since 4.8

NOTE: This section is relevant to the majority of midPoint deployments.
It refers to the most significant functionality removals and changes in this version.

// * The `mailNonce` and `securityQuestionsForm` authentication modules were re-worked.
// Since 4.8, we won't support authentication sequences with only `mailNonce` or only `securityQuestionsForm` module defined for password reset flow.
// These modules have to be used together with `focusIdentification` module.
// So, once the `mailNonce` or `securityQuestionsForm` module is executed, we already have information about the user who's trying to perform action (either password reset or login or anything else using flexible authentication sequence except registration/invitation flows).
// These modules cannot be first in the sequence and cannot be alone.
// Also added support to automatically remove nonce after successful authentication.
//
// * Another change concerns reset password functionality.
// Since 4.8, the user should be granted with `http://midpoint.evolveum.com/xml/ns/public/security/authorization-ui-3#resetPassword` authorization to be able to use Reset password feature.
//
// * The support for XML filters was removed from the GUI.
// Since 4.8 we recommend to use midPoint (axiom) query language instead.
// Query converter was improved to provide the possibility to convert XML filters to midPoint query language.
//
// * Ninja command line options were consolidated, some options were renamed.
// More info xrefv:/midpoint/reference/support-4.9/deployment/ninja[here] and in bug:MID-7483[].

=== Changes In Initial Objects Since 4.9

NOTE: This section is relevant to the majority of midPoint deployments.

MidPoint has a built-in set of "initial objects" that it will automatically create in the database if they are not present.
This includes vital objects for the system to be configured (e.g., the role `Superuser` and the user `administrator`).
These objects may change in some midPoint releases.
However, midPoint is conservative and avoids overwriting customized configuration objects.
Therefore, midPoint does not overwrite existing objects when they are already in the database.
This may result in upgrade problems if the existing object contains configuration that is no longer supported in a new version.

The following list contains a description of changes to the initial objects in this midPoint release.
The complete new set of initial objects is in the `config/initial-objects` directory in both the source and binary distributions.

_Actions required:_ Please review the changes and apply them appropriately to your configuration. Ninja can help with updating existing initial objects during upgrade procedure using `initial-objects` command.
For more information see xrefv:/midpoint/reference/support-4.9/deployment/ninja/use-case/upgrade-with-ninja/#initial-objects[here].

* 536-archetype-task-certification-start-campaign.xml: task activity panel was fixed to display the data from the certificationStartCampaign container.
* 538-archetype-task-certification-reiterate-campaign.xml: task activity panel was fixed to display the data from the certificationReiterateCampaign container.
* 029-archetype-application.xml: fixed the displaying of the application classifications.
* 028-archetype-application-role.xml: fixed the plural label.
* 041-role-approver.xml: added manualProvisioningContext item to read authorization of the CaseType object in order to correctly display case details page.
* 010-value-policy.xml: improved localization

Please review link:https://github.com/Evolveum/midpoint/commits/master/gui/admin-gui/src/main/resources/initial-objects[source code history] for detailed list of changes.

TIP: Copies of initial object files are located in `config/initial-objects` directory of midPoint distribution packages. These files can be used as a reference during upgrades.
On-line version can be found in https://github.com/Evolveum/midpoint/tree/v{release-version}/config/initial-objects[midPoint source code].

=== Schema Changes Since 4.9

NOTE: This section is relevant to the majority of midPoint deployments.
It describes what data items were marked as deprecated, or removed altogether from the schema.
You should at least scan through it - or use the `ninja` tool to check the deprecations for you.

.Items being deprecated
[%autowidth]
|===
| Type | Item or value | Note
| `AccessCertificationConfigurationType`
| `availableResponse`
| Configure actions in the cert. items collection view instead.

| `ItemRefinedDefinitionType`
| `emphasized`
| Use `displayHint` instead.

| `ResourceObjectTypeDefinitionType`
| `association`
| Use association types (in schemaHandling) instead.

| `ResourceObjectTypeDefinitionType`
| `protected`
| Use "marking" instead.

| `ShadowType`
| `association`
| Legacy associations of this shadow. Not used anymore.

| `SynchronizationActionsType`
| `unlink`
| Use `<synchronize/>` action instead.
|===

The `synchronize/membership` container was added to the object operation policy object, present in xrefv:/midpoint/reference/support-4.9/concepts/mark/[object marks] (like the `Protected` one).
It controls the handling of the membership of entitlements possessing given object mark.

_Actions required:_

* Inspect your configuration for deprecated items, and replace them by their suggested equivalents.
Make sure you don't use any removed items.
You can use `ninja` tool for this.

* Be sure to apply the changes to initial objects 800-804 (object marks), as well as to your custom object marks to handle the membership in the expected way.

[#_behavior_changes_since_4_9]
=== Behavior Changes Since 4.9

* The contract for `ModificationsSupplier` in dynamic object modifications (repo API) was changed.
+
The original approach was that the caller, i.e., repository, cloned the existing object before handling it to the callback (modifications supplier).
Now, the implementor of the callback is responsible for not modifying the provided object in any way.

* Projections with denied access no longer cause "preview changes" operation to fail.
+
If a user has no authorization to see particular projection (shadow), the "preview changes" operation used to finish with "Access denied" fatal error even if there were parts of the result visible to the user.
This is now changed (fixed): only the relevant projections are hidden now.
All the remaining data are displayed to the user.
See also bug:MID-10397[].

[#_behavior_changes_since_4_8]
=== Behavior Changes Since 4.8

[NOTE]
====
This section describes changes in the behavior that existed before this release.
New behavior is not mentioned here.
Plain bugfixes (correcting incorrect behavior) are skipped too.
Only things that cannot be described as simple "fixing" something are described here.

The changes since 4.8 are of interest probably for "advanced" midPoint deployments only.
You should at least scan through them, though.
====

* Checking for conflicts for single-valued items was fixed (strengthened).
In 4.8.3 and before, there were situations that two strong mappings produced different values for a given single-valued item, yet no error was produced.
(If the item contained the same value that was produced by one of these mappings.)
Such configurations are in principle unstable, so this kind of errors should be identified and fixed.
Please see bug:MID-9621[] and https://github.com/Evolveum/midpoint/commit/22e2d8429e269e4c54b19c3e2df153b9fbfd1437[this commit].

* The default configuration for caching was changed.
Currently, only the attributes defined in `schemaHandling` are cached by default.
(Except for the situation when the caching is enabled by `cachingOnly` property in the read capability.)

* When processing live sync changes that contain only the object identifiers, a more aggressive approach to fetching actual objects was adopted:
We now always fetch the actual object, if possible.
The reason is that the cached version may be incomplete or outdated.

* The behavior of `disableTimestamp` and `disableReason` in the shadow activation container was changed.
Before 4.9/4.8.1, these properties were updated only if there was an actual change in the administrative status from something to `DISABLED`.
Since 4.9/4.8.1, both of these properties are updated even if the administrative status is already `DISABLED`:
the `disableReason` is determined anew, and the `disableTimestamp` is updated if the status and/or the reason are modified.
See bug:MID-9220[].

* Automatic caching of association binding attributes (the "value" side, i.e. `valueAttribute` in the association definition) is no longer provided.
It is recommended to mark them as secondary identifiers.

* The filtering of associations was changed slightly.
In particular, even if the required auxiliary object class is not present for the subject, the association values are still shown - if they exist on the resource.
(They were hidden before.)

* To address bug:MID-9638[] and bug:MID-9670[] (leaking data via searching objects by filters), the handling of items allowed for search operations was changed.

It is now evaluated not only for the type we are searching for (like `RoleType`), but for all types whose items are to be used for the search (like `UserType` for a filter like "give me `RoleType` `referencedBy` `UserType` via `assignment/targetRef`").

The checks are "yes/no" style only, based on the presence or absence of authorizations against specified type and item(s), with appropriate action URIs (read, search, and the new searchBy).
No detailed checking for the values is done. E.g. if the search for `UserType:name` is allowed even for potentially a single user object (via an authorization clause that can provide any number of matching objects, even zero), then the `name` item can be used for any search concerning `UserType` or even `FocusType` objects.

Effects on existing deployments:

. Some queries allowed previously may now fail because of missing item-searching authorizations.
As a quick fix, new (experimental, temporary) `searchBy` authorization is available to give search access to these items without providing any additional access to data values.

. Some queries denied previously may now be allowed.
This should be quite rare, but possible.
It can happen if the original authorization was not applied because of some specific limitations (like `roleRelation` with no explicit role information), and hence the `item`/`exceptItem` part of it was skipped.
This is no longer the case.

See link:https://github.com/Evolveum/midpoint/commit/60928672b8e51946edf01fcbe0d253e4ae65c4cf[commit 609286].

* The `effectiveMarkRef` item now has value metadata to determine the values' origin. See link:https://github.com/Evolveum/midpoint/commit/351d7e4718bef9ac90dffde8920bc7d536f42e84[commit 351d7e].

* The mapping specification in provenance metadata now contains also object type name, association type name, and the shadow tag.
See xrefv:/midpoint/reference/support-4.9/expressions/mappings/#_mapping_maintenance_tasks[Mapping Maintenance Tasks], link:https://github.com/Evolveum/midpoint/commit/0dd1c011d9bc99fae037a4e27cb583cbd43da5bb[commit 0dd1c0], and link:https://github.com/Evolveum/midpoint/commit/8557f5945222ac2a7c535f0d0458af725442b61b[commit 8557f5].

* "<a:indexed/>" and "<a:indexOnly/>" annotations - when present but without any value - was interpreted as "false".
This was now changed to a more intuitive interpretation (similar to a:object, a:container, etc), where annotation present but without value means "true".
Also, "a:container" and other markers were interpreted as "true", even if the value was actually "false".
This is now fixed as well.

* Years-old ref-style schema annotations like <r:identifier ref="icfs:uid"/> are no longer supported.
They are not used since midPoint 2.0.
If you happen to use them in your manually configured resource XSD schemas, please replace them with the supported <r:identifier>icfs:uid</r:identifier> style.

* Support for getting/setting objects embedded in references marked as `a:objectReference` directly, like `LensElementContext.getObjectOld()`.
This feature was used only internally by midPoint.

* The `<xsd:documentation>` element in resource schemas is now ignored.
It was never used by ConnId connectors, but, in theory, it might be used for manually entered schemas.

* Default target set for mappings emitting multivalue properties is based on provenance metadata, mapping can only remove values, it added.
** If value has multiple provenances (user entry, or multiple mappings), the mapping removes only its provenance section, value still remains.

NOTE: The addition of the value metadata at various places of objects means that the objects are larger than in previous versions of midPoint.
In a similar way, the shadow caching feature - enabled by default for new installations - will probably increase the size of shadow objects further.
All this will probably have an impact on the database size as well as on the runtime performance.
(The exact proportions depend on specifics of the deployment.)
All these features can be configured - or even turned off in the extreme case - so you can do your own tradeoff between functionality and performance.
Moreover, we plan to improve the performance in the forthcoming releases.

=== Java and REST API Changes Since 4.8

NOTE: As for the Java API, this section describes changes in `midpoint` and `basic` function libraries.
(MidPoint does not have explicitly defined Java API, yet.
But these two objects are something that can be unofficially considered to be the API of midPoint, usable e.g. from scripts.)

// * Some of `javax` namespaces were migrated to `jakarta` namespaces, due to upgrade of Spring and Groovy 4. This may affect your scripts / overlays if you were using them. Most notable is `javax.xml.bind`, which was migrated to `jakarta.xml.bind`.
// ** Most notable rename for Groovy scripts is `javax.xml.bind.JAXBElement` to `jakarta.xml.bind.JAXBElement`.
//
// * Groovy was updated to version 4, which changed some of exposed java package names. See https://groovy-lang.org/releasenotes/groovy-4.0.html[Groovy 4.0 Release Notes] for more details.
//
// * The following methods were not checking authorizations of currently logged-in user, and were fixed to do so:
// `midpoint.countAccounts`, `midpoint.getObjectsInConflictOnPropertyValue`, `midpoint.isUniquePropertyValue`.
// See bug:MID-6241[] and commit https://github.com/Evolveum/midpoint/commit/1471bba52e363f81feabbec6f997507d8a7655fb[1471bb].

=== Internal Changes Since 4.8

NOTE: These changes should not influence people that use midPoint "as is".
They should also not influence the XML/JSON/YAML-based customizations or scripting expressions that rely just on the provided library classes.
These changes will influence midPoint forks and deployments that are heavily customized using the Java components.

* Internal APIs were massively changed with regard to passing `prismContext` object between methods.
This object has been statically available for quite a long time.
Now it was definitely removed from methods' signatures.
+
*The official APIs (like `midpoint` and `basic` objects) were not touched by this change.
However, if you use some of the unofficial or undocumented APIs, please make sure you migrate your code appropriately.*
+
The change itself is very simple: basically, the `PrismContext` parameter was removed from methods' signatures.

* Likewise, the internals of prism definitions were changed in https://github.com/Evolveum/prism/commit/12808dc91f4ea358dda3666cd0b01eba7d08300c[12808d].
You should not be affected by this; however, if you use some of the unofficial/undocumented APIs, please check your code.

// * The post-processing of retrieved objects in the IDM Model subsystem (sometimes called "apply schemas and security") was xref:/midpoint/devel/design/apply-schemas-and-security-4.8/summary.adoc[simplified].
//
// * Internal `SearchBasedActivityRunSpecifics` interface was changed.
// This may affect those deployments that provide their own activity handlers.
// See https://github.com/Evolveum/midpoint/commit/12f6f66d[12f6f66d].


++++
{% include release-issues.html %}
++++
