---
layout: release
release-version: '4.10'
visibility: hidden
---
= MidPoint 4.10
:release-version: 4.10
:page-visibility: hidden
:page-liquid:
:page-toc: top

Release {release-version} is a sixtieth midPoint release, code-named _Verne_.
The {release-version} release brings improvements in role engineering, certification, approvals, stability and miscellaneous improvements.

++++
{% include release-data.html %}
++++

++++
{% capture dedicationContent %}
<p>
<a href="https://en.wikipedia.org/wiki/Jules_Verne">Jules Gabriel Verne</a> (1828-1905) was a French novelist, poet, and playwright.
His best-selling novels, always well-researched according to the scientific knowledge then available, taking into account the technological advances of the time.
Verne, considered to be one of the fathers of science-fiction genre, inspired several generations of readers.
</p>
<p>
Similarly to Verne's novels, midPoint 4.9 brings several technological advancements, bringing them from the drawing board to real life.
Shadow caching and value metadata were prototyped a long time ago, they became production-quality reality in midPoint 4.9.
Improvements in role mining and brand-new outlier detection functionality are reaching up to the boundaries of science fiction.
The new access certification look and feel is reminiscent of the colorful worlds that Verne has described.
Other features and improvements of this release make midPoint more complete, easier to use and much more sophisticated.
Overall, midPoint 4.9 is a major step from the past into the future.
</p>
{% endcapture %}
{% include release-dedication.html content=dedicationContent %}
++++

== Changes With Respect To Version 4.9

=== New Features and Major Improvements

* bug:MID-10147[] Added support for new capability `lastLoginTimestamp`.
* bug:MID-10213[] Fix synchronization of large number of tasks (>10 000).
* bug:MID-10270[] Summary panel for roles now uses display name and identifier (same as for organizations and services).
* bug:MID-10204[] Fix error during preview of changes.
* bug:MID-10319[] Fixed incorrect error message displayed when performing "Unlock" action on user list page.
* bug:MID-10317[] Fixed missing message when user disable fails.
* bug:MID-10320[] Fixed ninja zip option used during export/import.
* bug:MID-10218[] Task execution constraints added to advanced options tab.
* bug:MID-10216[] Support exclusion of metadata in `get`/`search` rest APIs.
* bug:MID-10305[] Remove max password length constraint.
* bug:MID-10048[] Fix ClassCastException when creating duplicates of object types with new archetype
* bug:MID-9300[] Secure schema usage in PostgresSQL (not using public schema).

=== Other Improvements

* Implemented xrefv:/midpoint/reference/support-4.9/resources/attribute-caching/#_caching_passwords[shadow password caching], with the possibility of storing them in reversible encrypted form.
* Improved handling of xrefv:/midpoint/reference/support-4.9/resources/resource-configuration/schema-handling/volatility/[volatile shadow attributes].
* Update GUI views after changing of the archetype, that is used in the view. See bug:MID-9776[].
* Adding support for PKCE (Proof Key for Code Exchange) as additional security for OIDC authentication module. See bug:MID-10155[].
* Adding new configuration attribute for OIDC authentication module, that is used for ID Token signing algorithm. See xref:/midpoint/reference/security/authentication/flexible-authentication/modules/oidc/[Oidc Module].
* Apply the Web Content Accessibility Guidelines (WCAG) to all login pages and self-service pages. See bug:MID-9847[].
** Used 'honeypot' instead of captcha on self-registration and post-authentication pages to protect against spam bots.
* Improved the documentation on the resource configuration. See bug:MID-10176[].

=== Other Bug Fixes

* Fixed "Couldn't get assignments conflicts" error occurring during Request access. See bug:MID-10124[].
* Fixed "No definition for item ... in outbound mapping for association" error. See bug:MID-10214[].
* Fixed the issue with policy rules `minAssignees`/`maxAssignees` not being triggered. See bug:MID-9869[].
* Fixed retrieving referenced objects with their own references when caching is enabled. See bug:MID-10271[].
* Fixed inconsistent behaviour for `deleted` situation in combination with `deleteFocus` reaction. See bug:MID-10195[].
* Fixed midPoint freezing when shadow partitioning, referenced objects, and shadow caching was used. See bug:MID-10231[].
* Added support for removing "dangling" non-tolerant reference attribute values (i.e., those that do not match any association). See bug:MID-10285[].
* Changes in default shadow caching policy are now correctly applied, without requiring any action on the user side. See bug:MID-10126[].
* Fixed `NullPointerException` occurring in mappings when the source reference value pointed to non-existing object. See bug:MID-10162[].
* "Native references" capability is now correctly shown in GUI. See bug:MID-10194[].
* Fixed handling of multi-valued resource configuration properties defined using `const` expression. See the last comment in bug:MID-7918[].
* Fixed repeated modifications of objects when manually attached object marks were used. See bug:MID-10121[].
* Fixed preview changes when auto-assigned roles with approvals were used. See bug:MID-10345[].
* Stopped generating passwords with "problematic" characters, like comma, apostrophe, ampersand, and so on.
Now it's possible to define characters that are accepted in the password, but not used when generating a new password value.
The default password policy was updated in this regard.
See bug:MID-9541[].
* Stopped displaying some shadow operational properties (like the synchronization timestamp, iteration, and so on) among changes in simulation results.
See bug:MID-9737[] and bug:MID-9986[].

=== Releases Of Other Components

* New version (1.5.2.0) of xref:/connectors/connectors/org.identityconnectors.databasetable.DatabaseTableConnector/[DatabaseTable Connector] was released and bundled with midPoint. The connector suggest all names of columns for configuration properties related with name of column.

* New version (2.8) of xref:/connectors/connectors/com.evolveum.polygon.connector.csv.CsvConnector/[CSV Connector] was released and bundled with midPoint. The connector suggest all names of columns for configuration properties related with name of column.
** Fixed NPE with multivalue attributes when delimiter is not defined. (bug:MID-8609[]).
** Fix UTF-8 BOM character in csv file during of discovery functions. (bug:MID-9497[] and bug:MID-9498[]).

* New version (3.8) of xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[AD/LDAP Connector] was released and bundled with midPoint. The connector suggest all names of columns for configuration properties related with name of column.
** Native association support.
** Possibility to choose attributes that should not be returned by default.
** Possibility to choose to encode string values in case of the presence of non standard ASCII characters.
** Workaround for open-ldap mandatory member attribute.
** Possibility to specify used auxiliary object classes in connector configuration.
** Allow to send the LDAP_DIRSYNC_OBJECT_SECURITY flag in Active Directory sync request control.

++++
{% include release-quality.html %}
++++

=== Limitations

Following list provides summary of limitation of this midPoint release.

* Functionality that is marked as xref:/midpoint/versioning/experimental/[Experimental Functionality] is not supported for general use (yet).
Such features are not covered by midPoint support.
They are supported only for those subscribers that funded the development of this feature by the means of
xref:/support/subscription-sponsoring/[subscriptions and sponsoring] or for those that explicitly negotiated such support in their support contracts.

* MidPoint comes with bundled xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector].
Support for LDAP connector is included in standard midPoint support service, but there are limitations.
This "bundled" support only includes operations of LDAP connector that 100% compliant with LDAP standards.
Any non-standard functionality is explicitly excluded from the bundled support.
We strongly recommend to explicitly negotiate support for a specific LDAP server in your midPoint support contract.
Otherwise, only standard LDAP functionality is covered by the support.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector] page for more details.

* MidPoint comes with bundled xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)].
Support for AD connector is included in standard midPoint support service, but there are limitations.
Only some versions of Active Directory deployments are supported.
Basic AD operations are supported, but advanced operations may not be supported at all.
The connector does not claim to be feature-complete.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)] page for more details.

* MidPoint user interface has flexible (responsive) design, it is able to adapt to various screen sizes, including screen sizes used by some mobile devices.
However, midPoint administration interface is also quite complex, and it would be very difficult to correctly support all midPoint functionality on very small screens.
Therefore, midPoint often works well on larger mobile devices (tablets), but it is very likely to be problematic on small screens (mobile phones).
Even though midPoint may work well on mobile devices, the support for small screens is not included in standard midPoint subscription.
Partial support for small screens (e.g. only for self-service purposes) may be provided, but it has to be explicitly negotiated in a subscription contract.

* There are several add-ons and extensions for midPoint that are not explicitly distributed with midPoint.
This includes xrefv:/midpoint/reference/support-4.9/interfaces/midpoint-client-java/[Java client library],
various https://github.com/Evolveum/midpoint-samples[samples], scripts, connectors and other non-bundled items.
Support for these non-bundled items is limited.
Generally speaking, those non-bundled items are supported only for platform subscribers and those that explicitly negotiated the support in their contract.

* MidPoint contains a basic case management user interface.
This part of midPoint user interface is not finished.
The only supported parts of this user interface are those that are used to process requests, approvals, and manual correlation.
Other parts of case management user interface are considered to be experimental, especially the parts dealing with manual provisioning cases.

This list is just an overview, it may not be complete.
Please see the documentation regarding detailed limitations of individual features.

== Platforms

MidPoint is known to work well in the following deployment environment.
The following list is list of *tested* platforms, i.e. platforms that midPoint team or reliable partners personally tested with this release.
The version numbers in parentheses are the actual version numbers used for the tests.

It is very likely that midPoint will also work in similar environments.
But only the versions specified below are supported as part of midPoint subscription and support programs - unless a different version is explicitly agreed in the contract.

=== Operating System

MidPoint is likely to work on any operating system that supports the Java platform.
However, for *production deployment*, only some operating systems are supported:

* Linux (x86_64)
* Windows Server (2022)

We are positive that midPoint can be successfully installed on other operating systems, especially macOS and Microsoft Windows desktop.
Such installations can be used to for evaluation, demonstration or development purposes.
However, we do not support these operating systems for production environments.
The tooling for production use is not maintained, such as various run control (start/stop) scripts, low-level administration and migration tools, backup and recovery support and so on.
Please see xref:/midpoint/install/bare-installation/platform-support/[] for details.

Note that production deployments in Windows environments are supported only for LTS releases.

=== Java

Following Java platform versions are supported:

* Java 21.
This is a *recommended* platform.

* Java 17.

OpenJDK 21 is the recommended Java platform to run midPoint.

Support for Oracle builds of JDK is provided only for the period in which Oracle provides public support (free updates) for their builds.

MidPoint is an open source project, and as such it relies on open source components.
We cannot provide support for platform that do not have public updates as we would not have access to those updates, and therefore we cannot reproduce and fix issues.
Use of open source OpenJDK builds with public support is recommended instead of proprietary builds.

=== Databases

Since midPoint 4.4, midPoint comes with two repository implementations: _native_ and _generic_.
Native PostgreSQL repository implementation is strongly recommended for all production deployments.

See xrefv:/midpoint/reference/support-4.9/repository/repository-database-support/[] for more details.

Since midPoint 4.0, *PostgreSQL is the recommended database* for midPoint deployments.
Our strategy is to officially support the latest stable version of PostgreSQL database (to the practically possible extent).
PostgreSQL database is the only database with clear long-term support plan in midPoint.
We make no commitments for future support of any other database engines.
See xrefv:/midpoint/reference/support-4.9/repository/repository-database-support/[] page for the details.
Only a direct connection from midPoint to the database engine is supported.
Database and/or SQL proxies, database load balancers or any other devices (e.g. firewalls) that alter the communication are not supported.

==== Native Database Support

xrefv:/midpoint/reference/support-4.9/repository/native-postgresql/[Native PostgreSQL repository implementation] is developed and tuned
specially for PostgreSQL database, taking advantage of native database features, providing improved performance and scalability.

This is now the *primary and recommended repository* for midPoint deployments.
Following database engines are supported:

* PostgreSQL 16, 15, 14

PostgreSQL 16 is recommended.

==== Generic Database Support (deprecated)

xrefv:/midpoint/reference/support-4.9/repository/generic/[Generic repository implementation] is based on object-relational
mapping abstraction (Hibernate), supporting several database engines with the same code.
Following database engines are supported with this implementation:

* Oracle 21c
* Microsoft SQL Server 2019

Support for xrefv:/midpoint/reference/support-4.9/repository/generic/[generic repository implementation] together with all the database engines supported by this implementation is *deprecated*.
It is *strongly recommended* to migrate to xrefv:/midpoint/reference/support-4.9/repository/native-postgresql/[native PostgreSQL repository implementation] as soon as possible.
See xrefv:/midpoint/reference/support-4.9/repository/repository-database-support/[] for more details.

=== Supported Browsers

* Firefox
* Safari
* Chrome
* Edge
* Opera

Any recent version of the browsers is supported.
That means any stable stock version of the browser released in the last two years.
We formally support only stock, non-customized versions of the browsers without any extensions or other add-ons.
According to the experience most extensions should work fine with midPoint.
However, it is not possible to test midPoint with all of them and support all of them.
Therefore, if you chose to use extensions or customize the browser in any non-standard way you are doing that on your own risk.
We reserve the right not to support customized web browsers.

== Important Bundled Components

.Important bundled components
[%autowidth]
|===
| Component | Version | Description

| Tomcat
| 10.1.28
| Web container

| ConnId
| 1.6.0.0-RC1
| ConnId Connector Framework

| xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP connector bundle]
| 3.8
| LDAP and Active Directory

| xref:/connectors/connectors/com.evolveum.polygon.connector.csv.CsvConnector/[CSV connector]
| 2.8
| Connector for CSV files

| xref:/connectors/connectors/org.identityconnectors.databasetable.DatabaseTableConnector/[DatabaseTable connector]
| 1.5.2.0
| Connector for simple database tables

|===

++++
{% include release-download.html %}
++++

== Upgrade

MidPoint is a software designed with easy upgradeability in mind.
We do our best to maintain strong backward compatibility of midPoint data model, configuration and system behavior.
However, midPoint is also very flexible and comprehensive software system with a very rich data model.
It is not humanly possible to test all the potential upgrade paths and scenarios.
Also, some changes in midPoint behavior are inevitable to maintain midPoint development pace.
Therefore, there may be some manual actions and configuration changes that need to be done during upgrades,
mostly related to xref:/midpoint/versioning/feature-lifecycle/[feature lifecycle].

This section provides overall overview of the changes and upgrade procedures.
Although we try to our best, it is not possible to foresee all possible uses of midPoint.
Therefore, the information provided in this section are for information purposes only without any guarantees of completeness.
In case of any doubts about upgrade or behavior changes please use services associated with xref:/support/subscription-sponsoring/[midPoint subscription programs].

Please refer to the xrefv:/midpoint/reference/support-4.9/upgrade/upgrade-guide/[] for general instructions and description of the upgrade process.
The guide describes the steps applicable for upgrades of all midPoint releases.
Following sections provide details regarding release {release-version}.

=== Upgrade From MidPoint 4.8

MidPoint {release-version} data model is backwards compatible with previous midPoint version.
Please follow our xrefv:/midpoint/reference/support-4.9/upgrade/upgrade-guide/[Upgrade guide] carefully.

[IMPORTANT]
Be sure to be on the latest maintenance version for 4.8, otherwise you will not be warned about all the necessary schema changes and other possible incompatibilities.

Note that:

 * There are database schema changes (see xrefv:/midpoint/reference/support-4.9/upgrade/database-schema-upgrade/[Database schema upgrade]).

 * Version numbers of some bundled connectors have changed.
 Connector references from the resource definitions that are using the bundled connectors need to be updated.

 * See also the _Actions required_ information below.

// It is strongly recommended migrating to the xrefv:/midpoint/reference/support-4.9/repository/native-postgresql/[new native PostgreSQL repository implementation]
// for all deployments that have not migrated yet.
// However, it is *not* recommended upgrading the system and migrating the repositories in one step.
// It is recommended doing it in two separate steps.
// Please see xrefv:/midpoint/reference/support-4.9/repository/native-postgresql/migration/[] for the details.

=== Upgrade From Other MidPoint Versions

Upgrade from midPoint versions other than 4.8.x to midPoint {release-version} is not supported directly.
Please upgrade to 4.8.5 first.

=== Deprecation, Feature Removal And Major Incompatible Changes Since 4.8

NOTE: This section is relevant to the majority of midPoint deployments.
It refers to the most significant functionality removals and changes in this version.

// * The `mailNonce` and `securityQuestionsForm` authentication modules were re-worked.
// Since 4.8, we won't support authentication sequences with only `mailNonce` or only `securityQuestionsForm` module defined for password reset flow.
// These modules have to be used together with `focusIdentification` module.
// So, once the `mailNonce` or `securityQuestionsForm` module is executed, we already have information about the user who's trying to perform action (either password reset or login or anything else using flexible authentication sequence except registration/invitation flows).
// These modules cannot be first in the sequence and cannot be alone.
// Also added support to automatically remove nonce after successful authentication.
//
// * Another change concerns reset password functionality.
// Since 4.8, the user should be granted with `http://midpoint.evolveum.com/xml/ns/public/security/authorization-ui-3#resetPassword` authorization to be able to use Reset password feature.
//
// * The support for XML filters was removed from the GUI.
// Since 4.8 we recommend to use midPoint (axiom) query language instead.
// Query converter was improved to provide the possibility to convert XML filters to midPoint query language.
//
// * Ninja command line options were consolidated, some options were renamed.
// More info xrefv:/midpoint/reference/support-4.9/deployment/ninja[here] and in bug:MID-7483[].

=== Changes In Initial Objects Since 4.8

NOTE: This section is relevant to the majority of midPoint deployments.

MidPoint has a built-in set of "initial objects" that it will automatically create in the database if they are not present.
This includes vital objects for the system to be configured (e.g., the role `Superuser` and the user `administrator`).
These objects may change in some midPoint releases.
However, midPoint is conservative and avoids overwriting customized configuration objects.
Therefore, midPoint does not overwrite existing objects when they are already in the database.
This may result in upgrade problems if the existing object contains configuration that is no longer supported in a new version.

The following list contains a description of changes to the initial objects in this midPoint release.
The complete new set of initial objects is in the `config/initial-objects` directory in both the source and binary distributions.

_Actions required:_ Please review the changes and apply them appropriately to your configuration. Ninja can help with updating existing initial objects during upgrade procedure using `initial-objects` command.
For more information see xrefv:/midpoint/reference/support-4.9/deployment/ninja/use-case/upgrade-with-ninja/#initial-objects[here].

* 040-role-enduser.xml: The `End user` role was updated with a hidden visibility for `myCertificationItems` dashboard widget.
* 042-role-enduser.xml: The `Reviewer` role was extended with `myActiveCertificationCampaigns` UI authorization for active campaigns page and with more items of the certification campaign object to be read.
* 000-system-configuration.xml: The `SystemConfiguration` object was extended with a new dashboard widget configuration for certification items.
* 250-object-collection-resource.xml: The `All resources` object collection was updated with a filter to exclude resource templates.
* 251-object-collection-resource-up.xml: The `Resources up` object collection was updated with a filter to exclude resource templates.
* 520-archetype-task-certification.xml: Changes for proper functioning of certification related tasks.
* 534-archetype-task-certification-campaign-open-next-stage.xml: Archetype for campaign open next stage (start campaign) related task.
* 535-archetype-task-certification-remediation.xml: Archetype for campaign remediation related task.
* A set of initial objects was updated to extend polystring type elements with translation keys configuration.
The full set of changed objects you can see in the link:https://github.com/Evolveum/midpoint/commit/cf7cade899b8f663d90e5a9785037e0d0d1927c0[commit] with some further changes in the next commits: link:https://github.com/Evolveum/midpoint/commit/d381b6637139464ee967e5c553e1233ba1750499[archetype correlation case label fix], link:https://github.com/Evolveum/midpoint/commit/54f03f9b6e919d45a9651d22a71f796efa662989[fixes in system configuration object], link:https://github.com/Evolveum/midpoint/commit/54f03f9b6e919d45a9651d22a71f796efa662989[archetype and report objects fixes], link:https://github.com/Evolveum/midpoint/commit/16e3f923aaca7433452689565fa6ede40aab9573[application label fix].
* 029-archetype-application.xml: updated panels for application archetype.
* 700-archetype-event-mark.xml: updated admin gui configuration - hidden object operation policy panel.
* 800-804 marks: updated object operation policy membership.
* 030-role-superuser.xml: updated policy.

Please review link:https://github.com/Evolveum/midpoint/commits/master/gui/admin-gui/src/main/resources/initial-objects[source code history] for detailed list of changes.

TIP: Copies of initial object files are located in `config/initial-objects` directory of midPoint distribution packages. These files can be used as a reference during upgrades.
On-line version can be found in https://github.com/Evolveum/midpoint/tree/v{release-version}/config/initial-objects[midPoint source code].

=== Schema Changes Since 4.8

NOTE: This section is relevant to the majority of midPoint deployments.
It describes what data items were marked as deprecated, or removed altogether from the schema.
You should at least scan through it - or use the `ninja` tool to check the deprecations for you.

.Items being deprecated
[%autowidth]
|===
| Type | Item or value | Note
| `AccessCertificationConfigurationType`
| `availableResponse`
| Configure actions in the cert. items collection view instead.

| `ItemRefinedDefinitionType`
| `emphasized`
| Use `displayHint` instead.

| `ResourceObjectTypeDefinitionType`
| `association`
| Use association types (in schemaHandling) instead.

| `ResourceObjectTypeDefinitionType`
| `protected`
| Use "marking" instead.

| `ShadowType`
| `association`
| Legacy associations of this shadow. Not used anymore.

| `SynchronizationActionsType`
| `unlink`
| Use `<synchronize/>` action instead.
|===

The `synchronize/membership` container was added to the object operation policy object, present in xrefv:/midpoint/reference/support-4.9/concepts/mark/[object marks] (like the `Protected` one).
It controls the handling of the membership of entitlements possessing given object mark.

_Actions required:_

* Inspect your configuration for deprecated items, and replace them by their suggested equivalents.
Make sure you don't use any removed items.
You can use `ninja` tool for this.

* Be sure to apply the changes to initial objects 800-804 (object marks), as well as to your custom object marks to handle the membership in the expected way.

[#_behavior_changes_since_4_8]
=== Behavior Changes Since 4.8

[NOTE]
====
This section describes changes in the behavior that existed before this release.
New behavior is not mentioned here.
Plain bugfixes (correcting incorrect behavior) are skipped too.
Only things that cannot be described as simple "fixing" something are described here.

The changes since 4.8 are of interest probably for "advanced" midPoint deployments only.
You should at least scan through them, though.
====

* Checking for conflicts for single-valued items was fixed (strengthened).
In 4.8.3 and before, there were situations that two strong mappings produced different values for a given single-valued item, yet no error was produced.
(If the item contained the same value that was produced by one of these mappings.)
Such configurations are in principle unstable, so this kind of errors should be identified and fixed.
Please see bug:MID-9621[] and https://github.com/Evolveum/midpoint/commit/22e2d8429e269e4c54b19c3e2df153b9fbfd1437[this commit].

* The default configuration for caching was changed.
Currently, only the attributes defined in `schemaHandling` are cached by default.
(Except for the situation when the caching is enabled by `cachingOnly` property in the read capability.)

* When processing live sync changes that contain only the object identifiers, a more aggressive approach to fetching actual objects was adopted:
We now always fetch the actual object, if possible.
The reason is that the cached version may be incomplete or outdated.

* The behavior of `disableTimestamp` and `disableReason` in the shadow activation container was changed.
Before 4.9/4.8.1, these properties were updated only if there was an actual change in the administrative status from something to `DISABLED`.
Since 4.9/4.8.1, both of these properties are updated even if the administrative status is already `DISABLED`:
the `disableReason` is determined anew, and the `disableTimestamp` is updated if the status and/or the reason are modified.
See bug:MID-9220[].

* Automatic caching of association binding attributes (the "value" side, i.e. `valueAttribute` in the association definition) is no longer provided.
It is recommended to mark them as secondary identifiers.

* The filtering of associations was changed slightly.
In particular, even if the required auxiliary object class is not present for the subject, the association values are still shown - if they exist on the resource.
(They were hidden before.)

* To address bug:MID-9638[] and bug:MID-9670[] (leaking data via searching objects by filters), the handling of items allowed for search operations was changed.

It is now evaluated not only for the type we are searching for (like `RoleType`), but for all types whose items are to be used for the search (like `UserType` for a filter like "give me `RoleType` `referencedBy` `UserType` via `assignment/targetRef`").

The checks are "yes/no" style only, based on the presence or absence of authorizations against specified type and item(s), with appropriate action URIs (read, search, and the new searchBy).
No detailed checking for the values is done. E.g. if the search for `UserType:name` is allowed even for potentially a single user object (via an authorization clause that can provide any number of matching objects, even zero), then the `name` item can be used for any search concerning `UserType` or even `FocusType` objects.

Effects on existing deployments:

. Some queries allowed previously may now fail because of missing item-searching authorizations.
As a quick fix, new (experimental, temporary) `searchBy` authorization is available to give search access to these items without providing any additional access to data values.

. Some queries denied previously may now be allowed.
This should be quite rare, but possible.
It can happen if the original authorization was not applied because of some specific limitations (like `roleRelation` with no explicit role information), and hence the `item`/`exceptItem` part of it was skipped.
This is no longer the case.

See link:https://github.com/Evolveum/midpoint/commit/60928672b8e51946edf01fcbe0d253e4ae65c4cf[commit 609286].

* The `effectiveMarkRef` item now has value metadata to determine the values' origin. See link:https://github.com/Evolveum/midpoint/commit/351d7e4718bef9ac90dffde8920bc7d536f42e84[commit 351d7e].

* The mapping specification in provenance metadata now contains also object type name, association type name, and the shadow tag.
See xrefv:/midpoint/reference/support-4.9/expressions/mappings/#_mapping_maintenance_tasks[Mapping Maintenance Tasks], link:https://github.com/Evolveum/midpoint/commit/0dd1c011d9bc99fae037a4e27cb583cbd43da5bb[commit 0dd1c0], and link:https://github.com/Evolveum/midpoint/commit/8557f5945222ac2a7c535f0d0458af725442b61b[commit 8557f5].

* "<a:indexed/>" and "<a:indexOnly/>" annotations - when present but without any value - was interpreted as "false".
This was now changed to a more intuitive interpretation (similar to a:object, a:container, etc), where annotation present but without value means "true".
Also, "a:container" and other markers were interpreted as "true", even if the value was actually "false".
This is now fixed as well.

* Years-old ref-style schema annotations like <r:identifier ref="icfs:uid"/> are no longer supported.
They are not used since midPoint 2.0.
If you happen to use them in your manually configured resource XSD schemas, please replace them with the supported <r:identifier>icfs:uid</r:identifier> style.

* Support for getting/setting objects embedded in references marked as `a:objectReference` directly, like `LensElementContext.getObjectOld()`.
This feature was used only internally by midPoint.

* The `<xsd:documentation>` element in resource schemas is now ignored.
It was never used by ConnId connectors, but, in theory, it might be used for manually entered schemas.

* Default target set for mappings emitting multivalue properties is based on provenance metadata, mapping can only remove values, it added.
** If value has multiple provenances (user entry, or multiple mappings), the mapping removes only its provenance section, value still remains.

NOTE: The addition of the value metadata at various places of objects means that the objects are larger than in previous versions of midPoint.
In a similar way, the shadow caching feature - enabled by default for new installations - will probably increase the size of shadow objects further.
All this will probably have an impact on the database size as well as on the runtime performance.
(The exact proportions depend on specifics of the deployment.)
All these features can be configured - or even turned off in the extreme case - so you can do your own tradeoff between functionality and performance.
Moreover, we plan to improve the performance in the forthcoming releases.

=== Java and REST API Changes Since 4.8

NOTE: As for the Java API, this section describes changes in `midpoint` and `basic` function libraries.
(MidPoint does not have explicitly defined Java API, yet.
But these two objects are something that can be unofficially considered to be the API of midPoint, usable e.g. from scripts.)

// * Some of `javax` namespaces were migrated to `jakarta` namespaces, due to upgrade of Spring and Groovy 4. This may affect your scripts / overlays if you were using them. Most notable is `javax.xml.bind`, which was migrated to `jakarta.xml.bind`.
// ** Most notable rename for Groovy scripts is `javax.xml.bind.JAXBElement` to `jakarta.xml.bind.JAXBElement`.
//
// * Groovy was updated to version 4, which changed some of exposed java package names. See https://groovy-lang.org/releasenotes/groovy-4.0.html[Groovy 4.0 Release Notes] for more details.
//
// * The following methods were not checking authorizations of currently logged-in user, and were fixed to do so:
// `midpoint.countAccounts`, `midpoint.getObjectsInConflictOnPropertyValue`, `midpoint.isUniquePropertyValue`.
// See bug:MID-6241[] and commit https://github.com/Evolveum/midpoint/commit/1471bba52e363f81feabbec6f997507d8a7655fb[1471bb].

=== Internal Changes Since 4.8

NOTE: These changes should not influence people that use midPoint "as is".
They should also not influence the XML/JSON/YAML-based customizations or scripting expressions that rely just on the provided library classes.
These changes will influence midPoint forks and deployments that are heavily customized using the Java components.

* Internal APIs were massively changed with regard to passing `prismContext` object between methods.
This object has been statically available for quite a long time.
Now it was definitely removed from methods' signatures.
+
*The official APIs (like `midpoint` and `basic` objects) were not touched by this change.
However, if you use some of the unofficial or undocumented APIs, please make sure you migrate your code appropriately.*
+
The change itself is very simple: basically, the `PrismContext` parameter was removed from methods' signatures.

* Likewise, the internals of prism definitions were changed in https://github.com/Evolveum/prism/commit/12808dc91f4ea358dda3666cd0b01eba7d08300c[12808d].
You should not be affected by this; however, if you use some of the unofficial/undocumented APIs, please check your code.

// * The post-processing of retrieved objects in the IDM Model subsystem (sometimes called "apply schemas and security") was xref:/midpoint/devel/design/apply-schemas-and-security-4.8/summary.adoc[simplified].
//
// * Internal `SearchBasedActivityRunSpecifics` interface was changed.
// This may affect those deployments that provide their own activity handlers.
// See https://github.com/Evolveum/midpoint/commit/12f6f66d[12f6f66d].


++++
{% include release-issues.html %}
++++
