= How to provide password values to bulk actions (and other task types) securely
:page-wiki-name: How to provide password values to bulk actions (and other task types) securely
:page-wiki-id: 30245626
:page-wiki-metadata-create-user: mederly
:page-wiki-metadata-create-date: 2019-05-22T09:50:00.480+02:00
:page-wiki-metadata-modify-user: mederly
:page-wiki-metadata-modify-date: 2019-05-22T10:07:41.313+02:00
:page-upkeep-status: green

MidPoint automatically encrypts all protected string values that it recognizes in objects that are to be stored into repository.
The key precondition is that such protected strings are recognizable.
So, for example, if you provide a password as a part of a Groovy script, midPoint has no chance of detecting it.
In a similar way, if you provide it as a part of untyped XML/JSON/REST value, midPoint cannot recognize it, at least not until the time of interpretation of this data (i.e. at the time of task execution), that is obviously too late.

So, in order to ensure that a value is protected, it has to be correctly typed.

For example:

.*Correct way of marking protected data*
[%collapsible]
====
link:https://github.com/Evolveum/midpoint-samples/blob/master/samples/tasks/bulk-actions/change-password-value.xml[Git]

sampleRef::samples/tasks/bulk-actions/change-password-value.xml[]
====

Note the `xsi:type`  declarations on lines 53 and 48.
It is necessary to specify item types at all places where arbitrary objects can be used, namely in bulk actions parameters, and in item delta values.
