---
midpoint-feature: expression
doc-type: config
---
= Expression Security
:page-upkeep-status: yellow
:page-visibility: hidden

MidPoint is a very flexible system.
Being an identity governance platform, all the flexibility is needed to allow practical and efficient deployments.
However, with great power comes great responsibility.

One of the most powerful parts of midPoint are xref:/midpoint/reference/expressions/[mappings and expressions]. Expressions allow to customize midPoint behavior, and they are essential for the success of midPoint deployments.
However, the expressions are very powerful, maybe even a bit too powerful for some use cases.
The expressions can use general-purpose scripting languages such as Groovy or JavaScript.
Therefore, such expressions have almost unlimited capabilities.
Which means that the expressions can damage the system or compromise security of the system.

As a general guideline, *utmost care* should be applied wherever expressions are used.
Expressions, especially xref:/midpoint/reference/expressions/expressions/script/[scripting expressions], create inherent security risks.

However, there is a limit to such an recommendation.
Expressions are the fuel that drives midPoint flexibility on too many levels.
It is difficult to image really complex configuration where all the roles are designed by system administrator.
And it is also difficult to imagine a life with just a static roles.
That would easily lead to role explosion.
Therefore, midPoint contains several mechanisms that make use of expressions reasonably secure.

== Expression Profiles

Expression profiles are definitions, what an expression can and cannot do.
For example, an expression profile may dictate, that particular expression can only use `asIs` and `path` evaluators.
In case that `script` evaluator is used, only Groovy can be used as a scripting language, the script should be type-checked and only use of particular safe classes should be allowed.

Expression profiles are defined in xref:/midpoint/reference/concepts/system-configuration-object/[system configuration].
Use of expression profiles is integrated with xref:/midpoint/reference/schema/archetypes/[archetypes].

Expression profiles are constraining evaluation of expressions, no matter how they were introduced in the object and regardless of xref:/midpoint/reference/security/authorization/[authorizations].
In case that expression is constrained by a profile, that profile will stop evaluation of the expression even if _superuser_ is initiating the operation.
In that respect, expression profile are an _orthogonal_ mechanisms to authorizations, providing complementary security layer.
In practice, coordinated use of expression profiles and authorizations is necessary to create safe configuration (see below).

See xref:/midpoint/reference/expressions/expressions/profiles/[Expression Profiles] page for more details.

== Safe Expression Evaluators

The features and characteristics of individual expression evaluators vary.
Some expression evaluators (such as xref:/midpoint/reference/expressions/expressions/script/[`script`]) are very powerful, yet they can cause a lot of harm.
Other evaluators (such as `asIs`) are simple, yet they are very safe to use.

Following table summarizes security properties of expression evaluators.

[%autowidth]
|===
| Evaluator | Is safe? | Comments

| literal (`value`)
| Yes
|

| `asIs`
| Yes
|

| `path`
| Yes
|

| `filter`
| Yes
|

| `generate`
| Yes
|
// TODO: check system config profile

| `const`
| Yes
|

| `function`
| Yes
| Assuming that the invoked function is safe.

| `proportional`
| Yes
|
// TODO: check system config profile

| `script`
| No
|

| `assignmentTargetSearch`
| Uncertain
| Safety of this evaluator was not yet properly analysed.

| `associationTargetSearch`
| Uncertain
| Safety of this evaluator was not yet properly analysed.

| `referenceSearch`
| Uncertain
| Safety of this evaluator was not yet properly analysed.

| `shadowOwnerReferenceSearch`
| Uncertain
| Safety of this evaluator was not yet properly analysed.

| `associationFromLink`
| Uncertain
| Safety of this evaluator was not yet properly analysed.

| `assignmentFromAssociation`
| Uncertain
| Safety of this evaluator was not yet properly analysed.

| `sequentialValue`
| Uncertain
| Safety of this evaluator was not yet properly analysed.

| `assignmentFromAssociation`
| Uncertain
| Safety of this evaluator was not yet properly analysed.

| `assignmentFromAssociation`
| Uncertain
| Safety of this evaluator was not yet properly analysed.

|===

Evaluators marked as _safe_ are generally safe to use.
They do not have potential to execute arbitrary code or do execute operations that could impact security of the system.
However, even _safe_ expression operators still have potential for mis-configuration, which can impact the system indirectly.
For example, an evaluator may provide incorrect value, which may affect correctness of configuration or policies.
Also, an evaluator may affect performance of the system by using inefficient search filter.

Default midPoint xref:/midpoint/reference/concepts/system-configuration-object/[system configuration] contains a definition of `safe` xref:/midpoint/reference/expressions/expressions/profiles/[expression profile], which includes only safe expression evaluators.

NOTE: Prior to midPoint 4.10, the default system configuration contained expression profile identified as `safe`.
However, this expression profile contained `script` expression evaluator.
Although the script expressions were constrained by a permission profile, this configuration did not provide level of security adequate for current needs.
The profile included a description which warned users of this drawback.
However, denoting the profile as `safe` might have lead to unrealistic expectations and mis-configurations.
Therefore, the `script` expression evaluator was removed from the `safe` profile in midPoint 4.10.
Also, the `script-safe` permission profile was renamed to `script-limited` to avoid mis-interpretation of the name.
When upgrading midPoint deployments from versions earlier than 4.10, make sure that the profiles are correctly updated.

== Security of Scripting Expressions

// TODO: discuss safe expression language - how surprisingly hard it is
// TODO: Groovy sandboxing is unreliable

== Authorizations

== Semi-Safe Configuration

// TODO: How to use expressions in a secure way

// TODO: combination of authorizations and profiles

// TODO: expression profiles: safe, open, closed

// TODO: place logic in meta-roles (archetypes, policies) when needed
// TODO: use function libraries

// TODO: Safety of invoked functions, e.g. input sanitization


* xref:/midpoint/reference/roles-policies/policies/metaroles/policy/[Metaroles] can be used to group all the necessary logic, including expressions.
Meta roles can be setup by a trusted administrator.
Delegated administrators then just "use" the metarole, with possible parametrization using parameters in assignment extension.
However, even this method is not yet fully supported in midPoint user interface.

* xref:/midpoint/reference/concepts/object-lifecycle/[Object lifecycle] mechanism can be used to drive role definitions through an approval process.
This can be used to make sure that expressions used in the roles are safe.

== Limitations

// TODO: implementation of expression profiles is incomplete. Make sure to test the configuration thoroughly.
// TODO: Scripting sandbox (e.g. groovy) are limited, mostly unreliable.
// TODO: safety of some evaluators was not yet properly analysed
== See Also

* xref:/midpoint/reference/expressions/[Mappings and Expressions]

* xref:/midpoint/security/security-guide/[Security Guide]
