= API Concepts
:page-nav-title: API Concepts
:page-display-order: 100
:page-upkeep-status: green

== Description

MidPoint "REST API" is an HTTP-based application programming interface.
This interface is a set of web resources that provide access to internal midPoint functionality.

=== Approach

[NOTE]
.Terminology note
====
We call this interface "REST API" even though it is in fact not entirely RESTful.
This API is not hypertext-based.
Hypertext is not intended paradigm for this interface.
Also, we are not strictly restful in some details.
E.g. there are combined web resources that perhaps should be modeled as many smaller web resources if we would follow a strict RESTful approach.
However, that would be painfully inefficient to use.
There are also some parts that are obviously RPC-based.
We are doing this to make the API practical as practicality is our highest priority.
Yes, we should not call this interface "REST".
But almost everyone else does call things like this "REST", and almost everyone expects to see a "REST" interface, so please excuse us.
====

Basic concepts of the interface are described here:

- xref:/midpoint/reference/interfaces/rest/concepts/methods-http-and-outcome/[Use of HTTP Verbs]
- xref:/midpoint/reference/interfaces/rest/concepts/media-types-rest/[Supported Media Types]
- xref:/midpoint/reference/interfaces/rest/concepts/authentication/[Authentication]

For the Supported Endpoints and Operations please have a look here:

- xref:/midpoint/reference/interfaces/rest/operations[Operations]
- xref:/midpoint/reference/interfaces/rest/endpoints/[REST Endpoints]


== See Also

- xref:/midpoint/reference/interfaces/rest/[REST API]
- xref:/midpoint/reference/interfaces/midpoint-client-java/[MidPoint Client]
- xref:/midpoint/reference/interfaces/rest/operations/examples/[User Story Examples]
