= MidPoint Query Mechanisms
:page-nav-title: Query
:page-wiki-name: Object Query
:page-wiki-id: 13074769
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2013-12-03T14:09:37.917+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-10-09T11:35:35.793+02:00

MidPoint repository implements an abstraction of an object-oriented data store.
The data may be stored in several types of relational databases (with even more possibility for future).
Yet, the repository always presents the data in the same form, regardless of the actual storage mechanism.

However, data processing means much more than just a storage of data.
One of the most important aspects is how to _query_ the data, how to search for objects.
This too has to be done in a way that is independent of the underlying storage mechanism.

As the _query_ is such as important aspect, midPoint has its own xref:query-api/[Query API].
The API supports query specification in multiple languages so it can be used both by midPoint
user (xref:axiom-query-language/[Axiom], xref:xml-query-language/[XML]) or a programmer (Java API,
which can also be used in configuration scripts, e.g. in xref:/midpoint/reference/expressions/expressions/script/groovy/[Groovy]).

Query can be used in various contexts:

* for querying objects in the xref:/midpoint/reference/repository/[repository],
* querying remote objects on the xref:/midpoint/reference/resources/[resources],
* for collections of objects in-memory - this is more important for a programmer than for midPoint administrators.

Each of the contexts may have some natural limitations which are described in details in xref:query-api/[Query API].
Queries are often used in Tasks to specify the xref:/midpoint/reference/tasks/activities/object-set-specification/[set of objects] to work on.

== Query Languages

MidPoint has two query languages.
xref:axiom-query-language/[Axiom query language] is a new language, based on concepts of xref:/midpoint/devel/axiom/[Axiom data modeling].
This language is mostly user-friendly.
Then there is an older xref:xml-query-language/[XML-based query language].
This goes back to the times when midPoint was completely XML-based.
The languages are summarized in the following table:

[%autowidth]
|====
| Language | Summary | Available since | Example

| xref:axiom-query-language/[Axiom query language]
| User-friendly, text-based query language
| MidPoint 4.3 (experimental)
a|
 name = "jack"

| xref:xml-query-language/[XML-based query language]
| Pure XML, deep element hierarchy
| MidPoint 1.7
a|
 <q:equal>
   <q:path>name</q:path>
   <q:value>jack</q:value>
 </q:equal>

|====

Axiom query language is a relative new development, introduced in midPoint 4.3.
It is expected to be fully supported in midPoint 4.4 LTS, where it should become a recommended option.
The Axiom query language should replace the XML-based language as soon as possible.
The XML-based language will be still supported for several years, but it will be dropped eventually.

== Query API

MidPoint code deals with data queries all the time.
There is a special API designed to represent the queries as data structures internally.
The API can also be used to construct the queries programmatically in a fluent style (chained method calls).
Programmatic query construction can be used not only in midPoint code, but also in xref:/midpoint/reference/expressions/expressions/script/[Script expressions].

Please see an extensive xref:query-api/[Query API] document for further details about the supported query constructs,
available types of filters and examples how to write queries in various languages.
The document also specifies what Query API features work in various contexts, that is repository, provisioning or in-memory.
