= Query in midPoint
:page-nav-title: Query
:sectnums:
:sectnumlevels: 3

// TODO - toto je uvodna dokumentacia

MidPoint works with *objects* of various types.
These objects can be part of the running midPoint process in memory, stored persistently in xref:/midpoint/reference/repository/[midPoint repository], or can represent
objects on the xref:/midpoint/reference/resources/[resources].
MidPoint query provides option for selection only the objects that match specified criteria.

This section describes usage and configuration details of:

* xref:midpoint-query-language/[midPoint Query Language],
* xref:xml-query-language.adoc[XML Query Language],
* concept of xref:query-in-midpoint/[query in midPoint] in more depth.

The xref:midpoint-query-language/[midPoint Query Language] is universal language used to search for objects.
It can be used in GUI, or in configuration objects - in all places where we need to look for an object. It can be used even in xref:midpoint-query-language/query-language-in-groovy.adoc[groovy scripts] within configuration.

You can use also xref:xml-query-language.adoc[XML Query Language]. This was the original option for querying data. It is not entirely user-friendly.
This language is still supported, but we strongly recommend switch to midPoint Query Language.

It should be mentioned, that midPoint provides also xref:../../repository/full-text-search.adoc[Full text search] option.
It is available only for searching of specific data in GUI. The full text search is not enabled by default and must be configured by engineer.
The full text search was introduces just for user convenience. It definitely does not provide options and power of midPoint or XML query languages.
