= Role Catalog Configuration
:page-wiki-name: Role Catalog Configuration
:page-since: "3.5"
:page-upkeep-status: yellow
:page-toc: top


For an introduction to the role catalog concept please see wiki:Role+Catalog[Role Catalog] page.


== Role Catalog Implementation

Simply speaking, role catalog is just an wiki:Organizational+Structure[organizational structure] structure.
However, instead of divisions and sections the role catalog is composed of _categories_. And instead of member users there are _roles_. But apart from that the role catalog is just ordinary organizational structure.
The categories are ordinary wiki:OrgType[org objects]. The roles are assigned to the categories in exactly the same way as users are assigned to organizational structure.
Remember: MidPoint can have any number of organizational structures and the role catalog is just one of them.
There may even be several role catalogs at the same time as any midPoint object can be assigned to any number of orgs.
However, the current limitation is that only one role catalog will be presented to end users.


== Role Catalog Root

The root of this role catalog needs to be configured in the wiki:System+Configuration+Object[system configuration object] like this:

[source,xml]
----
<systemConfiguration>
    ...
    <roleManagement>
      <roleCatalogRef oid="8fbbe7b4-f422-11e6-b00e-e3483e7a1051"/>
    </roleManagement>
    ...
</systemConfiguration>
----

The roleCatalogRef reference above points to the wiki:OrgType[org] which is the root of the role catalog.


== See Also

* wiki:Role+Catalog[Role Catalog]

* wiki:Role+Request+and+Shopping+Cart+Configuration[Role Request and Shopping Cart Configuration]

* wiki:Advanced+Hybrid+RBAC[Advanced Hybrid RBAC]

* wiki:Organizational+Structure[Organizational Structure]

