=== Container environment upgrade

This article describes how to upgrade midPoint using ninja in container environments, e.g. deployments in Kubernetes, Docker.

Ninja in container environment can be accessed by using midPoint container started in interactive mode.
`$CURRENT_VERSION` in following command is version of midPoint that is currently running.

Container used to run ninja has to be started with same parameters as midPoint containers in deployment.
Environment variables or config maps or other configuration has to be passed to container the same way as to midPoint containers.
This is necessary to make sure that ninja uses same resources.
Another case when this is necessary is if database connection configuration is not present in `$MIDPOINT_HOME/config.xml`, but passed via parameters.

[source,bash]
----
docker run -ti --rm [-env VARIABLE=VALUE] -w=/opt/midpoint evolveum/midpoint:$CURRENT_VERSION /bin/bash
----

After container starts we're presented with bash prompt.
Now we can run ninja as in non-container environment, e.g.:

. Example printout of ninja version
[source,bash]
----
f41fde86786d:/opt/midpoint# ./bin/ninja.sh -V
Processing variable (MAP) ... midpoint.repository.database .:. oracle
Processing variable (MAP) ... midpoint.repository.missingSchemaAction .:. create
Processing variable (MAP) ... midpoint.logging.alt.enabled .:. true
Processing variable (MAP) ... midpoint.repository.initializationFailTimeout .:. 60000
Processing variable (MAP) ... file.encoding .:. UTF8
Processing variable (MAP) ... midpoint.repository.hibernateHbm2ddl .:. none
Processing variable (MAP) ... midpoint.repository.upgradeableSchemaAction .:. stop
Processing variable (MAP) ... midpoint.repository.jdbcUrl .:. jdbc:oracle:thin:@localhost:1521/xe
Version: 4.8-SNAPSHOT, rev. v4.8devel-1509-g8abd865, built by , 2023-09-27T07:05:44+0000
----

==== Upgrade procedure for container environment

Upgrade procedure is very similar to non-container environment, differences will be described in following sections.

*Preparation phase* is the same as for non-container environment:

* <<Pre-upgrade check>>
* <<Verification & upgrade objects>>

*Upgrade phase can't* be executed using simple `upgrade-distribution` command due to differences in handling of installation directory.
Following steps has to be executed instead:

* Stop current midPoint containers
* <<Setup ninja using new midPoint image>>
* <<Upgrade DB schema (container environment)>>
* <<Initial objects (container environment)>>
* <<Upgrade midPoint containers>>
* Start new midPoint containers

==== Setup ninja using new midPoint image

New midPoint image has to be pulled from Docker Hub before upgrade procedure can be started.
`$NEXT_VERSION` in following command is version of midPoint that is going to be used after upgrade.
At the time of writing it's `4.8`.

As previously mentioned <<Container environment upgrade, here>>, container used to run ninja has to be started with same parameters as midPoint containers in deployment.

[source,bash]
----
docker pull evolveum/midpoint:$NEXT_VERSION

docker run -ti --rm [-env VARIABLE=VALUE] -w=/opt/midpoint evolveum/midpoint:$NEXT_VERSION /bin/bash
----

Now we're presented with bash prompt, new version of ninja can be used to upgrade midPoint.

==== Upgrade DB schema (container environment)

Database schema has to be upgraded by starting new midPoint image in interactive mode and running `run-sql` command.

[source,bash]
----
# upgrade DB schema of midPoint repository
./bin/ninja.sh run-sql \
  --mode repository \
  --upgrade

# upgrade DB schema of midPoint audit repository
./bin/ninja.sh run-sql \
  --mode audit \
  --upgrade
----

==== Initial objects (container environment)

Initial objects can be updated using ninja started withing new midPoint image in interactive mode.
As for the update itself, <<Initial objects>> chapter describes how to review and update initial objects.

==== Upgrade midPoint containers

Now is the time to update definition of midPoint containers in deployment.
This means we should update configuration in `docker-compose.yml` when using Docker compose command, or stateful set in Kubernetes or any other related container configuration for midPoint cluster.
`$NEXT_VERSION` version of `evolveum/midpoint` image must be used.

Containers can be started.
MidPoint in new version should start.

Please review logs of midPoint containers to make sure there are no errors.
