package com.evolveum.midpoint.repo.sql.handler;

/**
 * > modify object UserType, oid=92686866-0689-4bfb-9175-143c66ca8cd5, modifications=[ReferenceDelta( / {.../common/common-3}linkRef, ADD)]
 * select this_.oid as oid1_18_0_, this_2_.createChannel as createCh2_18_0_, this_2_.createTimestamp as createTi3_18_0_, this_2_.creatorRef_relation as creatorR4_18_0_, this_2_.creatorRef_targetOid as creatorR5_18_0_, this_2_.creatorRef_type as creatorR6_18_0_, this_2_.datesCount as datesCou7_18_0_, this_2_.fullObject as fullObje8_18_0_, this_2_.longsCount as longsCou9_18_0_, this_2_.modifierRef_relation as modifie10_18_0_, this_2_.modifierRef_targetOid as modifie11_18_0_, this_2_.modifierRef_type as modifie12_18_0_, this_2_.modifyChannel as modifyC13_18_0_, this_2_.modifyTimestamp as modifyT14_18_0_, this_2_.name_norm as name_no15_18_0_, this_2_.name_orig as name_or16_18_0_, this_2_.objectTypeClass as objectT17_18_0_, this_2_.polysCount as polysCo18_18_0_, this_2_.referencesCount as referen19_18_0_, this_2_.stringsCount as strings20_18_0_, this_2_.tenantRef_relation as tenantR21_18_0_, this_2_.tenantRef_targetOid as tenantR22_18_0_, this_2_.tenantRef_type as tenantR23_18_0_, this_2_.version as version24_18_0_, this_1_.administrativeStatus as administ1_15_0_, this_1_.archiveTimestamp as archiveT2_15_0_, this_1_.disableReason as disableR3_15_0_, this_1_.disableTimestamp as disableT4_15_0_, this_1_.effectiveStatus as effectiv5_15_0_, this_1_.enableTimestamp as enableTi6_15_0_, this_1_.validFrom as validFro7_15_0_, this_1_.validTo as validTo8_15_0_, this_1_.validityChangeTimestamp as validity9_15_0_, this_1_.validityStatus as validit10_15_0_, this_.additionalName_norm as addition1_39_0_, this_.additionalName_orig as addition2_39_0_, this_.costCenter as costCent3_39_0_, this_.emailAddress as emailAdd4_39_0_, this_.employeeNumber as employee5_39_0_, this_.familyName_norm as familyNa6_39_0_, this_.familyName_orig as familyNa7_39_0_, this_.fullName_norm as fullName8_39_0_, this_.fullName_orig as fullName9_39_0_, this_.givenName_norm as givenNa10_39_0_, this_.givenName_orig as givenNa11_39_0_, this_.hasPhoto as hasPhot12_39_0_, this_.honorificPrefix_norm as honorif13_39_0_, this_.honorificPrefix_orig as honorif14_39_0_, this_.honorificSuffix_norm as honorif15_39_0_, this_.honorificSuffix_orig as honorif16_39_0_, this_.locale as locale17_39_0_, this_.locality_norm as localit18_39_0_, this_.locality_orig as localit19_39_0_, this_.name_norm as name_no20_39_0_, this_.name_orig as name_or21_39_0_, this_.nickName_norm as nickNam22_39_0_, this_.nickName_orig as nickNam23_39_0_, this_.preferredLanguage as preferr24_39_0_, this_.status as status25_39_0_, this_.telephoneNumber as telepho26_39_0_, this_.timezone as timezon27_39_0_, this_.title_norm as title_n28_39_0_, this_.title_orig as title_o29_39_0_ from m_user this_ inner join m_focus this_1_ on this_.oid=this_1_.oid inner join m_object this_2_ on this_.oid=this_2_.oid where this_.oid=?
 * select parentorgr0_.owner_oid as owner_oi2_18_0_, parentorgr0_.owner_oid as owner_oi2_28_0_, parentorgr0_.relation as relation3_28_0_, parentorgr0_.targetOid as targetOi4_28_0_, parentorgr0_.owner_oid as owner_oi2_28_1_, parentorgr0_.relation as relation3_28_1_, parentorgr0_.targetOid as targetOi4_28_1_, parentorgr0_.containerType as containe5_28_1_, parentorgr0_.reference_type as referenc1_28_1_ from m_reference parentorgr0_ where ( parentorgr0_.reference_type=0) and parentorgr0_.owner_oid=?
 * select roextstrin0_.eName as eName1_23_0_, roextstrin0_.owner_oid as owner_oi2_23_0_, roextstrin0_.ownerType as ownerTyp3_23_0_, roextstrin0_.stringValue as stringVa4_23_0_, roextstrin0_.dynamicDef as dynamicD5_23_0_, roextstrin0_.eType as eType6_23_0_, roextstrin0_.valueType as valueTyp7_23_0_ from m_object_ext_string roextstrin0_ where roextstrin0_.eName=? and roextstrin0_.owner_oid=? and roextstrin0_.ownerType=? and roextstrin0_.stringValue=?
 * select rlinkref0_.owner_oid as owner_oi2_28_0_, rlinkref0_.relation as relation3_28_0_, rlinkref0_.targetOid as targetOi4_28_0_, rlinkref0_.containerType as containe5_28_0_ from m_reference rlinkref0_ where rlinkref0_.owner_oid=? and rlinkref0_.relation=? and rlinkref0_.targetOid=? and rlinkref0_.reference_type=1
 * select createappr0_.owner_oid as owner_oi2_18_0_, createappr0_.owner_oid as owner_oi2_28_0_, createappr0_.relation as relation3_28_0_, createappr0_.targetOid as targetOi4_28_0_, createappr0_.owner_oid as owner_oi2_28_1_, createappr0_.relation as relation3_28_1_, createappr0_.targetOid as targetOi4_28_1_, createappr0_.containerType as containe5_28_1_, createappr0_.reference_type as referenc1_28_1_ from m_reference createappr0_ where ( createappr0_.reference_type=5) and createappr0_.owner_oid=?
 * select dates0_.owner_oid as owner_oi2_18_0_, dates0_.eName as eName1_19_0_, dates0_.owner_oid as owner_oi2_19_0_, dates0_.ownerType as ownerTyp3_19_0_, dates0_.dateValue as dateValu4_19_0_, dates0_.eName as eName1_19_1_, dates0_.owner_oid as owner_oi2_19_1_, dates0_.ownerType as ownerTyp3_19_1_, dates0_.dateValue as dateValu4_19_1_, dates0_.dynamicDef as dynamicD5_19_1_, dates0_.eType as eType6_19_1_, dates0_.valueType as valueTyp7_19_1_ from m_object_ext_date dates0_ where dates0_.owner_oid=?
 * select longs0_.owner_oid as owner_oi2_18_0_, longs0_.eName as eName1_20_0_, longs0_.owner_oid as owner_oi2_20_0_, longs0_.ownerType as ownerTyp3_20_0_, longs0_.longValue as longValu4_20_0_, longs0_.eName as eName1_20_1_, longs0_.owner_oid as owner_oi2_20_1_, longs0_.ownerType as ownerTyp3_20_1_, longs0_.longValue as longValu4_20_1_, longs0_.dynamicDef as dynamicD5_20_1_, longs0_.eType as eType6_20_1_, longs0_.valueType as valueTyp7_20_1_ from m_object_ext_long longs0_ where longs0_.owner_oid=?
 * select modifyappr0_.owner_oid as owner_oi2_18_0_, modifyappr0_.owner_oid as owner_oi2_28_0_, modifyappr0_.relation as relation3_28_0_, modifyappr0_.targetOid as targetOi4_28_0_, modifyappr0_.owner_oid as owner_oi2_28_1_, modifyappr0_.relation as relation3_28_1_, modifyappr0_.targetOid as targetOi4_28_1_, modifyappr0_.containerType as containe5_28_1_, modifyappr0_.reference_type as referenc1_28_1_ from m_reference modifyappr0_ where ( modifyappr0_.reference_type=6) and modifyappr0_.owner_oid=?
 * select polys0_.owner_oid as owner_oi2_18_0_, polys0_.eName as eName1_21_0_, polys0_.owner_oid as owner_oi2_21_0_, polys0_.ownerType as ownerTyp3_21_0_, polys0_.orig as orig4_21_0_, polys0_.eName as eName1_21_1_, polys0_.owner_oid as owner_oi2_21_1_, polys0_.ownerType as ownerTyp3_21_1_, polys0_.orig as orig4_21_1_, polys0_.dynamicDef as dynamicD5_21_1_, polys0_.norm as norm6_21_1_, polys0_.eType as eType7_21_1_, polys0_.valueType as valueTyp8_21_1_ from m_object_ext_poly polys0_ where polys0_.owner_oid=?
 * select references0_.owner_oid as owner_oi2_18_0_, references0_.eName as eName1_22_0_, references0_.owner_oid as owner_oi2_22_0_, references0_.ownerType as ownerTyp3_22_0_, references0_.targetoid as targetoi4_22_0_, references0_.eName as eName1_22_1_, references0_.owner_oid as owner_oi2_22_1_, references0_.ownerType as ownerTyp3_22_1_, references0_.targetoid as targetoi4_22_1_, references0_.dynamicDef as dynamicD5_22_1_, references0_.relation as relation6_22_1_, references0_.targetType as targetTy7_22_1_, references0_.eType as eType8_22_1_, references0_.valueType as valueTyp9_22_1_ from m_object_ext_reference references0_ where references0_.owner_oid=?
 * select strings0_.owner_oid as owner_oi2_18_0_, strings0_.eName as eName1_23_0_, strings0_.owner_oid as owner_oi2_23_0_, strings0_.ownerType as ownerTyp3_23_0_, strings0_.stringValue as stringVa4_23_0_, strings0_.eName as eName1_23_1_, strings0_.owner_oid as owner_oi2_23_1_, strings0_.ownerType as ownerTyp3_23_1_, strings0_.stringValue as stringVa4_23_1_, strings0_.dynamicDef as dynamicD5_23_1_, strings0_.eType as eType6_23_1_, strings0_.valueType as valueTyp7_23_1_ from m_object_ext_string strings0_ where strings0_.owner_oid=?
 * select trigger0_.owner_oid as owner_oi2_18_0_, trigger0_.id as id1_38_0_, trigger0_.owner_oid as owner_oi2_38_0_, trigger0_.id as id1_38_1_, trigger0_.owner_oid as owner_oi2_38_1_, trigger0_.handlerUri as handlerU3_38_1_, trigger0_.timestampValue as timestam4_38_1_ from m_trigger trigger0_ where trigger0_.owner_oid=?
 * select assignment0_.owner_oid as owner_oi2_18_0_, assignment0_.id as id1_1_0_, assignment0_.owner_oid as owner_oi2_1_0_, assignment0_.id as id1_1_1_, assignment0_.owner_oid as owner_oi2_1_1_, assignment0_.administrativeStatus as administ3_1_1_, assignment0_.archiveTimestamp as archiveT4_1_1_, assignment0_.disableReason as disableR5_1_1_, assignment0_.disableTimestamp as disableT6_1_1_, assignment0_.effectiveStatus as effectiv7_1_1_, assignment0_.enableTimestamp as enableTi8_1_1_, assignment0_.validFrom as validFro9_1_1_, assignment0_.validTo as validTo10_1_1_, assignment0_.validityChangeTimestamp as validit11_1_1_, assignment0_.validityStatus as validit12_1_1_, assignment0_.assignmentOwner as assignm13_1_1_, assignment0_.createChannel as createC14_1_1_, assignment0_.createTimestamp as createT15_1_1_, assignment0_.creatorRef_relation as creator16_1_1_, assignment0_.creatorRef_targetOid as creator17_1_1_, assignment0_.creatorRef_type as creator18_1_1_, assignment0_.extId as extId31_1_1_, assignment0_.extOid as extOid32_1_1_, assignment0_.modifierRef_relation as modifie19_1_1_, assignment0_.modifierRef_targetOid as modifie20_1_1_, assignment0_.modifierRef_type as modifie21_1_1_, assignment0_.modifyChannel as modifyC22_1_1_, assignment0_.modifyTimestamp as modifyT23_1_1_, assignment0_.orderValue as orderVa24_1_1_, assignment0_.targetRef_relation as targetR25_1_1_, assignment0_.targetRef_targetOid as targetR26_1_1_, assignment0_.targetRef_type as targetR27_1_1_, assignment0_.tenantRef_relation as tenantR28_1_1_, assignment0_.tenantRef_targetOid as tenantR29_1_1_, assignment0_.tenantRef_type as tenantR30_1_1_, rassignmen1_.owner_id as owner_id1_7_2_, rassignmen1_.owner_owner_oid as owner_ow2_7_2_, rassignmen1_.datesCount as datesCou3_7_2_, rassignmen1_.longsCount as longsCou4_7_2_, rassignmen1_.polysCount as polysCou5_7_2_, rassignmen1_.referencesCount as referenc6_7_2_, rassignmen1_.stringsCount as stringsC7_7_2_ from m_assignment assignment0_ left outer join m_assignment_extension rassignmen1_ on assignment0_.extId=rassignmen1_.owner_id and assignment0_.extOid=rassignmen1_.owner_owner_oid where assignment0_.owner_oid=?
 * select linkref0_.owner_oid as owner_oi2_18_0_, linkref0_.owner_oid as owner_oi2_28_0_, linkref0_.relation as relation3_28_0_, linkref0_.targetOid as targetOi4_28_0_, linkref0_.owner_oid as owner_oi2_28_1_, linkref0_.relation as relation3_28_1_, linkref0_.targetOid as targetOi4_28_1_, linkref0_.containerType as containe5_28_1_, linkref0_.reference_type as referenc1_28_1_ from m_reference linkref0_ where ( linkref0_.reference_type=1) and linkref0_.owner_oid=?
 * select jpegphoto0_.owner_oid as owner_oi1_18_0_, jpegphoto0_.owner_oid as owner_oi1_43_0_, jpegphoto0_.owner_oid as owner_oi1_43_1_, jpegphoto0_.photo as photo2_43_1_ from m_user_photo jpegphoto0_ where jpegphoto0_.owner_oid=?
 * insert into m_reference (containerType, reference_type, owner_oid, relation, targetOid) values (?, 1, ?, ?, ?)
 * update m_object set createChannel=?, createTimestamp=?, creatorRef_relation=?, creatorRef_targetOid=?, creatorRef_type=?, datesCount=?, fullObject=?, longsCount=?, modifierRef_relation=?, modifierRef_targetOid=?, modifierRef_type=?, modifyChannel=?, modifyTimestamp=?, name_norm=?, name_orig=?, objectTypeClass=?, polysCount=?, referencesCount=?, stringsCount=?, tenantRef_relation=?, tenantRef_targetOid=?, tenantRef_type=?, version=? where oid=?
 * delete from m_user_employee_type where user_oid=?
 * delete from m_user_organization where user_oid=?
 * delete from m_user_organizational_unit where user_oid=?
 * <p/>
 * CAN BE IMPROVED:
 * <p/>
 * select full object xml...
 * insert into m_reference (containerType, reference_type, owner_oid, relation, targetOid) values (?, 1, ?, ?, ?)
 * update m_object set createChannel=?, createTimestamp=?, creatorRef_relation=?, creatorRef_targetOid=?, creatorRef_type=?, datesCount=?, fullObject=?, longsCount=?, modifierRef_relation=?, modifierRef_targetOid=?, modifierRef_type=?, modifyChannel=?, modifyTimestamp=?, name_norm=?, name_orig=?, objectTypeClass=?, polysCount=?, referencesCount=?, stringsCount=?, tenantRef_relation=?, tenantRef_targetOid=?, tenantRef_type=?, version=? where oid=?
 *
 * @author lazyman
 */
public class ShadowLinkRefHandler {
}
