= Generate and Validate Operations for Specific objects
:page-nav-title: Generate And Validate Concrete Objects
:page-display-order: 200
:page-toc: top
:page-keywords: [ 'rest', 'generate', 'validate', 'operation' ]
:page-upkeep-status: green

== Description

Request to validate or generate a value for a specific object on midPoint. The operations
url in this case contains a unique identifier of the object, for which we generate/validate a
value and also the endpoint part of the URI of the object.

== Request

For the request use the HTTP POST for the request.

The client has to provide the type of the web resource used in the request "{endpoint}"
and the oid of the specific object for which we execute the operation "{oid}".

.Generate operation
[source, http]
----
POST http://localhost:8080/midpoint/ws/rest/{endpoint}/{oid}/generate
----

.Validate operation
[source, http]
----
POST http://localhost:8080/midpoint/ws/rest/{endpoint}/{oid}/validate
----

=== Headers

Regarding authorization type, the "Basic" Authorization header should be used.

.Authorization header example replace {Base64EncodedCredentials} with the encoded credentials
[source, http]
----
Authorization: Basic {Base64EncodedCredentials}
----

Another header would be the Content-Type Header.

.Content-Type header example, other media types are supported as well
[source, http]
----
"Content-Type: application/json"
----

You might need to specify the accepted type of content in case
you are interested in a format different from xml (default)

.Accept type header example, other media types are supported as well
[source, http]
----
"Accept: application/json"
----

.For supported media types please refer to the following section of the documentation
xref:/midpoint/reference/interfaces/rest/concepts/media-types-rest/[Supported Media Types]

=== Body

The body should contain a payload consisting of a policyItemDefinition type of object.
Based on the use case you might need to specify which value policy should be used for the operation
or which item should be the target of the operation. Please see the examples below.

=== Options

There are no supported operation options for this type of operation.

include::../../rest/concepts/raw/outcome.adoc[]

== Access Authorization

include::../operations/raw/a-auth.adoc[]

- `+http://midpoint.evolveum.com/xml/ns/public/security/authorization-rest-3#generateValue+`
- `+http://midpoint.evolveum.com/xml/ns/public/security/authorization-rest-3#validateValue+`

== Model Authorization

include::../operations/raw/m-auth.adoc[]

- `+http://midpoint.evolveum.com/xml/ns/public/security/authorization-model-3#get+`
- `+http://midpoint.evolveum.com/xml/ns/public/security/authorization-model-3#read+`

Additionally, for generate:

- `+http://midpoint.evolveum.com/xml/ns/public/security/authorization-model-3#modify+`

== Examples

include::../raw/curl-env-note.adoc[]

For some help regarding the REST examples please see this link:

xref:/midpoint/reference/interfaces/rest/concepts/using-rest-examples.adoc[How to use MidPoint REST examples]


include::../../rest/operations/examples/raw/role-id-generate.adoc[]

include::../../rest/operations/examples/raw/modify-id-generate.adoc[]

== See Also

- xref:/midpoint/reference/interfaces/rest/concepts/media-types-rest/[Supported Media Types]
- xref:/midpoint/reference/interfaces/rest/concepts/authentication/[Authentication]
- xref:/midpoint/reference/security/authorization/service/[]
