= Generate and Validate Operations
:page-nav-title: Generate And Validate
:page-display-order: 200
:page-toc: top

== Description

Request to validate or generate a value.

== Request

For the request use the HTTP POST for the request.

.Generate operation
[source, http]
----
POST http://localhost:8080/midpoint/ws/rest/generate
----

.Validate operation
[source, http]
----
POST http://localhost:8080/midpoint/ws/rest/validate
----

=== Headers

Regarding authorization type, the "Basic" Authorization header should be used.

.Authorization header example replace {Base64EncodedCredentials} with the encoded credentials
[source, http]
----
Authorization: Basic {Base64EncodedCredentials}
----

Another header would be the Content-Type Header.

.Content-Type header example, other media types are supported as well
[source, http]
----
"Content-Type: application/json"
----

You might need to specify the accepted type of content in case
you are interested in a format different from xml (default)

.Accept type header example, other media types are supported as well
[source, http]
----
"Accept: application/json"
----

.For supported media types please refer to the following section of the documentation
xref:/midpoint/reference/interfaces/rest/concepts/media-types-rest/[Supported Media Types]

=== Body

The body should contain a payload consisting of a policyItemDefinition type of object.
Based on the use case you might need to specify which value policy should be used for the operation
or which item should be the target of the operation. Please see the examples below.

=== Options

There are no supported operation options for this type of operation.

include::../../rest/concepts/raw/outcome.adoc[]

== Examples

include::../../rest/operations/examples/raw/validate-value-rpc.adoc[]

== See Also

- xref:/midpoint/reference/interfaces/rest/concepts/media-types-rest/[Supported Media Types]
- xref:/midpoint/reference/interfaces/rest/concepts/authentication/[Authentication]
