= Get Operation
:page-nav-title: REST API Get Operation
:page-display-order: 100

== Description

Request for data related to a specific object. The information contains the properties and relations
of this object as well as metadata and other technical information.

=== Safe Get

HTTP GET is a safe operation. The use of GET does not change the state of a web resource.
GET will never cause a (direct) modification. This is given by the REST architectural style.
We consider this to be a very good idea and this approach is adopted by midPoint REST API.

However, object retrieval in midPoint can have side effects.
Maybe midPoint will find out that an account that HTTP GET is trying to retrieve does not exist.
In that case midPoint consistency mechanism may be triggered and it can modify the state of the midPoint objects.
Therefore, there may be indirect changes in the objects even if GET is used. However,
those changes are not direct consequence of the GET operation.
Those are consequence of changed environment, and they are only discovered when GET operation is in progress.
Those changes would happen anyway, whether GET is used or not. It just may take a bit longer for midPoint to discover that.
Therefore, we still consider GET to be a safe operation.

To make sure no consistency related change might occur, use the *raw* option set to *true* in your
get queries.

[source, http]
----
 http://localhost:8080/midpoint/ws/rest/users/{oid}?options=raw
----


== Request

[source, http]
----
GET http://localhost:8080/midpoint/ws/rest/users/{oid}
GET http://localhost:8080/midpoint/ws/rest/users/self
----


=== Headers

In case of the get operation you often you might like to specify the accepted content type:

[source, http]
----
Accept: application/json
----

For supported media types please refer to the following section of the documentation:

- TODO Supported Media Types

=== Body

The get operation does not need to contain any specific payload data in the body of the
request.

=== Options and Functions



=== Response
The response is a set of identity data describing the fetched object. The

== Examples

== Authorizations
//TODO ??

== See Also

