/*
 * Copyright (c) 2010-2013 Evolveum
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.20 at 05:41:15 PM CEST 
//


package com.evolveum.prism.xml.ns._public.types_2;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.evolveum.prism.xml.ns._public.types_2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory implements Serializable {

    private final static QName _ObjectDelta_QNAME = new QName("http://prism.evolveum.com/xml/ns/public/types-2", "objectDelta");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.evolveum.prism.xml.ns._public.types_2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObjectReferenceType }
     * 
     */
    public ObjectReferenceType createObjectReferenceType() {
        return new ObjectReferenceType();
    }

    /**
     * Create an instance of {@link ItemDeltaType }
     * 
     */
    public ItemDeltaType createItemDeltaType() {
        return new ItemDeltaType();
    }

    /**
     * Create an instance of {@link ObjectDeltaType }
     * 
     */
    public ObjectDeltaType createObjectDeltaType() {
        return new ObjectDeltaType();
    }

    /**
     * Create an instance of {@link Extension }
     * 
     */
    public Extension createExtension() {
        return new Extension();
    }

    /**
     * Create an instance of {@link PolyStringType }
     * 
     */
    public PolyStringType createPolyStringType() {
        return new PolyStringType();
    }

    /**
     * Create an instance of {@link XPathType }
     * 
     */
    public XPathType createXPathType() {
        return new XPathType();
    }

    /**
     * Create an instance of {@link ObjectReferenceType.Filter }
     * 
     */
    public ObjectReferenceType.Filter createObjectReferenceTypeFilter() {
        return new ObjectReferenceType.Filter();
    }

    /**
     * Create an instance of {@link ItemDeltaType.Value }
     * 
     */
    public ItemDeltaType.Value createItemDeltaTypeValue() {
        return new ItemDeltaType.Value();
    }

    /**
     * Create an instance of {@link ObjectDeltaType.ObjectToAdd }
     * 
     */
    public ObjectDeltaType.ObjectToAdd createObjectDeltaTypeObjectToAdd() {
        return new ObjectDeltaType.ObjectToAdd();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectDeltaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://prism.evolveum.com/xml/ns/public/types-2", name = "objectDelta")
    public JAXBElement<ObjectDeltaType> createObjectDelta(ObjectDeltaType value) {
        return new JAXBElement<ObjectDeltaType>(_ObjectDelta_QNAME, ObjectDeltaType.class, null, value);
    }

}
