//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.20 at 05:41:15 PM CEST 
//


package com.evolveum.prism.xml.ns._public.types_2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Polymorphic string. String that may have more than one representation at
 * 				the same time. The primary representation is the original version that is
 * 				composed of the full Unicode character set. The other versions may be
 * 				normalized to trim it, normalize character case, normalize spaces,
 * 				remove national characters or even transliterate the string.
 * 
 * WARNING: THIS IS NOT A GENERATED CODE
 * Although it was originally generated, it has local modifications.			
 * 
 * <p>Java class for PolyStringType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolyStringType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orig" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="norm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolyStringType", propOrder = {
    "orig",
    "norm",
    "any"
})
public class PolyStringType {

    @XmlElement(required = true)
    protected String orig;
    protected String norm;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the orig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrig() {
        return orig;
    }

    /**
     * Sets the value of the orig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrig(String value) {
        this.orig = value;
    }

    /**
     * Gets the value of the norm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNorm() {
        return norm;
    }

    /**
     * Sets the value of the norm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNorm(String value) {
        this.norm = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * toString is tweaked to provide convenience and compatibility with normal strings.
     * If PolyStringType is used in expressions that target the entire PolyString, the result
     * will be the "orig" value of PolyString.
     * 
     * WARNING: This method was NOT generated. If the code is re-generated then it must be
     * manually re-introduced to the code.
     */
	@Override
	public String toString() {
		return orig;
	}
    
}
