CREATE OR REPLACE FUNCTION cleanupTestDatabase()
  RETURNS INTEGER AS $$
BEGIN
  TRUNCATE TABLE m_account_shadow RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_any RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_any_clob RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_any_date RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_any_long RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_any_string RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_any_reference RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_assignment RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_audit_delta RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_audit_event RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_connector RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_connector_host RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_connector_target_system RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_container RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_exclusion RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_generic_object RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_node RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_object RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_operation_result RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_org RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_org_closure RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_org_org_type RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_password_policy RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_reference RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_resource RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_resource_shadow RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_role RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_sync_situation_description RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_system_configuration RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_task RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_user RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_user_employee_type RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_user_organizational_unit RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_user_organization RESTART IDENTITY CASCADE;
  TRUNCATE TABLE m_user_template RESTART IDENTITY CASCADE;

  ALTER SEQUENCE hibernate_sequence RESTART WITH 1;

  RETURN 0;
END;
$$ LANGUAGE plpgsql;