= Predefined Columns Configuration
:page-nav-title: Predefined Columns Configuration
:page-upkeep-status: yellow
:page-moved-from: /midpoint/reference/roles-policies/certification/columns-configuration/
:page-description: This page shows how you can configure columns for your certification items collection view.
:page-keywords: columns configuration, predefined columns, accessCertification, certification
:page-toc: top

This page shows how you can configure columns for your certification items collection view.
It shows you how to configure column visibility, labels, and ordering by using column identifiers and custom path/expression settings.

== General Information

MidPoint enables you to configure columns within the object collection view configuration.
This configuration is based on the _path_ element, or the _export -> expression_ element value.
See xref:/midpoint/reference/admin-gui/admin-gui-config/admin-gui-config-examples/#custom-columns-configuration[a sample] of such a configuration.

Starting with midPoint-4.9, a predefined columns configuration is introduced.

Predefined columns are the default view columns which are already implemented in the code.
To apply a configuration to a predefined column, the identifier (column name in this case) is used.
This page shows you how to customize the predefined columns configuration.

WARNING: This feature is still under development and the configuration may change in the future.
For now, predefined columns configuration can be defined only for the certification items collection view.

== Predefined Columns Configuration

Predefined columns configuration is done within the _Object Collection View_ configuration.

A column should contain an identifier (a _name_ element within the column configuration).
The identifier should match one of the <<available_predefined_columns,available predefined columns>>.

See an example of the certification items collection view which can be located within the system configuration object:

.Certification items default collection view configuration with predefined columns
[source,xml]
----
    <accessCertification>
        <defaultView>
            <identifier>defaultCertItemsView</identifier>
            <column>
                <name>certItemObject</name>
                <display>
                    <label>Cert. item object</label>
                </display>
            </column>
            <column>
                <name>certItemTargetDisplayName</name>
                <visibility>hidden</visibility>
            </column>
            <column>
                <name>certItemEditableComment</name>
            </column>
            <includeDefaultColumns>true</includeDefaultColumns>
            <type>AccessCertificationWorkItemType</type>
        </defaultView>
    </accessCertification>
----

In the configuration above, the _Object_ column title is set to a custom value ("Cert. item object"), the target object _Display name_ column is hidden and an editable _Comment_ column is added.

Individual column configuration options can be defined in different places.
They will still be recognized as parts of the same column definition if you use the same identifier, i.e. the `name` element.
For example, you can define some column aspects in the default collection view configuration in the system configuration object, and others in the view configuration in the certification definition object.

The identifier based columns configuration can be combined with a path/expression based columns configuration.
For example:

.Combined columns configuration
[source,xml]
----
    <accessCertification>
        <defaultView>
            <identifier>defaultCertItemsView</identifier>
            <column>
                <name>certItemObject</name>
                <display>
                    <label>Cert. item object</label>
                </display>
            </column>
            <column>
                <name>certItemTargetDisplayName</name>
                <visibility>hidden</visibility>
            </column>
            <column>
                <name>stage</name>
                <display>
                    <label>Stage number</label>
                </display>
                <path>stageNumber</path>
            </column>
            <includeDefaultColumns>true</includeDefaultColumns>
            <type>AccessCertificationWorkItemType</type>
        </defaultView>
    </accessCertification>
----

[[available_predefined_columns]]
== Available Predefined Columns

As mentioned above, predefined columns can be configured only for the certification items collection view.
Therefore, the list of the available predefined columns is limited to the certification items columns.

[%autowidth]
|===
| Column | Identifier | Default | Description

| Object
| `certItemObject`
| Yes
| Linked column for the certification item object.

| Display name (for object)
| `certItemObjectDisplayName`
| Yes
| Display name of the certification item object.

| Target
| `certItemTarget`
| Yes
| Linked column for the certification item target.

| Display name (for target)
| `certItemTargetDisplayName`
| Yes
| Display name of the certification item target.

| Reviewers
| `certItemReviewers`
| Yes
| Linked reviewers column.

| Response
| `certItemResponse`
| Yes
| Displays the value of the certification item response if any exists.

| Comment icon
| `certItemCommentIcon`
| Yes
| Displays icon in the case certification item has a comment.
The comment is displayed in the icon tooltip.

| Editable comment
| `certItemEditableComment`
| No
| Contains an editable input field for commenting the certification item.

| View details link column
| `certItemDetailsLink`
| No
| Column with a "View details" link to display the popup with the certification item object and target information, response information and decision buttons.

|===


