---
midpoint-feature: access-certification
doc-type: intro
---
= Access Certification
:page-wiki-name: Access Certification
:page-wiki-id: 21200930
:page-wiki-metadata-create-user: mederly
:page-wiki-metadata-create-date: 2015-09-08T10:37:07.596+02:00
:page-wiki-metadata-modify-user: mederly
:page-wiki-metadata-modify-date: 2020-06-18T07:37:54.090+02:00
:page-upkeep-status: orange
:page-moved-from: /midpoint/reference/roles-policies/certification/
:experimental:
:page-description: This introduces certification campaigns and explains how they work.
:page-keywords: certification campaign, campaign definition, campaign configuration, campaign dashboard widget


== Introduction

MidPoint enables you to periodically review various settings, e.g. assignment of roles to users.
This feature is called *Access certification*. It is implemented in the form of certification campaigns.

A *certification campaign* is a review process that consists of identifying a set of certification cases, selecting reviewers for them, gathering decisions of these reviewers, and executing a remediation process, if needed.
Reviewer selection and decision gathering can be done multiple times, in case of multi-stage campaigns.
The remediation process can be automated or manual.
It is assumed that certification campaigns will be run regularly, e.g. yearly, twice a year, monthly, and so on.

A *certification case* is a particular "access" item which can be assessed by a reviewer.
For example, it can be a particular role assigned to a particular user.
The reviewer can decide if such access should be accepted or revoked (what decisions will be available to the reviewer depends on the configuration).

Certification campaigns consist of one or more *stages*.
Campaign stages enable you, for example, to divide the certification process between separate groups of reviewers.
The first campaign stage is assessed by one group of reviewers, while the second stage could be assessed by a different group of reviewers.
Which cases are "transferred" between stages depends on the campaign definition.
The default is that only cases which were not revoked/reduced are transferred.

Finished (closed) campaigns can be *reiterated*.
Reiteration re-starts campaigns, giving another chance to reviewers who, for example, have not provided their responses (decisions) in time.
For more details on iterations, see xref:/midpoint/reference/roles-policies/policies/certification/iteration/[].


// TODO: write more descriptive and helpful intro, explaining terminology and general flow of a campaign

== Configuration options of campaigns and related functionality

There are many aspects of what you can configure regarding certification campaigns and related midPoint functionality.
Refer to the following articles for options to configure scope, stages, GUI, notifications, or reporting.

++++
{% children style: table %}
++++
