= Access Certification Notifications
:page-nav-title: Notifications
:page-wiki-name: Access Certification Notifications
:page-wiki-id: 22282406
:page-wiki-metadata-create-user: mederly
:page-wiki-metadata-create-date: 2016-02-03T18:48:10.282+01:00
:page-wiki-metadata-modify-user: mederly
:page-wiki-metadata-modify-date: 2016-02-03T21:57:13.280+01:00
:page-upkeep-status: orange
:page-alias: { "parent" : "/midpoint/reference/misc/notifications/", "slug" : "certification",  "title" : "Access Certification" }
:page-toc: top
:page-moved-from: /midpoint/reference/roles-policies/certification/notifications/

Certification module provides the following notifications:

[%autowidth]
|===
| Event | Recipient(s) | Comment

| Campaign start
| campaign owner
| Emitted when the stage 1 is started.
(Along with "campaign stage start" described next.)


| Campaign stage start
| campaign owner
| Sent when a new review or remediation stage is opened.


| Campaign review stage end approaching
| campaign owner
| Sent when a deadline for a review stage is approaching, i.e. X hours before the deadline.
X is a number set by the "notifyBeforeDeadline" parameter.
It is interpreted as a number of hours.
This parameter is multivalued, so a notification can be sent e.g. 48 and 6 hours before the deadline occurs.


| Campaign review stage end
| campaign owner
| Sent when a review stage is closed.


| Campaign end
| campaign owner
| Sent when a campaign as such is closed.
(Not if it is deleted before being actually closed!)


| Review request
| reviewer
| Emitted when a review is requested for a set of cases.
(Currently, this is done at the same time as "campaign review stage start" event is created.
I.e. when the campaign stage is started, one notification is sent to the campaign owner and one to each of the reviewers.)


| Review deadline approaching
| reviewer
|


|===

*Planned* events (i.e. not implemented yet):

[%autowidth]
|===
| Event | Recipient(s) | Comment

| Case final decision
| campaign ownerand maybe case owner
| This event is generated when a certification case is decided.
I.e. when there we don't expect any changes in the state of this case as part of the approval processes.
(Either when it's finally rejected or when last stage is closed.)


| Case remediation
| campaign ownerand maybe case owner
| This event is generated when a certification case is remedied.


|===

Note that the recipients listed are the default ones.
By configuring the notifiers appropriately - namely, by overriding the recipientExpression - you can define other recipients as well.
You can also override the notification messages subjects and bodies.


== An example of notifications sent

The following snipped of the system configuration object can be used to configure certification notifications:

[source,xml]
----
<notificationConfiguration>
    <handler>
        <simpleReviewerNotifier>
            <transport>mail</transport>
        </simpleReviewerNotifier>
        <simpleCampaignNotifier>
            <transport>mail</transport>
        </simpleCampaignNotifier>
        <simpleCampaignStageNotifier>
            <transport>mail</transport>
        </simpleCampaignStageNotifier>
    </handler>
    <mail>
        <server>
            <host>smtp.gmail.com</host>
            <port>587</port>
            <username>...</username>
            <password>...</password>
            <transportSecurity>starttlsEnabled</transportSecurity>
         </server>
         <redirectToFile>d:\midpoint\home\mail-notifications.txt</redirectToFile>		<!-- just for debugging -->
      </mail>
</notificationConfiguration>
----

Now we create a certification definition "Test" having two stages:

[source,xml]
----
<accessCertificationDefinition xmlns="http://midpoint.evolveum.com/xml/ns/public/common/common-3"
                               xmlns:c="http://midpoint.evolveum.com/xml/ns/public/common/common-3"
                               xmlns:q="http://prism.evolveum.com/xml/ns/public/query-3">
   <name>Test</name>
   <description>test certification</description>
   <handlerUri>http://midpoint.evolveum.com/xml/ns/public/certification/handlers-3#direct-assignment</handlerUri>
   <scopeDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:type="c:AccessCertificationAssignmentReviewScopeType">
      <objectType>UserType</objectType>
      <includeAssignments>true</includeAssignments>
      <includeInducements>false</includeInducements>
      <includeResources>true</includeResources>
      <includeOrgs>true</includeOrgs>
      <enabledItemsOnly>true</enabledItemsOnly>
   </scopeDefinition>
   <ownerRef oid="00000000-0000-0000-0000-000000000002" type="c:UserType"><!-- administrator --></ownerRef>
   <remediationDefinition>
      <style>automated</style>
   </remediationDefinition>
   <stageDefinition>
      <number>1</number>
      <name>Stage 1</name>
      <duration>P3D</duration> <!-- 3 days -->
      <notifyBeforeDeadline>6</notifyBeforeDeadline>
      <notifyOnlyWhenNoDecision>false</notifyOnlyWhenNoDecision>
      <reviewerSpecification>
         <defaultReviewerRef oid="00000000-0000-0000-0000-000000000002" type="c:UserType"><!-- administrator --></defaultReviewerRef>
      </reviewerSpecification>
   </stageDefinition>
   <stageDefinition>
      <number>2</number>
      <name>Stage 2</name>
      <duration>P5D</duration> <!-- 5 days -->
      <notifyBeforeDeadline>6</notifyBeforeDeadline>
      <notifyOnlyWhenNoDecision>true</notifyOnlyWhenNoDecision>
      <reviewerSpecification>
         <defaultReviewerRef oid="75f2806d-e31b-40c9-8133-85ed4d9e6252" type="c:UserType"><!-- boss1 --></defaultReviewerRef>
      </reviewerSpecification>
   </stageDefinition>
</accessCertificationDefinition>
----

=== Action 1: Campaign is started

This results in three mail notifications being sent:


==== Notification 1.1: Campaign started notification

[source]
----
To: campaign owner (i.e. administrator)
Subject: Campaign Test 1 started

Campaign Test 1 (oid c8df2447-4f03-4d9c-94a6-2452b5ded4aa) was STARTED.

Time: Wed Feb 03 19:24:05 CET 2016
Requester: administrator (midPoint Administrator)
Operation status: SUCCESS

Current state: In review stage 1/2 (Stage 1)

Number of cases:       8
Marked as ACCEPT:      0
Marked as REVOKE:      0 (remedied: 0)
Marked as REDUCE:      0 (remedied: 0)
Marked as NOT DECIDED: 0
Marked as DELEGATE:    0
No response:           8

Requester: midPoint Administrator (administrator)
Channel: http://midpoint.evolveum.com/xml/ns/public/gui/channels-3#user
----

==== Notification 1.2: Campaign stage started notification

[source]
----
To: campaign owner (i.e. administrator)
Subject: Campaign Test 1 stage 1/2 started

A certification campaign stage has been started.

Campaign: Test 1 (oid c8df2447-4f03-4d9c-94a6-2452b5ded4aa)
State: In review stage 1/2 (Stage 1)

Time: Wed Feb 03 19:24:05 CET 2016

Stage start time: Wed Feb 03 19:24:04 CET 2016
Stage end time: Sat Feb 06 23:59:59 CET 2016

Requester: administrator (midPoint Administrator)
Operation status: SUCCESS

Number of cases:       8
Marked as ACCEPT:      0
Marked as REVOKE:      0 (remedied: 0)
Marked as REDUCE:      0 (remedied: 0)
Marked as NOT DECIDED: 0
Marked as DELEGATE:    0
No response:           8

Requester: midPoint Administrator (administrator)
Channel: http://midpoint.evolveum.com/xml/ns/public/gui/channels-3#user
----

==== Notification 1.3: Review requested notification

[source]
----
To: reviewer (i.e. administrator)
Subject: Your review is requested in campaign Test 1

You have been requested to provide a review in a certification campaign.

Campaign: Test 1 (oid c8df2447-4f03-4d9c-94a6-2452b5ded4aa)
State: In review stage 1/2 (Stage 1)

Stage start time: Wed Feb 03 19:24:04 CET 2016
Stage end time: Sat Feb 06 23:59:59 CET 2016

The stage ends in 3 days 4 hours 35 minutes 54 seconds

There are 8 cases assigned to you. Out of them, 8 have no response from you yet.
----

=== Action 2: Campaign stage end is approaching

Six hours before the stage ends the following notifications are sent:


==== Notification 2.1: Campaign review stage end approaching

[source]
----
To: campaign owner (i.e. administrator)
Subject: Campaign Test 1 stage 1/2 about to be closed

A certification campaign stage is about to be closed.

Campaign: Test 1 (oid c8df2447-4f03-4d9c-94a6-2452b5ded4aa)
State: In review stage 1/2 (Stage 1)

Time: ....

Stage start time: Wed Feb 03 19:24:04 CET 2016
Stage end time: Sat Feb 06 23:59:59 CET 2016

Stage ends in 0 days 5 hours 59 minutes 8 seconds

Number of cases:       8
Marked as ACCEPT:      3
Marked as REVOKE:      0 (remedied: 0)
Marked as REDUCE:      0 (remedied: 0)
Marked as NOT DECIDED: 0
Marked as DELEGATE:    0
No response:           5

Requester: midPoint Administrator (administrator)
Channel: null
----

==== Notification 2.2: Review deadline approaching

[source]
----
To: reviewer (i.e. administrator)
Subject: Deadline for your review in campaign Test 1 is approaching

You have been requested to provide a review in a certification campaign.

Campaign: Test 1 (oid c8df2447-4f03-4d9c-94a6-2452b5ded4aa)
State: In review stage 1/2 (Stage 1)

Stage start time: Wed Feb 03 19:24:04 CET 2016
Stage end time: Sat Feb 06 23:59:59 CET 2016

This is to notify you that the stage ends in 0 days 5 hours 59 minutes 8 seconds

There are 8 cases assigned to you. Out of them, 5 have no response from you yet.
----

=== Action 3: Campaign stage is closed (automatically, or - as in this case - manually)

==== Notification 3.1: Stage closed

[source]
----
To: campaign owner (i.e. administrator)
Subject: Campaign Test 1 stage 1/2 closed

A certification campaign stage has been closed.

Campaign: Test 1 (oid c8df2447-4f03-4d9c-94a6-2452b5ded4aa)
State: Done review stage 1/2 (Stage 1)

Time: Wed Feb 03 21:35:32 CET 2016

Stage start time: Wed Feb 03 19:24:04 CET 2016
Stage end time: Sat Feb 06 23:59:59 CET 2016

Requester: administrator (midPoint Administrator)
Operation status: SUCCESS

Number of cases:       8
Marked as ACCEPT:      3
Marked as REVOKE:      0 (remedied: 0)
Marked as REDUCE:      0 (remedied: 0)
Marked as NOT DECIDED: 0
Marked as DELEGATE:    0
No response:           5

Requester: midPoint Administrator (administrator)
Channel: http://midpoint.evolveum.com/xml/ns/public/gui/channels-3#user
----

=== Actions 4, 5: Second stage is opened and closed

Notifications similar to the ones we have already seen are produced.

=== Action 6: Remediation is started

Notification produced:


==== Notification 6.1: Remediation started notification

[source]
----
To: campaign owner (i.e. administrator)
Subject: Campaign Test 1 remediation stage started

A certification campaign stage has been started.

Campaign: Test 1 (oid c8df2447-4f03-4d9c-94a6-2452b5ded4aa)
State: Remediation in progress

Time: Wed Feb 03 21:49:04 CET 2016

Requester: administrator (midPoint Administrator)
Operation status: SUCCESS

Number of cases:       8
Marked as ACCEPT:      1
Marked as REVOKE:      1 (remedied: 0)
Marked as REDUCE:      0 (remedied: 0)
Marked as NOT DECIDED: 0
Marked as DELEGATE:    0
No response:           6

Requester: midPoint Administrator (administrator)
Channel: http://midpoint.evolveum.com/xml/ns/public/gui/channels-3#user
----

=== Action 7: Campaign is closed

The following notification is produced:

*Notification 7.1: Campaign closed notification*

[source]
----
To: campaign owner (i.e. administrator)
Subject: Campaign Test 1 closed

Campaign Test 1 (oid c8df2447-4f03-4d9c-94a6-2452b5ded4aa) was CLOSED.

Time: Wed Feb 03 21:49:04 CET 2016
Requester: administrator (midPoint Administrator)
Operation status: SUCCESS

Current state: Closed

Number of cases:       8
Marked as ACCEPT:      1
Marked as REVOKE:      1 (remedied: 1)
Marked as REDUCE:      0 (remedied: 0)
Marked as NOT DECIDED: 0
Marked as DELEGATE:    0
No response:           6

Requester: midPoint Administrator (administrator)
Channel: null
----
