:page-toc: top
:page-since: "4.9"
:visibility: data

== How to use Lifecycle state

Resource, object type, attribute, mapping, synchronization situation and other aspects of resource configuration can be configured in different lifecycle states.
As it was mentioned earlier, the Lifecycle state property can be used  with xref:/midpoint/reference/admin-gui/simulations/[Simulations].
The resource is created in `Proposed` lifecycle state by default, it won't work for normal deployment without switching to `Active` state.

By using the lifecycle state `Proposed`, you can test (simulate) the configuration without causing any damage to your target system data.
When the simulation results are satisfactory, you can switch the lifecycle state to `Active`.

As the lifecycle state can be set on various configuration items, midPoint gives you a way of turning on specific parts of configuration incrementally.
For example, after you switch your resource to `Active` lifecycle state, we recommend to add any new mappings first in `Proposed` lifecycle state.
The new mapping can be simulated without causing any harm and switched to `Active` lifecycle state when ready.

See also:

* xref:/midpoint/reference/concepts/object-lifecycle/[]
* xref:/midpoint/methodology/first-steps/[]
