:page-toc: top
:page-since: "4.9"
:page-visibility: hidden

== How to Use Lifecycle States

You can use different lifecycle states for resources, object types, attributes, mappings, synchronization situations, and other aspects of resource configuration.
You can use the lifecycle state property for xref:/midpoint/reference/admin-gui/simulations/[simulations].
Resources are created in the _Proposed_ lifecycle state by default, and don't work in normal deployment before switching the state to _Active_.

You can use the _Proposed_ lifecycle state to test (_simulate_) the configuration without causing any damage to your target system data.
When the simulation results are satisfactory, you can switch the lifecycle state to _Active_.

You can set different lifecycle states for various configuration items, which lets you put specific parts of configuration to production incrementally.

For example, after you switch your resource to the _Active_ lifecycle state, you can add new mappings in _Proposed_ lifecycle state first.
You can simulate the new mapping safely and switch it to _Active_ when it's ready.

See also:

* xref:/midpoint/reference/concepts/object-lifecycle/[]
* xref:/midpoint/methodology/first-steps/[]
