= Resource Wizards
// :page-toc: top
:page-nav-title: Resource Wizards
:page-description: Simplify identity resource management with midPoint's resource wizard. Create and configure resources effortlessly and efficiently.
:page-keywords: [ 'resource wizard', 'resource management', 'configure resources', 'integration' ]
:page-since: "4.6"
:page-since-improved: [ "4.8", "4.9" ]

Resource wizards in midPoint empower you to effortlessly manage your resource configurations through an intuitive graphical interface.
You can create and configure resources without needing to understand complex XML configurations.

Using resource wizards, you can connect various systems,
define object types,
set up mappings for data transformation,
specify reactions to synchronization situations, or
define correlation rules.
The wizards streamline the process of integrating resources, so that you to focus on what matters most—efficiently managing your identity data.

By utilizing the resource wizard, you can enhance your organization's identity management capabilities.
Whether you are creating new resources,
configuring object types for user accounts, or
defining inbound and outbound mappings,
wizards simplify the complexities of resource management, ensuring a smooth and effective experience.

There are multiple resource wizards ready to help you with various configurations related to your resources:

* xref:./create-resource-using-wizard[Create a new resource]
* xref:../resource-wizard/object-type[Configure resource object types]
* xref:../resource-wizard/association-type[Define object type relations for group membership]

//Resource wizard was completely rewritten and redesigned in midPoint version 4.6.
//It was further enhanced in midPoint 4.8.

If you would like to see the resource wizards in action, watch our resource wizard webinar video:

video::-JUXHMGrFyI[youtube,title="Resource Wizard Webinar Video"]

You can also see resource wizards used in the xref:/midpoint/methodology/first-steps/[First Steps Methodology] webinar:

video::suo775ym_PE[youtube,title="First Steps Methodology Webinar Video"]

include::limitation-all.adoc[]

include::configuration-resource-panels.adoc[]
