= Resource Wizards
// :page-toc: top
:page-nav-title: Resource Wizards
:page-since: "4.6"
:page-since-improved: [ "4.8", "4.9" ]

Resource wizards let you create and update resource configurations.
You don't need to know midPoint XML language, the wizards are entirely GUI-based.
Resource wizards take a form of screens with choices for specific parts of resource configuration.

There are multiple resource wizards ready to help you with various configurations related to your resources:

* xref:create-resource-using-wizard[Create a new resource]
* xref:resource-wizard/object-type[Configure resource object types]
* xref:resource-wizard/association-type[Define object type relations for group membership]

//Resource wizard was completely rewritten and redesigned in midPoint version 4.6.
//It was further enhanced in midPoint 4.8.

If you would like to see the resource wizards in action, watch our resource wizard webinar video:

video::-JUXHMGrFyI[youtube,title="Resource Wizard Webinar Video"]

You can also see the resource wizards used in the xref:/midpoint/methodology/first-steps/[First Steps Methodology] webinar:

video::suo775ym_PE[youtube,title="First Steps Methodology Webinar Video"]

include::limitation-all.adoc[]

include::configuration-resource-panels.adoc[]
