ALTER TABLE m_audit_event
  ALTER COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE m_audit_prop_value
  ALTER COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE m_audit_ref_value
  ALTER COLUMN id BIGINT AUTO_INCREMENT;

DROP TABLE m_exclusion;