= Global access certification settings in system configuration
:page-nav-title: Global configuration
:page-display-order: 40
:page-upkeep-status: orange
:experimental:
:page-description: This article describes the global access certification configuration concerning all campaigns regardless the template on which they are based.
:page-keywords: certification campaign, campaign definition, campaign configuration

Some aspects of access certification campaigns configuration are defined in the system configuration object.
These configuration aspects are used globally and applied to all campaigns.

You can define the following items within the _accessCertification_ element:

allowCertificationItemsMenus ::
    Defines if the certification menu items should be added to the left menu so that the "Certification items" and "My certification items" pages can be reached directly from the main menu.
    If not defined, or set to `false` (default), the certification items pages can be reached only from the active campaigns panel.
    This configuration option was added to support the old behavior where the certification items pages had their own menu items.

multiselect ::
    Defines if multiple items can be selected in the certification items collection view table. +
    The available values are:
    ** _selectAll_ - All items can be selected at once.
    ** _selectIndividualItems_ - Only individual items can be selected.
    ** _noSelect_ - No items can be selected.

defaultView ::
    Defines the default view for a presentation of the certification items collection.

availableResponse ::
    Defines which responses are available to reviewers.
    An empty list means all responses. +
    This element is *deprecated*.
    Use the configuration of actions for certification items collection view instead.
    Refer to xref:/midpoint/reference/certification/certification-campaign-configuration/gui-configuration/[]. +
    Available options:
        ** _accept_
        ** _revoke_
        ** _noResponse_
// Deprecated since 4.9.
