<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~ Copyright (c) 2010-2017 Evolveum
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->


<definitions name="reportService"
    targetNamespace="http://midpoint.evolveum.com/xml/ns/public/report/report-3"
    xmlns:tns="http://midpoint.evolveum.com/xml/ns/public/report/report-3"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

    <types>
        <xsd:schema>
            <!-- here are XSDs that are not included by means of report-3.wsdl mentioned below -->
            <!-- this is to compile all XSDs for midPoint (see explanation in pom.xml) -->
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/connector-schema-3"
                        schemaLocation="../../public/connector/icf-1/connector-schema-3.xsd"/>
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/gui/admin-1"
                        schemaLocation="../../public/gui/admin-1.xsd"/>
        </xsd:schema>
    </types>

    <import namespace="http://midpoint.evolveum.com/xml/ns/public/report/report-3"
            location="http://midpoint.evolveum.com/xml/ns/public/report/report-3"/>
    <service name="reportService">
        <port name="reportPort" binding="tns:reportBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/report/report-3"/>
        </port>
    </service>
</definitions>
