<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~ Copyright (c) 2010-2017 Evolveum and contributors
  ~
  ~ This work is dual-licensed under the Apache License 2.0 
  ~ and European Union Public License. See LICENSE file for details.
  -->


<definitions name="reportService"
    targetNamespace="http://midpoint.evolveum.com/xml/ns/public/report/report-3"
    xmlns:tns="http://midpoint.evolveum.com/xml/ns/public/report/report-3"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

    <types>
        <xsd:schema>
            <!-- here are XSDs that are not included by means of report-3.wsdl mentioned below -->
            <!-- this is to compile all XSDs for midPoint (see explanation in pom.xml) -->
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/connector-schema-3"
                        schemaLocation="../../public/connector/icf-1/connector-schema-3.xsd"/>
        </xsd:schema>
    </types>

    <import namespace="http://midpoint.evolveum.com/xml/ns/public/report/report-3"
            location="http://midpoint.evolveum.com/xml/ns/public/report/report-3"/>
    <service name="reportService">
        <port name="reportPort" binding="tns:reportBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/report/report-3"/>
        </port>
    </service>
</definitions>
