<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 * Copyright (c) 2011 Evolveum
 *
 * The contents of this file are subject to the terms
 * of the Common Development and Distribution License
 * (the License). You may not use this file except in
 * compliance with the License.
 *
 * You can obtain a copy of the License at
 * http://www.opensource.org/licenses/cddl1 or
 * CDDLv1.0.txt file in the source code distribution.
 * See the License for the specific language governing
 * permission and limitations under the License.
 *
 * If applicable, add the following below the CDDL Header,
 * with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted 2011 [name of copyright owner]"
 * Portions Copyrighted 2011 ForgeRock Inc.
 * -->
<definitions name="resourceObjectChangeListener"
    targetNamespace="http://midpoint.evolveum.com/xml/ns/public/provisioning/resource-object-change-listener-1.wsdl"
    xmlns:tns="http://midpoint.evolveum.com/xml/ns/public/provisioning/resource-object-change-listener-1.wsdl"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:c="http://midpoint.evolveum.com/xml/ns/public/common/common-1.xsd"
    xmlns:cw="http://midpoint.evolveum.com/xml/ns/public/common/object-1.wsdl"
    xmlns:i="http://midpoint.evolveum.com/xml/ns/public/common/common-1.xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

    <!-- Prefix "i" defined above is all wrong! It is workaround for OPENIDM-124 -->

    <documentation>
        Interface for submitting changes detected by the provisioning modules.

        The interface should be implemented by modules that can process the
        changes, most likely by the IDM Model implementations.
    </documentation>


    <types>
        <xsd:schema targetNamespace="http://midpoint.evolveum.com/xml/ns/public/model/model-1.wsdl">

            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/common/common-1.xsd" schemaLocation="../common/common-1.xsd"/>

            <!-- This should import identity schema. But it deos not now. Workaround for OPENIDM-124 -->
            <!--
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/identity/1#" schemaLocation="../repository/identity.xsd"/>
            -->

        </xsd:schema>
    </types>


    <message name="notifyChangeRequest">
        <part name="change" type="c:ResourceObjectShadowChangeDescriptionType">
            <documentation>
                Describes the change that happened on the resource.
                See documentation of the XSD type for more details.
                Note: This is quite an atrificial structure. In fact it should
                be split into message parts instead one XSD type. But the ObjectChangeType
                is polymorphic and OpenESB has problems with such types if placed
                directly into message parts.
            </documentation>
        </part>
    </message>

    <message name="notifyChangeResponse">
        <part name="empty" type="c:EmptyType">
            <documentation>
                Returns nothing
            </documentation>
        </part>
    </message>

    <message name="FaultMessage">
        <part name="fault" element="c:fault"/>
    </message>

    <portType name="resourceObjectChangeListenerPortType">

        <operation name="notifyChange">
            <documentation>
                Submits notification about a specific change that happened on
                the resource. The call should return without a major delay.
                It means that the implementation can do calls to repository, but
                it should not (synchronously) initiate a long-running process or
                provisioning request.

                This operation may be called multiple times with the same change,
                e.g. in case of failures in IDM or on the resource. The implementation
                must be able to handle such duplicates.
                
                Faults:
                  any SystemFaultType
            </documentation>
            <input name="notifyChangeInput" message="tns:notifyChangeRequest"/>
            <output name="notifyChangeOutput" message="tns:notifyChangeResponse"/>
            <fault name="fault" message="tns:FaultMessage">
                <documentation>
                    This is all wrong. Specific fault types should be there.
                    But because of Netbeans/JAXWS bug we need to do this ugliness.
                    Please see the list of fault types in operation documentation.
                </documentation>
            </fault>
        </operation>

    </portType>

    <binding name="resourceObjectChangeListenerBinding" type="tns:resourceObjectChangeListenerPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="notifyChange">
            <soap:operation/>
            <input name="notifyChangeInput">
                <soap:body use="literal"  namespace="http://midpoint.evolveum.com/xml/ns/public/provisioning/resource-object-change-listener-1.wsdl"/>
            </input>
            <output name="notifyChangeOutput">
                <soap:body use="literal"  namespace="http://midpoint.evolveum.com/xml/ns/public/provisioning/resource-object-change-listener-1.wsdl"/>
            </output>
            <fault name="fault">
                <soap:fault name="fault" use="literal"/>
            </fault>
        </operation>
    </binding>
    
</definitions>
