/*
 * Copyright (c) 2019 Evolveum and contributors
 *
 * This work is dual-licensed under the Apache License 2.0 
 * and European Union Public License. See LICENSE file for details.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.05.20 at 05:41:15 PM CEST
//


package com.evolveum.prism.xml.ns._public.types_3;

import com.evolveum.midpoint.prism.delta.PlusMinusZero;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;

@XmlType(name = "PlusMinusZeroType")
@XmlEnum
public enum PlusMinusZeroType implements Serializable {

    @XmlEnumValue("plus")
    PLUS("plus", PlusMinusZero.PLUS),
    @XmlEnumValue("minus")
    MINUS("minus", PlusMinusZero.MINUS),
    @XmlEnumValue("zero")
    ZERO("zero", PlusMinusZero.ZERO);
    private final String value;
    private final PlusMinusZero enumValue;

    PlusMinusZeroType(String v, PlusMinusZero eV) {
        value = v;
        enumValue = eV;
    }

    public String value() {
        return value;
    }

    public static PlusMinusZeroType fromValue(String v) {
        for (PlusMinusZeroType c: PlusMinusZeroType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static PlusMinusZeroType fromValue(PlusMinusZero v) {
        if (v == null) {
            return null;
        }
        for (PlusMinusZeroType c: PlusMinusZeroType.values()) {
            if (v == c.enumValue) {
                return c;
            }
        }
        throw new IllegalArgumentException(String.valueOf(v));
    }
}
