= Paged Search on Resources
:page-wiki-name: Paged search on resources HOWTO - UPDATED
:page-wiki-id: 17760304
:page-wiki-metadata-create-user: mederly
:page-wiki-metadata-create-date: 2014-10-22T12:00:50.321+02:00
:page-wiki-metadata-modify-user: mederly
:page-wiki-metadata-modify-date: 2014-12-16T19:17:55.492+01:00
:page-upkeep-status: orange
:page-experimental: true
:page-outdated: true

There is a feature of the ConnId framework since version 1.4: *paged search*.
The client can specify that it would like to retrieve not all query results in one operation, but only a part of it - specified by an offset and an item count.

By default, midPoint does not utilize the paged search when retrieving accounts from a resource.
For background activities, like live sync and reconciliation, this is not necessary at all.
However, for listing accounts (Resources -> All resources -> select a resource -> Resource objects) such a feature is really useful, if you have many accounts on your resource.
In non-paged case, midPoint has to retrieve all accounts up to the currently displayed page (and it does not know how many accounts are there, so showing something like "Displaying 1 to 20, unknown number of matching results.").
When using paged search, it is sufficient to retrieve only those records, which are to be displayed.
And midPoint knows how many objects are there.

How to enable paged search?

First of all, you have to use a connector that supports paged searches.

Now you have to specify that paged searches are to be used.
You can do this by creating `*<pagedSearch>` capability* - either at the level of resource or a resource object type.
A minimal config looks like this:

At the level of resource:

[source,xml]
----
<capabilities>
    <native> ... </native>
    <configured xmlns:cap="http://midpoint.evolveum.com/xml/ns/public/resource/capabilities-3">
        <cap:pagedSearch/>
    </configured>
</capabilities>
----

At the level of resource object type:

[source,xml]
----
<schemaHandling>
    <objectType>
        <kind>account</kind>
        <displayName>Default Account</displayName>
        <default>true</default>
        ...
        <configuredCapabilities xmlns:cap="http://midpoint.evolveum.com/xml/ns/public/resource/capabilities-3">
            <cap:pagedSearch/>
        </configuredCapabilities>
        ...
----

As paged searches require sorting of any kind (without sorting, the concept of a "page" has no meaning), you may define a default sorting - a field and an order.
If you do not specify it, the connector may - or may not - supply its own default sorting.
E.g. AD connector uses Common Name as a sorting criteria as the default.
But you can use e.g. "sn", as indicated below:

[source,xml]
----
<configuredCapabilities xmlns:cap="http://midpoint.evolveum.com/xml/ns/public/resource/capabilities-3">
    <cap:pagedSearch>
        <cap:defaultSortField xmlns:ri="http://midpoint.evolveum.com/xml/ns/public/resource/instance-3">ri:sn</cap:defaultSortField>
    </cap:pagedSearch>
 </configuredCapabilities>
----

Finally, you have to tell midPoint to use paged search to estimate the number of objects.
To do that, `countObjects` capability has to be used, e.g.

[source,xml]
----
<configuredCapabilities xmlns:cap="http://midpoint.evolveum.com/xml/ns/public/resource/capabilities-3">
    <cap:pagedSearch/>
    <cap:countObjects>
        <cap:simulate>pagedSearchEstimate</cap:simulate>
    </cap:countObjects>
</configuredCapabilities>
----

Note that there is also a possibility to set simulate to "sequentialSearch".
This method *does not* require paged searches.
However, it is quite inefficient, because

. it causes midPoint to fetch all resource objects in order to know their count;

. when displaying objects in the middle of the list (e.g. those from 1001 to 1010), midPoint has to uselessly fetch first 1000 objects, just to get the required ones.
Paged search is much more effective than this.

== Some AD-Related Notes

. AD/Exchange connector implements paged search for objects that get retrieved from AD: users, orgs, groups.
It does not support this kind of search for objects retrieved using PowerShell (all other Exchange-related object classes).

. The sorting key must be indexed in AD.
For example, icfs:name (a.k.a. `pass:[__NAME__]` a.k.a. distinguishedName) is not, neither is ad_container attribute.
Among attributes that are indexed by default are cn and sn.
The cn attribute is used by the connector if no sorting key is specified.

. The implementation is based on VLV.
So, in order to work, the VLV must not be disabled (see e.g. link:http://technet.microsoft.com/en-us/library/cc540446%28v=exchg.80%29.aspx[here]).

. If you still get the "*The server does not support the requested critical extension.*" error, consider

.. applying link:http://support.microsoft.com/kb/977180[kb977180-v2]

.. setting HKLM\System\CurrentControlSet\Services\NTDS\Parameters\DSA Heuristics to 000000000001 (string) - see link:https://social.technet.microsoft.com/Forums/windowsserver/en-US/51c2dbd4-91fe-4f38-a4dc-d7f04c3d7f8a/c-application-virtual-view-list-with-directoryvirtuallistview-the-server-does-not-support-the?forum=winserverDS[this discussion thread] - although beware if this fits into your environment!

. If you encounter problems with queries with large result sets, you might want to link:http://support2.microsoft.com/kb/2009267[tune your server's LDAP parameters].
