= Read-Only Resource
:page-wiki-name: Read-only Resource HOWTO
:page-keywords: [ 'readonly', 'capabilities' ]
:page-upkeep-status: orange

This page describes how to pretend that ordinary read-write resource is in fact read-only.

There are many reasons for this.
But it perhaps is most useful during midPoint setup, testing and migration.
You can test midpoint on real resources by setting them to read-only mode.
You can be sure that midPoint will not destroy the data on the resource even if you have a bug in mappings or make a mistake during a migration procedure.

MidPoint resource can be switched to read-only mode by disabling the resource capabilities that create, modify and delete resource objects.
The capabilities are checked by low-level components of midPoint (in wiki:Provisioning+Subsystem[Provisioning Subsystem]) therefore even a severe misconfiguration of high-level midPoint features will not be able circumvent this protection.

TODO

.Read-only capabilities
[source,xml]
----
<capabilities xmlns:cap="http://midpoint.evolveum.com/xml/ns/public/resource/capabilities-2">
  <configured>
    <cap:create>
      <cap:enabled>false</cap:enabled>
    </cap:create>
    <cap:update>
      <cap:enabled>false</cap:enabled>
    </cap:update>
    <cap:delete>
      <cap:enabled>false</cap:enabled>
    </cap:delete>
  </configured>
</capabilities>
----

