= Import From Report
:page-nav-title: Import From Report
:page-display-order: 400
:page-toc: top
:page-keywords: [ 'report', 'import' ,'reverse' ]
:page-upkeep-status: green


[WARNING]
.Advanced Feature
====
The import from report, often requires scripting and other special configuration options.
If the set-up is not correct you are risking potential *override* or *deletion* of midPoint and/or account data.

Proceed with caution.
====

== Import Behaviour 'Import From report'

MidPoint supports 'import reports'/'reverse reports'.
This feature is still *xref:/midpoint/versioning/experimental/[experimental]*.
The basic idea is that the report output generated by midPoint can also be used in reverse way - you can import it back to midPoint.
In addition, it is also possible to import a custom defined report output.

This might be handy if you wand to update or change some already imported objects in some other way than through the midPoint UI (e.g. in some spreadsheet) and reimport them back.
Yet as mentioned above, this feature is still experimental and such details often require custom configuration.

Midpoint support two kind of import configuration.
Configuration for _Object Import_ and _Import script_.

== Object Import

MidPoint has to *understand* the report output data structure to preform the import correctly.
This is configured in the report (ReportType), in a similar way as for exporting, so the configuration has to contain the information about columns and paths to which they are mapped.
For details on how to configure standard reports please see xref:/midpoint/reference/misc/reports/configuration/[this] link.
For now, only reports generated from xref:/midpoint/reference/misc/reports/configuration/collection-report.adoc[object collections] and CSV format is supported (CSV FileFormatType).

Example of Imported File:

.CSV file
[source,csv]
----
"Name";"Administrative status";"Valid from";"Nick";"AssignmentOid";"Subtype"
"testUser01";"enabled";"2020-07-07T00:00:00.000+02:00";"nick1";"00000000-0000-0000-0000-000000000008,00000000-0000-0000-0000-000000000004";"sub1,sub22"
"testUser02";"enabled";"2020-07-07T00:00:00.000+02:00";"NICK2";;
----


Example below shows report (ReportType) configuration for importing CSV file with header and two records above.

.*Import Behavior Example*
[%collapsible]
====
sampleRef::samples/reports/import/import-report-with-view.xml[]
====

=== Behaviour and Options

You have to specify the direction of the report,in this case import and rather than the export direction, for this you need define the element _behavior_.
_Behavior_  contains the direction _Import_ or _Export_.
Also, a part of the _behavior_ configuration is the parameter *_importOptions_*, which has the following elements:

[%autowidth]
|===
| Name | Description | Type

| *overwrite*
| If set to "true", objects that are in the repository will be overwritten by the imported objects.
It may not be applicable to all import types.
E.g. it makes no sense for import from resource, as this is not storing objects in the repository directly.
| *boolean*


| *keepOid*
| If set to "true", objects that are overwritten will reuse the same OID as previous objects.
May be potentially dangerous.
USE WITH CARE.
| *boolean*


| *stopAfterErrors*
| Number of errors that will cause import to stop.
If set to one the import will stop on first error.
If set to zero or a negative value the import will continue in case of any number of errors.
| *int*


| *summarizeSucceses*
| If set to true the successfully imported items will be summarized in the result.
WARNING: setting this to false may result in a very large result structure and may cause overflow of the system memory.
| *boolean*


| *summarizeErrors*
| If set to true the import errors will be summarized in the result.
| *boolean*


| *referentialIntegrity*
|

| *boolean*


| *validateStaticSchema*
|

| *boolean*


| *validateDynamicSchema*
|

| *boolean*


| *encryptProtectedValues*
|

| *boolean*


| *fetchResourceSchema*
|

| *boolean*


| *keepMetadata*
| If set to true then the metadata from the source file will be kept after the operation.
If set to false then the original metadata will be replaced with new metadata on each object.
| *boolean*


| *modelExecutionOptions*
| If present, these options are used for adding objects into the repository.
Null option values might be overridden by import-related options.
In particular, the missing "raw" option is overridden to "true".
So, if you want the operation run in non-raw mode, set "raw" option to "false" (e.g. runs also global templates, policy configuration, etc...).
| *ModelExecuteOptionsType*


| *compatMode*
| Compatibility model.
If selected then the data parsing will be less strict.
E.g. removed element will be ignored.
| *boolean*


|===

In previous example of report we define mapping values from columns to items in new object.
The name of the column in the CSV file has to be same as the name defined in view.
Definition of the name from a view has some rules.
Name is obtained from _Label_ of _DispalyType_ for column, when _Label_ is empty, then Midpoint finds the name from the item definition based on the _Path_ element in a column.

Definition of a column also contains _import/expression_ which can be used to define a script for generating items.
Scripts have to return a real value, for example _String_ or _List_ of values for multivalued items, for example _List<AssignmentType>_.
The script has a variable _input_ which is a _String_ when the item is single valued or a _List<String>_, when item is multivalued.

== Import Script

You can define _importScript_ in element _behaviour_.
// Import script is _ExecuteScriptType_ type, so we can define more actions.
The Script contains variables with the same name as headers of imported CSV file.
For example the following file will provide us with the variables with names _username, role_name, action, valid_from_ and _valid_to_.

.*Example of Imported File*
[%collapsible]
====
.CSV file
[source,csv]
----
"username";"role_name";"action";"valid_from";"valid_to"
"testUser02";"Superuser";"A";"2018-01-01";"2025-05-01"
"testUser01";"Superuser";"D";;
"fakeUser";"Superuser";"M";"2018-01-01";"2025-05-01"
"jack";"Superuser";A;"2018-01-01";"2025-02-01"
"jack";"Superuser";"M";"2018-01-01";"2025-05-01"
"jack";"FakeRole";"M";"2018-01-01";"2025-05-01"
----
====

In the next example we change the assignments of users based on _username_.(e.g. the first line 'testUser02').
The operation which is executed is specified by the variable _action_ ('A'=add, 'M'=modify, 'R'=remove).
The target of the assignment is chosen via the variable _role_name_, which represents a role in midPoint.
Variables _valid_from_ and _valid_to_ are mapped to the properties _activation/validFrom_ and _activation/validTo_ of assignment.

.*Import Script Behavior Example*
[%collapsible]
====
sampleRef::samples/reports/import/report-with-import-script.xml[]
====

== See Also

- xref:/midpoint/reference/misc/reports/examples/[Report Examples]
- xref:/midpoint/reference/misc/reports/configuration/[Report Configuration]
- xref:/midpoint/reference/misc/reports/configuration/collection-report.adoc[Collection Based Reports]
- xref:/midpoint/reference/misc/reports/configuration/dashboard-report.adoc[Dashboard Based Reports]
- xref:/midpoint/reference/misc/reports/configuration/report-security.adoc[Report Security]
- xref:/midpoint/reference/misc/reports/configuration/report-task-definition.adoc[Report Task Definition]

