---
midpoint-feature: approval-process
doc-type: config
---
= Approval
:page-wiki-name: Approval
:page-wiki-id: 24084555
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2016-11-28T14:20:31.930+01:00
:page-wiki-metadata-modify-user: vera
:page-wiki-metadata-modify-date: 2020-03-31T15:04:51.194+02:00
:page-upkeep-status: red
:page-upkeep-note: Old approvals vs new approvals

Approval is perhaps the most frequently used type of workflow in the IDM solutions.
It is used so often that the approval process has a special place in midPoint.
The approval mechanisms are pre-defined and pre-configured in such a way that it is easy to implement majority of approval scenarios by simply using declarative approach.
Workflow process modeling is almost never needed.


== Basic Idea

MidPoint does *not* have any special way how to request something.
E.g. there is no special mechanism how to request assignment of a role or how to request creation of a new organizational unit.
The request is simply the operation itself: user requests an assignment of a role simply by trying to assign the role to himself.
When midPoint encounters an operation like this it will consult the policies (xref:/midpoint/reference/roles-policies/policies/policy-rules/[Policy Rules]) and decide whether the operation needs to be driven through an approval process.
If an approval is needed then midPoint will automatically compute the approvers and start a workflow process to drive the approvals.
When the approval process is done then midPoint will gather the results and proceed with the operation.

Therefore the only thing that is usually needed to set up an approval mechanism is the definition of the approvers and the xref:/midpoint/reference/roles-policies/policies/policy-rules/[policy rules]. MidPoint will take care of the rest.

There are two broad categories for approvals: assignment approval and lifecycle approvals.
These are described in the following sections.


== Assignment Approval

Assignment approvals decide whether a user can have some kind of xref:/midpoint/reference/roles-policies/roles/assignment/[assignment]. This usually means approval of a role assignment.
The process usually goes like this:

* User selects a role in the midPoint user interface (shopping cart).
The user simply selects the roles and clicks on the "request" button.
What the user does not know is that in fact this starts an operation that adds new assignment to the user object xref:/midpoint/architecture/archive/data-model/midpoint-common-schema/usertype/[UserType].

* When that operation is evaluated, xref:/midpoint/reference/concepts/clockwork/clockwork-and-projector/[internal algorithms] in midPoint will analyze all the requested roles.
MidPoint will evaluate xref:/midpoint/reference/roles-policies/roles/rbac/[role hierarchies], xref:/midpoint/reference/roles-policies/policies/metaroles/gensync/[metaroles], gather all the applicable xref:/midpoint/reference/roles-policies/policies/policy-rules/[policy rules] and apply default policies.
This determines how the role assignment needs to be approved - and by whom.
This also determines whether the role can be assigned at all (e.g. whether it does not violate the xref:/midpoint/reference/roles-policies/policies/segregation-of-duties/[SoD constraints]).

* If there are any approvers then midPoint suspends the operation and it will drive it through an approval workflow.

* After approvals are done the operation continues (if it was approved) or it is discarded.

The default policy in midPoint is to drive the request through approvals only if there are any approvers defined for the role.
If no approvers are defined then the request is not driven through the approval process and it is automatically executed.
This default can be changed by properly setting up the xref:/midpoint/reference/roles-policies/policies/policy-rules/[policy rules].

Default role approvers are defined by using the xref:/midpoint/reference/roles-policies/roles/assignment/[assignment mechanism].
Role approvers have an assignment pointing to the role that are approving.
This assignment has xref:/midpoint/reference/concepts/relation/[Relation] set to `approver`.
The default midPoint policy will look for these assignments.
Application of the default mechanism can be controlled using `useDefaultApprovalPolicyRules` in xref:/midpoint/reference/concepts/system-configuration-object/[system configuration].

[WARNING]
.Default approval mechanism may be confusing
====
The default approval mechanism is *not* applied if any other approval-related policy rule is applied.
I.e. if any approval-related policy rule is applied, then the default approval step must be explicitly included in such policy rules, if the default behavior is still desired.
This can be quite confusing, especially when approval is configured using feature:applicable-policies[applicable policies].
====


== Lifecycle Approval

Lifecycle approvals take place when an object is changed, e.g. when a new organizational unit is created, when a role definition is modified, when a role is deprecated and so on.
The lifecycle approval process is very similar to that of assignment approval.
The lifecycle approval goes like this:

* User creates or modifies an object.
E.g. a junior role engineer creates a new role.
Operation to add a new role object is started in midPoint.

* When that operation is evaluated, xref:/midpoint/reference/concepts/clockwork/clockwork-and-projector/[internal algorithms] in midPoint will analyze xref:/midpoint/reference/roles-policies/policies/policy-rules/[policy rules] that are applicable to the new role.
As this role is new then the global policy rules will be applied.
The policy rules may define an approver for the role modification.

* MidPoint will suspend the operation and start an approval workflow.

* After approvals are done the operation continues (if it was approved) or it is discarded.

See xref:/midpoint/reference/roles-policies/roles/role-lifecycle/[Role Lifecycle] page for more details about specific use of lifecycle approval to control role lifecycle.

[TIP]
.MidPoint 3.5 or later
====
This functionality is available in midPoint 3.5 and later.
Although it was - in some form - present also in midPoint 3.4.1 and earlier (using approval aspects), it is strongly recommended to use this new (policy rules based) mechanism instead.
====


== See Also

* xref:/midpoint/reference/roles-policies/roles/assignment/[Assignment]

* xref:/midpoint/reference/roles-policies/policies/policy-rules/[Policy Rules]

* xref:/midpoint/reference/roles-policies/roles/role-lifecycle/[Role Lifecycle]

* xref:/midpoint/reference/misc/deputy/[Deputy]
