= User Type Web Resource
:page-nav-title: REST API User Type Resource
:page-display-order: 200
:page-toc: top

== Description

Here we are describing the User object type in relation to midPoints REST API. The
User objects are a part of the REST API web resources.

.Endpoint
[source, http]
----
users/
----

== Applicable Operations

The User web resource is a part of the Create-Read-Update-Delete (CRUD) web resources
present in midPoint. This is apparent in the operations which are available for this type of object.

// TODO referencie na operacie

- xref:/midpoint/reference/interfaces/rest/operations/create-op-rest/[Create Operation]
- xref:/midpoint/reference/interfaces/rest/operations/get-op-rest/[Get Operation]
- xref:/midpoint/reference/interfaces/rest/operations/search-op-rest/[Search Operation]
- xref:/midpoint/reference/interfaces/rest/operations/modify-op-rest/[Modify Operation]
- xref:/midpoint/reference/interfaces/rest/operations/delete-op-rest/[Delete Operation]
- xref:/midpoint/reference/interfaces/rest/operations/user-specific-op-rest/[User specific Operations]
- xref:/midpoint/reference/interfaces/rest/operations/generate-and-validate-concrete-op-rest/[Generate and Validate Operations]

== JSON Example

Example output of information regarding a specific user object. Metadata is usually a part of
the output, yet it was removed for the purpose of the example.

.Show JSON Example
[%collapsible]
====
[source, json]
----
{
  "user" : {
    "oid" : "00000000-0000-0000-0000-000000000002",
    "name" : "administrator",
    "indestructible" : true,
    "assignment" : [ {
      "@id" : 1,
      "identifier" : "superuserRole",
      "targetRef" : {
        "oid" : "00000000-0000-0000-0000-000000000004",
        "relation" : "org:default",
        "type" : "c:RoleType"
      },
      "activation" : {
        "effectiveStatus" : "enabled"
      }
    }, {
      "@id" : 2,
      "identifier" : "archetype",
      "targetRef" : {
        "oid" : "00000000-0000-0000-0000-000000000300",
        "relation" : "org:default",
        "type" : "c:ArchetypeType"
      },
      "activation" : {
        "effectiveStatus" : "enabled"
      }
    } ],
    "iteration" : 0,
    "iterationToken" : "",
    "archetypeRef" : {
      "oid" : "00000000-0000-0000-0000-000000000300",
      "relation" : "org:default",
      "type" : "c:ArchetypeType"
    },
    "roleMembershipRef" : [ {
      "oid" : "00000000-0000-0000-0000-000000000300",
      "relation" : "org:default",
      "type" : "c:ArchetypeType"
    }, {
      "oid" : "00000000-0000-0000-0000-000000000004",
      "relation" : "org:default",
      "type" : "c:RoleType"
    } ],
    "credentials" : {
      "password" : {
        "value" : {
          "clearValue" : "5ecr3t"
      }
    },
    "fullName" : "midPoint Administrator",
    "givenName" : "midPoint",
    "familyName" : "Administrator"
  }
}
}
----
====

== See Also
- xref:/midpoint/reference/interfaces/rest/concepts/media-types-rest/[Supported Media Types]
- xref:/midpoint/reference/interfaces/rest/concepts/media-types-rest/[Authentication]
