= Attribute Limitations

The limitations include

* *Ignore* flag, if set to `true` will make the attribute effectively disappear.
The attribute will still be passed between midPoint and the resource, but the GUI and other parts of midPoint logic will pretend that it is not there.

* *Multiplicity override* by use of *minOccurs* and *maxOccurs* element.
It can be used to adjust multiplicity of the attribute.
The multiplicity is usually determined by the schema which is generated by the connector.
However, the connector might provide a wrong schema.
Or more commonly the schema is used differently as is formally defined.
Perhaps the most common case is LDAP.
Most LDAP attributes are defined as multi-value while vast majority of systems use them as single-value.
The multiplicity override can be used to let midPoint think that these attributes are in fact single-valued.

* *Access* limitations of the attribute.
E.g. administrator can make the attribute read-only even if the connector can both read and write the attribute value.
The access limitation consists of three boolean switches:

** *add*

** *read*

** *modify*



.Listing 4. Attribute limitation example
[source,xml]
----
<attribute>
    <ref>ri:cn</ref>
    ...
    <limitations>
        <minOccurs>1</minOccurs>
        <maxOccurs>1</maxOccurs>
        <access>
            <add>true</add>
            <read>true</read>
            <modify>false</modify>
        </access>
    </limitations>
    ...
</attribute>

----

The limitations can be expressed for several layers.
Currently there are two layers defined:

* *Presentation* layer is aimed at the GUI and other forms of external data presentation such as an application behind a web service.

* *Model* layer defines midPoint internals.
It is applied to mappings, internal schema validations, etc.

Separate set of limitations can be configured for each layer.
This is often used to hide some attributes in the GUI while compute them in the model.
Therefore such attribute needs to be ignored in the GUI but it has to be read-write in the model.
Following example illustrates such configuration.
A limitation that does not specify any layer applies to all the layers.
The other limitations may modify that.

.Listing 5. Attribute limitation with layers
[source,xml]
----
<attribute>
    <ref>ri:cn</ref>
    ...
    <limitations>
        <minOccurs>1</minOccurs>
        <maxOccurs>1</maxOccurs>
        <access>
            <add>true</add>
            <read>true</read>
            <modify>true</modify>
        </access>
    </limitations>
    <limitations>
        <layer>presentation</layer>
        <ignore>true</ignore>
    </limitations>
    ...
</attribute>
----


// There is a separate access limitation configuration for each resource attribute supported by the resource schema:
//
// * *create*: the attribute can be set when creating a resource account.
// Useful for attributes that can be set only once.
//
// * *update*: the attribute can be set when updating a resource account.
//
// * *read*: the attribute is read-only and can't be modified.
//
// By default, no access limitation is enforced (create, update, read).
