= Attribute Modification Priority

Modification priority of this item.
Items with specified priorities are modified in order that follows these priorities: these with lower numbers are modified first, these with higher numbers next, and items with unspecified priorities are modified last.
Each priority level gets its own modify operation (or operations, if required by ConnId limitations).
Currently this property is supported only for simple attributes.
(It is envisioned that 'addingPriority' could be created as well in the future; it would concern creating new objects.
In that case, attributes with numerically lowest adding priority would be used to create an object, and other attributes would be set via MODIFY operation, again, according to their priorities.)

Attributes with specified priorities are modified in order that follows these priorities:

- these with lower numbers are modified first,
- these with higher numbers next,
- and items with unspecified priorities are modified last.

Each priority level gets its own modification operation.
