= Bulk Actions Authorizations
:page-since: 4.8
:toc-top:
:page-keywords: bulk actions, action authorizations, bulk action, action, actions, authorization, authorizations
:page-description: This page describes authorizations required to run bulk actions.


This describes authorizations required to run bulk actions.

Bulk xref:/midpoint/reference/misc/bulk/index.adoc#_actions[actions] in midPoint allow users to execute operations on many objects at once, making large-scale management tasks faster and more efficient.
Because such operations can affect many objects simultaneously, midPoint requires both the standard object authorization and an additional bulk-action authorization.

To enable users to run bulk actions, you need to grant them:

. Access to the actual objects on which bulk actions are executed. +
For example, to be able to delete objects in bulk, you need the http://midpoint.evolveum.com/xml/ns/public/security/authorization-model-3#delete authorization for those individual objects. +
See xref:/midpoint/reference/security/authorization/model[].

. Authorization to run bulk actions - `http://midpoint.evolveum.com/xml/ns/public/security/authorization-bulk-3`.
You can grant this bulk authorization either for:

** Individual actions, such as `assign`, `unassign`, `delete`, `resolve`.  +
For example, when you grant the `http://midpoint.evolveum.com/xml/ns/public/security/authorization-bulk-3#assign` authorization to users, they will be able to execute the `assign` action in bulk.

** Or for all bulk actions using the following authorization -  `http://midpoint.evolveum.com/xml/ns/public/security/authorization-bulk-3#all`.
This allows users to execute all bulk actions, such as `assign`, `unassign`, `delete`, `resolve`, etc.


The primary names of actions are used, e.g., `generate-value` (as opposed to `generateValue`).
See xref:/midpoint/reference/misc/bulk/index.adoc#_actions[Actions] for more details.

[NOTE]
====
Before midPoint 4.8, the `http://midpoint.evolveum.com/xml/ns/public/security/authorization-bulk-3#all` authorization was named `http://midpoint.evolveum.com/xml/ns/public/security/authorization-model-3#executeScript`.
Despite the confusing name, this authorization would not allow you to run Groovy (or Velocity, Python, JavaScript, and similar).
As scripts are powerful tools, running them still required the `#all` authorization.
====


== See Also

* xref:../[Authorization]
* xref:/midpoint/reference/misc/bulk/index.adoc#_actions[Actions]
* xref:/midpoint/reference/security/authorization/model[]
