= Flexible Authentication Configuration
:page-nav-title: Configuration
:page-wiki-name: Flexible Authentication Configuration
:page-wiki-id: 41517151
:page-wiki-metadata-create-user: lskublik
:page-wiki-metadata-create-date: 2019-11-25T09:32:45.286+01:00
:page-wiki-metadata-modify-user: virgo
:page-wiki-metadata-modify-date: 2020-10-14T10:12:43.521+02:00
:page-since: "4.4"
:page-toc: top


Basic idea of flexible authentication is described on xref:..[Flexible Authentication] page.
Before we describe configuration of flexible authentication, we have to become acquainted with a few terms.

TODO it would be nice to warn the user who starts flexible authentication configuration about the risk not to have an access to midPoint GUI part. E.g. in case of incorrect LoginForm module configuration or in case of its absence, there will be no possibility to login via standard login form again. In that case the user should have another way to restore midPoint environment.

TODO please, add a sample of urlSuffix attribute usage. There is a sample with explanation "Midpoint searches authentication sequence base-on next part of URL, in this case 'emergency'". But it's not clear here that 'emergency' is a value of urlSuffix attribute. I would suggest to paste url sample right to the table with attribute description.

== Basic concepts


=== Authentication module

Authentication module is basic building unit of flexible authentication.
The easiest example of authentication module is classic login form, which we can find on every application.
Login form contains field for username or email and password.
Login form represent one authentication module, next modules can be authentication by LDAP, HTTP basic authentication, authentication via Identity Provider server, etc.
Every Authentication module contains some configuration properties, which define configuration for this kind of authentication module.


=== Authentication sequence

Authentication sequence is made up of authentication modules, so it contains chain of authentication modules.
Each of module has its order in chain and necessity for this sequence.
Sequence is defined by channel.
Channel represents part of Midpoint, for which this authentication sequence is valid, for example GUI, REST service, etc.
Also channel contains url suffix for this authentication sequence.
So channel defines, which authentication sequence will be used for http request.


=== Authentication channel

Flexible authentication knows following channels:

[%autowidth]
|===
| Request servlet suffix | Channel | Note

|
| http://midpoint.evolveum.com/xml/ns/public/common/channels-3#user
| Default one, represents GUI.
No suffix specified.


| /ws, /rest, /api
| http://midpoint.evolveum.com/xml/ns/public/common/channels-3#rest
|


| /actuator
| http://midpoint.evolveum.com/xml/ns/public/common/channels-3#actuator
|


| /resetPassword
| http://midpoint.evolveum.com/xml/ns/public/common/channels-3#resetPassword
|


| /registration
| http://midpoint.evolveum.com/xml/ns/public/common/channels-3#selfRegistration
|


|===

Channels for _rest_ and _actuator_ default don't create audit records about session creation or termination.
You can turn on it via variable in System Configuration _audit->eventRecording->recordSessionlessAccess_.


=== Choosing of Authentication sequence

We can describe flow on two examples.


==== First example

Midpoint receives HTTP request with URL 'http:localhost:8080/midpoint/actuator/metrics'.
Midpoint obtains suffix 'actuator' from URL and it gets channel from table base-on suffix.
Obtained channel is used for searching default sequence for channel.
Next midpoint initialize found authentication sequence.
After successful authentication Midpoint sends request to actuator service.


==== Second example

Midpoint receives HTTP request with URL 'http:localhost:8080/midpoint/auth/emergency/users'.
Midpoint obtains suffix 'auth' from URL, this suffix defines using of specific authentication sequence.
Midpoint searches authentication sequence base-on next part of URL, in this case 'emergency'.
After successful authentication Midpoint sends request to service, which defines channel in sequence configuration.
Let's say it is GUI for this example, so request is redirect to users page in GUI.


== Basic configuration

Flexible authentication is configured in xref:/midpoint/reference/security/security-policy[Security Policy], which is used as global security policy in System Configuration.
Base tag is _<authentication>_.  Configuration consists of modules and sequences.
Element `module` is basic building block of the configuration.
Each element has a configuration of a particular authentication module instance such as internal password-based authentication, SAML authentication and so on.
Each module specified in the container must have unique name.
Element `sequence` defines a sequence of authentication modules.
The modules are invoked in order as they are specified in the sequence.
The purpose of the sequence is to guide user through a complete authentication process.

*IMPORTANT*

*Midpoint GUI authentication form:* To be able to use Midpoint GUI, an authentication sequence for formLogin module should be configured. In case when no authentication is configured in the security policy at all or there is no sequence in the configured authentication, Midpoint will use standard (built in) login form for the user GUI authentication. In case when at least one /not formLogin/ sequence is configured in the authentication configuration, a sequence for formLogin module should be evidently specified in the authentication configuration to make Midpoint GUI work. To see the default formLogin sequence configuration, please use security policy from the Midpoint initial objects (015-security-policy.xml).

=== Module configuration

The following modules are supported now: `formLogin`, `saml2`, `httpHeader`, `httpBasic`, `httpSecQ`, `securityQuestionsForm`, `mailNonce`, `ldap.`
Each element contains common attributes:

[%autowidth]
|===
| Name | Description | Required | Type | Default

| `name`
| Unique name of the authentication module.
This name is fact a short identifier.
It is supposed to give some idea about nature of the module to system administrator.
But it is not supposed to be used as a user-friendly label for the module.
The name is also used in the url, so it should not contain special characters.
| true
| _String_
|


| `description`
| Free form description of the module (administrator comment).
| false
| _String_
|


| `focusType`
| Type of logged object that this authentication module applies to.
E.g UserType, RoleType, OrgType, ...
| false
|

| _UserType_


|===


==== Module formLogin

FormLogin module is used for interactive log-in of a user by using HTML forms.


.Example of formLogin module
[source,xml]
----
<loginForm>
	<name>internalLoginForm</name>
    <description>Internal username/password authentication, default user password, login form</description>
</loginForm>
----


==== Module httpBasic

Definition of HTTP BASIC authentication module (RFC 7617).

.Example of httpBasic module
[source,xml]
----
<httpBasic>
	<name>internalHttpBasic</name>
    <description>Http basic username/password authentication, default user password</description>
</httpBasic>
----


==== Module httpSecQ

Definition of HTTP SecQ module.
The module is used for quasi-interactive log-in of a user by answering a set of security questions.
The HTTP SecQ mechanism is similar to HTTP BASIC mechanism, but it is using security questions instead of password.

.Example of httpBasic module
[source,xml]
----
<httpSecQ>
	<name>httpSecurityQuestions</name>
</httpSecQ>
----


==== Module securityQuestionsForm

Definition of "security questions form" module.
The module is used for interactive log-in of a user by answering a set of security questions.

.Example of securityQuestionsFrom module
[source,xml]
----
<securityQuestionsForm>
	<name>securityQuestions</name>
</securityQuestionsForm>
----


==== Module mailNonce

Mail nonce authentication module.
Module that sends randomly generated nonce in URL in mail message.
This module contains next attribute:

[%autowidth]
|===
| Name | Description | Required | Type

| `credentialName`
| Name of credential definition that should be used when validating password.
This must point to a valid credential definition in the "credential" section of a security policy.
If not specified then default password definition is used.
| false
| _String_

|===


.Example of mailNonce module
[source,xml]
----
<mailNonce>
	<name>securityQuestions</name>
	<credentialName>mailNonceCredential</credentialName>
</mailNonce>
----


==== Module ldap

LDAP authentication module supports authentication via LDAP server.
This module contains next attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `host`
| Host of the LDAP server.
| true
| _String_


| `userDn`
| The user distinguished name.
| true
| _String_


| `userPassword`
| The password (credentials) to use for getting authenticated contexts.
| true
| _String_


| `dnPattern`
| The pattern which will be used to supply a DN for the user.
| false
| _String_


| `search`
| Search configuration which uses an Ldap filter to locate the user.
| false
| _AuthenticationModuleLdapSearchType_

|===


===== AuthenticationModuleLdapSearchType

[%autowidth]
|===
| Name | Description | Required | Type

| `pattern`
| The filter expression used in the user search.
This is an LDAP search filter (as defined in 'RFC 2254') with optional arguments.
Example: `(uid=\{0})`
| true
| _String_


| `namingAttr`
| Specifying explicit LDAP attribute that is retrieved from user's LDAP account and contains value that matches midPoint's username.
| false
| _String_


| `subtree`
| If true then searches the entire subtree as identified by context, if false (the default) then only searches the level identified by the context.
| false
| _Boolean_

|===


.Example of ldap module
[source,xml]
----
<ldap>
	<name>ldapAuth</name>
	<host>ldap://localhost:389/dc=example,dc=com</host>
	<userDn>cn=admin,dc=example,dc=com</userDn>
	<userPassword>
        <t:clearValue>secret</t:clearValue>
    </userPassword>
    <dnPattern>uid={0},ou=people</dnPattern>
    <search>
        <pattern>(uid={0})</pattern>
        <namingAttr>uid</namingAttr>
        <subtree>true</subtree>
    </search>
</ldap>
----


==== Module httpHeader

Pseudo-authentication for pre-authenticated users.
Based on HTTP header values.
This module contains specific attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `usernameHeader`
| Name of HTTP header that contains username.
| true
| _String_


| `logoutUrl`
| Url for redirect after logout.
Default is '/'.
| false
| _String_

|===



.Example of httpHeader module
[source,xml]
----
<httpHeader>AuthenticationModuleSaml2ProviderMetadataType
	<name>httpHeader</name>
    	<logoutUrl>http://localhost:8081/Identity_provider/Logout</logoutUrl>
        <usernameHeader>uid</usernameHeader>
</httpHeader>
----


==== Module saml2

SAML2 authentication module supports authentication via Identity provider with SAML2.
SAML2 module has a little bit complicated configuration.
This module contains specific attribute:

[%autowidth]
|===
| Name | Description | Required | Type

| `serviceProvider`
| Basic configuration of SP.
| true
| _AuthenticationModuleSaml2ServiceProviderType_

|===

===== AuthenticationModuleSaml2ServiceProviderType

_AuthenticationModuleSaml2ServiceProviderType_ contains following configuration attributes:

[%autowidth]
|===
| Name | Description | Required | Type | Default | Unused from 4.4

| `entityId`
| Unique identifier of the service provider.
| true
| _String_
|
|


| `alias`
| Unique alias used to identify the selected local service provider based on used URL.
| false
| _String_
|
|


| `aliasForPath`
| Alias used for AssertionConsumerServiceURL.
| false
| _String_
|
|


| `defaultSigningAlgorithm`
| Default signing algorithm.
Possible values are RSA_SHA1, RSA_SHA256, RSA_SHA512 and RSA_RIPEMD160.
| false
| _enum_
| RSA_SHA256
|


| `signRequests`
| Flag indicating whether this service signs authentication requests.
| false
| _boolean_
| false
|


| `keys`
| Key used by service provider.
| false
| _AuthenticationModuleSaml2KeyType_
|
|


| `identityProvider`
| Possible identity providers for this service provider.
| true
| _AuthenticationModuleSaml2ProviderType_
|
|


|===


===== AuthenticationModuleSaml2KeyType

_AuthenticationModuleSaml2KeyType_ contains following configuration attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `activeSimpleKey`
| Base key used for signing and dencryption.
You can use only one from active keys, or can be both null.
| true
| _ModuleSaml2SimpleKeyType_


| `activeKeyStoreKey`
| Base key used for signing and dencryption.
You can use only one from active keys, or can be both null.
| true
| _ModuleSaml2KeyStoreKeyType_


| `standBySimpleKey`
| Other keys.

| true
| _ModuleSaml2SimpleKeyType_


| `standByKeyStoreKey`
| Other keys.
| true
| _ModuleSaml2KeyStoreKeyType_


|===


===== ModuleSaml2SimpleKeyType

_ModuleSaml2SimpleKeyType_ contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `privateKey`
| Private key.
| true
| _ProtectedStringType_


| `passphrase`
| Password.
| true
| _ProtectedStringType_


| `certificate`
| Certificate of key.
| true
| _ProtectedStringType_


| `type`
| Type of key.
Possible values are SIGNING, UNSPECIFIED and DECRYPTION.
| false
| _enum_

|===



.Example of ModuleSaml2SimpleKeyType
[source,xml]
----
<activeSimpleKey>
	<name>sp-signing-key</name>
    <privateKey>
    	<t:clearValue>"primary key"</t:clearValue>
    </privateKey>
    <passphrase>
        <t:clearValue>"password"</t:clearValue>
    </passphrase>
    <certificate>
        <t:clearValue>"certificate"</t:clearValue>
    </certificate>
</activeSimpleKey>
----


===== ModuleSaml2KeyStoreKeyType

_ModuleSaml2KeyStoreKeyType_ contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `keyStorePath`
| Path to KeyStore.
| true
| _String_


| `keyStorePassword`
| Password of KeyStore.
| true
| _ProtectedStringType_


| `keyAlias`
| Alias of private key in KeyStore.
| true
| _ProtectedStringType_


| `keyPassword`
| Password of private key with alias '`keyAlias`' in KeyStore.
| true
| _ProtectedStringType_


| `type`
| Type of key.
Possible values are SIGNING, UNSPECIFIED and DECRYPTION.
| false
| _enum_

|===


.Example of ModuleSaml2KeyStoreKeyType
[source,xml]
----
<activeKeyStoreKey>
	<keyStorePath>/home/lskublik/keyStore</keyStorePath>
    <keyStorePassword>
		<t:clearValue>"password of keyStore"</t:clearValue>
    </keyStorePassword>
    <keyAlias>sp-signing-key-1</keyAlias>
    <keyPassword>
		<t:clearValue>"password of private key"</t:clearValue>
    </keyPassword>
</activeKeyStoreKey>
----


===== AuthenticationModuleSaml2ProviderType

_AuthenticationModuleSaml2ProviderType_ represents one Identity Providers.
AuthenticationModuleSaml2ProviderType contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type | Default

| `entityId`
| Unique identifier of the service provider.
| true
| _String_
|


| `metadata`
| Metadata of Identity provider.
| true
| _AuthenticationModuleSaml2MetadataType_
|


| `linkText`
| User friendly name of provider.
| false
| _String_
|


| `authenticationRequestBinding`
| SAML2 binding used for authentication request.
| true
| _String_
|


| `verificationKeys`
|
| false
| _ProtectedStringType_
|


| `nameOfUsernameAttribute`
| Name of attribute in response, which value define name of user in Midpoint.
For example 'uid'.
| true
| _String_
|

|===


===== AuthenticationModuleSaml2ProviderMetadataType

_AuthenticationModuleSaml2ProviderMetadataType_ represents metadata of provider.
You can choose from one definition for metadata: _metadataUrl_, _xml_ and _pathToFile_.

[%autowidth]
|===
| Name | Description

| `metadataUrl`
| URL, which show metadata.


| `xml`
| Xml of metadata encrypted by base64.


| `pathToFile`
| Path to xml file, which contains metadata.

|===


.Example of saml2 module
[source,xml]
----
<saml2>
	<name>mySamlSso</name>
    <description>My internal enterprise SAML-based SSO system.</description>
    <serviceProvider>
    	<entityId>sp_midpoint</entityId>
        <signRequests>true</signRequests>
        <keys>
            .
			.
			.
        </keys>
        <identityProvider>
        	<entityId>https://idptestbed/idp/shibboleth</entityId>
            <metadata>
		<xml>PD94bWwgdmVyc2lvbj0iMS4wI...</xml>
            </metadata>
            <linkText>Shibboleth</linkText>
            <authenticationRequestBinding>urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST</authenticationRequestBinding>
            <nameOfUsernameAttribute>uid</nameOfUsernameAttribute>
        </identityProvider>
    </serviceProvider>
</saml2>
----

===== Generation of service provider metadata
Midpoint can generate metadata of SP. You can get it via link http://<midpointHost>/midpoint/auth/<authenticationSequenceUrlSuffix>/<saml2ModuleName>/metadata/<registrationId>.
RegistrationId is 'aliasForPath', when is provided, or 'alias', when is provided, or 'entityId' of SP.

Generation of metadata works only if your sequence use only saml2 authentication module or saml2 authentication module is first in chain of your sequence. When you want use chain and saml2 module won't be first authentication module. We recommend create sequence only with saml module, generate metadata and in next step add other modules.

===== Migration Saml2 authentication module from 4.3
Dependency for support of `saml2` authentication module was changed to https://github.com/spring-projects/spring-security/tree/main/saml2/saml2-service-provider[Spring Security saml2-service-provider].


* Functionality of a new module is equivalent to the functionality of old `saml2` module, however some configuration properties are not available in the new module.
Such properties were tagged as _deprecated_ in schema of saml2 authentication module.
* We need change attribute 'provider' to 'identityProvider' in 'serviceProvider'.
* When we use some keys of 'type' ENCRYPTION, we need remove it service provider obtain it from metadata for identity provider.

==== Module oidc

[TIP]
.MidPoint 4.5 and later

This feature is available only in midPoint 4.5 and later.


OIDC authentication module supports authentication via Identity provider that support OpenID connect.

Oidc Authentication module contains two different kind of configuration. One for GUI with channel _http://midpoint.evolveum.com/xml/ns/public/common/channels-3#user_, that was defined by attribute _client_, and one for REST with channel _http://midpoint.evolveum.com/xml/ns/public/common/channels-3#rest_, that was defined by attribute _resourceServer_.

===== Configuration for GUI

Configuration for GUI is provided via attribute _client_, that is type _OidcClientAuthenticationModuleType_. Client supports only grand type *Authorization code*. We need configure client properties for client authentication and configuration of openID provider for provide identity for identification of midpoint focus.

Client contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `registrationId`
| Unique identifier of the client. RegistrationId is used in url path, so it has to contain only correct symbols.
| true
| _String_


| `clientId`
| OAuth 2.0 Client Identifier valid at the Authorization Server.
| true
| _String_


| `clientSecret`
| OAuth 2.0 Client Secret valid at the Authorization Server.
| false
| _ProtectedStringType_


| `clientAuthenticationMethod`
| Define client authentication method. Possible values is clientSecretBasic, clientSecretPost, clientSecretJwt and privateKeyJwt.
| false
| _OidcClientAuthenticationMethodType_


| `clientSigningAlgorithm`
| Required node group.
Identifier of algorithm for digitally sign or create a MAC of the content. (RFC7518 section-3.1)
| false
| _String_


| `scope`
| OpenID Connect Clients use scope values as defined in 3.3 of OAuth 2.0 [RFC6749] to specify what access privileges are being requested for Access Tokens. Scope contains 'openid'.
| false
| _String_


| `clientName`
| Human friendly name of client.
| false
| _String_

| `nameOfUsernameAttribute`
| Name of attribute in response, which value define name of user in Midpoint. Default value is 'sub'.
| false
| _String_

| `openIdProvider`
| OpenID Provider.
| false
| _OidcOpenIdProviderType_

| `simpleProofKey`
| Key used for sign with privateKeyJwt. Choice _simpleProofKey_ or _keyStoreProofKey_.
| false
| _AbstractSimpleKeyType_

| `keyStoreProofKey`
| Key from key store used for sign with privateKeyJwt. Choice _simpleProofKey_ or _keyStoreProofKey_.
| false
| _AbstractKeyStoreKeyType_

|===

*AbstractSimpleKeyType* contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `privateKey`
| Private key.
| true
| _ProtectedStringType_


| `passphrase`
| Password.
| true
| _ProtectedStringType_


| `certificate`
| Certificate of key.
| true
| _ProtectedStringType_

|===

*AbstractKeyStoreKeyType* contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `keyStorePath`
| Path to KeyStore.
| true
| _String_


| `keyStorePassword`
| Password of KeyStore.
| true
| _ProtectedStringType_


| `keyAlias`
| Alias of private key in KeyStore.
| true
| _ProtectedStringType_


| `keyPassword`
| Password of private key with alias '`keyAlias`' in KeyStore.
| true
| _ProtectedStringType_

|===

*OidcOpenIdProviderType*

Definition for OpenID Provider. Possible attributes are:

[%autowidth]
|===
| Name | Description | Required | Type

| `issuerUri`
| Issuer identifier uri for the OpenID Connect provider.
| true
| _String_

| `authorizationUri`
| Uri for the authorization endpoint.
| false
| _String_


| `tokenUri`
| Uri for the token endpoint.
| false
| _String_


| `userInfoUri`
| Uri for user info endpoint.
| false
| _String_


| `endSessionUri`
| Uri for logout endpoint.
| false
| _String_

|===

Required attribute is only 'issuerUri', because midPoint get configuration for all other uris from 'issuerUri'/.well-known/openid-configuration. MidPoint can write error to log file, that some from optional configuration uris is null and required. This error we can see when 'issuerUri'/.well-known/openid-configuration is unavailable.

.Example of Client configuration with client authentication for client signed JWT
[source,xml]
----
<securityPolicy>
	<authentication>
        ...
        <modules>
            <oidc>
                <name>oidcKeycloak</name>
                <client>
                    <registrationId>keycloak</registrationId>
                    <clientId>account</clientId>
                    <clientSecret>
                        <clearValue>'client_secret'</clearValue>
                    </clientSecret>
                    <clientAuthenticationMethod>privateKeyJwt</clientAuthenticationMethod>
                    <nameOfUsernameAttribute>preferred_username</nameOfUsernameAttribute>
                    <openIdProvider>
                        <issuerUri>https://keycloak.lab.evolveum.com/auth/realms/test</issuerUri>
                    </openIdProvider>
                    <keyStoreProofKey>
                        <keyStorePath>/home/user/keystore.jks</keyStorePath>
                        <keyStorePassword>
                            <clearValue>password</clearValue>
                        </keyStorePassword>
                        <keyAlias>account</keyAlias>
                        <keyPassword>
                            <clearValue>password</clearValue>
                        </keyPassword>
                    </keyStoreProofKey>
                </client>
            </oidc>
        </modules>
        <sequence>
            <name>admin-gui-default</name>
            <channel>
                <channelId>http://midpoint.evolveum.com/xml/ns/public/common/channels-3#user</channelId>
                <default>true</default>
                <urlSuffix>defaultGui</urlSuffix>
            </channel>
            <module>
                <name>oidcKeycloak</name>
                <order>10</order>
                <necessity>sufficient</necessity>
            </module>
        </sequence>
        ...
    </authentication>
</securityPolicy>
----

===== Configuration for REST

Configuration for REST is provided via attribute _resourceServer_, that is type _OidcResourceServerAuthenticationModuleType_. When we want to use oidc module for REST midPoint work as resource server. Midpoint needs JWT for verify and identify midpoint focus. Rest request have to contain WWW-Authentication header with syntax 'Authorization: Bearer {token}'. We have four choices for verification JWT, using issuerUri, JWKSetUri, singleSymmetricKey or using public key, by trustingAsymmetricCertificate or keyStoreTrustingAsymmetricKey.

Resource server contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `realm`
| Realm which Midpoint use for WWW-Authentication header
| false
| _String_

| `issuerUri`
| Issuer identifier uri for the OpenID Connect provider.
| false
| _String_


| `jwkSetUri`
| Uri for the JSON Web Key (JWK) Set endpoint.
| false
| _String_

| `nameOfUsernameClaim`
| Name of claim in jwt, which value define name of user in Midpoint. Default value is 'sub'.
| false
| _String_

| `singleSymmetricKey`
| Trusting a Single Asymmetric Key.
| false
| _ProtectedStringType_

| `trustedAlgorithm`
| Trusted Algorithms. (RFC7518 section-3.1).
| false
| _String_

| `trustingAsymmetricCertificate`
| Certificate of trusting a single asymmetric RSA public key.
| false
| _ProtectedStringType_

| `keyStoreTrustingAsymmetricKey`
| Key store with trusting a single asymmetric RSA public key.
| false
| _AbstractKeyStoreKeyType_

|===

.Example of Resource server configuration with issuerUri.
[source,xml]
----
<securityPolicy>
	<authentication>
        ...
        <modules>
            <oidc>
                <name>oidcResourceServer</name>
                <resourceServer>
                    <issuerUri>https://keycloak.lab.evolveum.com/auth/realms/test</issuerUri>
                    <nameOfUsernameClaim>preferred_username</nameOfUsernameClaim>
                </resourceServer>
            </oidc>
        </modules>
        <sequence>
            <name>rest</name>
            <channel>
                <channelId>http://midpoint.evolveum.com/xml/ns/public/common/channels-3#rest</channelId>
                <default>true</default>
                <urlSuffix>rest-default</urlSuffix>
            </channel>
            <module>
                <name>oidcResourceServer</name>
                <order>10</order>
                <necessity>sufficient</necessity>
            </module>
        </sequence>
        ...
    </authentication>
</securityPolicy>
----

=== Sequence Configuration

Sequence contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `name`
| Unique name of the authentication sequence.
This name is fact a short identifier.
It is supposed to give some idea about purpose of the sequence to system administrator.
But it is not supposed to be used as a user-friendly label.
Sequence name must be unique.
| true
| _String_


| `description`
| Free form description of the sequence (administrator comment).
| false
| _String_


| `channel`
| Specification of channel for authentication sequence.
| false
| _AuthenticationSequenceChannelType_


| `requireAssignmentTarget`
| Required assignment target.
This authentication sequence is applicable only to users that have active assignment with this target (and relation).
If the sequence is attempted on a user that does not have this assignment then the authentication will fail.
| false
| _ObjectReferenceType_


| `nodeGroup`
| Required node group.
This authentication sequence is applicable only to node group that have active assignment with this archetype.
| false
| _ObjectReferenceType_


| `module`
| Specification of authentication module in the sequence.
| true
| _AuthenticationSequenceModuleType_


| `focusBehaviorUpdate`
| Option for updating focus authentication behaviour attributes.
| false
| _FocusBehaviorUpdateType_

|===

==== FocusBehaviorUpdateType

We can enable/disable updating of focus authentication behavior (such as information about last login time) during every login, or we can use option for updating behaviour only when login failed and during success login after fails login. Default value is 'enabled'. Possible values are:

[%autowidth]
|===
| Value | Description

| `enabled`
| Behaviour attributes will be updated every login.


| `disabled`
| Authentication behaviour attributes will not be updated during login.


| `failureOnly`
| Authentication behaviour attributes will be updated when login failed and when login will be success, but previous login was failed and midPoint need update attributes as is number of login fails and lockout state.

|===

==== AuthenticationSequenceChannelType

Channel specification for authentication sequence.
It specifies whether this sequence is usable for a specific channel (user/GUI, REST, etc.) _AuthenticationSequenceChannelType_ contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `channelId`
| Name (URI) of the channel.
| true
| _String_


| `description`
| Free form description (administrator comment).
| false
| _String_


| `default`
| Specifies whether this sequence is the default sequence for a specified channel.
The default sequence will be chosen in case that specific sequence was not requested, e.g. by using URL suffix.
If this element is not present and only a single sequence is defined for a channel, then such sequence is considered to be the default.
If more than one sequence is specified then none of them is considered to be default.
In that case this element must be used explicitly.
| false
| _boolean_


| `urlSuffix`
| URL suffix that can be used to select this authentication sequence specifically.
| true
| _String_

|===


==== AuthenticationSequenceModuleType

Specification of authentication module in the sequence.
The authentication modules are evaluated in sequence (or in parallel if possible).
At least one authentication module must succeed for authentication to be successful.
If there are required or requisite modules in the sequence then all of them must succeed for the sequence to be successful.
_AuthenticationSequenceModuleType_ contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `name`
| Reference to the authentication module name.
Value of this element must match name of existing authentication module.
| true
| _String_


| `description`
| Free form description (administrator comment).
| false
| _String_


| `order`
| Ordering number for the module.
The modules are sorted according to those numbers.
| false
| 100


| `necessity`
| Necessity, i.e. the level of requirement, whether the module is mandatory or optional.
We support only SUFFICIENT modules in 4.1.
| false
| SUFFICIENT

|===


.Example of default sequence
[source,xml]
----
<sequence>
	<name>admin-gui-default</name>
    <description>
    	Default GUI authentication sequence.
        We want to try company SSO, federation and internal. In that order.
        Just one of then need to be successful to let user in.
    </description>
    <channel>
    	<channelId>http://midpoint.evolveum.com/xml/ns/public/common/channels-3#user</channelId>
        <default>true</default>
		<urlSuffix>default</urlSuffix>
    </channel>
	<nodeGroup oid="05b6933a-b7fc-4543-b8fa-fd8b278ff9ee" relation="org:default" type="c:ArchetypeType"/>
    <module>
    	<name>mySamlSso</name>
        <order>30</order>
        <necessity>sufficient</necessity>
    </module>
    <module>
    	<name>internalLoginForm</name>
        <order>20</order>
        <necessity>sufficient</necessity>
    </module>
</sequence>
----


.Example of sequence for administrator login
[source,xml]
----
<sequence>
	<name>admin-gui-emergency</name>
    <description>
    	Special GUI authentication sequence that is using just the internal user password.
        It is used only in emergency. It allows to skip SAML authentication cycles, e.g. in case
        that the SAML authentication is redirecting the browser incorrectly.
    </description>
    <channel>
    	<channelId>http://midpoint.evolveum.com/xml/ns/public/common/channels-3#user</channelId>
        <default>false</default>
        <urlSuffix>emergency</urlSuffix>
    </channel>
    <requireAssignmentTarget oid="00000000-0000-0000-0000-000000000004" relation="org:default" type="c:RoleType">
    <!-- Superuser -->
    </requireAssignmentTarget>
    <module>
    	<name>internalLoginForm</name>
        <order>1</order>
        <necessity>sufficient</necessity>
    </module>
</sequence>
----


== Ignored path Configuration

Tag <authentication> contains tag <ignoredLocalPath>, which defines path without authentication.
For example:

[source]
----
<authentication>
	.
	.
	.
	<ignoredLocalPath>/actuator</ignoredLocalPath>
	<ignoredLocalPath>/actuator/health</ignoredLocalPath>
</authentication>
----


== Logout

Midpoint supports logout by removing session and data connected with session. Removing session is provided by request to logout by user or termination of session after timeout.

'httpHeader' and 'saml2' authentication modul support send logout request to logout url, but only for logout requested by user. For timeout of session is supported only it's removing.

== Complete Configuration Examples

You can find example on link:https://github.com/Evolveum/midpoint-samples/blob/master/samples/policy/security/security-policy-flexible-authentication.xml[security-policy-flexible-authentication].


== Limitations

Those are the limitations of current implementation of flexible authentication mechanisms.

* Configuration schema for flexible authentication is designed to be mostly complete.
However, not all configuration options are currently supported.

* Social login functionality is not supported yet.

* It is unlikely that midPoint could be used as a member of identity federation directly.
Identity proxy or a similar technology may be needed.

* Authentication configuration is global.
Only global security policy can be used to configure the authentication (i.e. security policy referenced directly from system configuration object).
Per-organization security policies or any other security policies cannot be used.

* Support for authentication module _necessity_ is limited.
We support only SUFFICIENT modules in 4.1.

* Authentication modules for SOAP web services are not supported because SOAP is deprecated and it will be removed soon.

* REST service supports HTTP basic authentication and OpenID Connect authentication.

* Even though the authentication configuration often suggests that there may be more than one instances of credentials (password, nonce), midPoint currently supports only a single password, single nonce and a single set of security questions.
Multiple credentials are not supported.
The reason for mentioning credential names the configuration schema is to have ability to extend midPoint functionality in the future.

The implementation can be improved in the future.
Please see xref:/midpoint/features/planned/flexible-authentication/[Flexible Authentication Improvements] for the details.


== See Also

* xref:..[Flexible Authentication]

* xref:/midpoint/reference/security/security-policy[Security Policy Configuration]
