= Flexible Authentication Configuration
:page-nav-title: Configuration
:page-wiki-name: Flexible Authentication Configuration
:page-wiki-id: 41517151
:page-wiki-metadata-create-user: lskublik
:page-wiki-metadata-create-date: 2019-11-25T09:32:45.286+01:00
:page-wiki-metadata-modify-user: virgo
:page-wiki-metadata-modify-date: 2020-10-14T10:12:43.521+02:00
:page-since: "4.4"
:page-toc: top


Basic idea of flexible authentication is described on xref:..[Flexible Authentication] page.
Before we describe configuration of flexible authentication, we have to become acquainted with a few terms.

TODO it would be nice to warn the user who starts flexible authentication configuration about the risk not to have an access to midPoint GUI part. E.g. in case of incorrect LoginForm module configuration or in case of its absence, there will be no possibility to login via standard login form again. In that case the user should have another way to restore midPoint environment.

TODO please, add a sample of urlSuffix attribute usage. There is a sample with explanation "Midpoint searches authentication sequence base-on next part of URL, in this case 'emergency'". But it's not clear here that 'emergency' is a value of urlSuffix attribute. I would suggest to paste url sample right to the table with attribute description.

== Basic concepts


=== Authentication module

Authentication module is basic building unit of flexible authentication.
The easiest example of authentication module is classic login form, which we can find on every application.
Login form contains field for username or email and password.
Login form represent one authentication module, next modules can be authentication by LDAP, HTTP basic authentication, authentication via Identity Provider server, etc.
Every Authentication module contains some configuration properties, which define configuration for this kind of authentication module.


=== Authentication sequence

Authentication sequence is made up of authentication modules, so it contains chain of authentication modules.
Each module has its order and necessity configuration for the sequence.
Sequence is defined by channel.
Channel represents part of Midpoint, for which this authentication sequence is valid, for example GUI, REST service, etc.
Also channel contains url suffix for this authentication sequence.
So channel defines, which authentication sequence will be used for http request.


=== Authentication channel

Flexible authentication knows following channels:

[%autowidth]
|===
| Request servlet suffix | Channel | Note

|
| http://midpoint.evolveum.com/xml/ns/public/common/channels-3#user
| Default one, represents GUI.
No suffix specified.


| /ws, /rest, /api
| http://midpoint.evolveum.com/xml/ns/public/common/channels-3#rest
|


| /actuator
| http://midpoint.evolveum.com/xml/ns/public/common/channels-3#actuator
|


| /resetPassword
| http://midpoint.evolveum.com/xml/ns/public/common/channels-3#resetPassword
|


| /registration
| http://midpoint.evolveum.com/xml/ns/public/common/channels-3#selfRegistration
|


|===

Channels for _rest_ and _actuator_ default don't create audit records about session creation or termination.
You can turn on it via variable in System Configuration _audit->eventRecording->recordSessionlessAccess_.


=== Choosing of Authentication sequence

We can describe flow on two examples.


==== First example

Midpoint receives HTTP request with URL 'http:localhost:8080/midpoint/actuator/metrics'.
Midpoint obtains suffix 'actuator' from URL and it gets channel from table base-on suffix.
Obtained channel is used for searching default sequence for channel.
Next midpoint initialize found authentication sequence.
After successful authentication Midpoint sends request to actuator service.


==== Second example

Midpoint receives HTTP request with URL 'http:localhost:8080/midpoint/auth/emergency/users'.
Midpoint obtains suffix 'auth' from URL, this suffix defines using of specific authentication sequence.
Midpoint searches authentication sequence base-on next part of URL, in this case 'emergency'.
After successful authentication Midpoint sends request to service, which defines channel in sequence configuration.
Let's say it is GUI for this example, so request is redirect to users page in GUI.


== Basic configuration

Flexible authentication is configured in xref:/midpoint/reference/security/security-policy[Security Policy]. Security policy can be defined on different levels.
There is a global level, when the security policy is defined in System Configuration.
Since midPoint 4.7 it is also possible to define security policies for organization unit and archetype.
All security policies applicable for the user are merged together.
The merging is performed after user identification, so after the first module which was able to find a user in the system.

Base tag is _<authentication>_.  Configuration consists of modules and sequences.
Element `module` is basic building block of the configuration.
Each element has a configuration of a particular authentication module instance such as internal password-based authentication, SAML authentication and so on.
Each module specified in the container must have unique identifier.
Element `sequence` defines a sequence of authentication modules.
The modules are invoked in order as they are specified in the sequence.
The purpose of the sequence is to guide user through a complete authentication process.

*IMPORTANT*

*Midpoint GUI authentication form:* To be able to use Midpoint GUI, an authentication sequence for formLogin module should be configured.
In case when no authentication is configured in the security policy at all or there is no sequence in the configured authentication, midPoint will use standard (built-in) login form for the user GUI authentication.
In case when at least one /not formLogin/ sequence is configured in the authentication configuration, a sequence for formLogin module should be evidently specified in the authentication configuration to make midPoint GUI work.
To see the default formLogin sequence configuration, please use security policy from the Midpoint initial objects (015-security-policy.xml).

=== Module configuration

The following modules are supported now: `formLogin`, `saml2`, `httpHeader`, `httpBasic`, `httpSecQ`, `securityQuestionsForm`, `mailNonce`, `ldap`, `focusIdentification`, `attributeVerification`, `hint`.
Each element contains common attributes:

[%autowidth]
|===
| Name | Description | Required | Type | Default

| `name`
| Unique name of the authentication module.
This name is fact a short identifier.
It is supposed to give some idea about nature of the module to system administrator.
But it is not supposed to be used as a user-friendly label for the module.
The name is also used in the url, so it should not contain special characters.

*`name` attribute is deprecated, use `identifier` instead*.
| true
| _String_
|

| `identifier`
| Unique identifier of the authentication module.
Short identifier.
It is supposed to give some idea about nature of the module to system administrator.
But it is not supposed to be used as a user-friendly label for the module.
The name is also used in the url, so it should not contain special characters.
| true
| _String_
|

| `description`
| Free form description of the module (administrator comment).
| false
| _String_
|


| `focusType`
| Type of logged object that this authentication module applies to.
E.g UserType, RoleType, OrgType, ...
| false
|

| _UserType_


|===


==== Module formLogin

FormLogin module is used for interactive log-in of a user by using HTML forms.


.Example of formLogin module
[source,xml]
----
<loginForm>
	<identifier>internalLoginForm</identifier>
    <description>Internal username/password authentication, default user password, login form</description>
</loginForm>
----


==== Module httpBasic

Definition of HTTP BASIC authentication module (RFC 7617).

.Example of httpBasic module
[source,xml]
----
<httpBasic>
	<name>internalHttpBasic</name>
    <description>Http basic username/password authentication, default user password</description>
</httpBasic>
----


==== Module httpSecQ

Definition of HTTP SecQ module.
The module is used for quasi-interactive log-in of a user by answering a set of security questions.
The HTTP SecQ mechanism is similar to HTTP BASIC mechanism, but it is using security questions instead of password.

.Example of httpBasic module
[source,xml]
----
<httpSecQ>
	<name>httpSecurityQuestions</name>
</httpSecQ>
----


[#_securityQuestionsForm]
==== Module securityQuestionsForm

Definition of "security questions form" module.
The module is used for interactive log-in of a user by answering a set of security questions.

.Example of securityQuestionsFrom module
[source,xml]
----
<securityQuestionsForm>
	<identifier>securityQuestions</identifier>
</securityQuestionsForm>
----

[#_mailNonce]
==== Module mailNonce

Mail nonce authentication module.
Module that sends randomly generated nonce in URL in mail message.
This module contains next attribute:

[%autowidth]
|===
| Name | Description | Required | Type

| `credentialName`
| Name of credential definition that should be used when validating password.
This must point to a valid credential definition in the "credential" section of a security policy.
If not specified then default password definition is used.
| false
| _String_

|===


.Example of mailNonce module
[source,xml]
----
<mailNonce>
	<identifier>mailNonce</identifier>
	<credentialName>mailNonceCredential</credentialName>
</mailNonce>
----


==== Module ldap

LDAP authentication module supports authentication via LDAP server.
This module contains next attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `host`
| Host of the LDAP server.
| true
| _String_


| `userDn`
| The user distinguished name.
| true
| _String_


| `userPassword`
| The password (credentials) to use for getting authenticated contexts.
| true
| _String_


| `dnPattern`
| The pattern which will be used to supply a DN for the user.
| false
| _String_


| `search`
| Search configuration which uses an Ldap filter to locate the user.
| false
| _AuthenticationModuleLdapSearchType_

|===


===== AuthenticationModuleLdapSearchType

[%autowidth]
|===
| Name | Description | Required | Type

| `pattern`
| The filter expression used in the user search.
This is an LDAP search filter (as defined in 'RFC 2254') with optional arguments.
Example: `(uid=\{0})`
| true
| _String_


| `namingAttr`
| Specifying explicit LDAP attribute that is retrieved from user's LDAP account and contains value that matches midPoint's username.
| false
| _String_


| `subtree`
| If true then searches the entire subtree as identified by context, if false (the default) then only searches the level identified by the context.
| false
| _Boolean_

|===


.Example of ldap module
[source,xml]
----
<ldap>
	<identifier>ldapAuth</identifier>
	<host>ldap://localhost:389/dc=example,dc=com</host>
	<userDn>cn=admin,dc=example,dc=com</userDn>
	<userPassword>
        <t:clearValue>secret</t:clearValue>
    </userPassword>
    <dnPattern>uid={0},ou=people</dnPattern>
    <search>
        <pattern>(uid={0})</pattern>
        <namingAttr>uid</namingAttr>
        <subtree>true</subtree>
    </search>
</ldap>
----


==== Module httpHeader

Pseudo-authentication for pre-authenticated users.
Based on HTTP header values.
This module contains specific attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `usernameHeader`
| Name of HTTP header that contains username.
| true
| _String_


| `logoutUrl`
| Url for redirect after logout.
Default is '/'.
| false
| _String_

|===



.Example of httpHeader module
[source,xml]
----
<httpHeader>AuthenticationModuleSaml2ProviderMetadataType
	<identifier>httpHeader</identifier>
    	<logoutUrl>http://localhost:8081/Identity_provider/Logout</logoutUrl>
        <usernameHeader>uid</usernameHeader>
</httpHeader>
----


==== Module saml2

SAML2 authentication module supports authentication via Identity provider with SAML2.
SAML2 module has a little complicated configuration.
This module contains specific attribute:

[%autowidth]
|===
| Name | Description | Required | Type

| `serviceProvider`
| Basic configuration of SP.
| true
| _AuthenticationModuleSaml2ServiceProviderType_

|===

===== AuthenticationModuleSaml2ServiceProviderType

_AuthenticationModuleSaml2ServiceProviderType_ contains following configuration attributes:

[%autowidth]
|===
| Name | Description | Required | Type | Default | Unused from 4.4

| `entityId`
| Unique identifier of the service provider.
| true
| _String_
|
|


| `alias`
| Unique alias used to identify the selected local service provider based on used URL.
| false
| _String_
|
|


| `aliasForPath`
| Alias used for AssertionConsumerServiceURL.
| false
| _String_
|
|


| `defaultSigningAlgorithm`
| Default signing algorithm.
Possible values are RSA_SHA1, RSA_SHA256, RSA_SHA512 and RSA_RIPEMD160.
| false
| _enum_
| RSA_SHA256
|


| `signRequests`
| Flag indicating whether this service signs authentication requests.
| false
| _boolean_
| false
|


| `keys`
| Key used by service provider.
| false
| _AuthenticationModuleSaml2KeyType_
|
|


| `identityProvider`
| Possible identity providers for this service provider.
| true
| _AuthenticationModuleSaml2ProviderType_
|
|


|===


===== AuthenticationModuleSaml2KeyType

_AuthenticationModuleSaml2KeyType_ contains following configuration attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `activeSimpleKey`
| Base key used for signing and dencryption.
You can use only one from active keys, or can be both null.
| true
| _ModuleSaml2SimpleKeyType_


| `activeKeyStoreKey`
| Base key used for signing and dencryption.
You can use only one from active keys, or can be both null.
| true
| _ModuleSaml2KeyStoreKeyType_


| `standBySimpleKey`
| Other keys.

| true
| _ModuleSaml2SimpleKeyType_


| `standByKeyStoreKey`
| Other keys.
| true
| _ModuleSaml2KeyStoreKeyType_


|===


===== ModuleSaml2SimpleKeyType

_ModuleSaml2SimpleKeyType_ contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `privateKey`
| Private key.
| true
| _ProtectedStringType_


| `passphrase`
| Password.
| true
| _ProtectedStringType_


| `certificate`
| Certificate of key.
| true
| _ProtectedStringType_


| `type`
| Type of key.
Possible values are SIGNING, UNSPECIFIED and DECRYPTION.
| false
| _enum_

|===



.Example of ModuleSaml2SimpleKeyType
[source,xml]
----
<activeSimpleKey>
	<name>sp-signing-key</name>
    <privateKey>
    	<t:clearValue>"primary key"</t:clearValue>
    </privateKey>
    <passphrase>
        <t:clearValue>"password"</t:clearValue>
    </passphrase>
    <certificate>
        <t:clearValue>"certificate"</t:clearValue>
    </certificate>
</activeSimpleKey>
----


===== ModuleSaml2KeyStoreKeyType

_ModuleSaml2KeyStoreKeyType_ contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `keyStorePath`
| Path to KeyStore.
| true
| _String_


| `keyStorePassword`
| Password of KeyStore.
| true
| _ProtectedStringType_


| `keyAlias`
| Alias of private key in KeyStore.
| true
| _ProtectedStringType_


| `keyPassword`
| Password of private key with alias '`keyAlias`' in KeyStore.
| true
| _ProtectedStringType_


| `type`
| Type of key.
Possible values are SIGNING, UNSPECIFIED and DECRYPTION.
| false
| _enum_

|===


.Example of ModuleSaml2KeyStoreKeyType
[source,xml]
----
<activeKeyStoreKey>
	<keyStorePath>/home/lskublik/keyStore</keyStorePath>
    <keyStorePassword>
		<t:clearValue>"password of keyStore"</t:clearValue>
    </keyStorePassword>
    <keyAlias>sp-signing-key-1</keyAlias>
    <keyPassword>
		<t:clearValue>"password of private key"</t:clearValue>
    </keyPassword>
</activeKeyStoreKey>
----


===== AuthenticationModuleSaml2ProviderType

_AuthenticationModuleSaml2ProviderType_ represents one Identity Providers.
AuthenticationModuleSaml2ProviderType contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type | Default

| `entityId`
| Unique identifier of the service provider.
| true
| _String_
|


| `metadata`
| Metadata of Identity provider.
| true
| _AuthenticationModuleSaml2MetadataType_
|


| `linkText`
| User friendly name of provider.
| false
| _String_
|


| `authenticationRequestBinding`
| SAML2 binding used for authentication request.
| true
| _String_
|


| `verificationKeys`
|
| false
| _ProtectedStringType_
|


| `nameOfUsernameAttribute`
| Name of attribute in response, which value define name of user in Midpoint.
For example 'uid'.
| true
| _String_
|

|===


===== AuthenticationModuleSaml2ProviderMetadataType

_AuthenticationModuleSaml2ProviderMetadataType_ represents metadata of provider.
You can choose from one definition for metadata: _metadataUrl_, _xml_ and _pathToFile_.

[%autowidth]
|===
| Name | Description

| `metadataUrl`
| URL, which show metadata.


| `xml`
| Xml of metadata encrypted by base64.


| `pathToFile`
| Path to xml file, which contains metadata.

|===


.Example of saml2 module
[source,xml]
----
<saml2>
	<identifier>mySamlSso</identifier>
    <description>My internal enterprise SAML-based SSO system.</description>
    <serviceProvider>
    	<entityId>sp_midpoint</entityId>
        <signRequests>true</signRequests>
        <keys>
            .
			.
			.
        </keys>
        <identityProvider>
        	<entityId>https://idptestbed/idp/shibboleth</entityId>
            <metadata>
		<xml>PD94bWwgdmVyc2lvbj0iMS4wI...</xml>
            </metadata>
            <linkText>Shibboleth</linkText>
            <authenticationRequestBinding>urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST</authenticationRequestBinding>
            <nameOfUsernameAttribute>uid</nameOfUsernameAttribute>
        </identityProvider>
    </serviceProvider>
</saml2>
----

===== Generation of service provider metadata
Midpoint can generate metadata of SP. You can get it via link http://<midpointHost>/midpoint/auth/<authenticationSequenceUrlSuffix>/<saml2ModuleName>/metadata/<registrationId>.
RegistrationId is 'aliasForPath', when is provided, or 'alias', when is provided, or 'entityId' of SP.

Generation of metadata works only if your sequence use only saml2 authentication module or saml2 authentication module is first in chain of your sequence. When you want to use a chain and saml2 module won't be first authentication module, we recommend to create sequence only with saml module, generate metadata and then add other modules.

If Midpoint is located behind a reverse proxy it may be useful to set the _publicHttpUrlPattern_ setting to the right value in order for the SAML endpoints (in the SP Metadata and in the SAMLRequest) to reflect the right URLs (see below)

.Example of public URL configuration
[source,xml]
----
<systemConfiguration>
	.
    .
    .
    <infrastructure>
        <publicHttpUrlPattern>https://public.url.local/midpoint</publicHttpUrlPattern>
    </infrastructure>
    .
    .
    .
</systemConfiguration>
----

===== Migration Saml2 authentication module from 4.3
Dependency for support of `saml2` authentication module was changed to https://github.com/spring-projects/spring-security/tree/main/saml2/saml2-service-provider[Spring Security saml2-service-provider].


* Functionality of a new module is equivalent to the functionality of old `saml2` module, however some configuration properties are not available in the new module.
Such properties were tagged as _deprecated_ in schema of saml2 authentication module.
* Attribute 'provider' has to be changed to 'identityProvider' in 'serviceProvider'.
* When keys of 'type' ENCRYPTION are used, they need to be removed. Service provider will obtain them from metadata for identity provider.

==== Module oidc

[TIP]
.MidPoint 4.5 and later

This feature is available only in midPoint 4.5 and later.


OIDC authentication module supports authentication via Identity provider that support OpenID connect.

OIDC Authentication module contains two different kinds of configuration:

. for GUI with channel _http://midpoint.evolveum.com/xml/ns/public/common/channels-3#user_, that was defined by attribute _client_,
. for REST with channel _http://midpoint.evolveum.com/xml/ns/public/common/channels-3#rest_, that was defined by attribute _resourceServer_.

===== Configuration for GUI

Configuration for GUI is provided via attribute _client_, that is type _OidcClientAuthenticationModuleType_. Client supports only grand type *Authorization code*. We need to configure client properties for client authentication and configuration of OpenID provider for provide identity for identification of midpoint focus.

Client contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `registrationId`
| Unique identifier of the client. RegistrationId is used in url path, so it has to contain only correct symbols.
| true
| _String_


| `clientId`
| OAuth 2.0 Client Identifier valid at the Authorization Server.
| true
| _String_


| `clientSecret`
| OAuth 2.0 Client Secret valid at the Authorization Server.
| false
| _ProtectedStringType_


| `clientAuthenticationMethod`
| Define client authentication method. Possible values is clientSecretBasic, clientSecretPost, clientSecretJwt and privateKeyJwt.
| false
| _OidcClientAuthenticationMethodType_


| `clientSigningAlgorithm`
| Required node group.
Identifier of algorithm for digitally sign or create a MAC of the content. (RFC7518 section-3.1)
| false
| _String_


| `scope`
| OpenID Connect Clients use scope values as defined in 3.3 of OAuth 2.0 [RFC6749] to specify what access privileges are being requested for Access Tokens. Scope contains 'openid'.
| false
| _String_


| `clientName`
| Human friendly name of client.
| false
| _String_

| `nameOfUsernameAttribute`
| Name of attribute in response, which value define name of user in Midpoint. Default value is 'sub'.
| false
| _String_

| `openIdProvider`
| OpenID Provider.
| false
| _OidcOpenIdProviderType_

| `simpleProofKey`
| Key used for sign with privateKeyJwt. Choice _simpleProofKey_ or _keyStoreProofKey_.
| false
| _AbstractSimpleKeyType_

| `keyStoreProofKey`
| Key from key store used for sign with privateKeyJwt. Choice _simpleProofKey_ or _keyStoreProofKey_.
| false
| _AbstractKeyStoreKeyType_

|===

*AbstractSimpleKeyType* contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `privateKey`
| Private key.
| true
| _ProtectedStringType_


| `passphrase`
| Password.
| true
| _ProtectedStringType_


| `certificate`
| Certificate of key.
| true
| _ProtectedStringType_

|===

*AbstractKeyStoreKeyType* contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `keyStorePath`
| Path to KeyStore.
| true
| _String_


| `keyStorePassword`
| Password of KeyStore.
| true
| _ProtectedStringType_


| `keyAlias`
| Alias of private key in KeyStore.
| true
| _ProtectedStringType_


| `keyPassword`
| Password of private key with alias '`keyAlias`' in KeyStore.
| true
| _ProtectedStringType_

|===

*OidcOpenIdProviderType*

Definition for OpenID Provider. Possible attributes are:

[%autowidth]
|===
| Name | Description | Required | Type

| `issuerUri`
| Issuer identifier uri for the OpenID Connect provider.
| true
| _String_

| `authorizationUri`
| Uri for the authorization endpoint.
| false
| _String_


| `tokenUri`
| Uri for the token endpoint.
| false
| _String_


| `userInfoUri`
| Uri for user info endpoint.
| false
| _String_


| `endSessionUri`
| Uri for logout endpoint.
| false
| _String_

| `jwkSetUri`
| Uri for JSON web key set endpoint. Available from midPoint 4.8.
| false
| _String_


|===

Required attribute is only `issuerUri`, because midPoint gets configuration for all other URIs from 'issuerUri'/.well-known/openid-configuration. MidPoint can write error to log file that some from optional configuration URIs is null and required. This error we can see when 'issuerUri'/.well-known/openid-configuration is unavailable.

.Example of Client configuration with client authentication for client signed JWT
[source,xml]
----
<securityPolicy>
	<authentication>
        ...
        <modules>
            <oidc>
                <identifier>oidcKeycloak</identifier>
                <client>
                    <registrationId>keycloak</registrationId>
                    <clientId>account</clientId>
                    <clientSecret>
                        <clearValue>'client_secret'</clearValue>
                    </clientSecret>
                    <clientAuthenticationMethod>privateKeyJwt</clientAuthenticationMethod>
                    <nameOfUsernameAttribute>preferred_username</nameOfUsernameAttribute>
                    <openIdProvider>
                        <issuerUri>https://keycloak.lab.evolveum.com/auth/realms/test</issuerUri>
                    </openIdProvider>
                    <keyStoreProofKey>
                        <keyStorePath>/home/user/keystore.jks</keyStorePath>
                        <keyStorePassword>
                            <clearValue>password</clearValue>
                        </keyStorePassword>
                        <keyAlias>account</keyAlias>
                        <keyPassword>
                            <clearValue>password</clearValue>
                        </keyPassword>
                    </keyStoreProofKey>
                </client>
            </oidc>
        </modules>
        <sequence>
            <identifier>admin-gui-default</identifier>
            <channel>
                <channelId>http://midpoint.evolveum.com/xml/ns/public/common/channels-3#user</channelId>
                <default>true</default>
                <urlSuffix>defaultGui</urlSuffix>
            </channel>
            <module>
                <name>oidcKeycloak</name>
                <order>10</order>
                <necessity>sufficient</necessity>
            </module>
        </sequence>
        ...
    </authentication>
</securityPolicy>
----

If Midpoint is located behind a reverse proxy it may be useful to set the _publicHttpUrlPattern_ setting to the right value in order for the OIDC Redirect URI to point to a valid public URL (see below)

.Example of public URL configuration
[source,xml]
----
<systemConfiguration>
	.
    .
    .
    <infrastructure>
        <publicHttpUrlPattern>https://public.url.local/midpoint</publicHttpUrlPattern>
    </infrastructure>
    .
    .
    .
</systemConfiguration>
----

===== Configuration for REST

Configuration for REST is provided via attribute _resourceServer_, that is type _OidcResourceServerAuthenticationModuleType_. When we want to use OIDC module for REST, midPoint works as resource server. Midpoint needs JWT for verifying and identifying midpoint focus. REST request has to contain WWW-Authentication header with syntax `Authorization: Bearer {token}`. We have four choices for verification JWT, using issuerUri, JWKSetUri, singleSymmetricKey or using public key, by trustingAsymmetricCertificate or keyStoreTrustingAsymmetricKey.

Resource server contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `realm`
| Realm which Midpoint use for WWW-Authentication header
| false
| _String_

| `issuerUri`
| Issuer identifier URI for the OpenID Connect provider.
| false
| _String_


| `jwkSetUri`
| URI for the JSON Web Key (JWK) Set endpoint.
| false
| _String_

| `nameOfUsernameClaim`
| Name of claim in JWT, which value define name of user in midPoint. Default value is 'sub'.
| false
| _String_

| `singleSymmetricKey`
| Trusting a Single Asymmetric Key.
| false
| _ProtectedStringType_

| `trustedAlgorithm`
| Trusted Algorithms. (RFC7518 section-3.1).
| false
| _String_

| `trustingAsymmetricCertificate`
| Certificate of trusting a single asymmetric RSA public key.
| false
| _ProtectedStringType_

| `keyStoreTrustingAsymmetricKey`
| Key store with trusting a single asymmetric RSA public key.
| false
| _AbstractKeyStoreKeyType_

|===

.Example of Resource server configuration with issuerUri.
[source,xml]
----
<securityPolicy>
	<authentication>
        ...
        <modules>
            <oidc>
                <identifier>oidcResourceServer</identifier>
                <resourceServer>
                    <issuerUri>https://keycloak.lab.evolveum.com/auth/realms/test</issuerUri>
                    <nameOfUsernameClaim>preferred_username</nameOfUsernameClaim>
                </resourceServer>
            </oidc>
        </modules>
        <sequence>
            <identifier>rest</identifier>
            <channel>
                <channelId>http://midpoint.evolveum.com/xml/ns/public/common/channels-3#rest</channelId>
                <default>true</default>
                <urlSuffix>rest-default</urlSuffix>
            </channel>
            <module>
                <identifier>oidcResourceServer</identifier>
                <order>10</order>
                <necessity>sufficient</necessity>
            </module>
        </sequence>
        ...
    </authentication>
</securityPolicy>
----

[#_focusIdentification]
==== Module focusIdentification

Focus identification authentication module.
Module that according to the specified attributes tries to find a user in midPoint.
If only focusIdentification module is defined, authentication won't succeed.
This module is marked as not sufficient to live on its own.

[%autowidth]
|===
| Name | Description | Required | Type

| `item`
| Structure defining how the user should be looked for.
| true
| _ModuleItemConfigurationType_

|===

*ModuleItemConfigurationType consists of the following attributes:*

[%autowidth]
|===
| Name | Description | Required | Type

| `path`
| The path to the focus attribute according to which the focus should be found.
| true
| _ItemPathType_

| `matchingRule`
| Matching rule which should be used for this item while filtering or comparing
| false
| _QName_


|===

.Example of focusIdentification module
[source,xml]
----
<focusIdentification>
    <identifier>focusId</identifier>
    <item>
        <path>name</path>
        <matchingRule>polyStringNorm</matchingRule>
    </item>
</focusIdentification>
----

[#_hint]
==== Module hint

Hint authentication module.
Special module which was implemented to be able to use it during resetting password.
The aim of the module is to provide the password hint (if defined) to the user.
This module is marked as not sufficient to live on its own.

This module has no other configuration options.

.Example of hint module
[source,xml]
----
<hint>
    <identifier>hintAuth</identifier>
</hint>
----

[#_attributeVerification]
==== Module attributeVerification

Attribute verification authentication module.
Module which can be used as additional to any of the previous authentication modules.
The aim of the module is to check defined focus items if they match.
The focus must be identified for this module to be used.
This module is marked as not sufficient to live on its own.

[%autowidth]
|===
| Name | Description | Required | Type

| `item`
| Structure defining which items to check if they match.
| true
| _ModuleItemConfigurationType_

|===

*ModuleItemConfigurationType consists of the following attributes:*

[%autowidth]
|===
| Name | Description | Required | Type

| `path`
| The path to the focus attribute which should be checked if matches.
| true
| _ItemPathType_

| `matchingRule`
| Matching rule which should be used for this item while filtering or comparing the attribute values.
| false
| _QName_

|===

.Example of attributeVerification module
[source,xml]
----
<attributeVerification>
    <identifier>attributeVerification</identifier>
    <item>
        <path>extension/employeeCardID</path>
    </item>
</attributeVerification>
----

=== Sequence Configuration

Sequence contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `name`
| Unique name of the authentication sequence.
This name is fact a short identifier.
It is supposed to give some idea about purpose of the sequence to system administrator.
But it is not supposed to be used as a user-friendly label.
Sequence name must be unique.

*`name` attribute is DEPRECATED, use `identifier` instead.*
| true
| _String_

| `identifier`
| Unique identifier of the authentication sequence.
Short identifier.
It is supposed to give some idea about purpose of the sequence to system administrator.
But it is not supposed to be used as a user-friendly label.
Sequence name must be unique.
| true
| _String_

| `description`
| Free form description of the sequence (administrator comment).
| false
| _String_


| `channel`
| Specification of channel for authentication sequence.
| false
| _AuthenticationSequenceChannelType_


| `requireAssignmentTarget`
| Required assignment target.
This authentication sequence is applicable only to users that have active assignment with this target (and relation).
If the sequence is attempted on a user that does not have this assignment then the authentication will fail.
| false
| _ObjectReferenceType_


| `nodeGroup`
| Required node group.
This authentication sequence is applicable only to node group that have active assignment with this archetype.
| false
| _ObjectReferenceType_


| `module`
| Specification of authentication module in the sequence.
| true
| _AuthenticationSequenceModuleType_


| `focusBehaviorUpdate`
| Option for updating focus authentication behaviour attributes.
| false
| _FocusBehaviorUpdateType_

|===

==== FocusBehaviorUpdateType

We can enable/disable updating of focus authentication behavior (such as information about last login time) during every login, or we can use option for updating behaviour only when login failed and during success login after failed login. Default value is 'enabled'. Possible values are:

[%autowidth]
|===
| Value | Description

| `enabled`
| Behaviour attributes will be updated every login.


| `disabled`
| Authentication behaviour attributes will not be updated during login.


| `failureOnly`
| Authentication behaviour attributes will be updated when login failed and when login will be success, but previous login was failed and midPoint needs to update attributes as is number of login fails and lockout state.

|===

==== AuthenticationSequenceChannelType

Channel specification for authentication sequence.
It specifies whether this sequence is usable for a specific channel (user/GUI, REST, etc.) _AuthenticationSequenceChannelType_ contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `channelId`
| Name (URI) of the channel.
| true
| _String_


| `description`
| Free form description (administrator comment).
| false
| _String_


| `default`
| Specifies whether this sequence is the default sequence for a specified channel.
The default sequence will be chosen in case that specific sequence was not requested, e.g. by using URL suffix.
If this element is not present and only a single sequence is defined for a channel, then such sequence is considered to be the default.
If more than one sequence is specified then none of them is considered to be default.
In that case this element must be used explicitly.
| false
| _boolean_


| `urlSuffix`
| URL suffix that can be used to select this authentication sequence specifically.
| true
| _String_

|===


==== AuthenticationSequenceModuleType

Specification of authentication module in the sequence.
The authentication modules are evaluated in sequence (or in parallel if possible).
At least one authentication module must succeed for authentication to be successful.
If there are required or requisite modules in the sequence then all of them must succeed for the sequence to be successful.
_AuthenticationSequenceModuleType_ contains following attributes:

[%autowidth]
|===
| Name | Description | Required | Type

| `name`
| Reference to the authentication module name.
Value of this element must match name of existing authentication module.

*`name` attribute is DEPRECATED, use `identifier` instead.*
| true
| _String_

| `identifier`
| Reference to the authentication module identifier.
Value of this element must match the identifier of existing authentication module.
| true
| _String_

| `description`
| Free form description (administrator comment).
| false
| _String_


| `order`
| Ordering number for the module.
The modules are sorted according to those numbers.
| false
| 100


| `necessity`
| Necessity, i.e. the level of requirement, whether the module is mandatory or optional.
We support only SUFFICIENT modules in 4.1.

Since 4.7, supported necessity levels are SUFFICIENT, REQUIRED, REQUISITE, OPTIONAL
| false
| SUFFICIENT

| `acceptEmpty`
| Some modules might be automatically skipped if the concrete type of credentials is not defined.
E.g. if there is no "hint" defined for the user, we can skip evaluation of the hint module.
The same can apply for example for security questions.
In case the module can be skipped, accept empty must be set to `true`. When such module exits and it is skipped, it is marked as CALLED_OFF in the sequence.
| false
| false

|===

There is one hard-coded behavior for the modules which defines if the module itself is strong enough for authentication to succeed. FocusIdentification, Hint and AttributeVerification module are three specific modules, which are marked as not enough when exist on their own. Even when the sequence consist of other modules (sufficient) which were evaluated as failed and only those three (combination or one of them) succeed, the result of the authentication is failure.

.Example of default sequence
[source,xml]
----
<sequence>
	<identifier>admin-gui-default</identifier>
    <description>
    	Default GUI authentication sequence.
        We want to try company SSO, federation and internal. In that order.
        Just one of then need to be successful to let user in.
    </description>
    <channel>
    	<channelId>http://midpoint.evolveum.com/xml/ns/public/common/channels-3#user</channelId>
        <default>true</default>
		<urlSuffix>default</urlSuffix>
    </channel>
	<nodeGroup oid="05b6933a-b7fc-4543-b8fa-fd8b278ff9ee" relation="org:default" type="c:ArchetypeType"/>
    <module>
    	<identifier>mySamlSso</identifier>
        <order>30</order>
        <necessity>sufficient</necessity>
    </module>
    <module>
    	<identifier>internalLoginForm</identifier>
        <order>20</order>
        <necessity>sufficient</necessity>
    </module>
</sequence>
----


.Example of sequence for administrator login
[source,xml]
----
<sequence>
	<identifier>admin-gui-emergency</identifier>
    <description>
    	Special GUI authentication sequence that is using just the internal user password.
        It is used only in emergency. It allows to skip SAML authentication cycles, e.g. in case
        that the SAML authentication is redirecting the browser incorrectly.
    </description>
    <channel>
    	<channelId>http://midpoint.evolveum.com/xml/ns/public/common/channels-3#user</channelId>
        <default>false</default>
        <urlSuffix>emergency</urlSuffix>
    </channel>
    <requireAssignmentTarget oid="00000000-0000-0000-0000-000000000004" relation="org:default" type="c:RoleType">
    <!-- Superuser -->
    </requireAssignmentTarget>
    <module>
    	<identifier>internalLoginForm</identifier>
        <order>1</order>
        <necessity>sufficient</necessity>
    </module>
</sequence>
----

== Necessity Configuration

[TIP]
.MidPoint 4.7 and later
This feature is available only in midPoint 4.7 and later.

Each module defined in sequence can define its necessity. Since 4.7 following necessity levels are available:

* `SUFFICIENT` - The module is sufficient for authentication to succeed.
It is NOT required to succeed.
If this module succeeds, the evaluation stops.
The result is a success. Other modules are NOT evaluated.
Except for the case when "required" module that was evaluated before has failed.
If this module fails, the evaluation continues.
Other modules are evaluated.
* `REQUIRED` - The module is required.
The module must succeed for the entire sequence to be successful.
If this module succeeds, the evaluation continues.
Other modules are evaluated.
If this module fails, the evaluation continues.
Other modules are evaluated.
Final result of authentication sequence is a failure.
* `REQUISITE` - The module is required.
The module must succeed for the entire sequence to be successful.
If this module succeeds, the evaluation continues.
Other modules are evaluated.
If this module fails, the evaluation stops with an error.
Other modules are NOT evaluated.
Final result of authentication sequence is a failure.
* `OPTIONAL` - The module is optional.
It is NOT required to succeed.
Optional module does not really influence the result of the authentication.
But it may be used to add some authentication attributes, it may be used to  cross-authenticate is SSO realms and so on.
If this module succeeds, the evaluation continues.
If this module fails, the evaluation continues.
The result of the sequence is a failure only if this is the only module in the sequence, and it fails.

The necessity levels might be combined. E.g. there might be a sequence consisting of three different modules each defined with different necessity level.
The evaluation of the authentication is performed after each module.
If `SUFFICIENT` module is found and its evaluation was successful, all previous modules are checked. In case, all previously `REQUIRED` and `REQUISITE` modules were successful, the authentication ends with the success. If any of them failed, authentication continues. All other modules defined in the sequence are evaluated and the result of the authentication is failure.

If evaluation for `SUFFICIENT` module failed, authentication continues according to the sequence defined. In case, there are `REQUIRED` modules and all of them are successful, despite the `SUFFICIENT` module failed, authentication is evaluated as successful.
Only if the `SUFFICIENT` module is last and its evaluation failed, the whole authentication is evaluated as failed. Last `SUFFICIENT` module in the sequence MUST be successful for authentication to succeed.

If any of the `REQUISITE` modules failed, authentication stops and the result is failure.



== Ignored path Configuration

Tag <authentication> contains tag <ignoredLocalPath>, which defines path without authentication.
For example:

[source]
----
<authentication>
	.
	.
	.
	<ignoredLocalPath>/actuator</ignoredLocalPath>
	<ignoredLocalPath>/actuator/health</ignoredLocalPath>
</authentication>
----


== Logout

Midpoint supports logout by removing session and data connected with session. Removing session is provided by request to logout by user or termination of session after timeout.

'httpHeader' and 'saml2' authentication modules support sending logout request to logout URL, but only for logout requested by user. For session timeout only its removing is supported.

== Complete Configuration Examples

You can find example on link:https://github.com/Evolveum/midpoint-samples/blob/master/samples/policy/security/security-policy-flexible-authentication.xml[security-policy-flexible-authentication].


== Limitations

Those are the limitations of current implementation of flexible authentication mechanisms.

* Configuration schema for flexible authentication is designed to be mostly complete.
However, not all configuration options are currently supported.

* Social login functionality is not supported yet.

* It is unlikely that midPoint could be used as a member of identity federation directly.
Identity proxy or a similar technology may be needed.

* Support for authentication module _necessity_ is limited.
We support only SUFFICIENT modules in 4.1. However, since 4.7 full _necessity_ is supported.

* Authentication modules for SOAP web services are not supported because SOAP is deprecated and it will be removed soon.

* REST service supports HTTP basic authentication and OpenID Connect authentication.

* Even though the authentication configuration often suggests that there may be more than one instances of credentials (password, nonce), midPoint currently supports only a single password, single nonce and a single set of security questions.
Multiple credentials are not supported.
The reason for mentioning credential names the configuration schema is to have ability to extend midPoint functionality in the future.

The implementation can be improved in the future.
Please see xref:/midpoint/features/planned/flexible-authentication/[Flexible Authentication Improvements] for the details.


== See Also

* xref:..[Flexible Authentication]

* xref:/midpoint/reference/security/security-policy[Security Policy Configuration]
