/*
 * Copyright (C) 2010-2022 Evolveum and contributors
 *
 * This work is dual-licensed under the Apache License 2.0
 * and European Union Public License. See LICENSE file for details.
 */
package com.evolveum.midpoint.repo.common;

import com.evolveum.midpoint.repo.api.SystemConfigurationChangeEvent;
import com.evolveum.midpoint.util.annotation.Experimental;

/**
 * Application event related to system configuration being (re)loaded by {@link SystemObjectCache}.
 * It is generated by that component.
 *
 * The purpose of this event is to keep pre-4.6 behavior of cleaning expression profile cache
 * not only when system configuration is known to be changed (see {@link SystemConfigurationChangeEvent})
 * but also when the system configuration is known to be reloaded by {@link SystemObjectCache}. The latter
 * can occur more frequently because of safety checks that are there to ensure the system configuration
 * is up-to-date even if some change events are missed.
 *
 * TODO reconsider this - it looks really ugly
 *
 * @see SystemConfigurationChangeEvent
 */
@Experimental
public class SystemConfigurationLoadedEvent {

}
