= Connector Type REST Endpoint
:page-nav-title: Connector
:page-display-order: 1500
:page-toc: top
:page-keywords: [ 'rest', 'connector' ,'endpoint' ]
:page-upkeep-status: green

== Description

Here we are describing the Connector object type in relation to midPoints REST API. The
Connector objects are a part of the REST API web resources.accessCertificationDefinitions

.Endpoint
[source, http]
----
connectors/
----

== Operations And Examples

The Connector Type endpoint operations and examples.

include::../raw/curl-env-note.adoc[]

For some help regarding the REST examples please see this link:

xref:/midpoint/reference/interfaces/rest/concepts/using-rest-examples.adoc[How to use MidPoint REST examples]


=== Create Connector Type Object

- xref:/midpoint/reference/interfaces/rest/operations/create-op-rest/[Create Operation]

=== Get Connector Type Objects

Get operation for fetching a single specific object.

- xref:/midpoint/reference/interfaces/rest/operations/get-op-rest/[Get Operation]

=== Search for Connector Type Objects

Search operation usable for fetching the full list of objects or a list based on filter.

include::../operations/examples/raw/search-all.adoc[]

- xref:/midpoint/reference/interfaces/rest/operations/search-op-rest/[Search Operation]

=== Modify Connector Type Objects

- xref:/midpoint/reference/interfaces/rest/operations/modify-op-rest/[Modify Operation]

=== Delete Connector Type Objects

- xref:/midpoint/reference/interfaces/rest/operations/delete-op-rest/[Delete Operation]

=== Generate and Validate Operations for Generic Object Type Objects

Operations to generate or validate values.

- xref:/midpoint/reference/interfaces/rest/operations/generate-and-validate-concrete-op-rest/[Generate and Validate Operations]

== JSON Example

Example output of information regarding a specific Connector object. Some parts of the output were removed or simplified
for the purpose of the example.

.Show JSON Example
[%collapsible]
====
[source, json]
----
{
	"connector": {
		"oid": "01aa0a9e-dfe0-47c8-8fca-4446894a348c",
		"version": "50",
		"name": "ConnId com.evolveum.polygon.connector.csv.CsvConnector v2.7",
		"displayName": "CsvConnector",
		"framework": "http://midpoint.evolveum.com/xml/ns/public/connector/icf-1",
		"connectorType": "com.evolveum.polygon.connector.csv.CsvConnector",
		"connectorVersion": "2.7",
		"connectorBundle": "com.evolveum.polygon.connector-csv",
		"namespace": "http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/bundle/com.evolveum.polygon.connector-csv/com.evolveum.polygon.connector.csv.CsvConnector",
		"schema": {},
		"available": true
	}
}
----
====

== See Also
- xref:/midpoint/reference/interfaces/rest/concepts/media-types-rest/[Supported Media Types]
- xref:/midpoint/reference/interfaces/rest/concepts/authentication/[Authentication]
