= Lookup table type REST endpoint
:page-nav-title: Lookup Table
:page-display-order: 2100
:page-toc: top
:page-keywords: rest, lookup, endpoint
:page-description: This article describes the lookup tables REST API endpoint.
:page-upkeep-status: green

== Description

This article describes the `lookupTables` REST API endpoint.
The endpoint serves to create, read, update, delete, and list xref:/midpoint/reference/misc/lookup-tables/[lookup tables].

.Endpoint
[source, http]
----
lookupTables/
----

== Operations and examples

The `lookupTables` endpoint operations and examples.

include::../raw/curl-env-note.adoc[]

Refer to the following article for help regarding usage of the REST examples:

xref:/midpoint/reference/interfaces/rest/concepts/using-rest-examples.adoc[How to use MidPoint REST examples]


=== Create lookupTable type object

- xref:/midpoint/reference/interfaces/rest/operations/create-op-rest/[Create Operation]

=== Get lookupTable type objects

Get operation for fetching a single specific object.

- xref:/midpoint/reference/interfaces/rest/operations/get-op-rest/[Get Operation]

.Example: get the languages lookup table
[source,bash]
----
curl --user administrator:y0uR_P455woR*d \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -X GET \
    http://localhost:8080/midpoint/ws/rest/lookupTables/00000000-0000-0000-0000-000000000200 <1>
----
<1> The OID specifies the table to fetch.

.How to fetch rows with data
[TIP]
====
By default, the API returns the table rows empty with `"@incomplete": true` identifying that the row data have been omitted.

To force the API to return data in the rows, use the `include=row` query string parameter: +
`+++http://localhost:8080/midpoint/ws/rest/lookupTables/search?include=row+++`
====

=== Search for lookupTable type objects

Search operation usable for fetching the full list of objects or a list based on filter.
The empty query filter matches all objects.

include::../operations/examples/raw/search-all.adoc[]

- xref:/midpoint/reference/interfaces/rest/operations/search-op-rest/[Search Operation]

=== Modify lookupTable type objects

- xref:/midpoint/reference/interfaces/rest/operations/modify-op-rest/[Modify Operation]

=== Delete lookupTable type objects

- xref:/midpoint/reference/interfaces/rest/operations/delete-op-rest/[Delete Operation]

=== Generate and Validate Operations for Lookup Table objects

Operations to generate or validate values.

- xref:/midpoint/reference/interfaces/rest/operations/generate-and-validate-concrete-op-rest/[Generate and Validate Operations]

== Query and response examples

Here are example queries for the lifecycle states lookup table and their outputs.
Metadata are removed from the outputs here.

.Get the lifecycle states lookup table without its row data
[source,http]
----
http://localhost:8080/midpoint/ws/rest/lookupTables/00000000-0000-0000-0000-000000000230
----

.Show JSON reponse
[%collapsible]
====
[source, json]
----
{
	"lookupTable": {
		"oid": "00000000-0000-0000-0000-000000000230",
		"version": "1",
		"name": "Lifecycle States",
		"metadata": {},
		"operationExecution": {},
		"iteration": 0,
		"iterationToken": "",
		"row": {
			"@incomplete": true
		}
	}
}
----
====

To get the lookup table with the row data, you need to use the `include=row` parameter:

.Get the lifecycle states lookup table with its row data
[source,http]
----
http://localhost:8080/midpoint/ws/rest/lookupTables/00000000-0000-0000-0000-000000000230?include=row
----

.Show JSON reponse
[%collapsible]
====
[source, json]
----
{
  "lookupTable" : {
    "oid" : "00000000-0000-0000-0000-000000000230",
    "version" : "0",
    "name" : "Lifecycle States",
    "iteration" : 0,
    "iterationToken" : "",
    "row" : [ {
      "@ns" : "http://prism.evolveum.com/xml/ns/public/types-3",
      "@id" : 1,
      "key" : "draft",
      "label" : "Draft"
    }, {
      "@ns" : "http://prism.evolveum.com/xml/ns/public/types-3",
      "@id" : 2,
      "key" : "proposed",
      "label" : "Proposed"
    }, {
      "@ns" : "http://prism.evolveum.com/xml/ns/public/types-3",
      "@id" : 3,
      "key" : "active",
      "label" : "Active"
    }, {
      "@ns" : "http://prism.evolveum.com/xml/ns/public/types-3",
      "@id" : 4,
      "key" : "suspended",
      "label" : "Suspended"
    }, {
      "@ns" : "http://prism.evolveum.com/xml/ns/public/types-3",
      "@id" : 5,
      "key" : "deprecated",
      "label" : "Deprecated"
    }, {
      "@ns" : "http://prism.evolveum.com/xml/ns/public/types-3",
      "@id" : 6,
      "key" : "archived",
      "label" : "Archived"
    }, {
      "@ns" : "http://prism.evolveum.com/xml/ns/public/types-3",
      "@id" : 7,
      "key" : "failed",
      "label" : "Failed"
    } ]
  }
}
----
====



== See Also
- xref:/midpoint/reference/interfaces/rest/concepts/media-types-rest/[Supported Media Types]
- xref:/midpoint/reference/interfaces/rest/concepts/authentication/[Authentication]
