= Object Template Type REST Endpoint
:page-nav-title: Object Template
:page-display-order: 2500
:page-toc: top
:page-keywords: [ 'rest', 'template', 'endpoint' ]
:page-upkeep-status: green

== Description

Here we are describing the Object Template object type in relation to midPoints REST API. The
Object Template objects are a part of the REST API web resources.

.Endpoint
[source, http]
----
objectTemplates/
----

== Operations And Examples

The Object Template type endpoint operations and examples.

include::../raw/curl-env-note.adoc[]

For some help regarding the REST examples please see this link:

xref:/midpoint/reference/interfaces/rest/concepts/using-rest-examples.adoc[How to use MidPoint REST examples]


=== Create Object Template type Object

- xref:/midpoint/reference/interfaces/rest/operations/create-op-rest/[Create Operation]

=== Get Object Template type Objects

Get operation for fetching a single specific object.

- xref:/midpoint/reference/interfaces/rest/operations/get-op-rest/[Get Operation]

=== Search for Object Template type Objects

Search operation usable for fetching the full list of objects or a list based on filter.

include::../operations/examples/raw/search-all.adoc[]

- xref:/midpoint/reference/interfaces/rest/operations/search-op-rest/[Search Operation]

=== Modify Object Template type Objects

- xref:/midpoint/reference/interfaces/rest/operations/modify-op-rest/[Modify Operation]

=== Delete Object Template type Objects

- xref:/midpoint/reference/interfaces/rest/operations/delete-op-rest/[Delete Operation]

=== Generate and Validate Operations for Object Template Objects

Operations to generate or validate values.

- xref:/midpoint/reference/interfaces/rest/operations/generate-and-validate-concrete-op-rest/[Generate and Validate Operations]

== JSON Example

Example output of information regarding a specific Object Template object. Metadata is usually a
part of the output, yet it was removed for the purpose of the example.

.Show JSON Example
[%collapsible]
====
[source, json]
----
{
  "objectTemplate" : {
    "oid" : "00000000-0000-0000-0000-000000000380",
    "version" : "1",
    "name" : "Person Object Template",
    "description" : "Object template for Person users, contains mappings to generate fullName and username. Please enable appropriate mappings as needed.",
    "metadata" : {},
    "operationExecution" : {},
    "iteration" : 0,
    "iterationToken" : "",
    "iterationSpecification" : {},
    "mapping" : []
  }
}
----
====

== See Also
- xref:/midpoint/reference/interfaces/rest/concepts/media-types-rest/[Supported Media Types]
- xref:/midpoint/reference/interfaces/rest/concepts/authentication/[Authentication]
