= Report Data Type REST Endpoint
:page-nav-title: Report Data
:page-display-order: 2500
:page-toc: top
:page-keywords: [ 'rest', 'report', 'endpoint' ]
:page-upkeep-status: green

== Description

Here we are describing the Report Data object type in relation to midPoints REST API. The
Report Data objects are a part of the REST API web resources.

.Endpoint
[source, http]
----
reportData/
----

== Operations And Examples

The Report Data type endpoint operations and examples.

include::../raw/curl-env-note.adoc[]

For some help regarding the REST examples please see this link:

xref:/midpoint/reference/interfaces/rest/concepts/using-rest-examples.adoc[How to use MidPoint REST examples]


=== Get Report Data type Objects

Get operation for fetching a single specific object.

- xref:/midpoint/reference/interfaces/rest/operations/get-op-rest/[Get Operation]

=== Search for Report Data type Objects

Search operation usable for fetching the full list of objects or a list based on filter.

include::../operations/examples/raw/search-report-data-from-report-def.adoc[]

- xref:/midpoint/reference/interfaces/rest/operations/search-op-rest/[Search Operation]

=== Modify Report Data type Objects

- xref:/midpoint/reference/interfaces/rest/operations/modify-op-rest/[Modify Operation]

=== Delete Report Data type Objects

- xref:/midpoint/reference/interfaces/rest/operations/delete-op-rest/[Delete Operation]

=== Generate and Validate Operations for Report Data Objects

Operations to generate or validate values.

- xref:/midpoint/reference/interfaces/rest/operations/generate-and-validate-concrete-op-rest/[Generate and Validate Operations]

== JSON Example

Example output of information regarding a specific Report Data object. Metadata is usually a part
of the output, yet it was removed for the purpose of the example.

.Show JSON Example
[%collapsible]
====
[source, json]
----
{
  "reportData" : {
    "oid" : "",
    "version" : "1",
    "name" : "All users-EXPORT",
    "metadata" : {
      "requestTimestamp" : "",
      "requestorRef" : {
        "oid" : "00000000-0000-0000-0000-000000000002",
        "relation" : "org:default",
        "type" : "c:UserType"
      },
      "createTimestamp" : "",
      "creatorRef" : {
        "oid" : "00000000-0000-0000-0000-000000000002",
        "relation" : "org:default",
        "type" : "c:UserType"
      },
      "createTaskRef" : {
        "oid" : "",
        "relation" : "org:default",
        "type" : "c:TaskType"
      }
    },
    "operationExecution" : {},
    "iteration" : 0,
    "iterationToken" : "",
    "filePath" : "",
    "reportRef" : {},
    "nodeRef" : {}
  }
}
----
====

== See Also
- xref:/midpoint/reference/interfaces/rest/concepts/media-types-rest/[Supported Media Types]
- xref:/midpoint/reference/interfaces/rest/concepts/authentication/[Authentication]
