= Resource Type
:page-nav-title: Resource
:page-display-order: 700
:page-toc: top
:page-keywords: [ 'rest', 'resource', 'endpoint' ]
:page-upkeep-status: green

== Description

Here we are describing the Resource object type in relation to midPoints REST API. The
Resource objects are a part of the REST API web resources.

.Endpoint
[source, http]
----
resources/
----

== Operations And Examples

The Resource endpoint is a part of the Create-Read-Update-Delete (CRUD) web resources
present in midPoint. This is apparent in the operations which are available for this type of object.

include::../raw/curl-env-note.adoc[]

For some help regarding the REST examples please see this link:

xref:/midpoint/reference/interfaces/rest/concepts/using-rest-examples.adoc[How to use MidPoint REST examples]


=== Create Resource Objects

include::../operations/examples/raw/create-resource.adoc[]

- xref:/midpoint/reference/interfaces/rest/operations/create-op-rest/[Create Operation]

=== Get Resource Type Objects

Get operation for fetching a single specific object.

.Get Resource Type object with REST

include::../operations/examples/raw/get-resource.adoc[]

- xref:/midpoint/reference/interfaces/rest/operations/get-op-rest/[Get Operation]

=== Search for Resource Type Objects

Search operation usable for fetching the full list of objects or a list based on filter.

include::../operations/examples/raw/search-name-resource.adoc[]

include::../operations/examples/raw/search-gen-name.adoc[]

- xref:/midpoint/reference/interfaces/rest/operations/search-op-rest/[Search Operation]

=== Modify Resource Type Objects

include::../operations/examples/raw/modify-attr-resource.adoc[]

include::../operations/examples/raw/modify-attr-res-cap.adoc[]

- xref:/midpoint/reference/interfaces/rest/operations/modify-op-rest/[Modify Operation]

=== Delete Resource Type Objects

include::../operations/examples/raw/delete-resource.adoc[]

- xref:/midpoint/reference/interfaces/rest/operations/delete-op-rest/[Delete Operation]

=== Generate and Validate Operations for Resource Type Objects

Operations to generate or validate values.

- xref:/midpoint/reference/interfaces/rest/operations/generate-and-validate-concrete-op-rest/[Generate and Validate Operations]

=== Operations specific for Resources

include::../operations/examples/raw/test-resource.adoc[]

include::../operations/examples/raw/import-from-resource.adoc[]

- xref:/midpoint/reference/interfaces/rest/operations/resource-op-rest.adoc[Resource Specific Operations]

== Common Use-case Examples

== JSON Example

Example output of information regarding a specific object. Some data vas omitted to simplify the example.

.Show JSON Example
[%collapsible]
====
[source, json]
----
{
  "resource" : {
    "oid" : "ef2bc95b-76e0-59e2-86d6-9999cccccccc",
    "version" : "1",
    "name" : "Test CSV: username",
    "description" : "Simple CSV resource that is using single identifier (username)",
    "metadata" : {},
    "operationExecution" : {},
    "iteration" : 0,
    "iterationToken" : "",
    "connectorRef" : {
      "oid" : "01aa0a9e-dfe0-47c8-8fca-4446894a348c",
      "relation" : "org:default",
      "type" : "c:ConnectorType",
      "filter" : {
        "equal" : {
          "path" : "c:connectorType",
          "value" : "com.evolveum.polygon.connector.csv.CsvConnector"
        }
      }
    },
    "connectorConfiguration" : {
      "@ns" : "http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/connector-schema-3",
      "configurationProperties" : {
        "@ns" : "http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/bundle/com.evolveum.polygon.connector-csv/com.evolveum.polygon.connector.csv.CsvConnector",
        "multivalueDelimiter" : ";",
        "fieldDelimiter" : ",",
        "filePath" : "target/midpoint.csv",
        "encoding" : "utf-8",
        "passwordAttribute" : "password",
        "uniqueAttribute" : "username"
      }
    },
    "schemaHandling" : {
      "objectType" : {
        "@id" : 1,
        "displayName" : "Default Account",
        "default" : true,
        "objectClass" : "ri:AccountObjectClass",
        "attribute" : [ {
          "@id" : 2,
          "ref" : "ri:username",
          "outbound" : {
            "source" : {
              "path" : "$user/name"
            }
          }
        }, {
          "@id" : 3,
          "ref" : "ri:firstname",
          "outbound" : {
            "source" : {
              "path" : "$user/givenName"
            }
          }
        }, {
          "@id" : 4,
          "ref" : "ri:lastname",
          "outbound" : {
            "source" : {
              "path" : "$user/familyName"
            }
          }
        } ],
        "activation" : {
          "administrativeStatus" : {
            "outbound" : {
              "@id" : 5
            }
          }
        },
        "credentials" : {
          "password" : {
            "outbound" : {
              "@id" : 6
            }
          }
        }
      }
    },
    "capabilities" : {
      "configured" : {
        "activation" : {
          "status" : {
            "attribute" : "ri:disabled",
            "enableValue" : "false",
            "disableValue" : "true"
          }
        }
      }
    }
  }
}
----
====

== See Also
- xref:/midpoint/reference/interfaces/rest/concepts/media-types-rest/[Supported Media Types]
- xref:/midpoint/reference/interfaces/rest/concepts/authentication/[Authentication]
