= Security Policy Type REST Endpoint
:page-nav-title: Security Policy
:page-display-order: 2900
:page-toc: top
:page-keywords: [ 'rest', 'security', 'policy', 'endpoint' ]
:page-upkeep-status: green

== Description

Here we are describing the Security Policy object type in relation to midPoints REST API. The
Security Policy objects are a part of the REST API web resources.

.Endpoint
[source, http]
----
securityPolicies/
----

== Operations And Examples

The Security Policy type endpoint operations and examples.

include::../raw/curl-env-note.adoc[]

For some help regarding the REST examples please see this link:

xref:/midpoint/reference/interfaces/rest/concepts/using-rest-examples.adoc[How to use MidPoint REST examples]


=== Create Security Policy type Object

- xref:/midpoint/reference/interfaces/rest/operations/create-op-rest/[Create Operation]

=== Get Security Policy type Objects

Get operation for fetching a single specific object.

- xref:/midpoint/reference/interfaces/rest/operations/get-op-rest/[Get Operation]

=== Search for Security Policy type Objects

Search operation usable for fetching the full list of objects or a list based on filter.

include::../operations/examples/raw/search-all.adoc[]

- xref:/midpoint/reference/interfaces/rest/operations/search-op-rest/[Search Operation]

=== Modify Security Policy type Objects

- xref:/midpoint/reference/interfaces/rest/operations/modify-op-rest/[Modify Operation]

=== Delete Security Policy type Objects

- xref:/midpoint/reference/interfaces/rest/operations/delete-op-rest/[Delete Operation]

=== Generate and Validate Operations for Security Policy Objects

Operations to generate or validate values.

- xref:/midpoint/reference/interfaces/rest/operations/generate-and-validate-concrete-op-rest/[Generate and Validate Operations]

== JSON Example

Example output of information regarding a specific Security Policy object. Metadata is usually a part of the output, yet it was removed for the puprose of the
example.

.Show JSON Example
[%collapsible]
====
[source, json]
----
{
  "securityPolicy" : {
    "oid" : "00000000-0000-0000-0000-000000000120",
    "version" : "",
    "name" : "Default Security Policy",
    "metadata" : {},
    "operationExecution" : {},
    "iteration" : 0,
    "iterationToken" : "",
    "authentication" : {
      "modules" : {},
      "sequence" : [],
      "ignoredLocalPath" : "/actuator/health"
    },
    "credentials" : {},
    "credentialsReset" : {}
  }
}
----
====

== See Also
- xref:/midpoint/reference/interfaces/rest/concepts/media-types-rest/[Supported Media Types]
- xref:/midpoint/reference/interfaces/rest/concepts/authentication/[Authentication]
