---
midpoint-feature: object-collection-and-view
doc-type: intro
---
= Object Collections and Views
:page-wiki-name: Object Collections and Views
:page-wiki-id: 24676784
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2018-04-09T12:36:43.699+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-04-24T15:41:28.197+02:00
:page-since: "4.0"
:page-since-improved: [ "4.2", "4.3" ]
:page-toc: top
:page-upkeep-status: orange
:page-upkeep-note: Document recent improvements (4.2, 4.3)

== Introduction

MidPoint objects are quite a social animals.
They like to be grouped together.
There is often need to show collections of objects, such as employees, active users, new proposed roles and so on.
MidPoint has a flexible search and filter functionality that can be used for this purpose.
However, those collections are used so often that they deserve a special place in the system.
Those collections deserve its own definition, its own name and its own form of presentation.
That is the reason why midPoint supports functionality for object collections and views.

Collections and views are two concepts that are very related, but still somehow distinct:

* *Object collection* is a core midPoint concept.
There is a special object type (ObjectCollectionType) that is used to define a collection.
It is first-class midPoint object.
Collection defines which objects belong to the collection.
The plan is that collections can be used in the entire midPoint system, e.g. collections can be used in xref:/midpoint/reference/security/authorization/[authorizations], xref:/midpoint/reference/roles-policies/policies/policy-rules/[policy rules] may be applied to them and so on.
Some midPoint objects can act as an implicit collections, especially xref:/midpoint/reference/schema/archetypes/[archetypes] and xref:/midpoint/reference/org/organizational-structure/[organizational units]. Object collections are designed to be solid and stable.
Something that midPoint policies can rely on.

* *View* is a user interface concept.
View specifies how a particular collection should be displayed.
It defines the columns that should be displayed, default sorting, pre-defined filter properties and so on.
Views are designed to be flexible, customizable.
E.g. views can adjusted and overridden in xref:/midpoint/reference/admin-gui/admin-gui-config/[admin GUI configuration].

Although collections and view have different purposes and they are based on different mechanisms, they are almost always used together.


== Configuration

See xref:configuration/[] page for more details.


== Future

See xref:/midpoint/features/planned/object-collections-and-views/[Object Collections and Views Improvements] page for the plan to further improve this functionality.


== See Also

* xref:/midpoint/reference/roles-policies/policies/policy-rules/[Policy Rules]

* xref:/midpoint/reference/admin-gui/collections-views/configuration/[Object Collections and Views Configuration]

* xref:/midpoint/features/planned/object-collections-and-views/[Object Collections and Views Improvements]

* xref:/midpoint/reference/schema/archetypes/[Archetypes]

* xref:/midpoint/features/planned/compliance/[Compliance]

* xref:/midpoint/reference/admin-gui/dashboards/[Customizable Dashboards]
