/*
 * Copyright (C) 2010-2026 Evolveum and contributors
 *
 * Licensed under the EUPL-1.2 or later.
 */

package com.evolveum.midpoint.model.api.context;

import org.jetbrains.annotations.NotNull;

/**
 * A {@link DirectlyEvaluatedClockworkPolicyRule} that is attached to an assignment as a "foreign" rule, meaning that
 * it was evaluated on the other side of a one-sided constraint and then attached to the assignment on which it was not
 * originally evaluated.
 *
 * The primary (and currently probably the ony) reason for its existence is supporting exclusion constraints that
 * are defined only on one side, but should be applied to both sides. See {@link EvaluatedClockworkPolicyRule} for details.
 *
 * Important things to consider for foreign rules:
 *
 * . All triggers, including those generated by exclusion constraints, are in the same form as they were triggered
 * against their original assignments. It means that:
 *
 * .. {@link EvaluatedExclusionTrigger#getThisAssignment()} corresponds to {@link #getOriginatingAssignment()}
 * .. {@link EvaluatedExclusionTrigger#getConflictingAssignment()} corresponds to {@link #getAssignmentOverride()}
 * +
 * See also {@link EvaluatedExclusionTrigger#getRealConflictingAssignment(EvaluatedAssignment)}.
 *
 * . Also note that not all triggers on the original policy rule are relevant to this (new i.e. overridden) assignment.
 * For example, if a role `Coordinator` excludes all roles of type `Worker`, and has appropriate policy rule on it,
 * then when you are assigning `Worker1` and `Worker2`, both get this policy rule (with 2 triggers) as a foreign rule.
 * However, only one trigger is relevant for each of the `WorkerX` roles. Hence, use appropriate method to select
 * relevant triggers, e.g. {@link #getRelevantExclusionTriggers()} or {@link #getRelevantTriggersFilter()}.
 *
 * @see EvaluatedAssignment#getAllAssociatedPolicyRules()
 */
public interface ForeignEvaluatedClockworkPolicyRule extends EvaluatedClockworkPolicyRule {

    // We currently do not have any new methods here. This interface exists only for clarity and documentation purposes.

    /** The {@link EvaluatedAssignment} this rule was "transplanted" to. Always present. */
    @Override
    @NotNull EvaluatedAssignment getAssignmentOverride();
}
