= Secrets providers

Secrets providers are the new way to obtain secrets in midPoint.
They are configured in system configuration and can be used in configuration objects in two ways:

. Protected strings
+
New container `externalData` with fields `provider` and `key` are will be added to `ProtectedDataType`.
Therefore, it will be available in `ProtectedStringType` and `ProtectedByteArrayType`.
. Expressions
+
Using standard midpoint library `basic`.
New methods `resolveSecretString` and `resolveSecretBinary` were added.

This way XML objects doesn't have to contain secrets in plain text or encrypted form.
Nor tools have to resolve secrets before XML object is being uploaded to midPoint, e.g. midPoint Studio plugin or CI/CD pipes.

== Configuration

Configuration of secret providers is located in system configuration object in `secretsProviders` element.
Order of providers doesn't matter, but it is important to have unique identifiers for each provider.
Providers are initialized in order based on their configuration and declared dependencies.

.Example of configuration for secret providers
[source,xml]
----
<systemConfiguration xmlns="http://midpoint.evolveum.com/xml/ns/public/common/common-3"
                     xmlns:o="http://example.com/other">
    ...
    <secretsProviders>
        <docker>
            <identifier>docker-provider</identifier>
        </docker>
        <properties>
            <identifier>properties-provider</identifier>
            <propertiesFile>~/secrets-provider.properties</propertiesFile>
        </properties>
        <environmentVariables>
            <identifier>env-provider</identifier>
            <prefix>MP_</prefix>
        </environmentVariables>
        <file>
            <identifier>file-provider</identifier>
            <parentDirectoryPath>~/secrets</parentDirectoryPath>
        </file>
        <custom>
            <identifier>custom-provider</identifier>
            <className>com.example.MyCustomProvider</className>
            <configuration>
                <o:someConfigurationProperty>value1</someConfigurationProperty>
            </configuration>
        </custom>
    </secretsProviders>
    ...
</systemConfiguration>
----

.Use of such providers
[source,xml]
----
<resource xmlns="http://midpoint.evolveum.com/xml/ns/public/common/common-3">
    ...
    <connectorConfiguration>
        <configurationProperties>
            ...
            <ldap:password>
                <value>
                    <t:externalData>
                        <t:identifier>docker</t:identifier>
                        <t:key>mysecret</t:key>
                    </t:externalData>
                <!--<t:clearValue>...</t:clearValue>-->
                <!--<t:encryptedData>...</t:encryptedData>-->
                </value>
            </ldap:password>
            ...
        </configurationProperties>
    </connectorConfiguration>
    ...
</resource>
----

== Secret providers

Currently, midPoint supports multiple providers:

* `file` - provider for secrets stored in files
* `docker` - provider for secrets stored in Docker secrets files
* `properties` - provider for secrets stored in properties files
* `environmentVariables` - provider for secrets stored in environment variables
* `custom` - custom implementation of secrets provider

=== Generic part of provider configuration

All providers have common part of configuration:

[cols=4,opts=header]
|===
| Element
| Type
| Description
| Required

| identifier
| String
| Unique identifier of provider.
| Yes

| description
| String
| Optional description.
| No

| documentation
| String
| Optional documentation.
| No

| display
| c:DisplayType
| Optional display name.
| No

| cache
| xsd:duration
| Optional cache duration (TTL). Example: `PT1H` for 1 hour.
| No

|===

=== File provider

File provider is used to obtain secrets from files.
Where the file is located is defined by `parentDirectoryPath` and key is the name of the file.
Value of the key is the content of the file.

Optional configuration property is `charset` which defaults to `utf-8`.

.Example of file provider
[source,xml]
----
<file>
    <identifier>file-provider</identifier>
    <parentDirectoryPath>~/secrets</parentDirectoryPath>
</file>
----

=== Docker provider

Docker provider just specific implementation of <<File provider>> and it's used to obtain secrets from Docker secrets files (documentation available https://docs.docker.com/compose/use-secrets/[here]).
Secrets directory is defined by Docker and it is not configurable.
It is always `/run/secrets` on Linux and `C:\ProgramData\Docker\secrets` on Windows.

Optional configuration property is `charset` which defaults to `utf-8`.

.Example of Docker provider
[source,xml]
----
<docker>
    <identifier>docker-provider</identifier>
</docker>
----

=== Properties provider

#TODO#

.Example of properties provider
[source,xml]
----
<properties>
    <identifier>properties-provider</identifier>
    <propertiesFile>~/secrets-provider.properties</propertiesFile>
</properties>
----

=== Environment variables provider

#TODO#

.Example of environment variables provider
[source,xml]
----
<environmentVariables>
    <identifier>env-provider</identifier>
    <prefix>MP_</prefix>
</environmentVariables>
----

=== Custom provider

#TODO#

.Example of custom provider
[source,xml]
----
<custom>
    <identifier>custom-provider</identifier>
    <className>com.example.MyCustomProvider</className>
    <configuration>
        <o:someConfigurationProperty>value1</someConfigurationProperty>
    </configuration>
</custom>
----

