= Activity Constraints and Policies
:page-since: "4.10"
:page-toc: top
:page-upkeep-status: green
:page-description: This describes how administrators can set execution-time constraints on background iterative tasks and define automated responses (such as task suspension) when limits set by those constraints are breached.
:page-keywords: task constraint, activity constraint, task policy, execution time, notification, suspend task


This describes how administrators can set execution-time constraints on background iterative tasks and define automated responses (such as task suspension) when limits set by those constraints are breached.

By enabling proactive monitoring and control over task behavior, you can detect anomalies early and take immediate corrective action.

[NOTE]
====
As tasks are not xref:/midpoint/reference/schema/focus-and-projections[focus] objects (like users, roles, etc.), you cannot xref:/midpoint/reference/roles-policies/policies/policy-rules/[assign roles with policies] to them.
Instead, you need to set constraints and actions directly on task activities.
====

[[constraints]]
== Constraints

This sections describes limits that you can apply to activities.

=== Execution time

The `executionTime` constraint allows you to set a time limit for activity execution.
There are two options:

* `below` - Defines the lower limit.
Policy actions trigger when the task execution time is below this limit.
* `exceeds` - Defines the upper limit.
Policy actions trigger when the task execution time exceeds this limit.

See the <<example,example below>>.


== Actions

Actions define what midPoint does when a limit set by a <<constraints,constraint>> is breached.
It can:

* <<notification,Send a notification>>
* <<suspend,Suspend a task>>

[[notification]]
=== Notifications

To have notifications sent automatically when constraints are breached:

. xref:/midpoint/reference/misc/notifications[Configure] the notification in the xref:/midpoint/reference/concepts/system-configuration-object[system configuration object].
. In a task, use `<notification/>` in `<policyActions>` as seen in <<example,this example>>.

The following example shows a system configuration definition that will send (redirect) notifications to the `/opt/midpoint-home/notifications.txt` file.
You can configure the subject and body of the notification in the `simpleActivityPolicyRuleNotifier` handler.
The default value for the `to` field is the task owner `emailAddress` (if available).
If the owner does not have `emailAddress` set, the notification will not be sent.

.Example of a simple notification configuration for execution time policy action in the system configuration
[source, xml]
----
<systemConfiguration xmlns="http://midpoint.evolveum.com/xml/ns/public/common/common-3">
    <!-- more content skipped for brevity -->
    <messageTransportConfiguration>
        <mail>
            <name>mail</name>
            <redirectToFile>/opt/midpoint-home/notifications.txt</redirectToFile>
            <defaultFrom>idm@example.com</defaultFrom>
        </mail>
    </messageTransportConfiguration>
    <notificationConfiguration>
        <handler>
            <simpleActivityPolicyRuleNotifier>
                <transport>mail</transport>
            </simpleActivityPolicyRuleNotifier>
        </handler>
    </notificationConfiguration>
</systemConfiguration>
----

[[suspend]]
=== Suspend tasks

To suspend tasks automatically when constraints are breached, use `<suspendTask/>` in `<policyActions>` as seen in <<example,this example>>.

[[example]]
== Configuration example

[source, xml]
----
<task>
    ...
    <activity>
        <policies>
            <policy>
                <name>Reconciliation run max. 4 hours</name>
                <policyConstraints>
                    <executionTime> <!-- choice -->
                        <!--<below>PT5M</below>-->
                        <exceeds>PT4H</exceeds>
                    </executionTime>
                </policyConstraints>
                <policyActions>
                    <notification/>
                    <suspendTask/>
                </policyActions>
            </policy>
        </policies>
    </activity>
</task>    
----

== Limitations

* Activity policies are evaluated only for iterative (plain iterative or search based) activities.
Unsupported activities are:
** Non-iterative scripting
** Role analysis clustering
** Role analysis patter detection
** Repartition
** Cleanup
** Composite
* Activity policies are evaluated before each item processing and after activity completion.

== See also

* xref:/midpoint/reference/tasks/thresholds[]
* xref:/midpoint/reference/roles-policies/policies/policy-rules/[Policy Rules]
* xref:/midpoint/architecture/concepts/task/[Task]
* xref:/midpoint/devel/design/multi-node-partitioned-and-stateful-tasks/task-partitioning/[Task partitioning]

