= Shadow Refresh Task
:page-wiki-name: Shadow Refresh Task
:page-wiki-id: 30245434
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2019-04-23T10:58:30.469+02:00
:page-wiki-metadata-modify-user: vix
:page-wiki-metadata-modify-date: 2021-03-17T14:07:43.550+01:00
:page-toc: top
:page-upkeep-status: green

== Introduction

There are situations, when xref:/midpoint/reference/resources/shadow/[shadow objects] do not entirely reflect the reality.
Such situations are to be expected, as those "shadows" are actually copies of the data that originate from other systems.
The shadow objects also contain xref:/midpoint/reference/resources/manual/configuration/[pending operation data] that naturally change in time.
And there are also cases when the data model evolves and data in the "shadows" need to be updated.

All such situations mean that shadow objects need to _refreshed_. Refresh means that midPoint makes sure that a shadow is internally consistent and to execute all operations that need to be executed in order to re-gain consistency.
Shadow refresh will try to finish pending operations, e.g. xref:/midpoint/reference/synchronization/consistency/[re-try failed operations]. Refresh will update the status of xref:/midpoint/reference/resources/manual/[manual operations]. And so on.
Refresh task will also make sure that application-level indexes for shadow objects are right.
Therefore it can be useful in migration scenarios or in cases that system configuration was changed and stored data need to be updated.

[NOTE]
.Refresh and reconciliation
====
Refresh is not the same thing as xref:/midpoint/reference/synchronization/introduction/[reconciliation]. Reconciliation is quite heavy-weight, trying to get the object from the resources, checking mappings and policies and so on.
On the other hand, refresh is designed to a _lightweight_ task.
Refresh is going to execute operations that are easy and efficient, such as check whether shadow indexes are correct.
When it comes to operations with the resources, refresh will only execute those operations that need to be executed.
E.g. failed operations will be re-tried, but only if the re-try time was reached.
Refresh is meant to set the shadow objects right, nothing more.
It will not fix data on the resource, neither will it run the mappings to modify data of focal objects.
The purpose of refresh is to make sure that shadow objects are right.
====


== Refresh Task

Shadow refresh happens during normal operation of midPoint, e.g. it will happen during xref:/midpoint/reference/synchronization/introduction/[reconciliation process]. However, sometimes it is preferable to execute just the refresh operation in a controlled manner.
This may be achieved by shadow refresh task.

Shadow refresh task is a lightweight task that executes shadow refresh on selected shadows.
Refresh task is very simple:

.*Refresh shadows*
[%collapsible]
====
link:https://github.com/Evolveum/midpoint-samples/blob/master/samples/tasks/task-shadow-refresh.xml[Git]

sampleRef::samples/tasks/task-shadow-refresh.xml[]
====



Such refresh task will look for shadow objects that contain pending operations.
The reason is that those are the objects that most likely need to be refreshed, e.g. failed operation has to be retried or the status of manual operation needs to be checked.
This is a reasonable default for sustained operation of midPoint.


== Explicit Filter

There are cases when refresh task needs to be run explicitly on a selected group of shadows (e.g. migration scenarios).
In that case the search filter may be explicitly specified in the refresh task:

.*Refresh shadows with pending operations on specific resource*
[%collapsible]
====
link:https://github.com/Evolveum/midpoint-samples/blob/master/samples/tasks/task-shadow-refresh-forced.xml[Git]

sampleRef::samples/tasks/task-shadow-refresh-forced.xml[]
====

.*Refresh shadows on specific resource (regardless of pending operations)*
[%collapsible]
====
link:https://github.com/Evolveum/midpoint-samples/blob/master/samples/tasks/task-shadow-refresh-forced-n-p.xml[Git]

sampleRef::samples/tasks/task-shadow-refresh-forced-n-p.xml[]
====

Whenever you specify query, it overrides the default query (all shadows on all resources with pending operations).


== Performance

Refresh task is quite lightweight and efficient.
Therefore it can usually be scheduled for quite a frequent execution, usually executing every few minutes.


== See Also

* xref:/midpoint/reference/resources/manual/[Manual Resource and ITSM Integration]

* xref:/midpoint/reference/synchronization/consistency/[Consistency mechanism]
