= Security Advisory: HTTP error codes used for SecQ REST authentication reveal user existence
:page-wiki-name: Security Advisory: HTTP error codes used for SecQ REST authentication reveal user existence
:page-wiki-id: 39583892
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2019-10-11T11:38:30.331+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-10-11T11:43:56.858+02:00
:page-nav-title: HTTP error codes used for SecQ REST authentication reveal user existence
:page-display-order: 13
:page-upkeep-status: green

*Date:* 11 October 2019

*Severity:* Low (CVSS 0.1 - 3.9)

*Affected versions:* all released midPoint versions

*Fixed in versions:* 4.0.1 (unreleased), 3.9.1 (unreleased), 3.8.1 (unreleased), 3.7.3 (unreleased)


== Description

HTTP error codes used for REST authentication based on security questions (a.k.a. SecQ) reveal user existence.


== Severity and Impact

Attacker can use REST request to determine whether a user exists.
Attacker cannot gain access to any other information or any unauthorized operation.


== Mitigation

Users of affected MidPoint versions are advised to upgrade their deployments to the latest builds from the xref:/midpoint/install/using-support-branch/[support branches].

As this is a loq severity issue, it is not forcing official maintenance releases of midPoint.
However, the fix is provided in all the support branches.


== Credit

This issue was reported by Nicolas Destor by the means of link:https://joinup.ec.europa.eu/collection/eu-fossa-2/about[EU-Free and Open Source Software Auditing (EU-FOSSA2) project].


== See Also

* bug:MID-5725[]

* link:https://hackerone.com/midpoint_h1c?view_policy=true[MidPoint page at Hackerone]