---
midpoint-feature: identity-repository
doc-type: intro
---
= MidPoint repository
:page-nav-title: Repository
:page-display-order: 850
:page-upkeep-status: green
:page-liquid:
:page-description: MidPoint repository is a central database in which midPoint stores all the identity and operational data with which it works.
:page-keywords: repository, database, backup, mission critical

MidPoint repository is the central database in which midPoint stores all the identity, configuration, and operational data with which it works.

Without the repository, there is no midPoint. +
The repository is a mission-critical component. +
It is vital to keep the repository safely backed up and accessible at all times.

== Introduction to midPoint repository

The midPoint repository is a relational database and the beating heart of all operations midPoint performs.

The role of the repository is to store data, not to implement business logic.
It provides midPoint with all the data it needs to do its job.

In other words, repository stores, midPoint decides.
The repository holds xref:/glossary/#focus[focal objects], xref:/glossary/#shadow[shadows], xref:/glossary/#role[roles], xref:/glossary/#assignment[assignments], xref:/glossary/#policy[policies], etc.
All the policy evaluations, mapping execution, or synchronization decisions is what midPoint performs based on the data it fetches from the repository.

The repository also holds all the configuration and runtime operational data, such as the xref:/midpoint/reference/concepts/system-configuration-object/[global configuration] or statuses of xref:/midpoint/architecture/concepts/task/[tasks], preserving midPoint state across restarts.
It may also contain xref:/glossary/#audit[audit log] data, unless you decide to xref:/midpoint/reference/repository/native-audit/#sql-audit-using-its-own-database[store audit log in a separate database].

== Configuration and instructions

This section contains information on repository configuration, inspection, and upgrades.

++++
{% children style: table %}
++++

== See also

* xref:/midpoint/get-started/install/system-requirements/#database_system_sizing[] for information about sizing the repository server
* xref:/midpoint/reference/deployment/clustering-ha/[] regarding the high availability setup
* xref:/midpoint/reference/concepts/query/[] for information on querying objects in the repository
