= Proposed Improvements in Mappings and Expressions
:page-nav-title: Proposed Improvements
:page-display-order: 900

* Use of value metadata.

** Avoid execution of mappings where sources were not changed.
The metadata may supplement the missing zero sets from execution of other mappings.
I.e. the metadata will tell us whether this value was also produced by other mapping, and therefore it has to be kept instead of removing it.

** Open question: metadata of account attributes for outbound mappings.

* Implementation Optimization

** Avoid execution of mapping expression in obvious cases (e.g. condition is `false` -> `false`)

* Deprecation/removal +
Should we deprecate/remove following items?

** MappingType.authoritative - somehow replaced by range (but not entirely)

** MappingType.exclusive - naturally enforced for single-valued items, do we need this also for multi-value?


== Questions

* Mapping constraints: are they "turning mapping off"? Or are they relativistic (like condition)?

