/*
 * Copyright (C) 2010-2022 Evolveum and contributors
 *
 * This work is dual-licensed under the Apache License 2.0
 * and European Union Public License. See LICENSE file for details.
 */
package com.evolveum.midpoint.repo.api;

import java.util.Objects;

import com.evolveum.midpoint.xml.ns._public.common.common_3.SystemConfigurationType;

/**
 * Application event related to system configuration change.
 * It is generated by {@link SystemConfigurationChangeDispatcher}.
 *
 * TODO: This is not our (notification) Event, should we name it so? Shouldn't we rename notification events instead?
 */
public class SystemConfigurationChangeEvent {

    private final SystemConfigurationType systemConfiguration;

    public SystemConfigurationChangeEvent(SystemConfigurationType source) {
        systemConfiguration = Objects.requireNonNull(source);
    }

    public SystemConfigurationType getSystemConfiguration() {
        return systemConfiguration;
    }
}
