---
midpoint-feature: self-service-password-reset
doc-type: config
---
= Password Reset Configuration
:page-nav-title: Configuration
:page-wiki-name: Password Reset Configuration
:page-wiki-id: 24676562
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2018-02-26T10:28:15.324+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2018-02-26T10:43:01.590+01:00
:page-moved-from: /midpoint/reference/security/credentials/password-reset/new-configuration/
:page-upkeep-status: green

== Basic Mechanism

The idea is that all the password reset mechanisms have the same parts:

* *Request*: user requests password reset.
This may be as simple as a "forgot password" button on a login screen.
But there may be complicated methods, such as requesting password reset by asking a colleague or indirect helpdesk password reset scenarios.

* *Authentication*: the user that requests password reset is authenticated.
This may be a complete out-of-band authentication (which effectively means no extra authentication is performed by midPoint).
Or this may be a usual authentication using a nonce sent in an e-mail message.
Or this may be an authentication based on the security questions.
Or there may be other complex authentication schemes.

* *Source of new credentials* specifies how a new credential value is determined.
The new value may be entered by the user, randomly generated, determined by a key-exchange protocol and so on.

* *Delivery* specifies how the new credential value is delivered to the user.
The value may be simply displayed on the screen, sent in an e-mail or even distributed to several colleagues.


== Interfaces

Password reset process can be produced with the interfaces as well (xref:/midpoint/reference/interfaces/model-java/[IDM Model Interface], xref:/midpoint/reference/interfaces/rest/[REST API]).
The interaction can be done with the help of the following methods:

* Request caller authentication.
** xref:/midpoint/reference/interfaces/rest/concepts/authentication/[REST API interface authentication]

* Execute method
** ModelInteractionService.executeCredentialsReset(user, executeCredentialResetRequest, task, result)
** xref:/midpoint/reference/interfaces/rest/operations/user-specific-op-rest/[REST API reset password operation].
A sample can be found xref:/midpoint/reference/interfaces/rest/operations/examples/user-pwd-reset/[here].

The usual process would be request-authenticate-execute.
However, for simple cases it may be possible to invoke just execute method.

== See Also

* xref:/midpoint/reference/security/credentials/password-reset/[Reset Password Configuration] (old configuration, soon to be deprecated)
