---
midpoint-feature: expression-mel
doc-type: config
---
= Configuring Expression Evaluation

#TODO expand these bullets#

- In order to prohibit unsafe (Groovy, Velocity, JavaScript, Python) expressions, it is possible to disable their execution right in the system configuration
(so even midPoint administrator cannot enable their execution)
- This is done by setting `safeExpressionsOnly` to `true` like this:
+
[source,xml]
----
<configuration>
    <midpoint>
	    <expressions>
	        <safeExpressionsOnly>true</safeExpressionsOnly>
    	</expressions>
    </midpoint>
</configuration>
----
+
Any attempt to execute Groovy, Velocity, JavaScript, or Python expressions will result in an error being signalled.
+
NOTE: This does not cover executing Groovy code in connectors!

- In order to provide the required flexibility even with disabled general-purpose scripting languages, midPoint allows calling selected Java methods using newly-introduced `javaMethodReference` expression evaluator.
These methods must reside in classes whose packages are explicitly allowed in the system configuration, like this:
+
[source,xml]
----
<configuration>
    <midpoint>
	    <expressions>
            <javaMethodEvaluatorPackageName>com.example.scripting.extensions</javaMethodEvaluatorPackageName>
            <javaMethodEvaluatorPackageName>...</javaMethodEvaluatorPackageName>
	    </expressions>
    </midpoint>
</configuration>
----

Please see xref:/midpoint/reference/expressions/expressions/#_java_method_reference[Java Method Reference] expression evaluator for details.
