---
midpoint-feature: access-certification
doc-type: config
---
= Certification campaign configuration
:page-nav-title: Configuration
:page-toc: top
:page-upkeep-status: orange
:experimental:
:page-display-order: 100
:page-description: This article describes certification campaign configuration options.
:page-keywords: certification campaign, campaign definition, campaign configuration, campaign dashboard widget

This article describes certification campaign configuration options.

== Certification campaign definition

Certification campaigns are created using templates that are called *certification campaign definitions*, or certification definitions for short.

While you can configure certification campaign definitions in the user-friendly midPoint GUI by going to icon:certificate[] btn:[Certification] > icon:circle[] btn:[Campaign definitions], this page focuses on describing the concept and raw XML definition.

Each definition contains the following elements:

name ::
    The name of the certification campaign definition, e.g. "All user assignments".

description ::
    A more verbose description of the definition, e.g. "Certifies assignments for all users.
    Everything is certified by the administrator."

handlerUri ::
    Defines the software element (handler) that implements all the processing required by the certification campaigns of the given type. +
    Currently, there is one bundled handler named `http://midpoint.evolveum.com/xml/ns/public/certification/handlers-3#direct-assignment` that is able to handle certifications of many types of direct assignments, e.g. user-to-role, user-to-org, role-to-role, etc.
    However, you can create your own handlers.

scopeDefinition ::
    While the handler provides basic character of the certification (e.g. "we'll be dealing with direct assignments"), the scope definition says more precisely which objects (in this case, assignments) are involved.
    For example, the scope can be limited to user-to-role, only certain users, certain roles, etc.

ownerRef ::
    Defines the owner of the definition and the related campaigns.
    Campaign owner may be different from the owner of the campaign definition.

remediationDefinition ::
    Defines the remediation phase, for example, if it is automated or manual.

reiterationDefinition ::
    Defines the iteration part.
    For example, if it starts automatically (manual by default), or how many iterations are allowed.

stageDefinition ::
    Defines the individual review stages.
    One campaign may contain multiple `stageDefinition` elements, each per stage.
    It defines, for example, the duration of stages, the reviewer selection process, etc.

reviewStrategy ::
    Defines the strategy used to compute the review outcome for a given case.

view ::
    Specifies a view for the presentation of the certification items collections which are created on the basis of the current certification definition.
    This means that every certification campaign created on the basis of this definition will use this view while displaying certification items collection.

== Campaign definition example

See an example of a campaign definition (taken from the link:https://github.com/Evolveum/midpoint-samples/blob/master/samples/certification/def-all-user-assignments.xml[samples/certification/def-all-user-assignments.xml] file):

sampleRef::samples/certification/def-all-user-assignments.xml[18,-1]

In this case, the scope definition is missing.
It means that the default values are used, i.e., all assignments of all users are taken into account.

In the example above, there is only one stage.

Aside *name* and *description*, a stage definition consists of the following:

number ::
    As lists are generally not ordered in midPoint data structures, each stage has a number that specifies in which order it will be executed.
Numbers have to start at 1 and increase consecutively.

duration ::
    This property defines the duration of the stage and influences notifications and automated closure of the stage.

notifyBeforeDeadline ::
    Defines how long before the deadline (given by the stage duration) notifications are to be sent.
    This is a multi-valued property, so it is possible to specify more than one notification.
    In the example above, the first notification is sent 48 hours and the second one 12 hours before the deadline.

notifyOnlyWhenNoDecision ::
    If set to `true` (the default), notifications are sent only to reviewers that have not decided yet.

reviewerSpecification ::
    Defines how reviewers are selected.
    In our example, everything will be reviewed by the administrator.

Refer to xref:/midpoint/reference/roles-policies/policies/certification/stages/[] for a complete list of options for stage definitions and a more detailed explanation.

== Certification campaign configuration options

Beside the basic campaign configuration outlined above, the configuration options are much deeper.
Refer to the following articles for options to configure scope, stages, GUI, or reporting.

++++
{% children style: table %}
++++

[[scope_definition]]
// TODO: delete, moved to dedicated article

[[stage_definitions]]
// TODO: delete, no need to list here in a section; dedicated article

[[automated_scheduling_of_campaigns]]
// TODO: delete, moved to dedicated article


[[access_certification]]
// TODO: delete, moved to dedicated article (global config)

[[config_collection_views]]
// TODO: delete, moved to dedicated article (gui > index)

