= Ninja

:page-upkeep-status: red
:page-upkeep-note: Need to update, also for midScale and DB migration
:page-alias: { "parent" : "/midpoint/tools/" }
:page-toc: top

[NOTE]
====
Since midPoint 4.8. Also in 4.4.6, 4.7.2 and later.

* Commands and options names realigned:
** All command and option names are kebab cased
** File output is now `-o, --output`
** `-O, --overwrite` for all commands
====

Ninja is a command line tool bundled with midPoint.
Implemented features are based on "repo-ninja", but code was rewritten from the ground up.
This tool comes in handy when one needs to export or import objects from/to midPoint.
Operations can be done on top of repository (DB) layer or through REST API.
Access through DB layer can be very powerful, especially in cases when UI fails.
For example when midPoint fails to start because of configuration issue or objects data corruption.
Another great example is "administrator" user lockout.

Users of this tool need to be aware that using repository layer, access is not validated using
authorisations, model component is not used during processing and changes are not audited.
It allows you to obtain or modify data in an otherwise unusable midPoint.
Ninja also supports some other operations like listing keys from keystore, enforcing objects
reencryption with new key, DB schema validation, password reset or user unlock.

Ninja can be started using standard `java -jar` or via bundled shell/bat script.
Bundled shell and bat scripts are located in the midPoint installation directory, e.g. `<midpoint>/bin/ninja.sh`.
Bundled scripts will automatically fill in path to for xref:/midpoint/reference/deployment/midpoint-home-directory/[midPoint home]
option `-m` using `MIDPOINT_HOME` environment variable, defaulting to the `<midpoint>/var`.

== Connecting to midPoint

Connection options:

* using `${midpoint.home}`
* using REST service (not yet implemented)

=== midpoint.home connection

This type of connection initialises repository layer of midPoint and operates on top of the database.
For all commands that communicate with DB layer `${midpoint.home}` must be specified using `-m <path>` option.
Ninja will try to read database connection information from `config.xml`.
This will not work when there's only datasource definition in `config.xml` (no JDBC url/username/password).
In such chase one have to specify URL (`-U`), username (`-u`) and password (`-p` or `-P`).
These options can also be used to override JDBC URL, username and password specified in `config.xml`.

With bash, you can provide environment variable `MIDPOINT_HOME` for the `ninja.sh` command with this shortcut:

[source,bash]
----
MIDPOINT_HOME=/var/other-mp-home <midpoint>/bin/ninja.sh [general options] [command] [command options]
----

=== JDBC Driver

Only JDBC driver that is bundled is for PostgreSQL database.
This means that for other databases, you must provide JDBC driver yourself.
Most of the time JDBC driver is already present in `<midpoint>/lib` directory.
However, it will not be picked up automatically, and you must point ninja to it explicitly.
Example when using `java -jar`:

[source,bash]
----
java -Dloader.path=<jdbc_driver_jar_path> -jar ninja.jar [general/connection options] [command] [command options]
----

If the bundled scripts are used, you can specify the path to the driver with `-j` option, for example:

[source,bash]
----
<midpoint>/bin/ninja.sh -j <jdbc_driver_jar_path> [general/connection options] [command] [command options]
----

== Supported operations

Ninja currently supports these operations:

* <<Count>>
* <<Delete>>
* <<Download distribution>>
* <<Export>>
* <<Export audit>>
* <<Export mining>>
* <<Help>>
* <<Import>>
* <<Import audit>>
* <<Info>>
* <<Initial objects>>
* <<Keys>>
* <<Pre-upgrade check>>
* <<Run SQL>>
* <<Trace>>
* <<Upgrade distribution>>
* <<Upgrade installation>>
* <<Upgrade objects>>
* <<Verify>>

:leveloffset: +2

include::command/count.adoc[]

include::command/delete.adoc[]

include::command/download-distribution.adoc[]

include::command/export.adoc[]

include::command/export-audit.adoc[]

include::command/export-mining.adoc[]

include::command/help.adoc[]

include::command/import.adoc[]

include::command/import-audit.adoc[]

include::command/info.adoc[]

include::command/initial-objects.adoc[]

include::command/keys.adoc[]

include::command/pre-upgrade-check.adoc[]

include::command/run-sql.adoc[]

include::command/trace.adoc[]

include::command/upgrade-distribution.adoc[]

include::command/upgrade-installation.adoc[]

include::command/upgrade-objects.adoc[]

include::command/verify.adoc[]

:leveloffset: 0

== Other scenarios

=== Administrator unlock

Ninja does not provide unlock or password reset operations explicitly.
Normally administrator can do this via GUI.
It may happen that administrator locks out itself from the system, in which case we recommend to reinitialize the object:

.Administrator object refresh from the initial object
[source,bash]
----
ninja.sh import --input <midpoint>/doc/config/initial-objects/050-user-administrator.xml --overwrite
----

Now, this is rather a drastic measure - let's modify the existing user instead.
First we need to export it.

[NOTE]
If you want to use Ninja for midPoint running with H2 database (which is sensible only for testing), the application must be stopped first.
Other databases have dedicated servers and Ninja can be used while midPoint is running.

.Exporting administrator user by OID
[source,bash]
----
ninja.sh export --oid 00000000-0000-0000-0000-000000000002 --output admin.xml
----

Alternatively, you can use type option and filter to specify name
(don't forget the `--overwrite` option, if the file already exists):

.Exporting user by name
[source,bash]
----
ninja.sh export --type user --filter '% name = "administrator"' --output admin.xml
----

Now is the time to carefully edit the object XML.
If a single object is in the XML (which is our case), you can remove the `<objects>` wrapper element.
This may actually help with code completion if xref:/midpoint/tools/studio/[midPoint Studio] is used.

Typical fixes to shape up the uncooperative user object are:

* Remove `administrativeStatus` and `effectiveStatus` elements from the top-level `activation`
element (be sure not to modify `activation` under `assignments` inadvertently).
This should fix any problems with disabled user.
* If you forgot the password, change the whole content of the `credentials/password/value` element
to this snippet (must be inside the `value` element):
+
[source,xml]
----
<t:clearValue>asdf1234</t:clearValue>
----

After the fixes, it's time to push the object back into the repository.
Import process can handle both plain object or objects inside `<object>` container.
Use the following command:

.Importing the fixed user object
[source,bash]
----
./bin/ninja.sh import --input admin.xml --overwrite
----

Now you should enjoy easy administrator login.
Of course, this works for any user object, but using the GUI with working administrator is the way to go.

[IMPORTANT]
If you changed the password in this way, don't forget to change it immediately to something more solid.
This will also properly encrypt it in the object representation, as expected.

== Full help

.Full help
[source]
----
$ java -jar target/ninja.jar help
Usage: java [-Dloader.path=<jdbc_driver_jar_path>] -jar ninja.jar [options] [command] [command options]
  Options:
    -B, --batch-mode
      Run in non-interactive (batch) mode (disables output color).
      Default: false
    -c, --charset
      Charset used for input/output
      Default: UTF-8
    -h, --help
      Print this help
    -m, --midpoint-home
      Path to MidPoint home folder. If relative path is specified, it will be translated to absolute path.
    -p, --password
      Password for JDBC connection
    -P, --password-ask
      Ninja will ask for JDBC connection password
    --psn-class-name
      PolyString normalizer class name
    --psn-lowercase
      PolyString normalizer lowercase
    --psn-nfkd
      PolyString normalizer NFKD. Unicode Normalization Form Compatibility Decomposition (NFKD). This process
      expands composed characters (e.g. diacritic marks, ligatures, roman numerals). Character components are
      then processed individually. E.g. ascii7 normalizer will then remove just the diacritic mark, but leave
      the base letter. Therefore, for a-acute character with NFKD processing the output will be plain "a"
      character. Without NFKD processing the whole character will be removed.
    --psn-trim
      PolyString normalizer trim. Removes whitespace from beginning and end of the string. Trimming is done
      before any other processing.
    --psn-trim-whitespace
      PolyString normalizer trim whitespace
    -s, --silent
      No output at all
      Default: false
    -U, --url
      JDBC URL to database. If '-m' option is used URL will be used to connect to JDBC database.
    -u, --username
      Username for JDBC connection
    -v, --verbose
      Verbose output
      Default: false
    -V, --version
      Version and build description

  Commands:

    import                  Imports objects into MidPoint
    export                  Exports objects from midPoint
    delete                  Delete objects from MidPoint
    count                   Count objects in midPoint repository
    verify                  Verify objects in midPoint repository
    keys                    List keys from keystore
    info                    Shows information about the repository for the provided midPoint home
    import-audit            Imports audit records into MidPoint
    export-audit            Exports audit records from MidPoint
    export-mining           Export of anonymized structure of relationships between roles, users and organizations objects.
    trace                   Edit trace file
    download-distribution   Download target midPoint distribution (latest LTS).
    run-sql                 Run arbitrary SQL scripts
    upgrade-installation    Upgrade installation
    upgrade-distribution    Upgrade midPoint distribution and related DB schema
    upgrade-objects         Upgrade objects
    pre-upgrade-check       Pre-upgrade check
    help                    Print this help, or prints help for specific command.
    initial-objects         Initial objects
----
