= Execution and Execution Mode
:page-toc: top

The execution of an xref:../[activity] is primarily driven by the `executionMode` setting.

== Execution Mode

.Listing 1: Specifying activity execution mode in midPoint 4.7
[source, xml]
----
<task xmlns="http://midpoint.evolveum.com/xml/ns/public/common/common-3">
    <!-- ... -->
    <activity>
        <!-- ... -->
        <execution>
            <mode>full</mode>
        </execution>
    </activity>
</task>
----

=== Execution Mode Values

.Values of execution mode property
[%header]
[%autowidth]
|===
| Mode | Meaning | Supported by
| `full`
| Full execution mode.
Changes are computed and also executed.
| All activities.

| `preview`
| A preview (simulation) of changes: Changes are computed, but nothing is executed.
Used for example to check the thresholds before the full (real) execution or to xref:/midpoint/reference/simulation/[simulate] the execution (since 4.7).
| See note below.
| `shadowManagementPreview`
| Low-level simulation of shadow classification and correlation.
Since 4.7.
Experimental.
| See note below.

| `dryRun`
| Nothing is executed.
Just metadata are handled.
E.g. during reconciliation, only situations in shadows are set.
| See note below.

| `none`
| Items are fetched from repository or resource, but no specific processing is executed.
This is very similar to `dryRun`, but - technically speaking - items are discarded right after being fetched from the source.
Provisioning pre-processing of shadows may or may not be done, depending on the implementation.
This mode is used just to test the object retrieval process.
| Multi-threading capable activities.

| `bucketAnalysis`
| In this mode no items are really fetched.
Only the size of individual buckets is measured (if supported by the item provider, e.g. the resource).
| Multi-node capable activities.
|===

[NOTE]
====
* The `dryRun` execution mode is supported only for the synchronization activities, i.e. import, live synchronization, and reconciliation.
* The `shadowManagementPreview` is supported only for the synchronization activities.
* The `preview` execution mode is supported for the activities described xref:/midpoint/reference/simulation/#_activities_supported[here].
====

== Other Execution Definition Items

.Other execution definition items
[%header]
[%autowidth]
|===
| Item | Description
| `configurationToUse`
| Using `predefined` property, one can select either `production` or `development` configuration. +
 The former is the default one.
|===

An example:

.Listing 2: Selecting the development configuration to be used by the activity
[source, xml]
----
<task xmlns="http://midpoint.evolveum.com/xml/ns/public/common/common-3">
    <!-- ... -->
    <activity>
        <work>
            <!-- ... -->
        </work>
        <execution>
            <mode>preview</mode>
            <configurationToUse>
                <predefined>development</predefined>
            </configurationToUse>
        </execution>
    </activity>
</task>
----
