:page-visibility: hidden
:page-upkeep-status: green

*Usage of Exclude*

To exclude an attribute in the output of your request, you can specify
the `exclude` parameter in your query request. The attribute which is
mentioned after the equals sign will be excluded. In case of excluding
multiple attributes, specify each exclude with an `&` character after each
other.
You can also exclude metadata from desired path using special `@metadata` attribute name.
However, excluding attributes from within the metadata is not supported, only whole metadata could be excluded.

*Example*:

Following will remove

- metadata from the root object
- metadata from the `assignment` object
- `value` object on the path `credentials/password`

[source,bash]
----
?exclude=@metadata&exclude=assignment/@metadata&exclude=credentials/password/value
----


*Usage of Include*

The `include` parameter can be used in cases when we would like our output to contain attribute values which are by default returned as "incomplete".
An example of such attribute is the `jpegPhoto` attribute of a `UserType` (or any other `FocusType`) object.

*Example*:

[source,bash]
----
?include=jpegPhoto
----
