= Security Policy Customization - DEPRECATED
:page-nav-title: Deprecated Configuration
:page-wiki-name: Security Policy Customization - DEPRECATED
:page-wiki-id: 3146129
:page-wiki-metadata-create-user: vix
:page-wiki-metadata-create-date: 2011-11-15T12:24:34.788+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2017-03-30T13:51:19.882+02:00
:page-deprecated: true
:page-replaced-by: ../
:page-upkeep-status: green

This page will guide you through midPoint security policy settings.

== Maximum Number of Failed Logins

Maximum Number of Failed Logins limits maximum subsequent unsuccessfull user login attempts.
If exceeded, user is locked and can't log in unless "Login Timeout" time has passed.
By default, Maximum Number of Failed Logins is set to 3. +
 To change Maximum Number of Failed Logins, edit the `<tomcat>\webapps\midpoint\WEB-INF\ctx-security.xml` and find "maxFailedLogins" property in "midPointAuthenticationProvider" section:

[source,xml]
----
<beans:bean id="midPointAuthenticationProvider" class="com.evolveum.midpoint.web.security.MidPointAuthenticationProvider">
  ...
  <beans:property name="maxFailedLogins">
    <beans:value type="java.lang.Integer">3</beans:value>
  </beans:property>
</beans:bean>

----

You have to restart the application server after this change.

[WARNING]
====
Do not change anything else unless you know what you are doing.
====


== Login Timeout

Login Timeout specifies how long (in minutes) will be user locked after the "Maximum Number of Failed Logins" is reached.
By default, Login Timeout is set to 15 minutes, that means user will be able to log in again after 15 minutes. +
 To change Login Timeout, edit the `<tomcat>\webapps\midpoint\WEB-INF\ctx-security.xml` and find "loginTimeout" property in "midPointAuthenticationProvider" section:

[source,xml]
----
<beans:bean id="midPointAuthenticationProvider" class="com.evolveum.midpoint.web.security.MidPointAuthenticationProvider">
  <beans:property name="loginTimeout">
    <beans:value type="java.lang.Integer">15</beans:value>
  </beans:property>
  ...
</beans:bean>

----

You have to restart the application server after this change.

[WARNING]
====
Do not change anything else unless you know what you are doing.
====