= Pre-upgrade check
:page-description: Pre-upgrade check verifies version consistency of the midPoint application and its database schemas across your running cluster nodes
:page-keywords: pre-upgrade check, version consistency, database, schema, upgrade, audit database, repository

The pre-upgrade check verifies version consistency of the midPoint application and its database schemas across your running cluster nodes.
It also checks that the identified midPoint version is eligible for upgrade.

== Database schema version check

The check verifies that the database schema versions match a supported version.
MidPoint stores the schema version values separately for the midPoint repository database and the audit database.
The schema versions are stored in `m_global_metadata` table.

You can skip the schema version check if necessary using `--skip-database-version-check`.

== Node version check

This check verifies that all nodes in your midPoint cluster run the same midPoint version and that the version is eligible for upgrade.
Running a cluster with nodes hosting different midPoint versions is not supported.

You can skip the node version check if necessary using `--skip-nodes-version-check`.

.Example of executing the pre-upgrade check with node version check skipped
[source,bash]
----
./bin/ninja.sh pre-upgrade-check \
  --skip-nodes-version-check
----
