= Pre-upgrade check

The pre-upgrade check verifies that the repository, audit and all running cluster nodes are on the same version that is going to be upgraded.
There are two items being checked:

* database schema version
* midPoint cluster nodes version

== Database schema version check

This check verifies that database schema version matches supported version.
Database schema version is stored in `m_global_metadata` table and separate version is stored for midPoint repository and audit.
Schema version check can be skipped if necessary using option `--skip-database-version-check`.

== Nodes version check

This check verifies that all nodes in midPoint cluster have the same version and that version is eligible for upgrade.
Running a cluster with nodes on different midPoint versions is not supported.
Nodes version check can be skipped if necessary using option `--skip-nodes-version-check`.

.Example of how to do pre-upgrade check
[source,bash]
----
./bin/ninja.sh pre-upgrade-check \
  --skip-nodes-version-check
----
