= Predefined Columns Configuration
:page-nav-title: Predefined Columns Configuration
:page-upkeep-status: yellow

== General Information

MidPoint already provides a configuration for the columns within object collection view configuration.
This configuration is based on the _path_ element value or the _export -> expression_ element value.
A sample of such columns configuration can be found by the xref:/midpoint/reference/admin-gui/admin-gui-config/admin-gui-config-examples/#custom-columns-configuration[link].
Starting with midPoint-4.9, the predefined columns configuration is introduced.
Predefined columns are default (buf not only default) view columns which are already implemented in the code.
To apply a configuration to a such predefined column, the identifier (column name in this case) is used.
This document is dedicated to the predefined columns configuration.

WARNING: This feature is still under development and the configuration may change in the future.
For now, predefined columns configuration can be defined only for the certification items collection view.

== Predefined Columns Configuration

Predefined columns configuration is done within the _Object Collection View_ configuration.
A column should contain the identifier (_name_ element within column configuration).
The identifier should match one of the list of the available predefined columns which is provided further in this document.

Let's have a look at the example of the certification items collection view which can be located within system configuration object.

.Certification items default collection view configuration with predefined columns
[source,xml]
----
    <accessCertification>
        <defaultView>
            <identifier>defaultCertItemsView</identifier>
            <column>
                <name>certItemObject</name>
                <display>
                    <label>Cert. item object</label>
                </display>
            </column>
            <column>
                <name>certItemTargetDisplayName</name>
                <visibility>hidden</visibility>
            </column>
            <column>
                <name>certItemEditableComment</name>
            </column>
            <includeDefaultColumns>true</includeDefaultColumns>
            <type>AccessCertificationWorkItemType</type>
        </defaultView>
    </accessCertification>
----

In the configuration above _Object_ column's title is set to a custom value ("Cert. item object"), target object _Display name_ column is hidden and editable _Comment_ column is added.
Columns configuration can be merged by theirs identifiers (_name_ element) within different collection view configurations (e.g. default collection view configuration in system configuration object and view configuration in the certification definition object).

Identifier based columns configuration can be combined with the path/expression based columns configuration.
For example:

.Combined columns configuration
[source,xml]
----
    <accessCertification>
        <defaultView>
            <identifier>defaultCertItemsView</identifier>
            <column>
                <name>certItemObject</name>
                <display>
                    <label>Cert. item object</label>
                </display>
            </column>
            <column>
                <name>certItemTargetDisplayName</name>
                <visibility>hidden</visibility>
            </column>
            <column>
                <name>stage</name>
                <display>
                    <label>Stage number</label>
                </display>
                <path>stageNumber</path>
            </column>
            <includeDefaultColumns>true</includeDefaultColumns>
            <type>AccessCertificationWorkItemType</type>
        </defaultView>
    </accessCertification>
----

=== Available Predefined Columns

As it was mentioned above, predefined columns can be configured only for the certification items collection view for now.
Therefore, the list of the available predefined columns is limited to the certification items columns.

[%autowidth]
|===
| Column | Identifier | Default | Description

| Object
| certItemObject
| Yes
| Linked column for the certification item object

| Display name (for object)
| certItemObjectDisplayName
| Yes
| Display name of the certification item object

| Target
| certItemTarget
| Yes
| Linked column for the certification item target

| Display name (for target)
| certItemTargetDisplayName
| Yes
| Display name of the certification item target

| Reviewers
| certItemReviewers
| Yes
| Linked reviewers column

| Response
| certItemResponse
| Yes
| Displays the value of the certification item response if any exists

| Comment icon
| certItemCommentIcon
| Yes
| Displays icon in case certification item has a comment. The icon's tooltip shows the comment itself.

| Editable comment
| certItemEditableComment
| No
| Contains editable input field for commenting the certification item.

| View details link column
| certItemDetailsLink
| No
| Column with a "View details" link to display the popup with certification item object and target information, responses information and decision buttons.

|===


