= Example of Dashboard report: Shadows on resource
:page-nav-title: Example: Shadows
:page-wiki-name: Example of dashboard report: Shadow of resource
:page-wiki-id: 52002826
:page-wiki-metadata-create-user: lskublik
:page-wiki-metadata-create-date: 2020-05-04T11:22:23.046+02:00
:page-wiki-metadata-modify-user: lskublik
:page-wiki-metadata-modify-date: 2020-05-04T13:07:47.860+02:00
:page-upkeep-status: green

Please see xref:/midpoint/reference/admin-gui/dashboards/configuration/[Dashboard configuration] for basic information about configuration variables.


== Example Use-case

Administrator needs to display all shadows on resource with actual state.


== Configuration

As first, we need to configure an object collection for shadows of a specific resource and the kind of object of managed in the resource.

.*Example Object Collection*
[%collapsible]
====
sampleRef::samples/objectCollection/resource-account-shadows.xml[]
====


The import Dashboard object with widget for our object collection.

.*Example Dashboard configuration*
[%collapsible]
====
sampleRef::samples/dashboard/shadow-dashboard.xml[]
====

We want report with the table of shadow, for this we can import the following dashboard report.

.*Example Report configuration*
[%collapsible]
====
sampleRef::samples/reports/dashboard-report-shadows-of-resource.xml[]
====

Now we can run the report in the report menu, and download the report.
By default, the reports created from dashboards are in the HTML format.

== See Also

- xref:/midpoint/reference/misc/reports/examples/[Report Examples]
- xref:/midpoint/reference/misc/reports/configuration/[Report Configuration]
- xref:/midpoint/reference/misc/reports/configuration/collection-report.adoc[Collection Based Reports]
- xref:/midpoint/reference/misc/reports/configuration/dashboard-report.adoc[Dashboard Based Reports]
- xref:/midpoint/reference/concepts/query/#reference-query[Reference Query]

