= MidPoint Configuration Reference
:page-nav-title: Configuration Reference
:page-upkeep-status: green
:page-liquid:

This is a reference documentation for midPoint administration and configuration.
Following documents describe the details of midPoint configuration, behavior, customization options and all the other details that are necessary to use midPoint to its full potential.

WARNING: Most of the documentation is still located in the wiki:Documentation[wiki].
The documentation is gradually migrated here.

This is a *reference* documentation.
Its purpose is depth and breath of information.
Each page is dedicated to a particular topic.
However, the pages are not ordered in a logical, easy-to-read ordering.
Therefore it may be confusing for people that are new to midPoint.

For an easy-to-read introduction to midPoint we highly recommend starting with xref:/book/[MidPoint Book] or https://www.youtube.com/channel/UCSDs8qBlv7MgRKRLu1rU_FQ[videos on Evolveum YouTube channel].
High-level description of midPoint features can be found in wiki:Features[] part of this site.
Instructions for handling particular tasks may also be found in wiki:Tutorials+and+HOWTOs[] section.

== Reference Documentation Sections

++++
{% children %}
++++

== See Also

* xref:/book/[MidPoint Book]
* https://www.youtube.com/channel/UCSDs8qBlv7MgRKRLu1rU_FQ[Evolveum YouTube channel]
* wiki:Features[]
* wiki:Tutorials+and+HOWTOs[]
* xref:/support/[Subscription and Support]
