---
midpoint-feature: expression-mel
doc-type: intro
---
= MidPoint Expression Language Introduction
:page-nav-title: Introduction
:page-upkeep-status: green
:page-toc: top

MidPoint Expression Language (MEL) is an expression language, designed to support customization of midPoint functionality in an easy-to-use and secure way.
MEL expressions are meant to be used in midpoint xref:/midpoint/reference/expressions/mappings/[mappings],
xref:/midpoint/reference/roles-policies/roles/role-autoassignment/[autoassignment expressions],
xref:/midpoint/reference/roles-policies/roles/[roles], xref:/midpoint/reference/roles-policies/policies/[policies],
xref:/midpoint/reference/admin-gui/admin-gui-config/[GUI customization] and similar places.

MEL is designed for security, therefore it can be used at places where feature:delegated-administration[administration privileges are delegated], such as administration of roles, policies, configuration of reports and dashboards.

== Synopsis

Following code returns a `name` property of a user:

[source,mel]
----
focus.name
----

Simple string concatenation to generate user's `fullName`:

[source,mel]
----
focus.givenName + ' ' + focus.familyName
----


Username generator, combining first letter of (normalized) user's given name, eight letters of family name and an iteration token:

[source,mel]
----
focus.givenName.norm.substring(0,1) + focus.familyName.norm.substring(0,7) + iterationToken
----

== The Basics

MEL is an _expression_ language which allows easy access to midPoint data structures (xref:/midpoint/reference/schema/common-data-model/[midPoint objects]), transforming or combining their values.
MEL expressions are similar to single-line functions or lambda expressions.

.MEL and CEL
NOTE: MidPoint Expression Language (MEL) is heavily based on link:https://cel.dev/[Common Expression Language (CEL)], which was extended with midPoint-specific features, functions and libraries.
CEL is used by many software platforms mostly focused in IT infrastructure, therefore it is likely that users may be already familiar with it.
CEL was extended with features that are essential for its efficient use in midPoint environment, thus creating MEL, a midPoint expression language.

Input to MEL expressions is provided by xref:/midpoint/reference/expressions/variables/[variables].
The variables available to the expression differ with respect to the type of expression and context.
E.g. the usual variables such as `focus` and `projection` are available in xref:/midpoint/reference/expressions/mappings/[mappings], whereas a different set of variables is available in expressions that deal with reports, dashboards and user interface customization.

A relatively rich set of _operators_ and _functions_ is available in MEL expressions.
There are the usual operators for algebra (`+`, `-`, etc.), comparison (`==`, `<`, `>`, etc.) and logic (`&&`, `||`, etc.)
The functions deal with string operations (`substring`, `contains`, etc.), list processing (`filter`, `map`, etc.), parsing, formatting, pattern matching, timestamp manipulation and many other things.
These are documented in xref:specification[MEL language specification].

Expressions are supposed to return a value.
There is no `return` statement in MEL.
In fact, there are no statements in MEL at all, just functions and operators and other "functional" things.
MEL is an _expression_ language, returning a value is the ultimate purpose of the expression.

MEL has a distinct _functional_ character.
There are no loops or other flow control constructs, but there is no _flow_ to control.
There is even no way to specify a _sequence_.
MEL functions and operators are invoked in a natural order, when all their inputs are computed.
MEL functions are supposed to be free of side effects, therefore the exact order of execution is not important.

.Migrating from Groovy
TIP: xref:migration[Migration guide] is a valuable resource for engineers that are used to Groovy and/or need to migrate existing Groovy expression to MEL.

This way of thinking may look a bit odd at the first sight if you are used to imperative programming language such as Groovy or Java.
_Expressions_ are not like that.
However, MEL expressions has numerous benefits, and the language will look very natural once you get used to it.
Just write the expression to compute and return a value.
Let midPoint do the rest: all the iterations, type conversions, delta computations, retries and all the other stuff, both mundane and smart.
That is what midPoint was built for.

== Security

MEL is _designed to be secure_.
MEL expressions can use only the safe operations that are provided to them and nothing else.
In that respect, MEL is very unlike Groovy, which exposes almost the entire Java environment to the script.
MEL is the exact opposite.
All mel operators and functions are designed to be secure.
In fact, the entire expression language environment is designed to contain the expression within secure constraints.

This means that MEL is _not_ Turing-complete language - by its very design.
There are no loops or similar flow control constructs, which means that an expression cannot even create an infinite loop to mount a _denial of service (DoS)_ attack.

TIP: Even though there are no loops, this does not mean that you cannot deal with lists and multivalued data.
Functions and macros such as `filter` and `map` provide very efficient and elegant means for list processing.
In addition to that, there is the good old conditional operator (`?:`).

MEL is designed in such a way that allows to expose the ability to write expressions even to users that cannot be fully trusted.
Delegated administrators of roles and organizational units, owners of policies, designers of reports, maintainers of dashboards, customizers of the user interface - all such users can use MEL expressions without the risk of compromising system security.

WARNING: The fact that MEL is a secure environment does not mean that you should grant ability to create expressions too liberally.
MEL expressions are designed not to cause any harm by means of their execution.
However, this does not mean that the return value provided by the expression cannot do any harm.
Even a simple expression which always returns `true` can have serious consequences, e.g. in case that it is used as a xref:/midpoint/reference/roles-policies/roles/role-autoassignment/[role autoassignment] expressions, assigning a dangerously powerful role to all users.
Expressions are often implementing policies, and policies can be powerful.
Always be mindful regarding the purpose of the expression and potential consequences it can have.

== Structured Data

Object structure can be accessed in MEL using the dot (`.`) convention.
Following expression returns value of `name` property of the object stored in `focus` xref:/midpoint/reference/expressions/variables/[variable].

[source,mel]
----
focus.name
----

MidPoint data structures are usually quite deep, therefore the access to structured data can be nested.
Following code returns value of `administrativeStatus` property located inside `activation` container, located in user object stored in variable `focus`.

[source,mel]
----
focus.activation.administrativeStatus
----

Structure of the data is dictated by xref:/midpoint/reference/schema/common-data-model/[midPoint schema].

== Creating Expressions

Simple computations can be executed on the data provided to the expression using the variables.
Following examples assume that midPoint _user_ is provided in variable `focus`, as it is the case in usual mapping expressions:

[source,mel]
----
focus.activation.effectiveStatus == `enabled`            // true if focus is active
has(focus.emailAddress) || has(focus.telephoneNumber)    // true if either one is set
size(focus.assignment) > 0                               // true if there is at least one assignment
matches(focus.telephoneNumber, '^[0-9]+$')               // true if number matches regexp
focus.givenName + ' ' + focus.familyName                 // concatenation of values
----

The examples demonstrate use of operators (`==`, `||`, etc.) as well as functions and macros (`has(...)`, `size(...)`, `matches(...)`).

There are two types of functions: global functions and member functions.

_Global functions_ are specified by their name, providing all the inputs to the function as parameters.
All the functions in the above example are global functions.

_Member functions_ are executed with respect to some value, usually a variable.
E.g. the `contains` function in the example below is a member function, which is executed on a string value provided in variable `s`.

[source,mel]
----
s.contains('foo')
----

Some functions are available in both _global_ and _member_ versions, such as `isEmpty()` function:

[source,mel]
----
foo.isEmpty()
isEmpty(foo)
----

See xref:specification[full MEP specification] for list of all applicable functions.

.Macros
NOTE: Some MEL functionality is implemented using _macros_ instead of functions.
Macros are interpreted differently than functions on a deep technical level.
However, to the common users, macros are functionally almost indistinguishable from functions for most practical cases.

MidPoint expressions usually expect a specific return type.
E.g. mapping conditions expect the expression to return a boolean value, while most mapping expression expect a string as return value.
MEL is a type-aware language, therefore MEL expressions must be written to return value of the correct type.

== Strings and Polystrings

String is perhaps the most frequently used data type in midPoint expressions.
In MEL, string literals are written using apostrophes:

[source,mel]
----
'foobar'
----

Addition operator can be used to concatenate strings:

[source,mel]
----
'foo' + 'bar'
----

There are many functions that can be invoked on strings (as _member_ functions) or using strings (as _global_ functions):

[source,mel]
----
ascii('Semančík')
'foobar'.contains('foo')
isBlank('bar')
size('foobar')
----

Regular expressions are often used to validate, analyze and manipulate strings.
MEL provides several functions for regular expression matching and replacement:

[source,mel]
----
telephoneNumber.matches('^[0-9]+$')
----

TODO: describe regex extension

MEL regular expressions are following link:https://github.com/google/re2/blob/main/README.md[RE2] syntax, which is basically a simplified Perl-compatible regular expression syntax.

Many string-like values in midPoint are provided in a form of xref:/midpoint/reference/concepts/polystring/[polystrings].
In MEL, polystrings work exactly as strings would when used in expressions and string functions.
When a polystring is used instead of string, its `orig` part is used.
E.g. assuming that the `focus` variable contains an object describing user `Radovan Semančík`, both `familyName` and `givenName` are provided to the expression in a form of polystrings.
However, these can be easily manipulated in MEL using the usual string conventions:

[source,mel]
----
focus.familyName + ', ' + focus.givenName   // Returns: Semančík, Radovan
----

Polystrings also work as structured object, with `orig` and `norm` parts.
E.g. the following expression is using `norm` part of the polystrings to generate a username:

[source,mel]
----
focus.givenName.norm.substring(0,1) + focus.familyName.norm
----

== Flow Control

MEL is an expression language.
Strictly speaking, expressions do not have a "flow", therefore there are no flow control mechanisms in MEL.

* No flow control, but we have conditional

== Lists and Multivalue Data

TODO: multivalued properties: size, [], map, filter

== Language Extensions

Common expression language (CEL) which was a foundation for MidPoint Expression Language (MEL) is quite limited.
Therefore, MEL provides additional language extensions that implement functions commonly used in midPoint environment.
Many MEL language extensions fit naturally into the language and are usually not noticed at all (e.g. in case of _polystrings_).
However, other extensions are explicitly distinguished, to make their purpose clear and to avoid conflicts with native functionality of the language.
Most of the extensions have explicit _prefix_ in function names.
Following extensions are available in MEL:

|===
|Prefix | Purpose | Description

| `format`
| Formating and parsing
| Format extension is used to format, parse and otherwise process string-formatted data.
It is used to format/parse timestamps and parse or format full name.

| `log`
| Logging and diagnostics
| Log extension is used to record diagnostic information in system logs.
Functions of the `log` extensions can be used to record errors, as well as troubleshoot the expressions.

| `ldap`
| LDAP-specific functions
| LDAP extension is used to process LDAP-specific data formats, such _distinguished name_ (DN).

| `secret`
| Secret providers
| Secret extension is used to interact with secret providers.


| _object_ +
(no prefix)
| Object data
| Object extensions provide convenience functions that allow easier processing of midPoint objects,
such as resources or shadows.

|===

== See Also

* xref:specification[MidPoint Expression Language Specification]
