---
midpoint-feature: expression-mel
doc-type: intro
---
= Null Values in MidPoint Expression Language
:page-nav-title: Null Values
:page-upkeep-status: yellow
:page-toc: top

MEL data structures and functions are generally null-safe.
I.e. expression authors do not need to worry about passing `null` values into functions, or even invoking member functions on `null` values.

== Null-Safe Functions

MEL interpreter substitutes a reasonable return value in such a case, which is usually also `null` value.
However, some functions may return empty string (`''`), zero (`0`) or appropriate boolean value instead.

Both examples below are null-safe.
These functions return `null` in case that the `givenName` variable is `null`.
No additional null checks are needed.

[source,mel]
----
givenName.substring(0,1)
----

[source,mel]
----
substring(givenName,0,1)
----

Other string functions are also null-safe, including functions returning boolean values.
For example, following expression returns `false` in case the `fullName` variable is `null`.

[source,mel]
----
fullName.contains('TEST')
----

== Null-Safe Navigation

Navigation of structured data is also null-safe.
Following example is null-safe navigation.
In case that `focus`, `activation` or `administrativeStatus` are null or not present, result of the expression is `null`.

[source,mel]
----
focus.activation.administrativeStatus
----

The `isPresent()` function can be used for tests regarding presence of items in structured objects and maps:

[source,mel]
----
isPresent(focus.activation.administrativeStatus)
----

CEL provides the `has()` macro, which can also be used for tests regarding presence of items in structured objects and maps:

[source,mel]
----
has(focus.fullName)
----

However, the `has()` macro cannot be used to check presence of plain values (e.g. variables).
Therefore, as a rule of thumb, it is recommended to use `isPresent()` function instead of `has()` macro.

== Null and Conditionals

However, there is one unpleasant detail regarding `null` literal.
CEL interpreter is regarding `null` as a special data type.
The `null` literal is considered to be statically-typed, which may cause problems in some cases.
The conditionals (`?:`) are the most notorious (see xref:../tips[] for details).
As a rule of thumb, use `nil` instead of `null` literal if your code does not work with `null`.
The `nil` provides a dynamically-typed null value, which usually fixes the situation.

E.g. following example may fail for some data types:

[source,mel]
----
condition ? value : null
----

In that case, use `nil` instead of `null`:

[source,mel]
----
condition ? value : nil
----

== See Also

* xref:../specification/[MidPoint Expression Language Specification]
* xref:../troubleshooting/[Troubleshooting MidPoint Expression Language]
