---
midpoint-feature: expression-mel
doc-type: config
---
= MidPoint Expression Language Specification
:page-nav-title: Specification
:page-upkeep-status: green
:page-toc: top

MidPoint Expression Language (MEL) is an expression language designed to support customization of midPoint functionality in an easy-to-use and secure way.

This page provides detailed description of the language.
It is meant to be a reference documentation of the language.

TIP: See xref:../introduction/[MEL Introduction] for a step-by-step introduction to MEL language.
If you are used to create Groovy scripts, xref:../migration/[MEL Migration Guide] may be a good start.

== Literals

[%autowidth]
|====
| Literal | Prefix / Delimiter / Values | Example | Notes

| String
| `'` (apostrophe)
| `'Hello world!'`
|

| Numeric
| none
| `42` +
`3.14`
|

| Boolean
| `true` +
`false`
| `true`
|

| Bytes
| `b`
| `b'\x68\x65\x6c\x6c\x6f'`
|

| Null
| `null` +
`nil`
| `null` +
`nil`
| `nil` is dynamically-typed,
see xref:../null/[nullability notes].

| List
| `[]` (square brackets)
| `[1, 2, 3]` +
`['foo', 'bar', 'baz']`
|

| Map
| `{}` (curly brackets)
| `{'one': 'unus', 'two': 'duo', 'thee': 'tres'}`
|

| Timestamp
| `timestamp()` constructor function
| `timestamp('2026-06-15T10:30:45.123Z')`
|

| Duration
| `duration()` constructor function
| `duration('1h30m')`
|

|====


== Operators

Following _operators_ can be used in MEL expressions:

[%autowidth]
|====
| Operator | Meaning | Notes

|`==`
| Equality
|

|`!=`
| Inequality
|

|`>`
| Greater than
|

|`>=`
| Greater than or equal
|

|`<`
| Less than
|

|`\<=`
| Less than or equal
|

|`+`
| Addition, concatenation
| Can be used for algebraic addition or string concatenation.

|`-`
| Negation, subtraction
|

|`*`
| Multiplication
|

|`/`
| Division
|

|`%`
| Remainder
|

|`!`
| Logical NOT
|

|`&&`
| Logical AND
|

|`\|\|`
| Logical OR
|

|`()`
| Grouping
|

|`in`
| Inclusion test
|

|`?:`
| Conditional
|

|`.`
| Selection
| Used to resolve structured data, assumes non-null operand.

|`[]`
| Index
| Used to retrieve specific value from a list, map or structured data.
Assumes non-null operand.

|====

== Variables

Variables are demoted without any prefix.
E.g. following expression is adding values of two variables, `foo` and `bar`:

[source,mel]
----
foo + bar
----

The usual xref:/midpoint/reference/expressions/variables/[expression and mapping] variables are available for MEL expressions.
However, there are few exceptions:

* Deprecated variables `user`, `account` and `shadow` are not present in MEL expressions.
Use correct variables names instead (`focus` and `projection`).

* Variables that represent services for Java-like languages (`prismContext`, `localizationService`) do not make sense in MEL environment, therefore these are not present.

* Some script expression environments expose built-in extension libraries in a form of variables (`basic`, `midpoint`, `log`).
These variables are not present in MEL environment.
Equivalent functionality is available to MEL expressions in a form of native MEL language extensions,
e.g. as `norm`, `log.debug(...)` or `midpoint.getObject(...)` functions.
See xref:../migration/[migration guide] for more details.

There is additional variable available to all MEL expressions:

* Variable `now` contains current timestamp.
It is a fixed timestamp of an approximate moment of the script execution.
Value of the variable does not change during script execution.


== Functions and Macros

There are two types of functions: global functions and member functions.

* _Global functions_ are specified by their name, providing all the inputs to the function as parameters.
+
[source,mel]
----
size(focus.assignment) > 0
matches(focus.telephoneNumber, '^[0-9]+$')
----

* _Member functions_ are executed with respect to some value, usually a variable.
E.g. the `contains` function in the example below is a member function, which is executed on a string value provided in variable `s`.
+
[source,mel]
----
s.contains('foo')
----

Some functions are available in both _global_ and _member_ versions, such as `isEmpty()` function:

----
foo.isEmpty()
isEmpty(foo)
----

Following sections provide description of functions available to all MEL expressions.

=== all

`list(A).all(A, predicate(A))` -> bool +
`map(A, B).all(A, predicate(A))` -> bool

Macro which tests whether all elements in the input list or all keys in a map satisfy the given predicate.

.Example
[source,mel]
----
// Returns true if all assignments in a focus have targetRef
focus.assignment.all(a, has(a.targetRef))
----

=== ascii

`ascii(any)` -> string

Converts the argument to plain ASCII (ASCII7), all non-ASCII characters and all non-printable characters are removed.
ASCII characters with diacritical marks are converted to their basic variants (removing the marks).

.Example
[source,mel]
----
// Returns 'Cortuv hrad, tam Strasa!'
ascii('Čórtův hrád, tam Strašá!')
----

=== capitalize

`string.capitalize()` -> string

Converts first character of a string to upper case.
Works on strings as well as polystrings.

.Example
[source,mel]
----
'midPoint'.capitalize()   // Returns 'MidPoint'
----


=== charAt

`string.charAt(int)` -> string

Returns the character at the given position (starting at 0).
If the position is negative, or greater than the length of the string, the function will produce an error.

.Example
[source,mel]
----
'midpoint'.charAt(1)   // Returns 'i'
----

=== contains(string)

`string.contains(substring)` -> bool +
`contains(string, substring)` -> bool

Function that tests whether the string contains the substring.
Works on strings as well as polystrings.
Global version of this function is `null` resistant, returning `null` in case that the input string is `null`.

.Example
[source,mel]
----
// Checks whether the full name contains substring 'Mr.'
focus.fullName.contains('Mr.')

// Checks whether the full name contains substring 'Mr.' (null resistant)
contains(focus.?fullName, 'Mr.')
----

=== contains(list)

`list.contains(any)` -> bool

Function that tests whether provided list contains specified item.

.Example
[source,mel]
----
['Alpha', 'Bravo', 'Charlie'].contains('Bravo')  // Returns true

focus.organizationUnit.contains('Sales')
----


=== containsIgnoreCase(string)

`string.containsIgnoreCase(substring)` -> bool +
`containsIgnoreCase(string, substring)` -> bool

Function that tests whether the string contains the substring without regard to character case.
Works on strings as well as polystrings.

.Example
[source,mel]
----
// Checks whether the full name contains substring 'phd.' in any combination of cases
focus.fullName.containsIgnoreCase('phd.')
----

=== containsIgnoreCase(list)

`list.containsIgnoreCase(any)` -> bool

Function that tests whether provided list contains specified item without regard to case.

.Example
[source,mel]
----
['Alpha', 'Bravo', 'Charlie'].contains('Bravo')            // Returns true

['Alpha', 'Bravo', 'Charlie'].containsIgnoreCase('bravo')  // Returns true

focus.organizationUnit.contains('sales')
----


=== debugDump

`debugDump(any)` -> string

Returns formatted, human-friendly, multi-line dump of a complex data structure.

.Example
[source,mel]
----
// Returns formatted, multi-line dump of the data structure in focus variable
debugDump(focus)
----

This function can be especially useful when combined with logging functions:

.Example
[source,mel]
----
// Returns formatted, multi-line dump of the data structure in focus variable
log.trace('Focus object: {}', debugDump(focus))
----

=== default

`default(any, defaultValue)` -> any

Returns a value provided as a first argument as long as that value is non-null.
If `null` (or equivalent) value is provided, it returns default value (second argument) instead.

.Example
[source,mel]
----
'Hello ' + default(foo, 'world')    // Returns 'Hello world' if value of foo is null
----

=== endsWith

`string.endsWith(suffix)` -> bool

Function that tests whether the string ends with a specified suffix.
Works on strings as well as polystrings.

.Example
[source,mel]
----
// Checks whether the full name ends with 'PhD.' suffix
focus.fullName.endsWith('PhD.')
----

=== equalsIgnoreCase

`string.equalsIgnoreCase(string)` -> bool +
`equalsIgnoreCase(string, string)` -> bool

Function that tests whether strings equally match without regard to character case.
Works on strings as well as polystrings.

.Example
[source,mel]
----
'FooBar'.equalsIgnoreCase('foobar')  // Returns true
----

=== exists

`list(A).exists(A, predicate(A))` -> bool +
`map(A,B).exists(A, predicate(A))` -> bool

Macro which tests whether any value in the list or any key in the map satisfies the predicate expression.

.Example
[source,mel]
----
// Returns true if any assignment in a focus contains a policy rule
focus.assignment.exists(a, has(a.policyRule))
----

=== exists_one

`list(A).exists_one(A, predicate(A))` -> bool +
`map(A,B).exists_one(A, predicate(A))` -> bool

Macro which tests whether exactly one value in the list or any key in the map satisfies the predicate expression.

.Example
[source,mel]
----
// Returns true if exactly one assignment in a focus contains a policy rule
focus.assignment.exists_one(a, has(a.policyRule))
----

=== filter

`list(A).filter(A, predicate(A))` -> list(A) +
`map(A,B).filter(A, predicate(A))` -> list(A)

Macro which returns a list containing only the elements from the input list that satisfy the given predicate.

.Example
[source,mel]
----
// Returns lists of assignments that have targetRef specified
focus.assignment.filter(a, has(a.targetRef))
----

=== format

`string.format(list)` -> string +
`format(string, list)` -> string

Format strings according to specified template, filling in data from the arguments.

Format specification follows https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Formatter.html[Java formatter conventions].

The `format()` function is null-safe in the Java way.
I.e. the `format()` function will not fail if a null argument is provided as input.
However, the null values of are rendered as string `null`.

.Example
[source,mel]
----
// Returns 'Jack has 3 apples'
'%s has %d apples'.format(['Jack', 3])
format('%s has %d apples', ['Jack', 3])
----

.Example
[source,mel]
----
// Returns 'null has null apples'
'%s has %d apples'.format([null, null])
----

=== has

`has(variable.item)` -> bool

Macro that checks whether the item exists within a data structure.

In MEL, it is recommended to use `isPresent()` function instead of `has()`.

.Example
[source,mel]
----
has(focus.activation.administrativeStatus)
----

=== indexOf

`string.indexOf(substring)` -> int +
`string.indexOf(substring, offset)` -> int

Returns the integer index of the first occurrence of the search string.
If offset is specified, the search begins at the offset.
If the search string is not found the function returns -1.

.Example
[source,mel]
----
'midpoint is in the middle'.indexOf('id')     // Returns 1
'midpoint is in the middle'.indexOf('id', 5)  // Returns 20
----

=== isBlank

`isBlank(string)` -> bool +
`string.isBlank()` -> bool

Returns true if string is blank (is null, has zero length or contains only white characters).

.Example
[source,mel]
----
'foo'.isBlank()  // Returns false
'   '.isBlank()  // Returns true
''.isBlank()     // Returns true
----

=== isEmpty

`isEmpty(string)` -> bool +
`isEmpty(list)` -> bool +
`string.isEmpty()` -> bool

Returns true if string is empty (has zero length), or if it is null.
Also returns true if the argument is an empty list.

.Example
[source,mel]
----
'foo'.isEmpty()  // Returns false
'   '.isEmpty()  // Returns false
''.isEmpty()     // Returns true
isEmpty([])      // Returns true
----

=== isPresent

`isPresent(any)` -> bool

Returns true if the argument is present, i.e. if it is not `null` nor any of its equivalents.
This function works reliably in all the cases when a test for presence would be done.
E.g. it works with primitive types as well as items of structured types.

.Example
[source,mel]
----
isPresent(null)     // Returns false
isPresent('foo')    // Returns true
----

Function `isPresent()` can be used with structured data as well.
The following expression returns `true` only if (non-null) value of `validFrom` property is present.
It returns `false` in all other cases, such as when `focus` variable contains `null`, if the object in `focus` variable does not have `activation` container, if the container does not contain `validFrom` property or if that property is `null`.

.Example
[source,mel]
----
isPresent(focus.activation.validFrom)
----

=== join

`list(string).join()` -> string +
`list(string).join(separator)` -> string +
join(`list(string))` -> string +
join(`list(string), separator)` -> string


Returns a new string where the elements of string list are concatenated using the separator.
If no separator is specified, empty string is used as separator.
List items that are `null` are ignored during processing.

.Example
[source,mel]
----
['foo','bar','baz'].join()       // Returns 'foobarbaz'
['foo','bar','baz'].join(',')    // Returns 'foo,bar,baz'
join(['foo', null, 'bar'], '/')  // Returns 'foo/bar'
----

=== lastIndexOf

`string.lastIndexOf(substring)` -> int +
`string.lastIndexOf(substring, offset)` -> int

Returns the integer index of the last occurrence of the search string.
If offset is specified, the search begins at the offset.
If the search string is not found the function returns -1.

.Example
[source,mel]
----
'midpoint is in the middle'.lastIndexOf('id')     // Returns 20
'midpoint is in the middle'.lastIndexOf('id', 5)  // Returns 1
----

=== lc

`string.lc()` -> string

Returns a new string where all characters are lower-cased.

.Example
[source,mel]
----
'Čórtúv Hrád'.lc()  // Returns 'čórtúv hrád'
----

=== list

`list(scalar)` -> list +
`list(list)` -> list

Returns list composed of specified argument.
If a scalar argument is provided, it returns a single-element list containing that argument.
If a list is provided as argument, the same list is returned.

This function always returns list.
Even if `null` or `nil` input is provided, empty list is returned.

.Example
[source,mel]
----
list('foo')          // Returns ['foo']
list(['foo'])        // Returns ['foo']
list(['foo','bar'])  // Returns ['foo','bar']
list(nil)            // Returns []
----

=== lowerAscii

`string.lowerAscii()` -> string

Returns a new string where all ASCII characters are lower-cased.
This function does not perform Unicode case-mapping for characters outside the ASCII range.

.Example
[source,mel]
----
'Čórtúv Hrád'.lowerAscii()  // Returns 'Čórtúv hrád'
----

This is s stock CEL function, it is mostly provided just for compatibility.

WARNING: As this function is not mapping non-ASCII characters, it is not suitable for international unvironments.
Use `lc()` function instead.


=== map

`list(A).map(A, transform(A))` -> list(A) +
`list(A).map(A, predicate(A), transform(A))` -> list(A) +
`map(A,B).map(A, transform(A))` -> list(A) +
`map(A,B).map(A, predicate(A), transform(A))` -> list(A)

Macro returns a list where each element is the result of applying the _transform_ expression to the corresponding input list element or input map key.

There are two forms of the map macro:

* The two argument form transforms all elements.
* The three argument form transforms only elements which satisfy the _predicate_.

The three-argument form of the macro is equivalent to combined filter / map operations.

.Examples
[source,mel]
----
// Returns lists of descriptions retrieved from all the assignments
focus.assignment.map(a, a.description)

// Returns lists of target OIDs retrieved from assignments that have targetRefs
focus.assignment.map(a, has(a.targetRef) a.targetRef.oid)
----

=== matches

`string.matches(regex)` -> bool +
`matches(string, regex)` -> bool

Function that tests whether the string matches a specified link:https://github.com/google/re2/blob/main/README.md[RE2 regular expression].
Works on strings as well as polystrings.

The `match` function tests for a _partial_ (non-anchored) match of regular expression.
I.e. the function returns true if any substring of the specified string matches specified regular expression.
If a different behavior is needed, the regular expression needs to be _anchored_, e.g. by using `^` and `$` anchors.

RE2 expressions are a subset of Perl/PCRE regular expressions.
See also link:https://github.com/google/re2/wiki/Syntax[RE2 syntax definition].

.Examples
[source,mel]
----
// Checks whether the telephone number contains numbers only
focus.telephoneNumber.matches('^[0-9]+$')

// Checks whether the full name contains a number anywhere in the string
focus.fullName.matches('[0-9]+')
----

See also `reMatches()` function, which is effectively a copy of this function.
The `matches()` function is provided only for compatibility with CEL conventions.
Use of `reMatches()` and other `re*` regular expression functions is recommended.

=== norm

`norm(string)` -> string

Returns string in a normalized form.
It follows the default normalization algorithm, the same algorithm as used for PolyString values.
This function works on strings as well as polystrings.

.Example
[source,mel]
----
norm('  Semančík')    // Returns 'semancik'
----

=== prefix

`string.prefix(string)` -> string +
`prefix(string, string)` -> string

Returns string prefixed with another string.

This function is null-safe. It returns null if the first string is null.

.Example
[source,mel]
----
'foo'.prefix('bar')  // Returns 'barfoo'
prefix('foo', 'bar') // Returns 'barfoo'
prefix(null, 'bar')  // Returns null
----

=== quote

`string.quote()` -> string

Takes orig part of the given string and makes it safe to print
(without any formatting due to escape sequences).
If any invalid UTF-8 characters are encountered, they are replaced with \uFFFD.

.Example
[source,mel]
----
'foo\nbar'.quote()  // Returns '"foo\\nbar"'
----

=== reFind

`string.reFind(regex)` -> string

Function that returns the string that corresponds to the fist occurrence of specified link:https://github.com/google/re2/blob/main/README.md[RE2 regular expression].
Works on strings as well as polystrings.

RE2 expressions are a subset of Perl/PCRE regular expressions.
See also link:https://github.com/google/re2/wiki/Syntax[RE2 syntax definition].

.Examples
[source,mel]
----
'foo 123 bar 456'.reFind('[0-9]+')    // Returns '123'
----

=== reFindAll

`string.reFindAll(regex)` -> list

Function that returns list of string that corresponds to all occurrences of specified link:https://github.com/google/re2/blob/main/README.md[RE2 regular expression].
Works on strings as well as polystrings.

RE2 expressions are a subset of Perl/PCRE regular expressions.
See also link:https://github.com/google/re2/wiki/Syntax[RE2 syntax definition].

Empty list is returned in case there are no occurences, or in case the input text is `null`.

.Examples
[source,mel]
----
'foo 123 bar 456'.reFindAll('[0-9]+')    // Returns ['123', '456']
----

=== reMatches

`string.reMatches(regex)` -> bool +
`reMatches(string, regex)` -> bool

Function that tests whether the string matches a specified link:https://github.com/google/re2/blob/main/README.md[RE2 regular expression].
Works on strings as well as polystrings.

The `match` function tests for a _partial_ (non-anchored) match of regular expression.
I.e. the function returns true if any substring of the specified string matches specified regular expression.
If a different behavior is needed, the regular expression needs to be _anchored_, e.g. by using `^` and `$` anchors.

RE2 expressions are a subset of Perl/PCRE regular expressions.
See also link:https://github.com/google/re2/wiki/Syntax[RE2 syntax definition].

.Examples
[source,mel]
----
// Checks whether the telephone number contains numbers only
focus.telephoneNumber.reMatches('^[0-9]+$')

// Checks whether the full name contains a number anywhere in the string
focus.fullName.reMatches('[0-9]+')
----

The `matches()` function described above is effectively a copy of this function.
The `matches()` function is provided only for compatibility with CEL conventions.
Use of `reMatches()` and other `re*` regular expression functions is recommended.

=== replace

`string.replace(search, replacement)` -> string +
`string.replace(search, replacement, limit)` -> string

Returns a new string based on the target, which replaces the occurrences of a search string with a replacement string if present.
The function accepts an optional limit on the number of substring replacements to be made.
When the replacement limit is 0, the result is the original string.
When the limit is a negative number, the function behaves the same as replace all.

.Example
[source,mel]
----
'sailpoint'.replace('sail','mid')  // Returns 'midpoint'
----

=== reReplace

`string.reReplace(regex, replacement)` -> string +
`string.reReplace(regex, replacement, replaceAll)` -> string

Function that returns the string that corresponds to the input string,
with matches of the specified link:https://github.com/google/re2/blob/main/README.md[RE2 regular expression] replaced.
The last argument specified whether to replace all occurrences (`true`) or just the first one (`false`).
The default behavior is to replace all occurrences.
Works on strings as well as polystrings.

RE2 expressions are a subset of Perl/PCRE regular expressions.
See also link:https://github.com/google/re2/wiki/Syntax[RE2 syntax definition].

.Examples
[source,mel]
----
'foo 123 bar 456'.reReplace('[0-9]+', 'X')          // Returns 'foo X bar X'
'foo 123 bar 456'.reReplace('[0-9]+', 'X', false)   // Returns 'foo X bar 456'
----

=== reverse

`string.reverse()` -> string

Returns a new string whose characters are the same as the target string,
only formatted in reverse order.

.Example
[source,mel]
----
'foobar'.reverse()  // Returns 'raboof'
----

=== single

`single(scalar)` -> scalar +
`single(list)` -> scalar

Function that returns a single value from a list.
If a list with a single element is provided as function argument, that element is returned.
If empty list is provided to the function, it returns `null`.
If a list with more than one element is provided, the function issues an error.
If a simple scalar value is presented to the function, the same value is returned.

.Examples
[source,mel]
----
// Returns 'foo'
single(['foo'])

// Returns 'foo'
single('foo')

// Error
single(['foo','bar'])
----

=== size

`string.size()` -> int +
`size(string)` -> int +
`bytes.size()` -> int +
`size(bytes)` -> int +
`list.size()` -> int +
`size(list)` -> int +
`map.size()` -> int +
`size(map)` -> int

Function that determines length of a string, number of bytes in a sequence or size of a list or map.

.Examples
[source,mel]
----
// Returns number of characters in a full name
focus.fullName.size()

// Returns number of assignments in a focus
size(focus.assignment)
----

=== split

`string.split(separator)` -> list(string) +
`string.split(separator, limit)` -> list(string)

Returns a list of strings split from the input by the given separator.
Limit on the number of substrings produced by the split can be specified.

.Example
[source,mel]
----
'foo,bar,baz'.split(',')  // Returns ['foo','bar','baz']
----

=== startsWith

`string.startsWith(prefix)` -> bool

Function that tests whether the string starts with a specified prefix.
Works on strings as well as polystrings.

.Example
[source,mel]
----
// Checks whether the full name ends with 'Ing.' prefix
focus.fullName.startsWith('Ing.')
----

=== str

`str(any)` -> string

Converts any value provided as an argument to string.
This function is nullable.
If a `null` argument is provided as an input, `null` value is returned.

This function is useful for type conversion and unification (e.g. converting string, polystring and numbers to basic string).
For a function suitable for string formatting see `stringify()`.

.Example
[source,mel]
----
str(['foo','bar'])        // Returns '["foo","bar"]'
str(3)                    // Returns '3'
str(null)                 // Returns null
----

=== stringify

`stringify(any)` -> string +
`stringify(any, default)`

Formats any value provided as an argument to string.
The value is converted to string in a sensitive way.
E.g. the function tries to detect collections and returns the first element (if there is only one).
This function always provides non-null output.
If `null` value is presented as an argument, the function returns the default value instead.
If no default value is explicitly specified, empty string is returned.

This function is useful for string formatting and diagnostics.
For type conversion function see `str()`.

.Example
[source,mel]
----
stringify(['foo','bar'])  // Returns '["foo","bar"]'
stringify(3)              // Returns '3'
stringify(null)           // Returns ''
stringify(null, '?')      // Returns '?'
----

=== substring

`string.substring(beginIndex)` -> string +
`string.substring(beginIndex, endIndex)` -> string +
`substring(string, beginIndex)` -> string +
`substring(string, beginIndex, endIndex)` -> string


Returns a string that is a substring of this string.
The substring begins at the specified `beginIndex` and extends to the character at index `endIndex - 1`.
Thus the length of the substring is `endIndex - beginIndex`.
If `endIndex` is not specified, the substring extends to the end of original string.

Empty string is returned in case that the indexes extend beyond the original string.

Global version of this function is `null` resistant, returning `null` in case that the input string is `null`.

.Example
[source,mel]
----
'midpoint'.substring(0,3)   // Returns 'mid'
substring('midpoint',0,3)   // Returns 'mid' (null resistant)
----

NOTE: The `substring` function does not fail in case the indexes extend beyond the original string.
This behavior differs from stock behavior of Google CEL string extensions.
This behavior change is very intentional, enabling creation of simpler expressions.

=== suffix

`string.suffix(string)` -> string +
`suffix(string, string)` -> string

Returns string suffix by another string.

This function is null-safe. It returns null if the first string is null.

.Example
[source,mel]
----
'foo'.suffix('bar')  // Returns 'foobar'
suffix('foo', 'bar') // Returns 'foobar'
suffix(null, 'bar')  // Returns null
----

=== trim

`string.trim()` -> string +
`trim(string)` -> string

Returns a new string which removes the leading and trailing whitespace in the target string.
The trim function uses the Unicode definition of whitespace which does not include the zero-width spaces.

Global version of this function is `null` resistant, returning `null` in case that the input string is `null`.

.Example
[source,mel]
----
' midpoint  '.trim()   // Returns 'midpoint'
trim(' midpoint  ')    // Returns 'midpoint' (null resistant)
----

=== upperAscii

`string.upperAscii()` -> string

Returns a new string where all ASCII characters are upper-cased.
This function does not perform Unicode case-mapping for characters outside the ASCII range.

.Example
[source,mel]
----
'Čórtúv Hrád'.upperAscii()  // Returns 'ČóRTúV HRáD'
----

This is s stock CEL function, it is mostly provided just for compatibility.

WARNING: As this function is not mapping non-ASCII characters, it is not suitable for international unvironments.
Use `uc()` function instead.

=== uc

`string.uc()` -> string

Returns a new string where all characters are upper-cased.

.Example
[source,mel]
----
'Čórtúv Hrád'.uc()  // Returns 'ČÓRTÚV HRÁD'
----


== Language Extensions

Common expression language (CEL) which was a foundation for MidPoint Expression Language (MEL) is quite limited.
Therefore, MEL provides additional language extensions that implement functions commonly used in midPoint environment.
Many MEL language extensions fit naturally into the language and are usually not noticed at all (e.g. see _polystrings_ below).
However, other extensions are explicitly distinguished, to make their purpose clear and to avoid conflicts with native functionality of the language.
Most of the extensions have explicit _prefix_ in function names.

=== Format Extension

Prefix: `format`.

Format extension is used to format, parse and otherwise process string-formatted data.

==== format.concatName

`format.concatName(list)` -> string

Concatenates a user-friendly name from the list of provided components.
Each argument is converted to string (stringified), trimmed and the result is concatenated by spaces.

.Example
[source,mel]
----
// Returns 'Radovan Semančík'
format.concatName(['Radovan', 'Semančík'])
----

==== format.strftime

`format.strftime(timestamp, format)` -> string +
`timestamp.strftime(format)` -> string

Formats provided timestamp to string, using a format template specified in POSIX notation.

This is POSIX-compatible function, using a xref:../strftime/[POSIX time formatting conventions].
This format is used by other variants of Common expression language (CEL).
Use of this function is generally *recommended* instead of Java-like variants below.

.Example
[source,mel]
----
// Returns formatted time, e.g. `11/02/26 09:32:15`
format.strftime(ts, '%d/%m/%Y %H:%M:%S')
----

This function can also be invoked as a _member_ function on a timestamp:

.Example
[source,mel]
----
// Returns formatted time, e.g. '11/02/26 09:32:15'
ts.strftime('%d/%m/%Y %H:%M:%S')
----

==== format.strptime

`format.strptime(string, format)` -> timestamp +
`string.strptime(format)` -> timestamp

Parses provided string to timestamp, using a format template specified in POSIX notation.

This is POSIX-compatible function, using a xref:../strftime/[POSIX time formatting conventions].
This format is used by other variants of Common expression language (CEL).
Use of this function is generally *recommended* instead of Java-like variants below.

.Example
[source,mel]
----
// Returns a timestamp
format.strptime('11/02/26 09:32:15', '%d/%m/%Y %H:%M:%S')
----

This function can also be invoked as a _member_ function on a string:

.Example
[source,mel]
----
// Returns a timestamp
'11/02/26 09:32:15'.strptime('%d/%m/%Y %H:%M:%S')
----

==== format.formatDateTime

`format.formatDateTime(timestamp, format)` -> string +
`timestamp.formatDateTime(format)` -> string

Formats provided timestamp to string, using a format template specified in Java SimpleDateFormat notation.

This is Java-like function, compatible with original midPoint 3.x xref:/midpoint/reference/expressions/expressions/script/functions/[_basic expression functions_].
This function is mostly provided for users that are accustomed to Java conventions and for the purposed of easier migration of Groovy scripts to MEL.
Use of this function is generally *not recommended*.
Use `strftime` function instead.

.Example
[source,mel]
----
// Returns formatted time, e.g. `11/02/26 09:32:15`
format.formatDateTime(ts, 'dd/MM/YY HH:mm:ss')
----

This function can also be invoked as a _member_ function on a timestamp:

.Example
[source,mel]
----
// Returns formatted time, e.g. '11/02/26 09:32:15'
ts.formatDateTime('dd/MM/YY HH:mm:ss')
----

==== format.parseDateTime

`format.parseDateTime(string, format)` -> timestamp +
`string.parseDateTime(format)` -> timestamp

Parses provided string to timestamp, using a format template specified in Java SimpleDateFormat notation.

This is Java-like function, compatible with original midPoint 3.x xref:/midpoint/reference/expressions/expressions/script/functions/[_basic expression functions_].
This function is mostly provided for users that are accustomed to Java conventions and for the purposed of easier migration of Groovy scripts to MEL.
Use of this function is generally *not recommended*.
Use `strptime` function instead.

.Example
[source,mel]
----
// Returns a timestamp
format.parseDateTime('11/02/26 09:32:15', 'dd/MM/YY HH:mm:ss')
----

This function can also be invoked as a _member_ function on a string:

.Example
[source,mel]
----
// Returns a timestamp
'11/02/26 09:32:15'.parseDateTime('dd/MM/YY HH:mm:ss')
----

==== format.parseGivenName

`format.parseGivenName(string)` -> string +
`string.parseGivenName()` -> string

Parses provided string as a person's full name, returning the given name (first name) part.

This functions makes some assumptions regarding common structure of full names (e.g. the given name comes first and family name comes last), trying to match individual name components.

.Example
[source,mel]
----
// Returns 'Radovan'
format.parseGivenName('Ing. Radovan Semančík, PhD.')
----

This function can also be invoked as a _member_ function on a string or polystring:

.Example
[source,mel]
----
// Returns 'Radovan'
'Ing. Radovan Semančík, PhD.'.parseGivenName()
----

==== format.parseFamilyName

`format.parseFamilyName(string)` -> string +
`string.parseFamilyName()` -> string

Parses provided string as a person's full name, returning the family name (last name) part.

This functions makes some assumptions regarding common structure of full names (e.g. the given name comes first and family name comes last), trying to match individual name components.

.Example
[source,mel]
----
// Returns 'Semančík'
format.parseFamilyName('Ing. Radovan Semančík, PhD.')
----

This function can also be invoked as a _member_ function on a string or polystring:

.Example
[source,mel]
----
// Returns 'Semančík'
'Ing. Radovan Semančík, PhD.'.parseFamilyName()
----

==== format.parseAdditionalName

`format.parseAdditionalName(string)` -> string +
`string.parseAdditionalName()` -> string

Parses provided string as a person's full name, returning the additional name (middle name) part.

This functions makes some assumptions regarding common structure of full names (e.g. the given name comes first and family name comes last), trying to match individual name components.

.Example
[source,mel]
----
// Returns 'Clerk'
format.parseAdditionalName('James Clerk Maxwell')
----

This function can also be invoked as a _member_ function on a string or polystring:

.Example
[source,mel]
----
// Returns 'Clerk'
'James Clerk Maxwell'.parseAdditionalName()
----

==== format.parseNickName

`format.parseNickName(string)` -> string +
`string.parseNickName()` -> string

Parses provided string as a person's full name, returning the nickname part.

This functions makes some assumptions regarding common structure of full names (e.g. the given name comes first and family name comes last), trying to match individual name components.

.Example
[source,mel]
----
// Returns 'The King'
format.parseNickName('Elvis "The King" Presley')
----

This function can also be invoked as a _member_ function on a string or polystring:

.Example
[source,mel]
----
// Returns 'The King'
'Elvis "The King" Presley'.parseNickName()
----

==== format.parseHonorificPrefix

`format.parseHonorificPrefix(string)` -> string +
`string.parseHonorificPrefix()` -> string

Parses provided string as a person's full name, returning the honorific prefix (titles before the name) part.

This functions makes some assumptions regarding common structure of full names (e.g. the given name comes first and family name comes last), trying to match individual name components.

.Example
[source,mel]
----
// Returns 'Ing.'
format.parseHonorificPrefix('Ing. Radovan Semančík, PhD.')
----

This function can also be invoked as a _member_ function on a string or polystring:

.Example
[source,mel]
----
// Returns 'Ing.'
'Ing. Radovan Semančík, PhD.'.parseHonorificPrefix()
----

==== format.parseHonorificSuffix

`format.parseHonorificSuffix(string)` -> string +
`string.parseHonorificSuffix()` -> string

Parses provided string as a person's full name, returning the honorific suffix (titles after the name) part.

This functions makes some assumptions regarding common structure of full names (e.g. the given name comes first and family name comes last), trying to match individual name components.

.Example
[source,mel]
----
// Returns 'PhD.'
format.parseHonorificSuffix('Ing. Radovan Semančík, PhD.')
----

This function can also be invoked as a _member_ function on a string or polystring:

.Example
[source,mel]
----
// Returns 'PhD.'
'Ing. Radovan Semančík, PhD.'.parseHonorificSuffix()
----

=== Log Extension

Prefix: `log`.

Log extension is used to record diagnostic information in system logs.
Functions of the `log` extensions can be used to record errors, as well as troubleshoot the expressions.

See also `debugDump` function, which can be useful when diagnosing content of a complex data structures.

==== log.info

`log.info(format, any)` -> any +
`log.info(format, list)` -> list

Records formatted message in system logs at `INFO` level.
The arguments are formatted into a log message.
Curly brackets (`{}`) act as placeholder for arguments in the message.

The function returns its argument as its output,
which enables placing of log functions into complex expression without breaking their flow.

.Example
[source,mel]
----
// Logs message 'The system is broken', returns 'system' as its output
log.info('The {} is broken', 'system')
----

.Example
[source,mel]
----
// Logs message 'The system is broken due to a bug', returns ['system', 'bug'] as its output
log.info('The {} is broken due to a {}', [ 'system', 'bug' ])
----

==== log.error

`log.error(format, any)` -> any +
`log.error(format, list)` -> list

Records formatted message in system logs at `ERROR` level.
The arguments are formatted into a log message.
Curly brackets (`{}`) act as placeholder for arguments in the message.

The function returns its argument as its output,
which enables placing of log functions into complex expression without breaking their flow.

.Example
[source,mel]
----
// Logs message 'The system is broken', returns 'system' as its output
log.error('The {} is broken', 'system')
----

.Example
[source,mel]
----
// Logs message 'The system is broken due to a bug', returns ['system', 'bug'] as its output
log.error('The {} is broken due to a {}', [ 'system', 'bug' ])
----

==== log.warn

`log.warn(format, any)` -> any +
`log.warn(format, list)` -> list

Records formatted message in system logs at `WARN` level.
The arguments are formatted into a log message.
Curly brackets (`{}`) act as placeholder for arguments in the message.

The function returns its argument as its output,
which enables placing of log functions into complex expression without breaking their flow.

.Example
[source,mel]
----
// Logs message 'The system is broken', returns 'system' as its output
log.warn('The {} is broken', 'system')
----

.Example
[source,mel]
----
// Logs message 'The system is broken due to a bug', returns ['system', 'bug'] as its output
log.warn('The {} is broken due to a {}', [ 'system', 'bug' ])
----

==== log.debug

`log.debug(format, any)` -> any +
`log.debug(format, list)` -> list

Records formatted message in system logs at `DEBUG` level.
The arguments are formatted into a log message.
Curly brackets (`{}`) act as placeholder for arguments in the message.

The function returns its argument as its output,
which enables placing of log functions into complex expression without breaking their flow.

.Example
[source,mel]
----
// Logs message 'The system is broken', returns 'system' as its output
log.debug('The {} is broken', 'system')
----

.Example
[source,mel]
----
// Logs message 'The system is broken due to a bug', returns ['system', 'bug'] as its output
log.debug('The {} is broken due to a {}', [ 'system', 'bug' ])
----

==== log.trace

`log.trace(format, any)` -> any +
`log.trace(format, list)` -> list

Records formatted message in system logs at `TRACE` level.
The arguments are formatted into a log message.
Curly brackets (`{}`) act as placeholder for arguments in the message.

The function returns its argument as its output,
which enables placing of log functions into complex expression without breaking their flow.

.Example
[source,mel]
----
// Logs message 'The system is broken', returns 'system' as its output
log.trace('The {} is broken', 'system')
----

.Example
[source,mel]
----
// Logs message 'The system is broken due to a bug', returns ['system', 'bug'] as its output
log.trace('The {} is broken due to a {}', [ 'system', 'bug' ])
----


=== LDAP Extension

Prefix: `ldap`.

LDAP extension is used to process LDAP-specific data formats, such _distinguished name_ (DN).

==== ldap.composeDn

`ldap.composeDn(list)` -> string

Creates a valid LDAP distinguished name from the wide range of components.
The resulting DN is well-formatted and properly escaped.
Note: the DN is not normalized. The case of the attribute names and white spaces are preserved.

.Example
[source,mel]
----
// Returns 'cn=foo,ou=baz,o=bar'
ldap.composeDn(['cn','foo','ou','baz','o','bar'])
----

==== ldap.composeDnWithSuffix

`ldap.composeDnWithSuffix(list)` -> string

Creates a valid LDAP distinguished name from the wide range of components, including a DN suffix at the end.
The resulting DN is well-formatted and properly escaped.
Note: the DN is not normalized. The case of the attribute names and white spaces are preserved.

.Example
[source,mel]
----
// Returns 'cn=foo,ou=baz,dc=example,dc=com'
ldap.composeDnWithSuffix(['cn','foo','ou','baz','dc=example,dc=com'])
----


==== ldap.hashPassword

`ldap.hashPassword(clearString, algorithm)` -> string +
`ldap.hashPassword(clearBytes, algorithm)` -> string

Hashes cleartext password in an (unofficial) LDAP password format.
The cleartext password can be provided as a string, polystring, or as bytes.
Supported algorithms: SSHA, SHA and MD5.

.Example
[source,mel]
----
// Returns '{SSHA}rxNYgQODi95h2bsjYXuBqvYz+I1gjgMkF9f0tA=='
ldap.hashPassword('password','SSHA')
----

==== ldap.determineSingleAttributeValue

`ldap.determineSingleAttributeValue(dn, attributeName, list(values))` -> string

Selects single value from many LDAP values, based on object DN.
E.g. value `bar` is selected from list of values `['foo','bar','baz']` because that value is present in DN `uid=bar,o=example`.

.Example
[source,mel]
----
// Returns 'bar'
ldap.determineSingleAttributeValue('uid=bar,o=example','uid', ['foo','bar','baz'])
----

=== Secret Extension

Prefix: `secret`.

Secret extension is used to interact with secret providers.

==== secret.resolveBinary

`secret.resolveBinary(provider, key)` -> string

Resolves a secret specified by the key, using a provider specified by its name.
Returns the secret in binary form (bytes).

.Example
[source,mel]
----
secret.resolveBinary('prov1', 'midpoint-ldap-admin')
----

==== secret.resolveString

`secret.resolveString(provider, key)` -> string

Resolves a secret specified by the key, using a provider specified by its name.
Returns the secret in string form.

.Example
[source,mel]
----
secret.resolveString('prov1', 'midpoint-ldap-admin')
----

==== secret.resolveProtectedString

`secret.resolveProtectedString(provider, key)` -> string

Resolves a secret specified by the key, using a provider specified by its name.
Returns the secret in protected string form for additional protection of the secret.

.Example
[source,mel]
----
secret.resolveProtectedString('prov1', 'midpoint-ldap-admin')
----

=== Object Extension

Object extensions provide convenience functions that allow easier processing of midPoint objects,
such as resources or shadows.

Functions in this language extension does not have a prefix.
They are invoked as a _member_ functions on appropriate value or variable containing midPoint object.

==== findItem

`object.findItem(path)` -> item

Returns an item to which the specified item path refers.

.Example
[source,mel]
----
// Returns a value of administrativeStatus property
focus.findItem('activation/administrativeStatus')
----

==== isEffectivelyEnabled

`object.isEffectivelyEnabled()` -> bool

Returns true if the object is effectively enabled.

If the object is not a `FocusType`, the method returns `true` (as there is no activation there).
For `FocusType` objects, it assumes that the object underwent standard computation and
`activation/effectiveStatus` is set.
If the `activation/effectiveStatus` is not present, the return value of the method is undefined.

.Example
[source,mel]
----
focus.isEffectivelyEnabled()
----

==== hasRelation

`assignment.hasRelation(relation)` -> bool

Returns true if `targetRef` of the assignment has specified relation.

Relation can be specified as string or qname.

Returns `false` in case that the assignment is `null`, or if it does not contain `targetRef`.

.Example
[source,mel]
----
assignment.hasRelation('owner')
----

==== has*Relation

`assignment.hasDefaultRelation()` -> bool +
`assignment.hasApproverRelation()` -> bool +
`assignment.hasConsentRelation()` -> bool +
`assignment.hasDeputyRelation()` -> bool +
`assignment.hasMetaRelation()` -> bool +
`assignment.hasOwnerRelation()` -> bool +
`assignment.hasRelatedRelation()` -> bool


Returns true if `targetRef` of the assignment has specified relation.

Returns `false` in case that the assignment is `null`, or if it does not contain `targetRef`.

.Example
[source,mel]
----
assignment.hasOwnerRelation()
----

==== isTarget

`assignment.isTarget(type)` -> bool

Returns true if `targetRef` of the assignment is of specified type.

Type can be specified as string or qname.

Returns `false` in case that the assignment is `null`, or if it does not contain `targetRef`.

.Example
[source,mel]
----
assignment.isTarget('RoleType')
----

==== isTarget*

`assignment.isTargetRole()` -> bool +
`assignment.isTargetOrg()` -> bool +
`assignment.isTargetService()` -> bool +
`assignment.isTargetPolicy()` -> bool +
`assignment.isTargetUser()` -> bool


Returns true if `targetRef` of the assignment is of specified type.

Returns `false` in case that the assignment is `null`, or if it does not contain `targetRef`.

.Example
[source,mel]
----
assignment.isTargetRole()
----

==== targetOid

`assignment.targetOid()` -> oid

Returns OID of targetRef of the assignment.

Returns `null` in case that the assignment is `null`, or if it does not contain `targetRef`.

.Example
[source,mel]
----
assignment.targetOid() == '9dbea12d-81dc-11f1-9bfe-9c6b00360713'
----

==== targetRelation

`assignment.targetRelation()` -> qname

Returns relation of targetRef of the assignment.

Returns `null` in case that the assignment is `null`, or if it does not contain `targetRef`.

.Example
[source,mel]
----
assignment.targetRelation() == 'owner'
----


==== targetType

`assignment.targetType()` -> qname

Returns type of targetRef of the assignment.

Returns `null` in case that the assignment is `null`, or if it does not contain `targetRef`.

.Example
[source,mel]
----
assignment.targetType() == 'RoleType'
----


==== connectorConfiguration

`resource.connectorConfiguration(propertyName)` -> list

Returns list of values of a resource connector configuration property specified by the argument.
The function is invoked as a member method on a variable containing midPoint resource.

Following expression returns a list containing values that are configured in a connector configuration property `host` in resource that is stored in the `resource` variable.

.Example
[source,mel]
----
resource.connectorConfiguration('host')
----

As most connector configuration properties as single-valued, this function is often combined with `single()` function:

.Example
[source,mel]
----
// Returns configured hostname as string, e.g. 'localhost'
single(resource.connectorConfiguration('host'))
----

==== primaryIdentifiers

`shadow.primaryIdentifiers()` -> list

Returns list of values of shadow primary identifier.
The function is invoked as a member method on a variable containing a shadow.

.Example
[source,mel]
----
// Returns list of values, e.g. ['381870aa-0731-11f1-b8d0-1baca68e8763']
shadow.primaryIdentifiers()
----

As most identifiers as single-valued, this function is often combined with `single()` function:

.Example
[source,mel]
----
// Returns string value, e.g. '381870aa-0731-11f1-b8d0-1baca68e8763'
single(shadow.primaryIdentifiers())
----

==== secondaryIdentifiers

`shadow.secondaryIdentifiers()` -> list

Returns list of values of shadow secondary identifier.
The function is invoked as a member method on a variable containing a shadow.

.Example
[source,mel]
----
// Returns list of values, e.g. ['uid=foo,ou=People,dc=example,dc=com']
shadow.secondaryIdentifiers()
----

As most identifiers as single-valued, this function is often combined with `single()` function:

.Example
[source,mel]
----
// Returns string value, e.g. 'uid=foo,ou=People,dc=example,dc=com'
single(shadow.secondaryIdentifiers())
----

=== MidPoint Extension

MidPoint extension provides functions that interact with midPoint, such as functions for reading midPoint objects from repository, searching for objects and so on.

Due to the nature of MEL, only functions that are safe and free of side effects are provided.
This means that the functions have read-only character.

==== midpoint.getLinkedShadow

`midpoint.getLinkedShadow(focus, resourceOid)` -> shadow +
`midpoint.getLinkedShadow(focus, resourceOid, repositoryObjectOnly)` -> shadow +
`midpoint.getLinkedShadow(focus, resourceOid, kind, intent)` -> shadow +
`midpoint.getLinkedShadow(focus, resourceOid, kind, intent, repositoryObjectOnly)` -> shadow

Returns a shadow on specified resource (`resourceOid`), which is linked to the specified focus.
The `repositoryOnly` parameter specifies whether the shadow has to be retrieved only from midPoint repository (`true`), or whether the data corresponding to the shadow can be retrieved from the resource (`false`, default).
Shadow _kind_ and _intent_ can be specified as well.
Null values of resource oid, kind, and intent mean "any".

This function assumes that at most one such shadow is linked to the focus.
If more than one shadow is linked, function behavior is unspecified.

.Example
[source,mel]
----
// Returns shadow on resource specified by OID, which has account kind and any intent.
midpoint.getLinkedShadow(focus, '5b1b59f6-805c-11f1-be6c-e3515ff454a8', 'account', null)
----

==== midpoint.getLinkedShadows

`midpoint.getLinkedShadows(focus, resourceOid)` -> list(shadow) +
`midpoint.getLinkedShadows(focus, resourceOid, repositoryObjectOnly)` -> list(shadow)

Returns a list of shadows on specified resource (`resourceOid`), which is linked to the specified focus.
The `repositoryOnly` parameter specifies whether the shadow has to be retrieved only from midPoint repository (`true`), or whether the data corresponding to the shadow can be retrieved from the resource (`false`, default).

.Example
[source,mel]
----
// Returns list of shadows on resource specified by OID
midpoint.getLinkedShadows(focus, '5b1b59f6-805c-11f1-be6c-e3515ff454a8')
----

==== midpoint.getManagersOids

`midpoint.getManagersOids(user)` -> list(string)

Returns a list of OIDs of user's managers.
Formally, for each Org O which this user has (any) relation to, all managers of O are added to the result.

.Example
[source,mel]
----
midpoint.getManagersOids(focus)
----

==== midpoint.getManagersOidsExceptUser

`midpoint.getManagersOidsExceptUser(user)` -> list(string)

Returns a list of OIDs of user's managers.
Formally, for each Org O which this user has (any) relation to, all managers of O are added to the result.
The list excludes OID of the user itself.

.Example
[source,mel]
----
midpoint.getManagersOidsExceptUser(focus)
----

==== midpoint.getObject

`midpoint.getObject(type, oid)` -> object

Returns object for provided OID.
It retrieves the object from an appropriate source for an object type
(e.g. internal repository, resource or both), merging data as necessary,
processing any policies, caching mechanisms, etc.

Object type can be specified as qname or as string.

.Example
[source,mel]
----
midpoint.getObject('user', '06407948-8061-11f1-96a1-631cb39ca677')
----

==== midpoint.getObjectsInConflictOnPropertyValue

`getObjectsInConflictOnPropertyValue(object, propertyPath, propertyValue, getAllConflicting)` -> list(object)

Returns a list of objects that are conflicting with the specified object on specified property.
The `propertyPath` parameter specifies xref:/midpoint/reference/concepts/item-path/[item path] of the item to be checked.
The `propertyValue` specifies the candidate value of that item.
Uniqueness of that value will be checked.
The `getAllConflicting` boolean parameter specifies whether to get all conflicting objects (`true`) or just the first one (`false`).

The object specified as the first parameter is used to determine type of objects to look for.
It is also always filtered out of list of conflicting objects.

.Example
[source,mel]
----
// Check for all objects that conflict on emailAddress property with the current focus
midpoint.getObjectsInConflictOnPropertyValue(focus, 'emailAddresses', focus.emailAddress, true)
----

==== midpoint.getOrgByName

`midpoint.getOrgByName(name)` -> object

Returns organization object (org) specified by name.

.Example
[source,mel]
----
midpoint.getOrgByName('F00101')
----

==== midpoint.hasLinkedObjectOnResource

`midpoint.hasLinkedObjectOnResource(resourceOid, kind,  intent)` -> boolean

Returns `true` if current focus has link to resource object on specified resource.

.Example
[source,mel]
----
midpoint.hasLinkedObjectOnResource('5b1b59f6-805c-11f1-be6c-e3515ff454a8', 'account', 'default')
----

==== midpoint.isFocusActivated

`midpoint.isFocusActivated()` -> boolean

Returns `true` if current clockwork operation brings the focus into existence, being effectively enabled, assuming previously it was either non-existent or effectively disabled.

.Example
[source,mel]
----
midpoint.isFocusActivated()
----

==== midpoint.isFocusDeactivated

`midpoint.isFocusDeactivated()` -> boolean

Returns `true` if current clockwork operation deletes or effectively disables the focus,
assuming previously it existed and was effectively enabled.

.Example
[source,mel]
----
midpoint.isFocusDeactivated()
----

==== midpoint.isFocusDeleted

`midpoint.isFocusDeleted()` -> boolean

Returns `true` if current clockwork operation deletes the focus.

.Example
[source,mel]
----
midpoint.isFocusDeleted()
----

==== midpoint.isUniquePropertyValue

`isUniquePropertyValue(object, propertyPath, propertyValue)` -> boolean

Checks uniqueness of property value.
Returns true if specified property value is unique.
Returns false if an object exists, conflicting with the specified object on specified property.

The `propertyPath` parameter specifies xref:/midpoint/reference/concepts/item-path/[item path] of the item to be checked.
The `propertyValue` specifies the candidate value of that item.
Uniqueness of that value will be checked.

.Example
[source,mel]
----
midpoint.isUniquePropertyValue(focus, 'emailAddresses', focus.emailAddress)
----

==== midpoint.isUniqueAccountValue

`isUniqueAccountValue(resource, shadow, attributeName, attributeValue)` -> boolean

Checks uniqueness of account attribute value.
Returns true if specified attribute value is unique.
Returns false if an account exists, conflicting with the specified shadow on specified attribute.

The `resource` and `shadow` parameters specify resource and shadow objects (usually present in `resource` and `projection` variables during computation).
The `attributeName` parameter specifies name of account attribute to be checked.
The `attributeValue` specifies the candidate value of that attribute.
Uniqueness of that value will be checked.

.Example
[source,mel]
----
midpoint.isUniqueAccountValue(resource, projection, 'uid', 'foobar')
----

==== midpoint.resolveReference

`midpoint.resolveReference(ref)` -> object

Resolves specified reference, returning an object that the reference references.
Error is raised in case that the referenced object does not exist.

.Example
[source,mel]
----
// Returns shadow linked to the current focus (assuming there is only one link)
midpoint.resolveReference(single(focus.linkRef))
----

==== midpoint.resolveReferenceIfExists

`midpoint.resolveReferenceIfExists(ref)` -> object

Resolves specified reference, returning an object that the reference references.
If the referenced object does not exist, null is returned.

.Example
[source,mel]
----
// Returns shadow linked to the current focus (assuming there is only one link)
midpoint.resolveReferenceIfExists(single(focus.linkRef))
----

==== midpoint.searchObjects

`midpoint.searchObjects(type, filter)` -> list(object)

Searches through all object of a specified type.
Returns a list of objects that match search criteria.

The `type` parameter may be a string (e.g. `UserType`) or QName.
The `filter` parameter is a string containing search filter specified in xref:/midpoint/reference/concepts/query/midpoint-query-language/[midPoint query language (MQL)].

.Example
[source,mel]
----
midpoint.searchObjects('UserType', 'name = \'jack\'')
----

==== midpoint.searchShadowOwner

`midpoint.searchShadowOwner(oid)` -> object

Returns the Focus object representing owner of specified shadow.
The function may return `null` if there is no owner specified for the shadow.

.Example
[source,mel]
----
midpoint.searchShadowOwner('3699defe-8133-11f1-b274-5b07c17a83bc')
----


== Timestamps and Durations

Timestamps can be constructed by using the `timestamp()` function.
The `timestamp()` constructor expect a string argument, specifying a timestamp formatted according to RFC 3339/ISO8601 format.

[source,mel]
----
timestamp('2026-03-15T12:34:56Z')
----

Similarly, there is a `duration()` constructor:

[source,mel]
----
duration('1h30m')
duration('-300ms')
----

The duration string used by CEL is not following any standardized format.
It is built on common conventions, where characters `h`, `m`, `s`, `ms`, `us` and `ns` specifying units of time.

CEL timestamps follow _protocol buffer_ convention, which means that the timestamps are kept as a combination of _epoch second_ and _nanosecond fraction_, referring to UNIX epoch (00:00:00 UTC on January 1, 1970).
There is no timezone information in timestamps, which means they are effectively fixed to UTC (`Z`) timezone.
Functions that work with timestamps in a timezone-specific manner (e.g. `atStartOfDay()`) assume system timezone as default, allowing optional explicit specification of a time zone.
Timezone specification follows _IANA Time Zone Database_ (a.k.a _Olson_ or _tz database_).

Timestamps and durations can be used in some arithmetic and comparison operations:

[source,mel]
----
timestamp('2026-03-15T12:34:56Z') + duration('1h30m')
timestamp('2026-03-15T12:34:56Z') < timestamp('2026-03-15T14:30:00Z')
----

Conversion of timestamp to integer (e.g. using `int(ts)`) renders the epoch second.

Timestamp referring to the "current" time instant is available in variable `now`.
The value of this variable refers to an approximate moment of the start of expression evaluation.
Value of this variable is fixed through the evaluation of the expression.

.Reference time vs "now"
TIP: Some expression provide a xref:/midpoint/reference/expressions/mappings/#time-constraints[reference time] in `referenceTime` variable.
This timestamp is different than the one provided in `now` variable.
Variable `now` always contains "current" time instant, which is usually a time when an expression evaluation started.
On the other hand, `referenceTime` variable contains a timestamp which is relevant for evaluation of a particular mapping, such as a timestamp when relevant object was disabled.
When dealing with time-constrained mappings, use of `referenceTime` is usually correct and use of `now` is usually wrong.

=== atStartOfDay

`timestamp.atStartOfDay()` -> timestamp +
`timestamp.atStartOfDay(timezone)` -> timestamp

Modifies the timestamp to refer to the start of the day.
Resulting timestamp refers to the same day as the argument timestamp, however the time is reset to the earliest time at that day.

Optional time zone can be specified.
If no timezone is specified, system default timezone is assumed.

Following example assume that system default time zone is UTC.

.Example
[source,mel]
----
timestamp('2026-02-11T12:34:56Z').atStartOfDay()    // Returns timestamp 2026-02-11T00:00:00Z
timestamp('2026-02-11T12:34:56Z').atStartOfDay('Z') // Returns timestamp 2026-02-11T00:00:00Z
----

=== atEndOfDay

`timestamp.atEndOfDay()` -> timestamp +
`timestamp.atEndOfDay(timezone)` -> timestamp

Modifies the timestamp to refer to the end of the day.
Resulting timestamp refers to the same day as the argument timestamp, however the time is set to the latest time at that day.

Optional time zone can be specified.
If no timezone is specified, system default timezone is assumed.

Following example assume that system default time zone is UTC.

.Example
[source,mel]
----
timestamp('2026-02-11T12:34:56Z').atEndOfDay()    // Returns timestamp 2026-02-11T23:59:59Z
timestamp('2026-02-11T12:34:56Z').atEndOfDay('Z') // Returns timestamp 2026-02-11T23:59:59Z
----

=== getDate

`timestamp.getDate()` -> int +
`timestamp.getDate(timezone)` -> int

Returns the day of the month (starting with 1) from a timestamp.

Optional time zone can be specified.
If no timezone is specified, UTC is assumed (because CEL stores timestamps in UTC).

.Example
[source,mel]
----
timestamp('2026-02-11T12:34:56Z').getDate()       // Returns 11
timestamp('2026-02-11T12:34:56Z').getDate('Z')    // Returns 11
----

=== getDayOfMonth

`timestamp.getDayOfMonth()` -> int +
`timestamp.getDayOfMonth(timezone)` -> int

Returns the day of the month (starting with 0) from a timestamp.

Optional time zone can be specified.
If no timezone is specified, UTC is assumed (because CEL stores timestamps in UTC).

.Example
[source,mel]
----
timestamp('2026-02-11T12:34:56Z').getDayOfMonth()     // Returns 10
timestamp('2026-02-11T12:34:56Z').getDayOfMonth('Z')  // Returns 10
----


=== getDayOfWeek

`timestamp.getDayOfWeek()` -> int +
`timestamp.getDayOfWeek(timezone)` -> int

Returns the day of the week (starting with 0 for Sunday) from a timestamp.

Optional time zone can be specified.
If no timezone is specified, UTC is assumed (because CEL stores timestamps in UTC).

.Example
[source,mel]
----
timestamp('2026-02-11T12:34:56Z').getDayOfWeek()     // Returns 3
timestamp('2026-02-11T12:34:56Z').getDayOfWeek('Z')  // Returns 3
----

=== getDayOfYear

`timestamp.getDayOfYear()` -> int +
`timestamp.getDayOfYear(timezone)` -> int

Returns the day of the year (starting with 0) from a timestamp.

Optional time zone can be specified.
If no timezone is specified, UTC is assumed (because CEL stores timestamps in UTC).

.Example
[source,mel]
----
timestamp('2026-02-11T12:34:56Z').getDayOfYear()     // Returns 40
timestamp('2026-02-11T12:34:56Z').getDayOfYear('Z')  // Returns 40
----

=== getEpochMillisecond

`timestamp.getEpochMillisecond()` -> int

Returns the number of milliseconds since the UNIX epoch.

.Example
[source,mel]
----
timestamp('2026-07-15T12:34:56.987Z').getEpochMillisecond()  // Returns 1784118896987
----

=== getEpochSecond

`timestamp.getEpochSecond()` -> int

Returns the number of seconds since the UNIX epoch.

.Example
[source,mel]
----
timestamp('2026-07-15T12:34:56.987Z').getEpochSecond()  // Returns 1784118896
----

=== getFullYear

`timestamp.getFullYear()` -> int +
`timestamp.getFullYear(timezone)` -> int

Returns the year from a timestamp.

Optional time zone can be specified.
If no timezone is specified, UTC is assumed (because CEL stores timestamps in UTC).

.Example
[source,mel]
----
timestamp('2026-02-11T12:34:56Z').getFullYear()     // Returns 2026
timestamp('2026-02-11T12:34:56Z').getFullYear('Z')  // Returns 2026
----

=== getHours

`timestamp.getHours()` -> int +
`timestamp.getHours(timezone)` -> int +
`duration.getHours()` -> int

Returns hours from a timestamp or converts a duration to hours.

Optional time zone can be specified.
If no timezone is specified, UTC is assumed (because CEL stores timestamps in UTC).

.Example
[source,mel]
----
timestamp('2026-02-11T12:34:56Z').getHours()     // Returns 12
timestamp('2026-02-11T12:34:56Z').getHours('Z')  // Returns 12
duration('2h').getHours()                        // Returns 2
----

=== getMilliseconds

`timestamp.getMilliseconds()` -> int +
`timestamp.getMilliseconds(timezone)` -> int +
`duration.getMilliseconds()` -> int

Returns milliseconds from a timestamp or duration.

Optional time zone can be specified.
If no timezone is specified, UTC is assumed (because CEL stores timestamps in UTC).

.Example
[source,mel]
----
timestamp('2026-02-11T12:34:56.789Z').getMilliseconds()     // Returns 789
timestamp('2026-02-11T12:34:56.789Z').getMilliseconds('Z')  // Returns 789
duration('1.234s').getMilliseconds()                        // Returns 234
----

=== getMinutes

`timestamp.getMinutes()` -> int +
`timestamp.getMinutes(timezone)` -> int +
`duration.getMinutes()` -> int

Returns minutes from a timestamp or converts a duration to minutes.

Optional time zone can be specified.
If no timezone is specified, UTC is assumed (because CEL stores timestamps in UTC).

.Example
[source,mel]
----
timestamp('2026-02-11T12:34:56Z').getMinutes()     // Returns 34
timestamp('2026-02-11T12:34:56Z').getMinutes('Z')  // Returns 34
duration('2h').getMinutes()                        // Returns 120
----

=== getMonth

`timestamp.getMonth()` -> int +
`timestamp.getMonth(timezone)` -> int

Returns the month (starting with 0 for January) from a timestamp.

Optional time zone can be specified.
If no timezone is specified, UTC is assumed (because CEL stores timestamps in UTC).

.Example
[source,mel]
----
timestamp('2026-02-11T12:34:56Z').getMonth()     // Returns 1
timestamp('2026-02-11T12:34:56Z').getMonth('Z')  // Returns 1
----

=== getNanos

`timestamp.getNanos()` -> int

Returns the number of fractional nanoseconds following the epoch second.
This value measures the total number of nanoseconds from the second returned by getEpochSecond.

.Example
[source,mel]
----
timestamp('2026-07-15T12:34:56.987Z').getNanos()  // Returns 987000000
----

=== getSeconds

`timestamp.getSeconds()` -> int +
`timestamp.getSeconds(timezone)` -> int +
`duration.getSeconds()` -> int

Returns seconds from a timestamp or converts a duration to seconds.

Optional time zone can be specified.
If no timezone is specified, UTC is assumed (because CEL stores timestamps in UTC).

.Example
[source,mel]
----
timestamp('2026-02-11T12:34:56Z').getSeconds()     // Returns 56
timestamp('2026-02-11T12:34:56Z').getSeconds('Z')  // Returns 56
duration('2m').getSeconds()                        // Returns 120
----

=== timestamp.longAgo

`timestamp.longAgo()` -> timestamp

Returns timestamp that is referring to a time long, long ago, too far in the past.
This timestamp can be used to make sure that no practical timestamp in the system is earlier that this moment in time.

Current implementation returns the start of the epoch used by the CEL implementation, which is 1^st^ January 1970.
However, as different time schemes are based on different mechanisms and epochs, the value returned by `timestamp.longAgo()` may change in the future, to be sure that the returned timestamp is always earlier than all other practical timestamps in the system.

.Example
[source,mel]
----
timestamp.longAgo()    // Returns timestamp 1970-01-01T00:00:00Z
----


== Polystrings

xref:/midpoint/reference/concepts/polystring/[Polystrings] are midPoint data structured used to store string values, together with their normalized and localized variants.

Polystrings are represented as simple structured objects in MEL.
Individual parts of polystring can be accessed by using the usual _dot notation_:

[source,mel]
----
polystring.orig
polystring.norm
----

In MEL, polystrings behave just like strings.
E.g. polystrings can be easily compared or concatenated with strings:

[source,mel]
----
polystring == 'foo'
'Hello ' + polystring
----

In such cases, the `orig` part of the polystring is used in these string-like operations.
If the normalized part of polystring is to be used, it must be explicitly referenced:

[source,mel]
----
'X' + polystring.norm
----

NOTE: The localization functionality of polystrings is not available in MEL at this time.

== Protected Strings

xref:/midpoint/reference/concepts/protectedstring/[Protected strings] are midPoint data structure meant to provide extra protection to string data.
They are usually used to contain passwords, API keys and similar sensitive data.

Unlike polystrings, protected strings _do not_ behave like strings in MEL.
This is an intentional behavior to provide additional protection against unintentional leakage of the data, e.g. in logfiles.
We do not want string functions (such as substring) to unintentionally reveal content of a protected string.
If you need to do string operations on a protected string, you have to explicitly decrypt it first.

[source,mel]
----
protectedString.decrypt()
----

Ordinary string value can be encrypted, to gain additional protection of a _protected string_:

[source,mel]
----
string.encrypt()
----

=== decrypt

`protectedString.decrypt()` -> string

Decrypts value of protected string, returning cleartext value as string.

=== encrypt

`string.encrypt()` -> protectedString

Encrypts a string value, creating protected string.
Works with strings as well as polystrings.


== QNames

MEL can work with QNames as simple structured objects.
QNames can be constructed using `qname()` function:

[source,mel]
----
qname(namespace, localPart)
qname(localPart)
----

Parts of a qname can be accessed using the _dot notation_:

[source,mel]
----
x.namespaceURI
x.localPart
----

QNames can be used instead of strings to access structured midPoint data when using _index operator_ (`[]`):

[source,mel]
----
focus.extension[qname('http://example.com/ns', 'ship')]
----

QNames can be compared with strings.
Namespace part is ignored in such case.

[source,mel]
----
qname('http://example.com/ns', 'ship') == 'ship'    // Returns true
----

Fully-qualified qnames can be compared with qnames without a namespace.
Namespace part is ignored in such case.

[source,mel]
----
qname('http://example.com/ns', 'ship') == qname(null, 'ship')    // Returns true
----

=== qname

`qname(namespaceURI, localPart)` -> qname +
`qname(localPart)` -> qname

Creates a qname value.
When namespace is not specified, qname with unspecified (null) namespace is created.

=== encrypt

`string.encrypt()` -> protectedString

Encrypts a string value, creating protected string.
Works with strings as well as polystrings.


== Structured Data

Object structure can be accessed in mel using the selection operator (`.`) (a.k.a. _dot convention_).
Following expression returns value of `name` property of the object stored in `focus` xref:/midpoint/reference/expressions/variables/[variable].

[source,mel]
----
focus.name
----

Access to structured data can be nested.
Following code returns value of `administrativeStatus` property located inside `activation` container, located in user object stored in variable `focus`.

[source,mel]
----
focus.activation.administrativeStatus
----

Alternatively, _index operator_ (`[]`) can be used to access structured data:

[source,mel]
----
focus['name']
----

Structure of the data is dictated by xref:/midpoint/reference/schema/common-data-model/[midPoint schema].

Access to extension items of objects is facilitated by an `extension` container.
E.g. extension attribute `ship` of the object stored in the `focus` variable can be accessed as follows:

[source,mel]
----
focus.extension.ship
focus.extension['ship']
----

When working with midPoint (prism) objects, both strings and qnames can be used as indexes.

Similar approach works with xref:/midpoint/architecture/concepts/shadow/[shadow attributes] as well:

[source,mel]
----
projection.attributes.cn
projection.attributes['cn']
----

The `isPresent()` function can be used for tests regarding presence of value:

[source,mel]
----
isPresent(foo)
----

The `isPresent()` function returns true value in case that the variable `foo` has value, i.e. it is not null.
The `isPresent()` function works on plain data (variables) as well as structured data:

[source,mel]
----
isPresent(focus.fullName)
----

Note that some MEL operators may not be able to work with `null` values.
E.g. addition operator (`+`) when dealing with numeric values.

=== Optional Values in Structured Data

The data structures are seldom complete.
In usual case, the data are only partially populated.
E.g. a focus may not have activation at all, and objects with `administrativeStatus` explicitly defined are quite rare.
MEL _selection_ operator (`.`) is null-safe.
The following expression does not fail when variable `focus` does not contain any value, or in case that there is no `activation` container or `administrativeStatus` property.
In such cases the expression evaluates to `null` without any error.

[source,mel]
----
focus.activation.administrativeStatus
----

The `isPresent()` function can be used for tests regarding presence of items in structured objects and maps:

[source,mel]
----
isPresent(focus.activation.administrativeStatus)
----

CEL provides the `has()` macro, which can also be used for tests regarding presence of items in structured objects and maps:

[source,mel]
----
has(focus.fullName)
----

However, the `has()` macro cannot be used to check presence of plain values (e.g. variables).
Therefore, as a rule of thumb, it is recommended to use `isPresent()` function instead of `has()` macro.

See xref:#null-and-optional-values[Null and Optional Values section] below.

=== Item QNames

QNames can be used instead of strings to access the data when using _index operator_ (`[]`):

[source,mel]
----
focus.extension[qname('http://example.com/ns', 'ship')]
----

Explicit use of QNames is usually not necessary.
However, it may be required in some cases, e.g. when several schema extensions are using items with the same local name.

=== Item Path

xref:/midpoint/reference/concepts/item-path/[Item path] can be used to locate an item in an object by using the `find()` function:

[source,mel]
----
focus.find('activation/administrativeStatus')
----

== Null and Optional Values

MEL data structures and functions are generally null-safe.
I.e. expression authors do not need to worry about passing `null` values into functions, or even invoking member functions on `null` values.
MEL interpreter substitutes a reasonable return value in such a case, which is usually also `null` value.
However, some functions may return empty string (`''`), zero (`0`) or appropriate boolean value instead.

Navigation of structured data is also null-safe.
See section xref:#optional-values-in-structured-data[Optional Values in Structured Data] for more details.

However, there is one unpleasant detail regarding `null` literal.
CEL interpreter is regarding `null` as a special data type.
The `null` literal is considered to be statically-typed, which may cause problems in some cases.
The conditionals (`?:`) are the most notorious (see xref:../tips[] for details).
As a rule of thumb, use `nil` instead of `null` literal if your code does not work with `null`.
The `nil` provides a dynamically-typed null value, which usually fixes the situation.

See xref:../null[] for details.

== Custom Function Libraries

Functions from custom xref:/midpoint/reference/expressions/function-libraries/[expression function libraries] can be easily invoked from MEL.
The function can be invoked by combining name of the library with name of the function.
Following expression is invoking function `determineOrg()` from function library `mylib`, using `foo` as arguments.

[source,mel]
----
mylib.determineOrg(foo)
----

The expression above is using simplified notation, which works for custom function that has at most one argument.
As arguments of functions in custom function libraries are referencing the parameters by _name_ rather than their position, functions that have more than one argument need to use _map_ to specify parameter values:

[source,mel]
----
mylib.generateIdentifier({ 'prefix': 'X', 'length': 10 })
----

The expression above invokes custom function `generateIdentifier()` with two parameters.
Parameter `prefix` with value `X` and parameter `length` with value `10`.

NOTE: Functional expression languages such as MEL/CEL are based on an assumption that functions as well as other operations are _free of any side effects_.
I.e. the functions are supposed to be _idempotent_: no matter how many times they are executed, they produce the same result.
This feature is important for consistency of expression evaluation, as the sequence of evaluation of individual functions or other operations is determined by CEL runtime.
It is important to keep that in mind when creating custom function libraries that are meant to be invoked by MEL expressions.
As a rule of thumb, the library function should _not_ make any modifications or change the state of midPoint repository.

== Miscellaneous Notes

* MEL expression can span multiple lines, which provides opportunity for indentation to increase readability.

* Two slashes (`//`) can be used to add comments in expressions.
The slashes start a comment, which ends at the end of line.

* Deprecated variables such as `user`, `account` and `shadow` are not available in MEL.
Use variables such as `focus` and `projection` instead.

== Expression Profiles

xref:/midpoint/reference/expressions/expressions/profiles/[Expression profiles] are applied to MEL expressions in the same way as they are applied to any other expression in midPoint.
E.g. the following expression profile configuration can be used to deny access to all scripting expression evaluators except for MEL, applying `script-mel-restricted` permission profile to MEL expressions:

[source,xml]
----
<systemConfiguration>
    ...
    <expressions>
        <expressionProfile>
            ...
            <evaluator>
                <type>script</type>
                <decision>deny</decision>
                <script>
                    <language>http://midpoint.evolveum.com/xml/ns/public/expression/language#mel</language>
                    <decision>allow</decision>
                    <typeChecking>true</typeChecking>
                    <permissionProfile>script-mel-restricted</permissionProfile>
                </script>
            </evaluator>
            ...
        </expressionProfile>
        ...
    </expressions>
    ...
</systemConfiguration>
----

MEL expression language is considered to be _secure_ in such a way that no MEL expression can compromise the platform on which it is running.
However, this does not mean that all the functionality available to MEL expressions is harmless.
Some MEL language extensions and custom function libraries may reveal sensitive information.
E.g. function `secret.resolveString()` has access to secret providers, which include credential vaults.
Functions in the `midpoint.*` language extension have read access to midPoint repository, which may reveal sensitive information.
Therefore, common recommendation is to use _permission profile_ to limit access to MEL language extensions that are not strictly necessary.
The `package` clause of a _permission profile_ can be used to control access to individual MEL language extensions, using their name (prefix).
Following configuration allows access to all MEL extensions, except for `midpoint` and `secret` extensions.

[source,xml]
----
<systemConfiguration>
    ...
    <expressions>
        ...
        <permissionProfile>
            <identifier>script-mel-restricted</identifier>
            <decision>allow</decision>
            <package>
                <name>midpoint</name>
                <description>midpoint.* MEL language extension</description>
                <decision>deny</decision>
            </package>
            <package>
                <name>secret</name>
                <description>secret.* MEL language extension</description>
                <decision>deny</decision>
            </package>
        </permissionProfile>
        ...
    </expressions>
    ...
</systemConfiguration>
----

// TODO: default expression profiles in 4.11

== MEL and CEL

MidPoint Expression Language (MEL) is based on link:https://cel.dev/[Common Expression Language], extended with midPoint-specific features, functions and libraries.
MEL is using basic CEL syntax, operators, basic functions and even some extensions (e.g. regexp).
However, as CEL is oriented towards the _protocol buffers_ world, MEL provides access to midPoint objects that are based on xref:/midpoint/devel/prism/[Prism].
Moreover, MEL is extending the basic CEL environment with midPoint data types such as xref:/midpoint/reference/concepts/polystring/[polystring] and xref:/midpoint/reference/concepts/protectedstring/[protected string] as well as variety of functions that adapt the language for midPoint environment.

Simple expressions in MEL and CEL are going to be the same.
However, MEL is expanding on CEL, especially with convenience functions and much better support for nullable values, MEL expressions have a very distinct "midPointish" look and feel.

== MEL and Java/Groovy

MEL is a secure expression language with a distinct functional character.
This makes MEL very _unlike_ Java and Groovy.
MEL is not suitable for implementing complex algorithms.
This is not a purpose of MEL.
MEL is meant to create mappings and customizations, including quite complex customization.
However, the way MEL is doing that is very different from the imperative Java/Groovy world, and it will require some time for adjustments.
See xref:../migration/[MEL Migration Guide] for more information.

MEL is meant to create expressions that are _secure_, which means that MEL needs to be limited by design.
Java classes and libraries are intentionally _not_ exposed to MEL expressions.
MEL expressions are living in their own safe little world.

// TODO: later: types and conversions

// TODO: cel.bind(var, val, expression)

// TODO: midpoint.* extension

== See Also

* xref:../introduction/[MidPoint Expression Language Introduction]
* xref:../migration/[MEL Migration Guide]
* link:https://cel.dev/[Common Expression Language]
* link:https://github.com/google/cel-spec/blob/master/doc/langdef.md[CEL Language Specification]
