---
midpoint-feature: expression-mel
doc-type: config
---
= MidPoint Expression Language Tips and Recommendations
:page-nav-title: Tips
:page-upkeep-status: green
:page-toc: top

xref:../introduction/[MidPoint Expression Language (MEL)] is an expression language, designed to support customization of midPoint functionality in an easy-to-use and secure way.
This page lists miscellaneous tips and recommendations for writing MEL expressions.

== Conditions

MEL as well as CEL are expression languages with distinct functional character.
There are no _commands_ in such expression languages.
Every clause is an operator or a function.
Therefore, the classic _if-then-else_ construct does not exist in a form of command.
Conditional operator (`?:`) is used instead.

.Conditional operator
[source,mel]
----
condition ? true-branch : false-branch
----

Short MEL expressions are usually written on a single line.
However, complicated expressions can be very long.
The expression can be split to several lines in MEL.
This can be used to the advantage, especially when the expression contains conditionals:

.Conditional operator indent
[source,mel]
----
condition
    ? true-branch
    : false-branch
----

While the practice of indenting the code can bring clarity, the indents are still considered just an ordinary white space and have no special semantic meaning.
This can become slightly confusing especially when nested conditional operators are used.

.Nested conditionals: error
[source,mel]
----
condition-A
    ? condition-B
        ? true-branch-B
        : false-branch-B
    : false-branch-A
----

The CEL engine cannot compile such code.
Nested conditionals have to be enclosed in parentheses:

.Nested conditionals: correct
[source,mel]
----
condition-A
    ? ( condition-B
        ? true-branch-B
        : false-branch-B
    )
    : false-branch-A
----

CEL conditionals tend to be quite strict.
Strictly speaking, the conditional operator expects the same data types in both branches.
This can be painful especially when strings are combined with polystrings:

.Wrong use of conditional with strings and polystrings
[source,mel]
----
fullName == null ? 'John Doe' : fullName
----

Such expression leads to an error, as the data types in the branches do not match.
While `'John Doe'` is a string, the value of `fullName` variable is polystring.
Quick fix would be to explicitly convert polystring to string:

.Quick fix of conditional with strings and polystrings
[source,mel]
----
fullName == null ? 'John Doe' : stringify(fullName)
----

However, the best approach is to avoid using conditionals whenever possible.
For example, function `default()` provides very elegant way to specify default value:

.Correct use of default() function to specify default value
[source,mel]
----
default(fullName, 'John Doe')
----

The `default()` function takes care of everything, null checks, data conversion and all other details.

== Formatting

// TODO: basic formatting using + (somehow null safe)

Use xref:../specification/#format[`format()`] function for advanced string formatting:

.Advanced string formatting
[source,mel]
----
'%s:%s'.format([foo, bar])
----

NOTE: The `format()` function is null-safe in the Java way.
I.e. the `format()` function will not fail if a null argument is provided as input.
However, the null values of are rendered as string `null`.


When formatting timestamps, use specialized timestamp functions, such as xref:../specification/#format-strftime[`format.strftime()`]:

.Timestamp formatting
[source,mel]
----
// Returns formatted time, e.g. `11/02/26 09:32:15`
format.strftime(ts, '%d/%m/%Y %H:%M:%S')
----

Overall, the xref:../specification/#format-extension[format extension] of MEL provides may useful functions for string formatting and parsing.

== Single-Valued and Multi-Valued Data

CEL and therefore MEL makes a strict distinction between single-valued (scalar) and multi-valued (list/array) data.
Functions often require multi-valued (list) arguments.
Also, some functions return list values.
Therefore, it is often necessary to convert single-valued and multi-valued (list) data.

Correct method to convert list (multi-valued data) to a single value is to use `single()` function:

.Converting list to single value
[source,mel]
----
single(['foo'])     // Returns 'foo'
----

Primary purpose of `single()` function is conversion of list to single value.
Moreover, it does the conversion in a safe way.
Error is raised in case that the argument is a list with more than one value.
The `single()` function returns `null` value in a robust way, handling all the valid argument values such as empty list, `null` and empty optional.
On the other hand, other methods (such as `x[0]`) does not provide such robustness.

Correct method to convert single value to list (multi-valued data) is use of `list()` function:

.Converting single value to list
[source,mel]
----
list('foo')       // Returns ['foo']
list(['foo'])     // Returns ['foo']
----

The `list()` function always returns list.
If a single-valued (scalar_ argument is provided, it returns a single-element list containing that argument.
If a list is provided as argument, the same list is returned.
Hence, the `list()` function can be used to make sure that list is provided in context where list arguments are required.

== See Also

* xref:../specification/[MidPoint Expression Language Specification]
* xref:../troubleshooting/[Troubleshooting MidPoint Expression Language]
