= Task
// NGDe2 redirect
:page-moved-from: /midpoint/architecture/concepts/task/
:page-wiki-name: Task
:page-wiki-id: 13074801
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2013-12-03T17:16:26.193+01:00
:page-wiki-metadata-modify-user: peterkortvel@gmail.com
:page-wiki-metadata-modify-date: 2016-02-20T15:41:50.298+01:00


== Introduction

The Task structure provides a context to most midPoint operations and functions.
It contains contextual information such as identity of the user that invoked the operation, it contains security context, it may be bound to scheduling data and so on.
It also holds the xref:/midpoint/architecture/concepts/operation-result/[operation result] data structure.
Each "business" operation in midPoint should be executed in a context of a task.


== Task Manager

Tasks are managed by xref:/midpoint/reference/tasks/task-manager/[Task Manager] component.
The task manager creates the tasks and manages the lifecycle of tasks.
Task manager can create broad range of tasks from lightweight synchronous tasks to a persistent asynchronous and scheduled tasks.
See the xref:/midpoint/reference/tasks/task-manager/[Task Manager] page for more details.


== Task Usage

.Creating a lightweight task instance
[source,java]
----
Task task = taskManager.createTaskInstance(MyClass.class.getName() + ".myOperation");
OperationResult result = task.getResult();
----


== See Also

* xref:/midpoint/reference/tasks/task-manager/[Task Manager]
* xref:/midpoint/reference/tasks/activities/[Activities]
