= REST API
:page-wiki-name: REST API
:page-wiki-id: 13074536
:page-wiki-metadata-create-user: katkav
:page-wiki-metadata-create-date: 2013-10-24T17:29:05.212+02:00
:page-wiki-metadata-modify-user: slavek
:page-wiki-metadata-modify-date: 2021-02-16T10:07:40.669+01:00
:page-midpoint-feature: true
:page-alias: { "parent" : "/midpoint/features/current/" }
:page-upkeep-status: green
:page-toc: top
:page-keywords: [ 'rest', 'interface', 'rest api', 'restful']
:search-alias: "rest"

== Description

The MidPoint *REST API* is one of the interfaces which gives you the possibility to
access and interact with the data present in your midPoint instance.

The REST api gives you a feature rich toolset with which you can operate over different
*web resources*, these are represented as specific endpoints to which you send your operation request.

There are many possibilities which we provide in regard to the endpoints you can access. So many
that we have a dedicated page for them.

.To display a *list of REST endpoints* please have a look at:
xref:/midpoint/reference/interfaces/rest/endpoints/[REST Endpoints]

.For a *more technical description* of our REST api please have a look here:
xref:/midpoint/reference/interfaces/rest/concepts/[Concepts]

== How To Use

The *format of the REST request* depends on the type of web resource you try to invoke, the  operation
which you want to execute and any additional options you wish to specify for the request.

.Also, you have to authenticate your self
xref:/midpoint/reference/interfaces/rest/concepts/authentication/#_basic_authentication[Authentication methods]

The most *basic form* of the url request would be:

.Request to read own profile data (raw)
[source,http]
----
GET http://localhost:8080/midpoint/ws/rest/self?options=raw
----
.Request to read own profile data (raw) full example using CURL
xref:/midpoint/reference/interfaces/rest/operations/examples/get-user-self/#_ex_get_own_profile_information_json_raw[Request to read own profile data]

Naturally by having a feature rich interface there is no "one size fits them all" way to invoke the operations, so the url will
be different in specific use cases. The most common ones you can see
at xref:/midpoint/reference/interfaces/rest/#_common_use_cases[this] section of the documentation.

The REST interface provides you with a long list of *Endpoints* which you can access. The interface also provides
you with *different kinds of operations*, based on the type of object endpoint you choose.

.*Commonly Used Object Endpoints:*
- xref:/midpoint/reference/interfaces/rest/endpoints/users/[users]
- xref:/midpoint/reference/interfaces/rest/endpoints/roles/[roles]
- xref:/midpoint/reference/interfaces/rest/endpoints/organizational-units/[orgs]
- xref:/midpoint/reference/interfaces/rest/endpoints/resources/[resources]
- xref:/midpoint/reference/interfaces/rest/endpoints/rpc/[rpc]


.The *full collection of Object Endpoints* can be found here:
xref:/midpoint/reference/interfaces/rest/endpoints/[Endpoints]

.Request Content Type
There are multiple possibilities regarding the content type of the request body and also
regarding the type of data which will be returned to the client.

The content type can be specified inside the URI of the request. This is done via the
addition of a *request header*.

.Content-Type header example, other media types are supported as well
[source, http]
----
"Content-Type: application/json"
----

You might need to specify the accepted type of content in case
you are interested in a format different from xml (default)

.Accept type header example, other media types are supported as well
[source, http]
----
"Accept: application/json"
----

By using the above request in the following example:

include::../rest/operations/examples/raw/get-user-self-xml.adoc[]

TIP:: Note the *"Accept: application/xml"* Header usage.

You could have multiple different types of output format:

[source,xml]
----
<user xmlns="http://midpoint.evolveum.com/xml/ns/public/common/common-3"
xmlns:c="http://midpoint.evolveum.com/xml/ns/public/common/common-3"
xmlns:icfs="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/resource-schema-3"
xmlns:org="http://midpoint.evolveum.com/xml/ns/public/common/org-3"
xmlns:q="http://prism.evolveum.com/xml/ns/public/query-3"
xmlns:ri="http://midpoint.evolveum.com/xml/ns/public/resource/instance-3"
xmlns:t="http://prism.evolveum.com/xml/ns/public/types-3"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
oid="00000000-0000-0000-0000-000000000002">
    <name>administrator</name>
    <description>Description parameter modified via REST</description>
    <metadata/>
    <operationExecution/>
    <operationExecution/>
    <indestructible>true</indestructible>
    <assignment/>
    <assignment/>
    <iteration>0</iteration>
    <iterationToken/>
    <archetypeRef oid="00000000-0000-0000-0000-000000000300" relation="org:default" type="c:ArchetypeType"/>
    <roleMembershipRef/>
    <roleMembershipRef/>
    <activation>
        <administrativeStatus>enabled</administrativeStatus>
        <effectiveStatus>enabled</effectiveStatus>
        <enableTimestamp></enableTimestamp>
        <lockoutStatus>normal</lockoutStatus>
    </activation>
    <credentials/>
    <behavior/>
    <fullName>midPoint Administrator</fullName>
    <givenName>midPoint</givenName>
    <familyName>Administrator</familyName>
</user>

----

[source,json]
----
{
  "user" : {
    "oid" : "00000000-0000-0000-0000-000000000002",
    "version" : "",
    "name" : "administrator",
    "description" : "Description parameter modified via REST",
    "metadata" : {},
    "operationExecution" : [ {}, {} ],
    "indestructible" : true,
    "assignment" : [ {}, {} ],
    "iteration" : 0,
    "iterationToken" : "",
    "archetypeRef" : {
      "oid" : "00000000-0000-0000-0000-000000000300",
      "relation" : "org:default",
      "type" : "c:ArchetypeType"
    },
    "roleMembershipRef" : [ {}, {}],
    "activation" : {
      "administrativeStatus" : "enabled",
      "effectiveStatus" : "enabled",
      "enableTimestamp" : "",
      "lockoutStatus" : "normal"
    },
    "credentials" : {},
    "behavior" : {},
    "fullName" : "midPoint Administrator",
    "givenName" : "midPoint",
    "familyName" : "Administrator"
  }
}
----

[source,yaml]
----
---
user:
  oid: "00000000-0000-0000-0000-000000000002"
  version: ""
  name: "administrator"
  description: "Description parameter modified via REST"
  metadata:
  operationExecution:
  - :
  - :
  indestructible: true
  assignment:
  - :
  - :
  iteration: 0
  iterationToken: ""
  archetypeRef:
    oid: "00000000-0000-0000-0000-000000000300"
    relation: "org:default"
    type: "c:ArchetypeType"
  roleMembershipRef:
  - :
  - :
  activation:
    administrativeStatus: "enabled"
    effectiveStatus: "enabled"
    enableTimestamp: "2024-01-09T14:44:06.815+01:00"
    lockoutStatus: "normal"
  credentials:
  behavior:
  fullName: "midPoint Administrator"
  givenName: "midPoint"
  familyName: "Administrator"
----


== MidPoint Client

To ease up the development of you own implementation of a MidPoint REST client. Please
have a look and consider using the midPoint Java Client project:

xref:/midpoint/reference/interfaces/midpoint-client-java/[MidPoint Client Library]

[#_common_use_cases]
== Common Use Cases

// TODO add links

1. List all users with their profile information.
2. xref:/midpoint/reference/interfaces/rest/operations/examples/get-user-unique-id/[Get User with the REST API]
3. Create User with the REST API
4. Assign User Account with the REST API

== See Also

* xref:/midpoint/reference/interfaces/[Interfaces]

* What is link:https://evolveum.com/midpoint/[midPoint Open Source Identity & Access Management]

* link:https://evolveum.com/[Evolveum] - Team of IAM professionals who developed midPoint

* xref:/midpoint/reference/concepts/query/[midPoint Query]
