= MidPoint REST API
:page-nav-title: MidPoint REST API
:page-display-order: 100
// :page-since: "4.4"
// :page-since-improved: [ "4.5", "4.6", "4.7", "4.8" ]

== Description

The MidPoint *REST API* is one of the interfaces which gives you the possibility to
access and interact with the data present in your midPoint instance.

The REST api gives you a feature rich toolset with which you can operate over different
*web resources*, these are represented as specific endpoints to which you send your operation request.

There are many possibilities which we provide in regard to the web resources you can access. So many
that we have a dedicated page for them.

To display a *list of the types of resources* please have a look at:

- "TODO" page(s) with list of web resources

For a *more technical description* of our REST api please have a look here:

- "TODO" page(s) with technical description and/or design pages etc...

== How To Use

The *format of the REST request* depends on the type of web resource you try to invoke, the  operation
which you want to execute and any additional options you wish to specify for the request.

The most *basic form* of the url request would be :

---TODO add full complexity or keep this simple example ???

[source, http]
----
http://localhost:8080/midpoint/ws/rest/{web_resource_type}/{operation}
----

Naturally by having a feature rich interface there is no "one size fits them all" way to invoke the operations, so the url will be different in specific use cases. The most common ones you can see
at this section {TODO add link to "Common Use Cases"} of the documentation.

For a list of available operations please have a look :

- "TODO"  HERE

== Common Use Cases

-- TODO add links

1. List all users with their profile information.
2. Get user based on his unique identificator (TODO link to OID docu)
3. Create or update a new user.
4. Modify the user by assigning an account.


== See Also
