<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~ Copyright (c) 2010-2013 Evolveum
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->


<definitions name="fake"
    targetNamespace="http://midpoint.evolveum.com/xml/ns/private/fake/fake-1.wsdl"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://midpoint.evolveum.com/xml/ns/private/fake/fake-1.wsdl"
    xmlns:m="http://midpoint.evolveum.com/xml/ns/public/model/model-3"
    xmlns:r="http://midpoint.evolveum.com/xml/ns/public/report/report-3"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

    <types>
        <xsd:schema targetNamespace="http://midpoint.evolveum.com/xml/ns/private/fake/fake-1.wsdl">
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/common/common-3"
                        schemaLocation="../../public/common/common-3.xsd"/>
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/resource/capabilities-3"
                        schemaLocation="../../public/resource/capabilities-3.xsd"/>
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/resource-schema-3"
                        schemaLocation="../../public/connector/icf-1/resource-schema-3.xsd"/>
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/connector-schema-3"
                        schemaLocation="../../public/connector/icf-1/connector-schema-3.xsd"/>
            <!--
			<xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/communication/workflow-1.xsd"
						schemaLocation="../../public/communication/workflow-1.xsd"/>
		    -->
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/model/workflow/common-forms-3"
                        schemaLocation="../../public/model/workflow/common-forms-3.xsd"/>
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/model/workflow/process-instance-state-3"
                        schemaLocation="../../public/model/workflow/process-instance-state-3.xsd"/>
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/model/scripting-3"
                        schemaLocation="../../public/model/scripting/scripting-3.xsd"/>

            <xsd:import namespace="http://prism.evolveum.com/xml/ns/public/query-3"
                        schemaLocation="http://prism.evolveum.com/xml/ns/public/query-3"/>
            <xsd:import namespace="http://prism.evolveum.com/xml/ns/public/types-3"
                        schemaLocation="http://prism.evolveum.com/xml/ns/public/types-3"/>
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/common/audit-3"
                        schemaLocation="../../public/common/audit-3.xsd"/>

            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/gui/admin-1"
                        schemaLocation="../../public/gui/admin-1.xsd"/>
        </xsd:schema>
    </types>

    <import namespace="http://midpoint.evolveum.com/xml/ns/private/fake/fake-1.wsdl" location="fake-1.wsdl"/>
    <import namespace="http://midpoint.evolveum.com/xml/ns/public/model/model-3"
            location="http://midpoint.evolveum.com/xml/ns/public/model/model-3"/>
    <import namespace="http://midpoint.evolveum.com/xml/ns/public/report/report-3"
            location="http://midpoint.evolveum.com/xml/ns/public/report/report-3"/>
    <!--<service name="fakeService">-->
        <!--<port name="fakePort" binding="tns:fakeBinding">-->
            <!--<soap:address location="http://localhost:${HttpDefaultPort}/fakeService/fakePort"/>-->
        <!--</port>-->
    <!--</service>-->
    <service name="modelService">
        <port name="modelPort" binding="m:modelBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/modelService/modelPort"/>
        </port>
    </service>
    <service name="reportService">
        <port name="reportPort" binding="r:reportBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/reportService/reportPort"/>
        </port>
    </service>
</definitions>






