<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 * Copyright (c) 2011 Evolveum
 *
 * The contents of this file are subject to the terms
 * of the Common Development and Distribution License
 * (the License). You may not use this file except in
 * compliance with the License.
 *
 * You can obtain a copy of the License at
 * http://www.opensource.org/licenses/cddl1 or
 * CDDLv1.0.txt file in the source code distribution.
 * See the License for the specific language governing
 * permission and limitations under the License.
 *
 * If applicable, add the following below the CDDL Header,
 * with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted 2011 [name of copyright owner]"
 * -->

<definitions name="fake"
    targetNamespace="http://midpoint.evolveum.com/xml/ns/private/fake/fake-1.wsdl"
    xmlns:tns="http://midpoint.evolveum.com/xml/ns/private/fake/fake-1.wsdl"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

    <documentation>
	
		TODO
	
    </documentation>

    <types>
        <xsd:schema targetNamespace="http://midpoint.evolveum.com/xml/ns/private/fake/fake-1.wsdl">
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/common/common-2a" 
            			schemaLocation="../../public/common/common-2a.xsd"/>
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/resource/capabilities-2" 
            			schemaLocation="../../public/resource/capabilities-2.xsd"/>
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/resource-schema-2" 
            			schemaLocation="../../public/connector/icf-1/resource-schema-2.xsd"/>
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/connector-schema-2" 
            			schemaLocation="../../public/connector/icf-1/connector-schema-2.xsd"/>
			<xsd:import namespace="http://midpoint.evolveum.com/xml/ns/public/communication/workflow-1.xsd" 
						schemaLocation="../../public/communication/workflow-1.xsd"/>
            <xsd:import namespace="http://midpoint.evolveum.com/xml/ns/model/workflow/common-forms-2"
                        schemaLocation="../../public/model/workflow/common-forms-2.xsd"/>

            <xsd:import namespace="http://prism.evolveum.com/xml/ns/public/query-2" 
            			schemaLocation="http://prism.evolveum.com/xml/ns/public/query-2"/>
            <xsd:import namespace="http://prism.evolveum.com/xml/ns/public/types-2" 
            			schemaLocation="http://prism.evolveum.com/xml/ns/public/types-2"/>
        </xsd:schema>
    </types>

	<message name="fakeRequest">
        <part name="fakePart" type="xsd:string">
        </part>
    </message>
    <message name="fakeResponse">
        <part name="fakePart" type="xsd:string">
        </part>
    </message>

    <portType name="fakePortType">

        <operation name="fake">
            <input name="fakeInput" message="tns:fakeRequest"/>
            <output name="fakeOutput" message="tns:fakeResponse"/>
        </operation>

    </portType>

    <binding name="fakeBinding" type="tns:fakePortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="fake">
            <soap:operation/>
            <input name="fakeInput">
                <soap:body use="literal" namespace="http://midpoint.evolveum.com/xml/ns/public/model/model-1.wsdl"/>
            </input>
            <output name="fakeOutput">
                <soap:body use="literal" namespace="http://midpoint.evolveum.com/xml/ns/public/model/model-1.wsdl"/>
            </output>
        </operation>
    </binding>
</definitions>



