---
midpoint-feature: policy-concept
doc-type: [ 'config' ]
---
= Pre-configured Policies
:page-keywords: governance, relationship, rules, policy
:page-upkeep-status: yellow
:page-moved-from: /midpoint/reference/roles-policies/preconfigured-policies/

Default midPoint configuration includes pre-packaged polices, in a ready-to-use form.
Following polices are included in midPoint xref:/midpoint/reference/deployment/initial-objects/[initial objects]:

|===
| Policy | Applied to | When violated | Description

| `Require owner`
| Individual objects (assignment) +
Archetypes (inducement)
| Applies mark `Unowned`
| Requires that all affected objects have at least one owner.

| `Require classification`
| Individual objects (assignment) +
Archetypes (inducement)
| Applies mark `No classification`
| Requires that all affected objects have a xref:/midpoint/reference/roles-policies/policies/classification/[classification].

|===

The policies can be used by assigning/inducing them to objects specified in the _Applied to_ column above.
E.g. the `Require owner` policy can be applied by inducing this policy in the `Application` archetype, which sets the requirement that all applications must have at least one owner.

NOTE: Affected objects have to be explicitly recomputed after the policy is applied for the policy to take effect.

== See Also

* xref:/midpoint/reference/roles-policies/policies/identity-governance-rules/[]

* xref:/midpoint/reference/roles-policies/policies/policy-rules/[]

* xref:/midpoint/reference/roles-policies/policies/object-governance/[]

* xref:/midpoint/reference/concepts/mark/[]
